force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Emergency.recordType-meta.xml
<RecordType>
    <fullName>Emergency</fullName>
    <active>true</active>
    <businessProcess>Emergency</businessProcess>
    <description>For Customer Emergency Services</description>
    <label>Emergency</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Activate_Logic_for_Services__c.field-meta.xml
<CustomField>
    <fullName>Activate_Logic_for_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate Logic for Services</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Activate_Threshold_Logic_for_Orders__c.field-meta.xml
<CustomField>
    <fullName>Activate_Threshold_Logic_for_Orders__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Used to control is threshold logic is used for Order Products with Equipment and Consumable Products</inlineHelpText>
    <label>Activate Threshold Logic for Orders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Consumables_Discount_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Consumables_Discount_Threshold__c</fullName>
    <label>Consumables Discount Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Equipment_Discount_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Discount_Threshold__c</fullName>
    <label>Equipment Discount Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Item_Type_for_Consumables__c.field-meta.xml
<CustomField>
    <fullName>Item_Type_for_Consumables__c</fullName>
    <label>Item Type for Consumables</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Item_Type_for_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Item_Type_for_Equipment__c</fullName>
    <label>Item Type for Equipment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Item_Type_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Item_Type_of_Services__c</fullName>
    <label>Item Type of Services</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Non_Recurring_Frequency_Value__c.field-meta.xml
<CustomField>
    <fullName>Non_Recurring_Frequency_Value__c</fullName>
    <label>Non Recurring Frequency Value</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Pest_LOB__c.field-meta.xml
<CustomField>
    <fullName>Pest_LOB__c</fullName>
    <label>Pest LOB</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Requested_Price_Blank_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Requested_Price_Blank_Error_Message__c</fullName>
    <label>Requested Price Blank Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/Order/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Line_of_Businesses__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Businesses__c</fullName>
    <label>Line of Businesses</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <formula>CASESAFEID(Order.AccountId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Bypass_Standing_Order_Price_Engine__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Standing_Order_Price_Engine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Standing Order Price Engine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Has_Warranty__c.field-meta.xml
<CustomField>
    <fullName>Has_Warranty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Warranty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <formula>PricebookEntry.Product2.Item_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Family)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Order Item cannot have the custom Order field set as it&apos;s Inactive.</errorMessage>
        <filterItems>
            <field>$Source.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Active Order Products without PO Number</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PBE_List_Price__c.field-meta.xml
<CustomField>
    <fullName>PBE_List_Price__c</fullName>
    <formula>PricebookEntry.UnitPrice</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PBE List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Item_Number__c</fullName>
    <formula>PricebookEntry.Product2.ExternalID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Item Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <inlineHelpText>Indicate if the Customer is charged a Price for the Purchase of this item. Price Entered is per unit. If only Purchase Price is filled in, this would be considered as a One Time Delivery.</inlineHelpText>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Requested_Price__c.field-meta.xml
<CustomField>
    <fullName>Requested_Price__c</fullName>
    <label>Requested Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Requested_Price_Approved__c.field-meta.xml
<CustomField>
    <fullName>Requested_Price_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requested Price Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OrderItemUtilityClass.cls
public class OrderItemUtilityClass {
    static Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
    static final String KEY_DELIMITER = '.';
    static final String ITEM_NUMBER_DELIMITER = '-';
    static final String PEST_SPECIAL = 'PEST_SPECIAL';
    static final String PEST_SPECIAL_CODE = '1-55';
    public static Set<Id> OrderInvFlagList = new Set<Id>();
    public static Map<Id, Order> mapOrders = new Map<Id, Order>();
    
    public static void setActiveLookupToOrder(List<OrderItem> orderItems) {
        for (OrderItem oi : orderItems) {
            oi.Order__c = oi.Active__c && String.isBlank(oi.PO_Number__c) ? oi.OrderId : null;
        }
    }
    
    public static List<OrderItem> orderItemPriceController(List<OrderItem> orderItems, Map<Id, OrderItem>oldItems) {
        List<OrderItem> orderItemsToReturn = new List<OrderItem>();
        
        if (!TriggerHelper.hasOrderItemPricingBeenSet) {
            TriggerHelper.hasOrderItemPricingBeenSet = true;
        } else {
            //already handled data in this transaction
            //return orderItemsToReturn;
        }
        
        if (orderItems.isEmpty()) {
            System.debug('empty list');
            return orderItemsToReturn;
        }
        
        Set<Id> accountIds = new Set<Id>();
        //Set<Id> orderIds = new Set<Id>();
        Set<String> productItemNumbers = new Set<String>();
        
        Map<Id, List<OrderItem>> orderAndLineItemsMap = new Map<Id, List<OrderItem>>();//opportuntyid -> orderitems
        Map<String, Decimal> standingOrderLinePriceItemMapWithFrequency = new Map<String, Decimal>();
        //Begin:Shashi:10-1-2019:Pest Control, Emergency order check
        //Map<Id, Order> mapOrders = new Map<Id, Order>();
        //End
        
        for (OrderItem oi : orderItems) {
            //If Create Invoice Adjustment Flag is set do not perform calculations : 3-23-2020
            if(OrderInvFlagList.contains(oi.OrderId)){continue;}
            
            OrderItem oldVersion = oldItems == null ? new OrderItem() : oldItems.get(oi.Id);
            
            System.debug('~~Bypass Standing Order~~' + oi.Bypass_Standing_Order_Price_Engine__c);
            System.debug('~~Has Warranty~~' + oi.Has_Warranty__c);
            
            //Bypass_Standing_Order_Price_Engine__c and Has_Warranty__c is for case 21618
            if (oi.Bypass_Standing_Order_Price_Engine__c ||
                oi.Has_Warranty__c ||
                (oldVersion.Id != null &&
				oi.Frequency__c == dataSets.Non_Recurring_Frequency_Value__c &&
                oi.Service_Price_Per_Unit__c == oldVersion.Service_Price_Per_Unit__c && 
                oi.Purchase_Price__c == oldVersion.Purchase_Price__c &&
                oi.Requested_Price_Approved__c == oldVersion.Requested_Price_Approved__c)) 
            {
                oi.Bypass_Standing_Order_Price_Engine__c = false;//allow the record to bypass the engine this one time
                System.debug('record thrown away');
                continue;
            }
            
            if (!orderAndLineItemsMap.containsKey(oi.OrderId)) {
                orderAndLineItemsMap.put(oi.OrderId, new List<OrderItem>());
            }
            
            orderAndLineItemsMap.get(oi.OrderId).add(oi);
            //orderIds.add(oi.OrderId);
            //accountIds.add(oi.Account_Id__c);
        }
        
        productItemNumbers.remove(null);
        //orderIds.remove(null);
        orderAndLineItemsMap.remove(null);
        
        if (orderAndLineItemsMap.isEmpty()) {
            System.debug('no records to process');
            return orderItemsToReturn;
        }
        
        //Shashi:12/22/2020:SOQL Query reduction
        for(Order o:mapOrders.values()){
            accountIds.add(o.AccountId);
        }
        /*if (!orderIds.isEmpty()) {
            //Begin:Shashi:10-1-2019:Pest Control, Emergency order check
            for (Order o : [SELECT Id, AccountId,Line_of_Businesses__c,Emergency__c FROM Order WHERE Id IN :orderIds]) {
                accountIds.add(o.AccountId);
                mapOrders.put(o.Id, o);
            }
            //End
        }*/
        
        accountIds.remove(null);
        
        standingOrderLinePriceItemMapWithFrequency = PriceCalculationUtility.buildStandingOrderPriceMap(accountIds);
        
        //System.debug(orderAndLineItemsMap);
        //System.debug(standingOrderLinePriceItemMapWithFrequency);
        
        //if (!standingOrderLinePriceItemMapWithFrequency.isEmpty()) {
            for (Id oliId : orderAndLineItemsMap.keySet()) {
                for (OrderItem oi : orderAndLineItemsMap.get(oliId)) {
                    //System.debug(oi.Product2Id);
                    //System.debug(oi.Product_Item_Number__c);
                    String[] delimitedValues = oi.Product_Item_Number__c.split(ITEM_NUMBER_DELIMITER);
                    //Begin:Shashi:9-6-2019:Prevent null exception if Product_Item_Number__c is empty
                    //String serviceKey = delimitedValues[0] + ITEM_NUMBER_DELIMITER + delimitedValues[1] + ITEM_NUMBER_DELIMITER + delimitedValues[2] + KEY_DELIMITER + oi.Account_Id__c + KEY_DELIMITER + oi.Frequency__c;
                    String serviceKey = '';
                    if(delimitedValues.size()>=1){serviceKey+=delimitedValues[0];}
                    if(delimitedValues.size()>=2){serviceKey+=ITEM_NUMBER_DELIMITER + delimitedValues[1];}
                    if(delimitedValues.size()>=3){serviceKey+=ITEM_NUMBER_DELIMITER + delimitedValues[2];}
                    serviceKey+=KEY_DELIMITER + oi.Account_Id__c + KEY_DELIMITER + oi.Frequency__c;
                    //End
                    String pestSpecialKey = oi.Product_Item_Number__c + KEY_DELIMITER + oi.Account_Id__c + KEY_DELIMITER + PEST_SPECIAL;
                    String allOtherKey = oi.Product_Item_Number__c + KEY_DELIMITER + oi.Account_Id__c;
                    Boolean isService = oi.Item_Type__c == dataSets.Item_Type_of_Services__c;
                    Decimal itemPrice;
                    
                    System.debug('isService: '+isService);
                    System.debug(oi.Item_Type__c);
                    
                    //use the price entered by the user for services
                    if (isService && !dataSets.Activate_Logic_for_Services__c) {
                        continue;
                    }
                    
                    //CPQCN-457: Shashi Puttaswamy: 12-10-2020 : Service Unit Price doesn't require override from Standing Order 
                    if (isService) {
                        if (oi.Product_Item_Number__c.startsWith(PEST_SPECIAL_CODE)) {
                            System.debug('PEST SPECIAL KEY >>> ' + pestSpecialKey);
                            itemPrice = standingOrderLinePriceItemMapWithFrequency.get(pestSpecialKey);
                        } else {
                            itemPrice = standingOrderLinePriceItemMapWithFrequency.get(serviceKey);
                        }
                    } 
                    else {
                        itemPrice = standingOrderLinePriceItemMapWithFrequency.get(allOtherKey);
                    }
                    
                    OrderItem oldVersion;
                    
                    if (oldItems != null) {
                    	oldVersion = oldItems.get(oi.Id);
                    }
                    
                    Boolean isPestEmergencyOrder = false;
                    if(mapOrders.containsKey(oi.OrderId)){
                    	Order curOrder = mapOrders.get(oi.OrderId);
                        if(curOrder.Emergency__c && ((curOrder.Line_of_Businesses__c!=null && curOrder.Line_of_Businesses__c==dataSets.Pest_LOB__c) ||
                                                     (oi.Line_of_Business__c!=null && oi.Line_of_Business__c==dataSets.Pest_LOB__c))){
                        	isPestEmergencyOrder = true;
                        }
                    }
                    
                    if (!oi.Requested_Price_Approved__c) {
                        if(!isPestEmergencyOrder){continue;}
                        //Begin:Shashi:10-1-2019:Pest Control, Emergency order check
                        Boolean isServicePriceCheck=false;
                        
                        if(isPestEmergencyOrder){isServicePriceCheck=true;}
                        else{if(oi.Service_Price_Per_Unit__c != null){isServicePriceCheck=true;}}
                        if (oi.Item_Type__c == dataSets.Item_Type_of_Services__c && isServicePriceCheck){ //&& oi.Service_Price_Per_Unit__c != null) {
                        //End
                            System.debug('~~itemPrice: '+itemPrice);
                            
                            if (itemPrice != null) {// && oi.Service_Price_Per_Unit__c != itemPrice
                                oi.Requested_Price__c = oi.Service_Price_Per_Unit__c;
                                oi.Service_Price_Per_Unit__c = itemPrice;
                            } else {
                                //leverage PBE
                                System.debug('leveraging PBE for service');
                                if (oi.Service_Price_Per_Unit__c != oi.PBE_List_Price__c) {
                                    oi.Requested_Price__c = oi.Service_Price_Per_Unit__c;
                                    oi.Service_Price_Per_Unit__c = oi.PBE_List_Price__c;
                                }
                            }
                        } 
                        else if (oi.Item_Type__c != dataSets.Item_Type_of_Services__c && oi.Purchase_Price__c != null) {
                            //check for SOLI
                            if (itemPrice != null) {
                                System.debug('checking SOLI price');
                                //if (oi.Purchase_Price__c != itemPrice) {
                                    oi.Requested_Price__c = oi.Purchase_Price__c;
                                    oi.Purchase_Price__c = itemPrice;
                                //}
                            } else {
                                System.debug('checking PBE price');
                                Decimal comparisonFinal = 0;
                                
                                //if threshold logic not activated, just use PBE price as is
                                if (dataSets.Activate_Threshold_Logic_For_Orders__c) {
                                    Decimal thresholdAdjustment;
                                    
                                    if (oi.Item_Type__c == dataSets.Item_Type_for_Equipment__c) {
                                        thresholdAdjustment = dataSets.Equipment_Discount_Threshold__c;
                                    } else if (oi.Item_Type__c == dataSets.Item_Type_for_Consumables__c) {
                                        thresholdAdjustment = dataSets.Consumables_Discount_Threshold__c;
                                    }
                                
                                    comparisonFinal = thresholdAdjustment == null ? oi.PBE_List_Price__c : ((100 - thresholdAdjustment) / 100) * oi.PBE_List_Price__c;
                                    comparisonFinal.setScale(2);
                                } else {
                                    comparisonFinal = oi.PBE_List_Price__c;
                                }
                                
                                if (oi.Item_Type__c != dataSets.Item_Type_of_Services__c && oi.Purchase_Price__c != null) {
                                    if (oi.Purchase_Price__c < comparisonFinal || oi.Purchase_Price__c > oi.PBE_List_Price__c) {
                                        oi.Requested_Price__c = oi.Purchase_Price__c;
                                        oi.Purchase_Price__c = oi.PBE_List_Price__c;
                                    }
                                }
                            }
                        }
                    } 
                    else if (oldVersion == null || (oi.Requested_Price_Approved__c && !oldVersion.Requested_Price_Approved__c)) {
                        if (oi.Requested_Price__c == null) {
                            oi.addError(dataSets.Requested_Price_Blank_Error_Message__c);
                        } else if (isService) {
                            oi.Service_Price_Per_Unit__c = oi.Requested_Price__c;
                            //oi.Requested_Price_Approved__c = false;
                        } else {
                            oi.Purchase_Price__c = oi.Requested_Price__c;
                            //oi.Requested_Price_Approved__c = false;
                        }
                    }
                    orderItemsToReturn.add(oi);
                }
            }
        //}
        return orderItemsToReturn;
    }
}