force-app/main/default/objects/Case/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>This field is System Generated during the nightly Work Order Generation batch job. Changing this would have implications on Work Order Generation Logic</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <label>Last InFlight WO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_Work_Order_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Work_Order_Completed_Date__c</fullName>
    <label>Last Work Order Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/CongaServiceAppointmentEmail__c.field-meta.xml
<CustomField>
    <fullName>CongaServiceAppointmentEmail__c</fullName>
    <formula>&quot;&amp;id=&quot;+Id+
&quot;&amp;queryid=[wo]&quot;+$Setup.Field_Service_Settings__c.ServiceAppointmentParentQueryId__c+&quot;,[wor]&quot;+$Setup.Field_Service_Settings__c.WorkOrderRoomQueryId__c+&quot;?pv0={QVar0},[con]&quot;+$Setup.Field_Service_Settings__c.ContactEmailQueryId__c+&quot;,[role]&quot;+$Setup.Field_Service_Settings__c.ContactRoleQueryId__c+&quot;?pv0=&quot;+Account__c+
&quot;&amp;congaemailtemplateid=&quot;+$Setup.Field_Service_Settings__c.CongaEmailTemplateId__c+
&quot;&amp;qvar0id=&quot;+$Setup.Field_Service_Settings__c.ServiceAppointmentParentQueryId__c+
&quot;&amp;qvar1id=&quot;+$Setup.Field_Service_Settings__c.ContactRoleQueryId__c+&quot;?pv0=&quot;+Account__c+
&quot;&amp;emailfromid=&quot;+$Setup.Field_Service_Settings__c.Customer_Success_OWA_Id__c+
&quot;&amp;emailtoid=&quot;+ContactId+
&quot;&amp;emailcc={QVar1}&quot;+
&quot;&amp;qmode=SendEmail&quot;+
&quot;&amp;DS7=3&quot;+
&quot;&amp;AC0=1&quot;+
&quot;&amp;AC1=Service+Appointment+Email+Notification+Sent&quot;+
&quot;&amp;SC0=1&quot;+
&quot;&amp;OCNR=1&quot;+
&quot;&amp;APIMode=12&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CongaServiceAppointmentEmail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/IsDispatched__c.field-meta.xml
<CustomField>
    <fullName>IsDispatched__c</fullName>
    <formula>NOT(TEXT(StatusCategory) = &apos;None&apos;)  &amp;&amp;  NOT(TEXT(StatusCategory) = &apos;Scheduled&apos;) &amp;&amp;  NOT(TEXT(StatusCategory) = &apos;Canceled&apos;) &amp;&amp; NOT( ISBLANK( SchedStartTime ) ) &amp;&amp;  NOT( ISBLANK(  SchedEndTime  ) )</formula>
    <label>IsDispatched</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/IsOpen__c.field-meta.xml
<CustomField>
    <fullName>IsOpen__c</fullName>
    <formula>TEXT(StatusCategory) = &apos;None&apos; || 
TEXT(StatusCategory) = &apos;Scheduled&apos; ||
TEXT(StatusCategory) = &apos;Dispatched&apos; ||
TEXT(StatusCategory) = &apos;In Progress&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsOpen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/IsPending__c.field-meta.xml
<CustomField>
    <fullName>IsPending__c</fullName>
    <formula>TEXT(StatusCategory) = &apos;None&apos; || 
TEXT(StatusCategory) = &apos;Scheduled&apos; ||
TEXT(StatusCategory) = &apos;Dispatched&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsPending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/ServiceReportAlreadySent__c.field-meta.xml
<CustomField>
    <fullName>ServiceReportAlreadySent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ServiceReportAlreadySent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Should_Auto_Generate_Service_Report__c.field-meta.xml
<CustomField>
    <fullName>Should_Auto_Generate_Service_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Should Auto Generate Service Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Should_Auto_Send_Service_Report__c.field-meta.xml
<CustomField>
    <fullName>Should_Auto_Send_Service_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Should Auto Send Service Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Status_UnSync_WO_SA__c.field-meta.xml
<CustomField>
    <fullName>Status_UnSync_WO_SA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to check if the Status_WO_SA field on the FSL mobile app should be used to Sync the status of Work Orders &amp; Service Appointments or not</description>
    <inlineHelpText>When checked, Changing the status of the Status or Status (WO/SA) fields on the Service Appointment will not sync the status of a WO &amp; SA</inlineHelpText>
    <label>Status UnSync (WO/SA)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Status_WO_SA__c.field-meta.xml
<CustomField>
    <fullName>Status_WO_SA__c</fullName>
    <description>Used to Sync Work Orders and Service Appointment status from the mobile FSL app</description>
    <label>Status (WO/SA)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>On Route</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Service Appointment</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/HasBeenDispatched__c.field-meta.xml
<CustomField>
    <fullName>HasBeenDispatched__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HasBeenDispatched</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Next_Scheduled_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Next_Scheduled_Appointment__c</fullName>
    <description>Date field that shows the Next Scheduled Service Appointment</description>
    <label>Next Scheduled Appointment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of Work Order, whether it is a delivery or a work order for a particular line of business</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Work Order</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>NoWork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>System field that is filled in by the nightly batch job generating Work Orders, modifying this field would affect the Service Schedule</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <formula>TEXT(Order_Product__r.Last_InFlight_WO_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last InFlight WO Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceAppointmentFutureCalls.cls
global class ServiceAppointmentFutureCalls {
    
    @Future
    global static void statusSyncMethod(Set<String> statusSyncSAIds) {
        if (!statusSyncSAIds.isEmpty()) {
            
            List<WorkOrder> workOrders = new List<WorkOrder>();
            
            Map<Id,ServiceAppointment> serviceAppointmentsWOMap = new Map<Id, ServiceAppointment>();

            List<ServiceAppointment> sas = [
                    SELECT Id, Status, ParentRecordId, Status_WO_SA__c, Status_UnSync_WO_SA__c, AppointmentNumber
                    FROM ServiceAppointment
                    WHERE Id IN :statusSyncSAIds
                    AND Status_UnSync_WO_SA__c = FALSE
            ];

            for (ServiceAppointment sa: sas) {
                serviceAppointmentsWOMap.put(sa.ParentRecordId, sa);
            }

            List<WorkOrder> wos = [
                    SELECT Id, Status, WorkOrderNumber
                    FROM WorkOrder
                    WHERE Id IN :serviceAppointmentsWOMap.keySet()
            ];

            for(WorkOrder wo : wos) {
                ServiceAppointment sa = serviceAppointmentsWOMap.get(wo.Id);
                
                if(sa != null) {
                    wo.Status = sa.Status;
                    workOrders.add(wo);
                }
            }
            upsert workOrders;
        }
    }
    
    @Future
    global static void lastInFlightDateUpdates(Set<Id> workOrderIds) {
        if (workOrderIds.isEmpty()) return;

        List<Order> updateOrders = new List<Order>();
        Map<Id,OrderItem> updateOrderItems = new Map<Id,OrderItem>();
        Map<Id,WorkOrder> workOrders = new Map<Id,WorkOrder>();

        Set<Order> updateOrdersSet = new Set<Order>();
        Set<WorkOrderLineItem> workOrderLineItems = new Set<WorkOrderLineItem>();

        workOrders = new Map<Id,WorkOrder>([
                SELECT Id, Next_Scheduled_Appointment__c, HasBeenDispatched__c, Emergency__c, Type__c,
                        (SELECT Id, IsPending__c, IsOpen__c, IsDispatched__c, DueDate, SchedStartTime, SchedEndTime,
                                Status
                        FROM ServiceAppointments
                        WHERE IsOpen__c = TRUE
                        ORDER BY DueDate)
                FROM WorkOrder
                WHERE Id IN :workOrderIds
        ]);

        for (WorkOrder wo : workOrders.values()) {
            WorkOrder updatedWo = new WorkOrder(Id=wo.Id, HasBeenDispatched__c=false);
            for (ServiceAppointment sa : wo.ServiceAppointments) {
                if (updatedWo.Next_Scheduled_Appointment__c == null && sa.IsPending__c) {
                    updatedWo.Next_Scheduled_Appointment__c = sa.SchedStartTime != null ? sa.SchedStartTime : sa.DueDate;
                }
                if (sa.IsDispatched__c) {
                    updatedWo.HasBeenDispatched__c = sa.IsDispatched__c;
                }
            }

            if (wo.Next_Scheduled_Appointment__c != updatedWo.Next_Scheduled_Appointment__c || wo.HasBeenDispatched__c != updatedWo.HasBeenDispatched__c) {
                workOrders.put(wo.Id, updatedWo);
            } else {
                workOrders.remove(wo.Id);
            }
        }

        update workOrders.values();

        List<WorkOrderLineItem> wolis = [
                SELECT Id, LineItemNumber, Order_Product__c, Order_Product__r.Id, Order_Product__r.OrderItemNumber,
                        Order_Product__r.Last_Work_Order_Completed_Date__c, WorkOrderId, OrderId,
                        Order_Product__r.Last_Automation_Created_Date__c, Order_Product__r.Last_InFlight_WO_Date__c,
                        Last_Automation_Created_Date__c, WorkOrder.StartDate, Order.Status, Order.RecordTypeId,
                        WorkOrder.Type__c, WorkOrder.HasBeenDispatched__c, WorkOrder.Emergency__c
                FROM WorkOrderLineItem
                WHERE Order_Product__c != NULL
                AND WorkOrder.HasBeenDispatched__c = TRUE
                AND WorkOrderId IN :workOrders.keySet()
        ];

        for (WorkOrderLineItem woli : wolis) {
            if (woli.WorkOrder.HasBeenDispatched__c) {
                if (woli.Order.Status == QueryUtils.fieldServiceSettings.Order_Active_Stage__c) {
                    updateOrdersSet.add(woli.Order);
                }
                if (!woli.WorkOrder.Emergency__c && woli.WorkOrder.Type__c!='Follow-Up'){
                    workOrderLineItems.add(woli);
                    OrderItem oi = updateOrderItems.get(woli.Order_Product__c);
                    Date startDate = woli.WorkOrder.StartDate.date();
                    if (oi==null){
                        oi = woli.Order_Product__r;
                        updateOrderItems.put(oi.Id, oi);
                    }

                    if (oi.Last_InFlight_WO_Date__c == null || oi.Last_InFlight_WO_Date__c < startDate){
                        oi.Last_InFlight_WO_Date__c = startDate;
                    }
                }
            }
        }

        if(!updateOrdersSet.isEmpty()) {
            updateOrders.addAll(updateOrdersSet);
        }

        for(Order o : updateOrders) {
            if(o.RecordTypeId == QueryUtils.fieldServiceSettings.Regular_Order_Record_Type_Id__c) {
                o.Status = QueryUtils.fieldServiceSettings.Regular_Order_Draft_Stage__c;
            } else {
                o.Status = QueryUtils.fieldServiceSettings.Shopping_Cart_Order_Draft_Stage__c;
            }
        }

        update updateOrders;

        update updateOrderItems.values();

        for(Order o : updateOrders) {
            o.Status = QueryUtils.fieldServiceSettings.Order_Active_Stage__c;
        }

        update updateOrders;
    }
    
    @Future (Callout = true)
    global static void createSendServiceReport(
            Set<Id> saAutoGenerateSendReports,
            Set<Id> completedSAParentIds,
            String passedSessionId)
    {
        Map<Id, Id> serviceAppointmentReportMap = new Map<Id, Id>();

       	Id noReplyConId = [SELECT Id, Email FROM Contact WHERE Email = :QueryUtils.fieldServiceSettings.CitronDoNotReply__c LIMIT 1].Id;

        Id emailTemplateId = QueryUtils.fieldServiceSettings.ServiceReportTemplateId__c;
        Id orgWideAddress = QueryUtils.fieldServiceSettings.Org_Wide_Email_Address__c;
        
        Map<Id, ServiceAppointment> completedSAMap =  new Map<Id, ServiceAppointment>([
                SELECT Id, AppointmentNumber, ParentRecordId, ContactId, ServiceReportAlreadySent__c,
                        Should_Auto_Generate_Service_Report__c, Should_Auto_Send_Service_Report__c
                FROM ServiceAppointment
                WHERE Id IN :saAutoGenerateSendReports
        ]);
        
        Map<Id, WorkOrder> workOrderMap = new Map<Id, WorkOrder>([
                SELECT Id, ServiceReportTemplateId
                FROM WorkOrder
                WHERE Id IN :completedSAParentIds
        ]);

        List<ServiceReport> srs = [
                SELECT Id, ParentId, CreatedDate, DocumentBody, ContentVersionDocumentId
                FROM ServiceReport
                WHERE ParentId IN :saAutoGenerateSendReports
                ORDER BY CreatedDate DESC
        ];

        for(ServiceReport sr : srs) {
            serviceAppointmentReportMap.put(sr.ParentId, sr.ContentVersionDocumentId);
        }
        
        Messaging.SingleEmailMessage[] emails = new Messaging.SingleEmailMessage[]{};
            
            for (ServiceAppointment sa : completedSAMap.values()) {
                Id reportId = serviceAppointmentReportMap.get(sa.Id);

                if(reportId == null && sa.Should_Auto_Generate_Service_Report__c) {
                    if (!Test.isRunningTest()) {
                        String content = Page.SessionId.getContent().toString();
                        Integer s = content.indexOf('Start_Of_Session_Id') + 'Start_Of_Session_Id'.length(),
                            e = content.indexOf('End_Of_Session_Id');
                        passedSessionId = content.substring(s, e);
                    }

                    Http http = new Http();
                    HttpRequest request = new HttpRequest();
                    request.setEndpoint('callout:ServiceReportCreate/services/data/v43.0/actions/standard/createServiceReport');
                    request.setMethod('POST');
                    request.setHeader('Content-Type', 'application/json;charset=UTF-8'); 
                    request.setHeader('Authorization', 'OAuth ' + passedSessionId); //This was fun
                    request.setBody('{"inputs" : [ {"entityId" : "' + sa.Id + '","templateId" : "' + workOrderMap.get(sa.ParentRecordId).ServiceReportTemplateId + '" } ]}');
                    HttpResponse response = http.send(request);

                    if (response.getStatusCode() != 201 && response.getStatusCode() != 200) {
                        System.debug('The status code returned was not expected: ' + response.getStatusCode() + ', ' + response.getStatus());
                    } else {
                        String srId = response.getBody().substring(response.getBody().indexOf('"contentVersionId":"')+20,response.getBody().indexOf('","entityId"'));
                        serviceAppointmentReportMap.put(sa.Id, srId); 
                    }
                }
                
                if(sa.Should_Auto_Send_Service_Report__c) {
                    reportId = serviceAppointmentReportMap.get(sa.Id);

                    if(reportId!=null) {
                        if (sa.ContactId != null) {
                            emails.add(ServiceAppointmentFutureCalls.sendSREmail(sa.ContactId, reportId, emailTemplateId, orgWideAddress));
                        } else {
                            emails.add(ServiceAppointmentFutureCalls.sendSREmail(noReplyConId, reportId, emailTemplateId, orgWideAddress));
                        }
                    }  
                }
            }
        
        try {
            if (emails.size() > 0){
                Messaging.sendEmail(emails, false);

                for (ServiceAppointment sa : completedSAMap.values()){
                    sa.ServiceReportAlreadySent__c = true;
                }

                update completedSAMap.values();
            }
        } catch (Exception exc) {
            System.debug('Emails Failed: ' + exc.getMessage());
        }
    }
    
    global static Messaging.SingleEmailMessage sendSREmail(Id contactId, Id srId, Id emailTemplateId, Id orgWideAddress){
        Messaging.SingleEmailMessage SREmail = new Messaging.SingleEmailMessage();
        SREmail.setTargetObjectId(contactId);
        List<String> completedSRIds = new List<String> { srId };                            
        SREmail.setEntityAttachments(completedSRIds);
        SREmail.setTemplateId(emailTemplateId);
        SREmail.setSaveAsActivity(false);
        SREmail.setOrgWideEmailAddressId(orgWideAddress);
        return SREmail;
    }
    
    @Future (Callout = true)
    global static void sendCongaNotificationEmails(Set<Id> ServiceAppointmentIds){ //Case 21616 - MD
        List<ServiceAppointment> SAs = [
                SELECT Id, CongaServiceAppointmentEmail__c
                FROM ServiceAppointment
                WHERE Id IN: ServiceAppointmentIds
        ];

        String servURL = Url.getSalesforceBaseUrl().toExternalForm()+'/services/Soap/u/29.0/'+UserInfo.getOrganizationId();
        Http h = new Http();
        String content = Page.SessionId.getContent().toString();
        Integer s = content.indexOf('Start_Of_Session_Id') + 'Start_Of_Session_Id'.length();
        Integer e = content.indexOf('End_Of_Session_Id');
        String passedSessionId = content.substring(s, e);

        for (ServiceAppointment SA : SAs){
            HttpRequest req = new HttpRequest();
            req.setMethod('GET');
            req.setTimeout(60000);
            req.setEndpoint('https://composer.congamerge.com/composer8/index.html?sessionId='+passedSessionId+'&ServerURL=' + EncodingUtil.urlEncode(servURL, 'UTF-8') + SA.CongaServiceAppointmentEmail__c);
            h.send(req);
        }
    }
}