force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/Frequency__c/fields/Chemical_Reschedule_Plus_Days__c.field-meta.xml
<CustomField>
    <fullName>Chemical_Reschedule_Plus_Days__c</fullName>
    <label>Chemical Reschedule Plus Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frequency__c/fields/Hygiene_Reschedule_Plus_Days__c.field-meta.xml
<CustomField>
    <fullName>Hygiene_Reschedule_Plus_Days__c</fullName>
    <label>Hygiene Reschedule Plus Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frequency__c/fields/Life_Safety_Reschedule_Plus_Days__c.field-meta.xml
<CustomField>
    <fullName>Life_Safety_Reschedule_Plus_Days__c</fullName>
    <label>Life Safety Reschedule Plus Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frequency__c/fields/Pest_Reschedule_Plus_Days__c.field-meta.xml
<CustomField>
    <fullName>Pest_Reschedule_Plus_Days__c</fullName>
    <label>Pest Reschedule Plus Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/Province_Time_Zones_Operating_Hours__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A table to map each province to appropriate time zones, for Citron users to only associate Accounts to appropriate time zones.</description>
    <label>Province Time Zones - Operating Hours</label>
</CustomObject>

force-app/main/default/objects/User/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RecalculateServiceAppointmentDatesTest.cls
/**
 * @FileName: RecalculateServiceAppointmentDatesTest
 * @Description: Test class for RecalculateServiceAppointmentDates
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       2/10/2020         Created
 *-----------------------------------------------------------  
 */
@IsTest
private class RecalculateServiceAppointmentDatesTest {
    @TestSetup
    static void setupTest() {
        setupHelper();
    }

    @IsTest
    static void recalculateServiceAppointmentDates() {
        List<Frequency__c> frequencySettings = (List<Frequency__c>) TestUtils.createSObjectList(
                new Frequency__c(
                        Chemical_Reschedule_Plus_Days__c = 5,
                        Hygiene_Reschedule_Plus_Days__c = 5,
                        Pest_Reschedule_Plus_Days__c = 1
                ),
                3,
                false
        );

        frequencySettings[0].Name = 'Weekly';
        frequencySettings[0].Life_Safety_Reschedule_Plus_Days__c = 1;
        frequencySettings[0].Pest_Reschedule_Plus_Days__c = 2;

        frequencySettings[1].Name = 'Monthly';
        frequencySettings[1].Life_Safety_Reschedule_Plus_Days__c = 2;

        frequencySettings[2].Name = 'One-Time';
        frequencySettings[2].Life_Safety_Reschedule_Plus_Days__c = 5;

        insert frequencySettings;

        WorkOrder wo = [SELECT Id, Order__c FROM WorkOrder LIMIT 1];

        ServiceAppointment testSA = new ServiceAppointment(
                ParentRecordId = wo.Id,
                DueDate = System.today().addDays(-8),
                EarliestStartTime = System.today().addDays(-10),
                Status='New'
        );
        insert testSA;

        FSL.GlobalAPIS.addStatusTransition('New','Missed Service');

        testSA.Status = 'Missed Service';
        update testSA;

        Test.startTest();
        Database.executeBatch(new RecalculateServiceAppointmentDates());
        Test.stopTest();
    }

    // HELPER METHODS
    static void setupHelper() {
        TestUtils.createSObject(new Field_Service_Settings__c(), true);
        TestUtils.createSObject(new Province_Time_Zones_Operating_Hours__c(), true);

        TestUtilsWrapperPricebook pricebookWrapper = new TestUtilsWrapperPricebook(5, false);

        for(Product2 p : pricebookWrapper.products) {
            p.Allowable_Frequencies__c = 'One-Time;Monthly;Weekly';
        }

        pricebookWrapper.doInsert();

        TestUtilsWrapperAccount accountWrapper = new TestUtilsWrapperAccount();
        TestUtilsWrapperOrder orderWrapper = new TestUtilsWrapperOrder(accountWrapper, pricebookWrapper);
        new TestUtilsWrapperWorkOrder(accountWrapper, orderWrapper);

        User newUser = new User(
                Alias = 'testA',
                Email = 'testUser@UserCommunity.com',
                EmailEncodingKey = 'ISO-8859-1',
                FirstName = 'TestFirstName',
                LastName = 'TestLastName',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_CA',
                ProfileId = UserInfo.getProfileId(),
                TimeZoneSidKey = 'America/New_York',
                UserName = 'testUser@UserCommunity.com',
                Employee_Number__c = 'ABCD123TEST'
        );
        insert newUser;

        Group testGroup = new Group(Name='TestGroup', Type='Queue');
        insert testGroup;
        QueueSobject testQueue = new QueueSobject(QueueId = testGroup.Id, SobjectType = 'Case');

        System.runAs(newUser) {
            insert testQueue;
        }
    }
}