force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <formula>Opportunity.Site_Survey__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Survey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Asset_Delete__c/Survey_Asset_Delete__c.object-meta.xml
<CustomObject>
    <description>Tracks deletes of Survey Asset Location records.</description>
    <label>Survey Asset Delete</label>
    <nameField>
        <displayFormat>SAD{0000}</displayFormat>
        <label>Survey Asset Delete Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Asset Deletes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Asset_Delete__c/fields/Deleted_By__c.field-meta.xml
<CustomField>
    <fullName>Deleted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deleted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Survey_Asset_Deletes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Delete__c/fields/Deletion_Reason__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Reason__c</fullName>
    <label>Deletion Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Deleted</fullName>
            </value>
            <value>
                <fullName>Opportunity Line Item Deleted</fullName>
            </value>
            <value>
                <fullName>Opportunity Line Item Quantity Reduced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Asset_Delete__c/fields/Originating_Parent_ID__c.field-meta.xml
<CustomField>
    <fullName>Originating_Parent_ID__c</fullName>
    <externalId>true</externalId>
    <label>Originating Parent ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Delete__c/fields/Originating_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Originating_Record_ID__c</fullName>
    <externalId>true</externalId>
    <label>Originating Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Delete__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Survey Asset Deletes</relationshipLabel>
    <relationshipName>Survey_Asset_Deletes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Delete__c/fields/Survey_Asset_Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Survey_Asset_Location_Id__c</fullName>
    <label>Survey Asset Location Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/Survey_Asset_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Asset Location</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>Survey Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Asset Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Originating_Parent_ID__c.field-meta.xml
<CustomField>
    <fullName>Originating_Parent_ID__c</fullName>
    <externalId>true</externalId>
    <label>Originating Parent ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Originating_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Originating_Record_ID__c</fullName>
    <description>Salesforce Record ID that created this record. Either the opportunity product or the order product record.</description>
    <externalId>true</externalId>
    <label>Originating Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Survey Asset Locations</relationshipLabel>
    <relationshipName>Survey_Asset_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHelper.cls
/**
* @FileName: OpportunityTriggerHelper
* @Description: Helper methods for the Opportunity Trigger
* @Author: Graeme Ward
* @ModificationLog:
*-----------------------------------------------------------
* Author            Date            Modification
* Graeme Ward       3/20/2020         Created
* 
*-----------------------------------------------------------  
*/
public inherited sharing class OpportunityTriggerHelper {
    
    public static String getProductFamilies(Opportunity opp) {
        Set<String> families = new Set<String>();
        
        for (OpportunityLineItem ol : opp.OpportunityLineItems) {
            families.add(ol.Line_of_Business__c);
        }
        
        List<String> productFamilies = new List<String>(families);
        
        return String.join(productFamilies, ';');
    }
    
    public static Id getContactId(Opportunity opp, Quote oppQuote) {
        Id contactId;
        
        if (opp.OpportunityContactRoles.isEmpty()) {
            if (opp.SyncedQuoteId == null) {
                if (oppQuote == null) {
                    contactId = null;
                }
                else {
                    contactId = oppQuote.ContactId;
                }
            }
            else {
                contactId = opp.SyncedQuote.ContactId;
            }
        }
        else {
            contactId = opp.OpportunityContactRoles[0].ContactId;
        }
        
        return contactId;
    }
    
    public static String getOwnerId(Opportunity opp, String productFamilies) {
        Id ownerId;
        system.debug('opp ownerId ' + opp.RecordTypeId);
        if(opp.RecordTypeId == QueryUtils.fieldServiceSettings.Opportunity_RecordType_Frequency_Change__c) {
            ownerId = QueryUtils.fieldServiceSettings.Customer_Service_Queue__c;
            system.debug('case ownerId ' + ownerId);
        }
        else if (productFamilies.contains('Pest Control')) {
            ownerId = QueryUtils.fieldServiceSettings.Pest_Site_Survey_Approval_Queue__c;
            system.debug('case ownerId ' + ownerId);
        }
        else {
            ownerId = QueryUtils.fieldServiceSettings.Hygiene_Site_Survey_Approval_Queue__c;
            system.debug('case ownerId ' + ownerId);
        }
        
        return ownerId;
    }
    
    public static Survey_Asset_Delete__c createSurveyAssetDeleteRecords(Survey_Asset_Location__c sal) {
        return new Survey_Asset_Delete__c(
            Survey_Asset_Location_Id__c = sal.Id,
            Deletion_Reason__c = 'Opportunity Deleted',
            Deleted_By__c = UserInfo.getUserId(),
            Site_Survey__c = sal.Site_Survey__c,
            Originating_Parent_ID__c = sal.Originating_Parent_ID__c,
            Originating_Record_ID__c = sal.Originating_Record_ID__c
        );
    }
}