force-app/main/default/objects/Case/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Work_Order_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Location</label>
    <referenceTo>Work_Order_Room__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Service_Order__c</fullName>
    <label>Service Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Survey Locations</relationshipLabel>
    <relationshipName>Survey_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/Work_Order_Room__c.object-meta.xml
<CustomObject>
    <label>Work Order Location</label>
    <nameField>
        <label>Work Order Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Room__c/fields/Cannot_Complete_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cannot_Complete_Reason__c</fullName>
    <label>Cannot Complete Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broken Unit</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Construction / Renovation</fullName>
            </value>
            <value>
                <fullName>Misc. / Other</fullName>
            </value>
            <value>
                <fullName>Missing Unit</fullName>
            </value>
            <value>
                <fullName>No Access</fullName>
            </value>
            <value>
                <fullName>No Bar Code</fullName>
            </value>
            <value>
                <fullName>Not ready</fullName>
            </value>
            <value>
                <fullName>Refused Service</fullName>
            </value>
            <value>
                <fullName>Scanner Malfunction</fullName>
            </value>
            <value>
                <fullName>Stall Locked</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Could not find unit</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Locked from Inside</fullName>
            </value>
            <value>
                <fullName>Pet in Unit</fullName>
            </value>
            <value>
                <fullName>COVID 19 Related</fullName>
            </value>
            <value>
                <fullName>Could not locate unit</fullName>
                <isActive>false</isActive>
                <label>Could not locate unit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Generate_Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Generate_Work_Order_Line_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Work Order Line Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Work Order Locations</relationshipLabel>
    <relationshipName>Work_Order_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <label>Survey Location</label>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Work_Order_Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Pricebook__c</fullName>
    <formula>CASESAFEID( Work_Order__r.Pricebook2Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Order Pricebook</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Cannot_Complete_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cannot_Complete_Reason__c</fullName>
    <label>Cannot Complete Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COVID 19 Related</fullName>
            </value>
            <value>
                <fullName>Broken Unit</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Construction / Renovation</fullName>
            </value>
            <value>
                <fullName>Misc. / Other</fullName>
            </value>
            <value>
                <fullName>Missing Unit</fullName>
            </value>
            <value>
                <fullName>No Access</fullName>
            </value>
            <value>
                <fullName>No Bar Code</fullName>
            </value>
            <value>
                <fullName>Not ready</fullName>
            </value>
            <value>
                <fullName>Refused Service</fullName>
            </value>
            <value>
                <fullName>Scanner Malfunction</fullName>
            </value>
            <value>
                <fullName>Stall Locked</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
            <value>
                <fullName>Could not find unit</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Locked from Inside</fullName>
            </value>
            <value>
                <fullName>Pet in Unit</fullName>
            </value>
            <value>
                <fullName>Could not locate unit</fullName>
                <isActive>false</isActive>
                <label>Could not locate unit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Work_Order_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Location</label>
    <referenceTo>Work_Order_Room__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WorkOrderLocationLineItemsWrapper.cls
/**
 * @FileName: WorkOrderLocationLineItemsWrapper
 * @Description: Wrapper class to update work order line items with room data
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       2/9/2020         Created
 *-----------------------------------------------------------  
 */
public inherited sharing class WorkOrderLocationLineItemsWrapper {
    private List<Work_Order_Room__c> workOrderRooms;
    private Map<Id, Work_Order_Room__c> oldMap;
    private List<WorkOrderLineItem> cannotCompleteLineItems = new List<WorkOrderLineItem>();
    private Map<Id, Work_Order_Room__c> cannotCompleteWorkOrderRooms = new Map<Id, Work_Order_Room__c>();
    private Map<Id, Work_Order_Room__c> roomsToGenerateLineItem = new Map<Id, Work_Order_Room__c>();
    private Map<Id, Decimal> surveyLocationsAndServiceOrders = new Map<Id, Decimal>();


    public WorkOrderLocationLineItemsWrapper(
            List<Work_Order_Room__c> workOrderRooms,
            Map<Id, Work_Order_Room__c> oldMap)
    {
        this.workOrderRooms = workOrderRooms;
        this.oldMap = oldMap;
        this.cannotCompleteLineItems = new List<WorkOrderLineItem>();
        this.cannotCompleteWorkOrderRooms = new Map<Id, Work_Order_Room__c>();
        this.roomsToGenerateLineItem = new Map<Id, Work_Order_Room__c>();
        this.surveyLocationsAndServiceOrders = new Map<Id, Decimal>();

        updateWorkOrderLineItemsFromRoom();
    }

    private void updateWorkOrderLineItemsFromRoom() {
        for (Work_Order_Room__c wor : workOrderRooms) {
            Work_Order_Room__c oldRec = oldMap.get(wor.Id);

            if(String.isNotBlank(wor.Id)) {
                if (wor.Status__c == QueryUtils.fieldServiceSettings.Cannot_Complete_Status_Value__c
                        && wor.Cannot_Complete_Reason__c != null)
                {
                    cannotCompleteWorkOrderRooms.put(wor.Id, wor);
                }

                if (wor.Generate_Work_Order_Line_Item__c
                        && wor.Work_Order_Pricebook__c != null
                        && wor.Product__c != null)
                {
                    roomsToGenerateLineItem.put(wor.Id, wor);
                }
            }

            if (oldRec.Service_Order__c != wor.Service_Order__c
                    && String.isNotBlank(wor.Survey_Location__c))
            {
                surveyLocationsAndServiceOrders.put(wor.Survey_Location__c, wor.Service_Order__c);
            }
        }


        if (!cannotCompleteWorkOrderRooms.isEmpty()) {
            updateLineItems();
        }

        //case 21478 - generate a Work Order Line Item [dk]
        if (!roomsToGenerateLineItem.isEmpty() && !TriggerHelper.hasRun) {
            createProductConsumedRecords();
        }

        if (!surveyLocationsAndServiceOrders.isEmpty() && !TriggerHelper.isWorkOrderLocationFutureCalled && !System.isFuture() && !System.isBatch()) {
            TriggerHelper.isWorkOrderLocationFutureCalled = true;
            WorkOrderLocationFutureCalls.updateServiceOrder(surveyLocationsAndServiceOrders);
        }

    }

    private void updateLineItems() {
        List<WorkOrderLineItem> wolis = [
                SELECT Id, Cannot_Complete_Reason__c, Work_Order_Location__c
                FROM WorkOrderLineItem
                WHERE Work_Order_Location__c IN :cannotCompleteWorkOrderRooms.keySet()
                ORDER BY Work_Order_Location__c
        ]; //CR21-40 20210407 Darcy AND Cannot_Complete_Reason__c = NULL
		
        for (WorkOrderLineItem woli : wolis) {
            Work_Order_Room__c wor = cannotCompleteWorkOrderRooms.get(woli.Work_Order_Location__c);

            if(wor == null) continue;

            woli.Status = QueryUtils.fieldServiceSettings.Work_Order_Line_Item_CannotComp_Status__c; 
            woli.Cannot_Complete_Reason__c = wor.Cannot_Complete_Reason__c;
            cannotCompleteLineItems.add(woli);
        }

        update cannotCompleteLineItems;
    }

    private void createProductConsumedRecords() {
        TriggerHelper.hasRun = true;

        List<WorkOrderLineItem> items = new List<WorkOrderLineItem>();
        Set<Id> productIds = new Set<Id>();
        Map<Id, Map<Id, Id>> pbe_pb_p2Map = new Map<Id, Map<Id, Id>>();
        Set<Id> pricebookIds = new Set<Id>();
        List<ProductConsumed> pcs = new List<ProductConsumed>();

        for (Work_Order_Room__c wor : roomsToGenerateLineItem.values()) {
            if(String.isNotBlank(wor.Work_Order_Pricebook__c)) {
                pricebookIds.add(wor.Work_Order_Pricebook__c);
            }

            if(String.isNotBlank(wor.Product__c)) {
                productIds.add(wor.Product__c);

                pbe_pb_p2Map.put(
                        wor.Product__c,
                        new Map<Id, Id>{
                                wor.Work_Order_Pricebook__c => null
                        }
                );
            }
        }

        List<PricebookEntry> pbes =  [
                SELECT Id, Product2Id, Pricebook2Id
                FROM PricebookEntry
                WHERE Product2Id IN :pbe_pb_p2Map.keySet()
                AND Pricebook2Id IN :pricebookIds
                AND IsActive = TRUE
                AND Product2.IsActive = TRUE
        ];

        for (PricebookEntry pbe : pbes) {
            pbe_pb_p2Map.get(pbe.Product2Id).put(pbe.Pricebook2Id, pbe.Id);
        }

        for (Work_Order_Room__c wor : roomsToGenerateLineItem.values()) {
            Id pEntryId = pbe_pb_p2Map.get(wor.Product__c).get(wor.Work_Order_Pricebook__c);

            if (pEntryId != null) {
                items.add(new WorkOrderLineItem(
                        WorkOrderId = wor.Work_Order__c,
                        Work_Order_Location__c = wor.Id,
                        Product__c = wor.Product__c,
                        Quantity = 1,
                        PricebookEntryId = pEntryId
                ));
            }
        }

        insert items;

        for (WorkOrderLineItem item : items) {
            pcs.add(new ProductConsumed(
                    WorkOrderId = item.WorkOrderId,
                    PricebookEntryId = item.PricebookEntryId,
                    QuantityConsumed = item.Quantity,
                    WorkOrderLineItemId = item.Id
            ));
        }

        insert pcs;
    }
}