force-app/main/default/objects/OrderMergeBatchSettings__c/OrderMergeBatchSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for the Order Merge Batch job.</description>
    <label>Order Merge Batch Settings</label>
</CustomObject>

force-app/main/default/objects/OrderMergeBatchSettings__c/fields/Order_Item_Field_Set__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_Field_Set__c</fullName>
    <label>Order Item Field Set</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderMergeBatchSettings__c/fields/Order_Item_Filter_Product_Codes__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_Filter_Product_Codes__c</fullName>
    <description>Comma-delimited list of Order Item Product Codes to filter out.</description>
    <inlineHelpText>Comma-delimited list of Order Item Product Codes to filter out.</inlineHelpText>
    <label>Order Item Filter Product Codes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderMergeBatchSettings__c/fields/Order_Item_Filters__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_Filters__c</fullName>
    <description>Comma-delimited list of filters to apply. Filter options include: LastAutomationCreatedDateOrderItemFilter, LastInflightWODateOrderItemFilter, FrequencyOrderItemFilter, ActiveOrderItemFilter.</description>
    <label>Order Item Filters</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MergeSchedulableImplTest.cls
/**
 * Unit test for MergeSchedulableImpl.
 * 
 * @author: Ahsan Butt
 */
@isTest
private class MergeSchedulableImplTest {
    
    static testmethod void testExecute() {
        // Create custom settings
        OrderMergeBatchSettings__c settings = new OrderMergeBatchSettings__c();
        settings.Name = 'Order Merge';
        settings.Batch_Size__c = 10;
        settings.Order_Item_Filters__c = 'LastAutomationCreatedDateOrderItemFilter,LastInflightWODateOrderItemFilter,ProductCodesOrderItemFilter,ActiveOrderItemFilter,FrequencyOrderItemFilter';
        settings.Order_Item_Field_Set__c = 'Clone_Fields';
        settings.Order_Item_Filter_Product_Codes__c = '1-43-12,1-40-23,1-40-33,1-40-43';
        
        insert settings;
        
        // Invoke schedulable
        MergeSchedulableImpl sched = new MergeSchedulableImpl('Test', settings.Name);
        sched.execute(null);
    }
}