force-app/main/default/objects/Order/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>(EffectiveDate &lt;= (Today() +  $Setup.Field_Service_Settings__c.Work_Orders_In_Advance__c )) &amp;&amp; ISPICKVAL(Status, &quot;Activated&quot;) &amp;&amp;  (EndDate &gt; Today() || ISBLANK(EndDate))</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item_Location__c/Order_Item_Location__c.object-meta.xml
<CustomObject>
    <label>Order Item Location</label>
    <nameField>
        <displayFormat>OIL-{000000}</displayFormat>
        <label>Order Item Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Item Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item_Location__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Item Locations</relationshipLabel>
    <relationshipName>Order_Item_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item_Location__c/fields/Survey_Asset_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Asset_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Asset Location</label>
    <referenceTo>Survey_Asset_Location__c</referenceTo>
    <relationshipLabel>Order Item Locations</relationshipLabel>
    <relationshipName>Order_Item_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>IF(PricebookEntry.Product2.Never_Generate_Work_Order__c, FALSE, IF(PricebookEntry.Product2.Heavy_Equipment__c, 
Inventory_Allocated__c &amp;&amp; NOT( ISBLANK(Serial_Number__c) ), 
Order.Inventory_Allocated__c || Order.Emergency__c || Inventory_Allocated__c))</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <formula>PricebookEntry.Product2.Item_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Order Item cannot have the custom Order field set as it&apos;s Inactive.</errorMessage>
        <filterItems>
            <field>$Source.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Active Order Products without PO Number</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Work_Order__c/Related_Work_Order__c.object-meta.xml
<CustomObject>
    <label>Related Work Order</label>
    <nameField>
        <label>Related Work Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Work Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Work_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Related Work Orders</relationshipLabel>
    <relationshipName>Related_Work_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Work_Order__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Related Work Orders</relationshipLabel>
    <relationshipName>Related_Work_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/Survey_Asset_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Asset Location</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>Survey Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Asset Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISBLANK(Survey_Location__c ), &quot;Unallocated&quot;, &quot;Allocated&quot;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>(Last_Batch_Updated_Date__c = TODAY() || Last_Batch_Updated_Date__c = TODAY() + (-1)) &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Completed&apos; &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Cannot Complete&apos; &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Dispatched&apos;</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SpawnWorkOrdersController.cls
public without sharing class SpawnWorkOrdersController {
    
    @AuraEnabled
    public static List<String> createWorkOrder(String recordId) {
        List<String> response = new List<String>{'', '', ''};
            
            if(recordId==null||recordId=='') {
                response[0] = 'error';
                response[2] = 'A record ID has not been provided.';
                System.debug('***** No ID Provided *****\n'+response);
            } else {
                
                Savepoint sp = Database.setSavepoint();

                try {
                    Order record = [SELECT Id, Status, Emergency__c, AccountId FROM Order WHERE Id=:recordId]; 
                    if(record.Emergency__c) {
                        List<OrderItem> productItems = [
                                SELECT Id, Item_Type__c, OrderId
                                FROM OrderItem
                                WHERE OrderId = :recordId
                                AND Item_Type__c !=:QueryUtils.fieldServiceSettings.Item_Type_of_Services__c
                                LIMIT 1
                        ];
                        
                        if(!productItems.isEmpty()) {
                            response[0] = 'error';
                            response[1] = 'Error!';
                            response[2] = ' You should only allocate Services to create an emergency work order. ';
                            System.debug('***** Other Products *****\n' + response);
                        } 
                        else {
                            List<Order_Item_Location__c> s = [
                                    SELECT Id
                                    FROM Order_Item_Location__c
                                    WHERE Order__c = :recordId AND Survey_Asset_Location__r.Status__c = 'Unallocated'
                            ];

                            if (s.isEmpty()) {
                                response[0] = 'success';
                                response[1] = 'Success!';
                                response[2] = 'Work Order(s) Successfully Created!';
                                
                                if(record.Status != QueryUtils.fieldServiceSettings.Order_Active_Stage__c) {
                                    record.Status = QueryUtils.fieldServiceSettings.Order_Active_Stage__c; 
                                    update record; 
                                }
                                
                                DeleteResourcePreferenceBatch del = new DeleteResourcePreferenceBatch(true);
                                del.handleRecords(new Set<Id>{record.AccountId});

                                SpawnWorkOrders sw = new SpawnWorkOrders();
                                sw.spawnWOUtil.fltaccntIds.add(record.AccountId);
                                sw.spawnWOUtil.fltOrderIds.add(record.Id);
                                sw.spawnWOUtil.IS_EMERGENCY=true;
                                sw.processOrders();
                                
                                Set<Id> workorderIds = new Set<Id>();
                                for(Related_Work_Order__c rwo: [SELECT id, WorkOrder__c FROM Related_Work_Order__c 
                                         WHERE Order__c =:record.Id AND WorkOrder__r.isValid__c = TRUE]){
                                            workorderIds.add(rwo.WorkOrder__c);
                                }


                                if(workorderIds.size()>0){
                                    //Generate Work Order Rooms
                                    SpawnWorkOrderRooms swr = new SpawnWorkOrderRooms();
                                    swr.processWorkOrders(workorderIds);    
                                    //Generate Service Appointments
                                    SpawnServiceAppointments ssp = new SpawnServiceAppointments();
                                    ssp.processWorkOrders(workorderIds);
                                }
                                
                                //SpawnWorkOrderFiles swf = new SpawnWorkOrderFiles(recordId, true);
                                //swf.processWorkOrderFiles(new Set<Id>{recordId});

                            } else {
                                response[0] = 'error';
                                response[1] = 'Error!';
                                response[2] = s.size()+' item(s) have not been allocated for this Order. Please allocate these items before creating a Work Order.';
                                System.debug('***** Unallocated Items *****\n'+response); 
                            }
                        }
                    } else {
                        response[0] = 'error';
                        response[1] = 'Error!';
                        response[2] = ' This is not an emergency Order. Please wait for the nightly job to create Work Orders and Service Appointments Or check the Emergency checkbox. ';
                        System.debug('***** No Services *****\n'+response);
                    }
                    
                } catch(DMLException e) {
                    Database.rollback(sp);
                    response[0]='error';
                    response[1]='Error!';
                    response[2]='An error has occured: ';
                    for (Integer i = 0; i < e.getNumDml(); i++) {
                        response[2]+=(e.getDmlMessage(i)+'\n');
                    }
                    System.debug('***** DML ERROR *****\n'+response+'\n\n'+e);
                } catch(Exception e) {
                    Database.rollback(sp);
                    response[0]='error';
                    response[1]='Error!';
                    response[2]='An error has occured: '+e.getMessage();
                    System.debug('***** ERROR *****\n'+response+'\n\n'+e);
                }
            }
        return response;    
    }
    
    @AuraEnabled
    public static List<String> compareWorkOrderToAppointments(String recordId) {
        String workOrderPrefix = Schema.WorkOrder.SObjectType.getDescribe().getKeyPrefix();
        List<String> response = new List<String>{'', '', ''};
            
        if(recordId.startsWith(workOrderPrefix)) {
            WorkOrder w = [
                    SELECT Id, Duration,
                            (SELECT Id, Duration
                            FROM ServiceAppointments)
                    FROM WorkOrder
                    WHERE Id = :recordId
            ];
            
            Decimal woDuration = w.Duration != null ? w.Duration:0;
            
            Decimal apptDuration = 0;
            
            if (w.ServiceAppointments != null && !w.ServiceAppointments.isEmpty()) {
                for (ServiceAppointment s : w.ServiceAppointments) {
                    if(s.Duration != null) {
                        apptDuration += s.Duration;
                    }
                }
            }
            
            if(woDuration > apptDuration) {
                response[0] = 'warning';
                response[1] = 'Warning!';
                response[2] = 'Work Order Duration (' + woDuration + ' hours) exceeds Service Appointment Duration  (' + apptDuration + ' hours)!';
            }
        }
        return response;    
    }
}