force-app/main/default/objects/Order/fields/Order_Merge_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Merge_Job_Status__c</fullName>
    <description>Used by the Order Merge batch job. Set the value to ‘To be Processed’ to have the batch job pick this record up.</description>
    <inlineHelpText>Used by the Order Merge batch job. Set the value to ‘To be Processed’ to have the batch job pick this record up.</inlineHelpText>
    <label>Order Merge Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ready for Work Order Reparenting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Surviving_Order__c.field-meta.xml
<CustomField>
    <fullName>Surviving_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surviving Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Surviving Order must have same account</errorMessage>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Surviving Order)</relationshipLabel>
    <relationshipName>SurvivingOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderMergeBatchSettings__c/WorkOrderMergeBatchSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Work Order Merge Batch Settings</label>
</CustomObject>

force-app/main/default/classes/WorkOrderMergeSchedulableImpl.cls
/**
 * A generic schedulable implementation that kicks off a batch job to perform Work Order merges based on a specified custom setting. This is related to the Order Merge functionality.
 * 
 * @author Ahsan Butt
 */

public class WorkOrderMergeSchedulableImpl implements ICustomSchedulable {
    public String batchJobName;
    public String customSettingsRecordName;
    
    private Integer DEFAULT_BATCH_SIZE = 10;
    
    private final static String MERGE_STATUS_READY_FOR_WO_REPARENTING = 'Ready for Work Order Reparenting';
    
    public WorkOrderMergeSchedulableImpl() {
    	setBatchJobName('Work Order Merge Batch Job');
        setCustomSettingsRecordName('Work Order Merge');
    }
    
    public WorkOrderMergeSchedulableImpl(String jobName, String csRecordName) {
        setBatchJobName(jobName);
        setCustomSettingsRecordName(csRecordName);
    }
    
    public void setBatchJobName(String name) {
        batchJobName = name;
    }
    
    public void setCustomSettingsRecordName(String name) {
        customSettingsRecordName = name;
    }
    
    public void execute(SchedulableContext context) {
        List<WorkOrderMergeBatchSettings__c> mergeSettings = [SELECT Name, Batch_Size__c
                                                     	  	  FROM WorkOrderMergeBatchSettings__c
                                                     	  	  WHERE Name =: customSettingsRecordName LIMIT 1];
        
        WorkOrderMergeBatchSettings__c mergeS = mergeSettings[0];
        
        
        String query = 'SELECT Id, Order__c, Order__r.Surviving_Order__c, (SELECT Id, Order_Product__c, OrderId FROM WorkOrderLineItems WHERE Order_Product__c != null) FROM WorkOrder WHERE Order__r.Surviving_Order__c != null AND Order__r.Order_Merge_Job_Status__c = \'' + MERGE_STATUS_READY_FOR_WO_REPARENTING + '\'';
        String batchExecutorClass = 'WorkOrderBatchExecutorImpl';
        
        BatchJobImpl b = new BatchJobImpl(batchJobName, query, false, batchExecutorClass, null);
        
        Integer batchSize = mergeS.Batch_Size__c != null ? (Integer) mergeS.Batch_Size__c : DEFAULT_BATCH_SIZE;
        
        Database.executeBatch(b, batchSize);
    }
}