force-app/main/default/objects/Order/fields/Order_Merge_Job_Message__c.field-meta.xml
<CustomField>
    <fullName>Order_Merge_Job_Message__c</fullName>
    <description>Used by the Order Merge batch job.</description>
    <inlineHelpText>Used by the Order Merge batch job.</inlineHelpText>
    <label>Order Merge Job Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Merge_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Merge_Job_Status__c</fullName>
    <description>Used by the Order Merge batch job. Set the value to ‘To be Processed’ to have the batch job pick this record up.</description>
    <inlineHelpText>Used by the Order Merge batch job. Set the value to ‘To be Processed’ to have the batch job pick this record up.</inlineHelpText>
    <label>Order Merge Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ready for Work Order Reparenting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prevent_Invoice_Change_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Invoice_Change_Ticket__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to prevent the Invoice Change Ticket from being created</description>
    <inlineHelpText>Used to prevent the Invoice Change Ticket from being created</inlineHelpText>
    <label>Prevent Invoice Change Ticket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Surviving_Order__c.field-meta.xml
<CustomField>
    <fullName>Surviving_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surviving Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Surviving Order must have same account</errorMessage>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Surviving Order)</relationshipLabel>
    <relationshipName>SurvivingOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderMergeBatchSettings__c/OrderMergeBatchSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for the Order Merge Batch job.</description>
    <label>Order Merge Batch Settings</label>
</CustomObject>

force-app/main/default/objects/OrderMergeBatchSettings__c/fields/Order_Item_Field_Set__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_Field_Set__c</fullName>
    <label>Order Item Field Set</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderMergeBatchSettings__c/fields/Order_Item_Filter_Product_Codes__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_Filter_Product_Codes__c</fullName>
    <description>Comma-delimited list of Order Item Product Codes to filter out.</description>
    <inlineHelpText>Comma-delimited list of Order Item Product Codes to filter out.</inlineHelpText>
    <label>Order Item Filter Product Codes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderMergeBatchSettings__c/fields/Order_Item_Filters__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_Filters__c</fullName>
    <description>Comma-delimited list of filters to apply. Filter options include: LastAutomationCreatedDateOrderItemFilter, LastInflightWODateOrderItemFilter, FrequencyOrderItemFilter, ActiveOrderItemFilter.</description>
    <label>Order Item Filters</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MergeSchedulableImpl.cls
/**
 * A generic schedulable implementation that kicks off a batch job to perform merges based on a specified custom setting.
 * 
 * @author Ahsan Butt
 */

public class MergeSchedulableImpl implements ICustomSchedulable {
    public String batchJobName;
    public String customSettingsRecordName;
    
    private Integer DEFAULT_BATCH_SIZE = 20;
    
    private String STATUS_TO_BE_PROCESSED = 'To be Processed';
    
    public MergeSchedulableImpl() {
    	setBatchJobName('Order Merge Batch Job');
        setCustomSettingsRecordName('Order Merge');
    }
    
    public MergeSchedulableImpl(String jobName, String csRecordName) {
        setBatchJobName(jobName);
        setCustomSettingsRecordName(csRecordName);
    }
    
    public void setBatchJobName(String name) {
        batchJobName = name;
    }
    
    public void setCustomSettingsRecordName(String name) {
        customSettingsRecordName = name;
    }
    
    public void execute(SchedulableContext context) {
        List<OrderMergeBatchSettings__c> mergeSettings = [SELECT Name,Batch_Size__c, Order_Item_Filters__c, 
                                                          	Order_Item_Field_Set__c, Order_Item_Filter_Product_Codes__c
                                                     	  FROM OrderMergeBatchSettings__c
                                                     	  WHERE Name =: customSettingsRecordName LIMIT 1];
        
        OrderMergeBatchSettings__c mergeS = mergeSettings[0];
        
        Map<String, String> params = new Map<String, String>();
        params.put('OrderItemFilters', mergeS.Order_Item_Filters__c);
        params.put('OrderItemFieldSet', mergeS.Order_Item_Field_Set__c);
        params.put('OrderItemFilterProductCodes', mergeS.Order_Item_Filter_Product_Codes__c);
        
        String query = 'SELECT Id, Surviving_Order__c, Status, Prevent_Invoice_Change_Ticket__c, Order_Merge_Job_Status__c, Order_Merge_Job_Message__c FROM Order WHERE Surviving_Order__c != null AND Order_Merge_Job_Status__c = \'' + STATUS_TO_BE_PROCESSED + '\'';
        String batchExecutorClass = 'OrderMergeBatchExecutorImpl';
        
        BatchJobImpl b = new BatchJobImpl(batchJobName, query, false, batchExecutorClass, params);
        
        Integer batchSize = mergeS.Batch_Size__c != null ? (Integer) mergeS.Batch_Size__c : DEFAULT_BATCH_SIZE;
        Database.executeBatch(b, batchSize);
    }
}