force-app/main/default/objects/Activity_Infestation__c/Activity_Infestation__c.object-meta.xml
<CustomObject>
    <label>Activity / Infestation</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Activity/Infestation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities / Infestations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Infestation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Asset_Bar_Code__c.field-meta.xml
<CustomField>
    <fullName>Asset_Bar_Code__c</fullName>
    <label>Asset Bar Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Location</label>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Work_Order_Room__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Room</label>
    <referenceTo>Work_Order_Room__c</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bar_Code__c.field-meta.xml
<CustomField>
    <fullName>Bar_Code__c</fullName>
    <label>Bar Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Site_Survey__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Survey_Location__c.Site_Survey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site_Survey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Work_Order_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Location</label>
    <referenceTo>Work_Order_Room__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Site_Survey__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Survey_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Survey Locations</relationshipLabel>
    <relationshipName>Survey_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/Work_Order_Room__c.object-meta.xml
<CustomObject>
    <label>Work Order Location</label>
    <nameField>
        <label>Work Order Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Room__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <formula>CASESAFEID( Work_Order__r.AccountId )</formula>
    <label>AccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <label>Survey Location</label>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Bar_Code__c.field-meta.xml
<CustomField>
    <fullName>Bar_Code__c</fullName>
    <formula>Asset.Bar_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bar Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Work_Order_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Location</label>
    <referenceTo>Work_Order_Room__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ActivityInfestationTriggerHandler.cls
/**
 * @FileName: ActivityInfestationTriggerHandler
 * @Description: Handler for Activity Infestation trigger
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       1/16/2020       Created
 *-----------------------------------------------------------  
 */
public class ActivityInfestationTriggerHandler extends TriggerHandler {
    private List<Activity_Infestation__c> activityInfestations;
    private List<Activity_Infestation__c> oldList;
    private Map<Id,Activity_Infestation__c> activityInfestationsMap;
    private Map<Id,Activity_Infestation__c> oldMap;

    public ActivityInfestationTriggerHandler() {
        this.setMaxLoopCount(5);

        this.activityInfestations = (List<Activity_Infestation__c>) Trigger.new;
        this.oldList = (List<Activity_Infestation__c>) Trigger.old;
        this.activityInfestationsMap = (Map<Id,Activity_Infestation__c>) Trigger.newMap;
        this.oldMap = (Map<Id,Activity_Infestation__c>) Trigger.oldMap;
    }

    protected override void beforeInsert() {
        setActivityInfestationFields();
    }

    protected override void beforeUpdate() {
        setActivityInfestationFields();
    }
    
    private void setActivityInfestationFields() {
        Map<String,Asset> assetMap = new Map<String,Asset>();
        Map<Id,WorkOrderLineItem> woliMap = new Map<Id,WorkOrderLineItem>();
        Map<Id,Work_Order_Room__c> worMap = new Map<Id,Work_Order_Room__c>();

        for (Activity_Infestation__c a : activityInfestations) {
            if (String.isNotBlank(a.Asset_Bar_Code__c)) {
                assetMap.put(a.Asset_Bar_Code__c, null);
            }
            if (String.isNotBlank(a.Work_Order_Line_Item__c)) {
                woliMap.put(a.Work_Order_Line_Item__c, null);
            } else if (String.isNotBlank(a.Work_Order_Room__c)) {
                worMap.put(a.Work_Order_Room__c, null);
            }
        }

        if (!assetMap.isEmpty()) {
            List<Asset> assets = [SELECT Id, Bar_Code__c FROM Asset WHERE Bar_Code__c IN :assetMap.keySet()];

            for (Asset a : assets) {
                assetMap.put(a.Bar_Code__c, a);
            }
        }

        if (!woliMap.isEmpty()) {
            woliMap = new Map<Id,WorkOrderLineItem>([
                    SELECT Id, WorkOrderId, WorkOrder.AccountId, OrderId, WorkOrder.Site_Survey__c,
                            Work_Order_Location__r.Survey_Location__c, Work_Order_Location__c
                    FROM WorkOrderLineItem
                    WHERE Id IN :woliMap.keySet()
            ]);
        }

        if (!worMap.isEmpty()) {
            worMap = new Map<Id,Work_Order_Room__c>([
                    SELECT Id, Work_Order__c, Site_Survey__c, Survey_Location__c, AccountId__c, Work_Order__r.Order__c
                    FROM Work_Order_Room__c
                    WHERE Id IN :worMap.keySet()
            ]);
        }

        for (Activity_Infestation__c a : activityInfestations) {
            Asset scannedAsset = assetMap.get(a.Asset_Bar_Code__c);

            if (scannedAsset != null) {
                a.Asset__c = scannedAsset.Id;
            }

            if (String.isNotBlank(a.Work_Order_Line_Item__c)) {
                WorkOrderLineItem li = woliMap.get(a.Work_Order_Line_Item__c);

                if (li != null) {
                    a.Work_Order__c = li.WorkOrderId;
                    a.Account__c = li.WorkOrder.AccountId;
                    a.Order__c = li.OrderId;
                    a.Site_Survey__c = li.WorkOrder.Site_Survey__c;
                    a.Work_Order_Room__c = li.Work_Order_Location__c;
                    a.Survey_Location__c = li.Work_Order_Location__r.Survey_Location__c;
                }
            } else if (String.isNotBlank(a.Work_Order_Room__c)) {
                Work_Order_Room__c wor = worMap.get(a.Work_Order_Room__c);

                if (wor != null) {
                    a.Work_Order__c = wor.Work_Order__c;
                    a.Account__c = wor.AccountId__c;
                    a.Order__c = wor.Work_Order__r.Order__c;
                    a.Site_Survey__c = wor.Site_Survey__c;
                    a.Work_Order_Room__c = wor.Id;
                    a.Survey_Location__c = wor.Survey_Location__c;
                }
            }
        }
    }
}