force-app/main/default/objects/Activity_Infestation__c/Activity_Infestation__c.object-meta.xml
<CustomObject>
    <label>Activity / Infestation</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Activity/Infestation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities / Infestations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Infestation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Location</label>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Infestation__c/fields/Work_Order_Room__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Room</label>
    <referenceTo>Work_Order_Room__c</referenceTo>
    <relationshipLabel>Activities / Infestations</relationshipLabel>
    <relationshipName>Activities_Infestations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Site_Survey__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Survey_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Survey Locations</relationshipLabel>
    <relationshipName>Survey_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/Work_Order_Room__c.object-meta.xml
<CustomObject>
    <label>Work Order Location</label>
    <nameField>
        <label>Work Order Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Room__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <formula>CASESAFEID( Work_Order__r.AccountId )</formula>
    <label>AccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <label>Survey Location</label>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Work_Order_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Location</label>
    <referenceTo>Work_Order_Room__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ActivityInfestationTriggerTest.cls
/**
 * @FileName: ActivityInfestationTriggerTest
 * @Description: Test methods for the Activity Infestation trigger
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       1/27/2020         Created
 *-----------------------------------------------------------  
 */
@IsTest
private class ActivityInfestationTriggerTest {

    @TestSetup
    static void setupTest() {
        setupHelper();
    }

    @IsTest
    static void insertWithLineItem(){
        WorkOrderLineItem li = [
                SELECT Id, WorkOrderId, WorkOrder.AccountId, OrderId, WorkOrder.Site_Survey__c, Work_Order_Location__c,
                        Work_Order_Location__r.Survey_Location__c
                FROM WorkOrderLineItem
                LIMIT 1
        ];

        Activity_Infestation__c ai = (Activity_Infestation__c) TestUtils.createSObject(
                new Activity_Infestation__c(
                        Work_Order_Line_Item__c = li.Id
                )
        );

        Test.startTest();
        insert ai;
        Test.stopTest();

        Activity_Infestation__c aiAfter = [
                SELECT Work_Order__c, Account__c, Order__c, Site_Survey__c, Survey_Location__c, Work_Order_Room__c
                FROM Activity_Infestation__c
                WHERE Id = :ai.Id
        ];

        System.assertEquals(li.WorkOrderId, aiAfter.Work_Order__c);
        System.assertEquals(li.WorkOrder.AccountId, aiAfter.Account__c);
        System.assertEquals(li.OrderId, aiAfter.Order__c);
        System.assertEquals(li.WorkOrder.Site_Survey__c, aiAfter.Site_Survey__c);
        System.assertEquals(li.Work_Order_Location__c, aiAfter.Work_Order_Room__c);
        System.assertEquals(li.Work_Order_Location__r.Survey_Location__c, aiAfter.Survey_Location__c);
    }

    @IsTest
    static void updateWithLocation(){
        Work_Order_Room__c wor = [
                SELECT Id, Work_Order__c, AccountId__c, Work_Order__r.Order__c, Site_Survey__c, Survey_Location__c
                FROM Work_Order_Room__c
                LIMIT 1
        ];

        Activity_Infestation__c ai = (Activity_Infestation__c) TestUtils.createSObject(
                new Activity_Infestation__c(),
                true
        );

        Activity_Infestation__c aiBefore = [
                SELECT Work_Order__c, Account__c, Order__c, Site_Survey__c, Survey_Location__c, Work_Order_Room__c
                FROM Activity_Infestation__c
                WHERE Id = :ai.Id
        ];

        Test.startTest();
        ai.Work_Order_Room__c = wor.Id;
        update ai;
        Test.stopTest();

        Activity_Infestation__c aiAfter = [
                SELECT Work_Order__c, Account__c, Order__c, Site_Survey__c, Survey_Location__c, Work_Order_Room__c
                FROM Activity_Infestation__c
                WHERE Id = :ai.Id
        ];

        System.assertNotEquals(wor.Work_Order__c, aiBefore.Work_Order__c);
        System.assertNotEquals(wor.AccountId__c, aiBefore.Account__c);
        System.assertNotEquals(wor.Work_Order__r.Order__c, aiBefore.Order__c);
        System.assertNotEquals(wor.Site_Survey__c, aiBefore.Site_Survey__c);
        System.assertNotEquals(wor.Id, aiBefore.Work_Order_Room__c);
        System.assertNotEquals(wor.Survey_Location__c, aiBefore.Survey_Location__c);
        System.assertEquals(wor.Work_Order__c, aiAfter.Work_Order__c);
        System.assertEquals(wor.AccountId__c, aiAfter.Account__c);
        System.assertEquals(wor.Work_Order__r.Order__c, aiAfter.Order__c);
        System.assertEquals(wor.Site_Survey__c, aiAfter.Site_Survey__c);
        System.assertEquals(wor.Id, aiAfter.Work_Order_Room__c);
        System.assertEquals(wor.Survey_Location__c, aiAfter.Survey_Location__c);
    }

    // HELPER METHODS
    static void setupHelper() {
        TestUtils.createSObject(new Field_Service_Settings__c(), true);

        TestUtilsWrapperPricebook pricebookWrapper = new TestUtilsWrapperPricebook(20);
        TestUtilsWrapperAccount accountWrapper = new TestUtilsWrapperAccount();
        TestUtilsWrapperOrder orderWrapper = new TestUtilsWrapperOrder(accountWrapper, pricebookWrapper);
        new TestUtilsWrapperWorkOrder(accountWrapper, orderWrapper);
    }
}