force-app/main/default/objects/Standing_Order__c/Standing_Order__c.object-meta.xml
<CustomObject>
    <label>Standing Order</label>
    <nameField>
        <label>Standing Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standing Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Standing_Order__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If the record is in Accpac, it is considered Active.</description>
    <inlineHelpText>If the record is in Accpac, it is considered Active.</inlineHelpText>
    <label>SO Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Standing_Order__c/fields/Upsert_Date__c.field-meta.xml
<CustomField>
    <fullName>Upsert_Date__c</fullName>
    <description>The date/time the data was exported from Accpac for the upsert.</description>
    <label>Upsert Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/StandingOrder.cls
public class StandingOrder{
   
    public static void setActive() {
       
        for (Standing_Order__c[] standingOrders:[SELECT Active__c from Standing_Order__c WHERE Upsert_Date__c > LAST_WEEK AND Active__c = FALSE LIMIT 10000])
        {
            for (Standing_Order__c s:standingOrders){
               s.Active__c = TRUE;
            }
            Update(standingOrders);
        }
        
    }
    
    public static void setInActive() {
       
        for (Standing_Order__c[] standingOrders:[SELECT Active__c from Standing_Order__c WHERE (Upsert_Date__c <= LAST_WEEK or Upsert_Date__c = null) AND Active__c = TRUE LIMIT 10000])
        {
            for (Standing_Order__c s:standingOrders){
               s.Active__c = FALSE;
            }
            Update(standingOrders);
        }
        
    }

}