force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <description>Used to track issues related to business systems, like Salesforce,</description>
    <label>Issue</label>
    <nameField>
        <label>Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/Business_Impact_Score__c.field-meta.xml
<CustomField>
    <fullName>Business_Impact_Score__c</fullName>
    <inlineHelpText>Score created from Business Value Driver dropdowns</inlineHelpText>
    <label>Business Impact Score</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Business_Impact_Score_Override__c.field-meta.xml
<CustomField>
    <fullName>Business_Impact_Score_Override__c</fullName>
    <inlineHelpText>Enter a value here to override the Business Impact Score. Only specific users have the ability to update this field.</inlineHelpText>
    <label>Business Impact Score Override</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Cost_One_Time__c.field-meta.xml
<CustomField>
    <fullName>Cost_One_Time__c</fullName>
    <inlineHelpText>One time costs such as services to build</inlineHelpText>
    <label>Cost  (One Time)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - &lt;$5K</fullName>
            </value>
            <value>
                <fullName>2 - $5 - $20K</fullName>
            </value>
            <value>
                <fullName>3 - $20 - $50K</fullName>
            </value>
            <value>
                <fullName>4 - $50 - $100K</fullName>
            </value>
            <value>
                <fullName>5 - &gt;$100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Cost_Recurring_Annual__c.field-meta.xml
<CustomField>
    <fullName>Cost_Recurring_Annual__c</fullName>
    <inlineHelpText>Recurring costs such as pre-scheduled maintenance, software subscriptions or licenses</inlineHelpText>
    <label>Cost (Recurring - Annual)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - &lt;$5K</fullName>
            </value>
            <value>
                <fullName>2 - $5 - $20K</fullName>
            </value>
            <value>
                <fullName>3 - $20 - $50K</fullName>
            </value>
            <value>
                <fullName>4 - $50 - $100K</fullName>
            </value>
            <value>
                <fullName>5 - &gt;$100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Scoring_Settings__c/Issue_Scoring_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Issue Scoring Settings</label>
</CustomObject>

force-app/main/default/objects/Issue_Scoring_Settings__c/fields/Override_Field__c.field-meta.xml
<CustomField>
    <fullName>Override_Field__c</fullName>
    <description>The name of an Issue field that can override the calculated score.</description>
    <inlineHelpText>The name of an Issue field that can override the calculated score.</inlineHelpText>
    <label>Override Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Scoring_Settings__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <label>Target Field</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Scoring_Settings__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestIssueScorer.cls
/**
 * Test class for Issue Scorer
 * @author: Ahsan Butt 
 */

@isTest
public class TestIssueScorer {
    
    private static Issue_Scoring_Settings__c createScoreSetting(String source, String target, Decimal weight, String overrideField) {        
        Issue_Scoring_Settings__c setting = new Issue_Scoring_Settings__c();
        setting.Name = source;
        setting.Source_Field__c = source;
        setting.Target_Field__c = target;
        setting.Weight__c = weight;
        setting.Override_Field__c = overrideField;
        
        return setting;
    }
    
    static testMethod void testScoreSettings() {
    	// Insert score settings
        List<Issue_Scoring_Settings__c> settings = new List<Issue_Scoring_Settings__c>();
        settings.add(createScoreSetting('Cost_One_Time__c', 'Business_Impact_Score__c', 0.25, ''));
        settings.add(createScoreSetting('Cost_Recurring_Annual__c', 'Business_Impact_Score__c', 0.75, ''));
        insert settings;
        
        // Insert issue
		Issue__c i = new Issue__c();
        i.Name = 'Test Issue';
        i.Cost_One_Time__c = '1 - <$5K';
        i.Cost_Recurring_Annual__c = '5 - >$100K';
        
        insert i;
        
        // Retrieve the issue
        List<Issue__c> issueAfterScoring = [SELECT Id, Business_Impact_Score__c
                                           	FROM Issue__c
                                            WHERE Id =: i.Id];
        
        Decimal expectedScore = (0.25 * 1) + (0.75 * 5);
        
        System.assertEquals(expectedScore, issueAfterScoring.get(0).Business_Impact_Score__c, 'Score should match.');
    }
    
        static testMethod void testOverrideSettings() {
    	// Insert score settings
        List<Issue_Scoring_Settings__c> settings = new List<Issue_Scoring_Settings__c>();
        settings.add(createScoreSetting('Cost_One_Time__c', 'Business_Impact_Score__c', 0.25, ''));
        settings.add(createScoreSetting('Cost_Recurring_Annual__c', 'Business_Impact_Score__c', 0.75, 'Business_Impact_Score_Override__c'));
        insert settings;
        
        // Insert issue
		Issue__c i = new Issue__c();
        i.Name = 'Test Issue';
        i.Cost_One_Time__c = '1 - <$5K';
        i.Cost_Recurring_Annual__c = '5 - >$100K';
        i.Business_Impact_Score_Override__c = 50;
        
        insert i;
        
        // Retrieve the issue
        List<Issue__c> issueAfterScoring = [SELECT Id, Business_Impact_Score__c
                                           	FROM Issue__c
                                            WHERE Id =: i.Id];
        
        
        System.assertEquals(i.Business_Impact_Score_Override__c, issueAfterScoring.get(0).Business_Impact_Score__c, 'Score should match override.');
    }
}