force-app/main/default/objects/Asset/fields/Bar_Code__c.field-meta.xml
<CustomField>
    <fullName>Bar_Code__c</fullName>
    <label>Bar Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/IsReallocated__c.field-meta.xml
<CustomField>
    <fullName>IsReallocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Reallocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Last_Scanned_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Scanned_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Scanned By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Last_Scanned_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Last_Scanned_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Scanned Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Site_Survey__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Survey_Location__c.Site_Survey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site_Survey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Work_Order_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Location</label>
    <referenceTo>Work_Order_Room__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Does_not_require_scanning__c.field-meta.xml
<CustomField>
    <fullName>Does_not_require_scanning__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicate whether this item requires Scanning by Technician onsite or not</inlineHelpText>
    <label>Does not require scanning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Survey_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Survey Locations</relationshipLabel>
    <relationshipName>Survey_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/Work_Order_Room__c.object-meta.xml
<CustomObject>
    <label>Work Order Location</label>
    <nameField>
        <label>Work Order Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Room__c/fields/PestAuditable__c.field-meta.xml
<CustomField>
    <fullName>PestAuditable__c</fullName>
    <formula>Work_Order__r.Account.PEST_Auditable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PestAuditable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Scanned_In_Excess_Bar_Codes__c.field-meta.xml
<CustomField>
    <fullName>Scanned_In_Excess_Bar_Codes__c</fullName>
    <label>Scanned In (Excess Bar Codes)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Scanned_In_Unknown_Barcodes__c.field-meta.xml
<CustomField>
    <fullName>Scanned_In_Unknown_Barcodes__c</fullName>
    <label>Scanned In (Unknown Barcodes)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Scanned_Out_Excess_Bar_Codes__c.field-meta.xml
<CustomField>
    <fullName>Scanned_Out_Excess_Bar_Codes__c</fullName>
    <label>Scanned Out (Excess Bar Codes)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Scanned_Out_Unknown_Barcodes__c.field-meta.xml
<CustomField>
    <fullName>Scanned_Out_Unknown_Barcodes__c</fullName>
    <label>Scanned Out (Unknown Barcodes)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <label>Survey Location</label>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Order_Room__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>Work_Order_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of Work Order, whether it is a delivery or a work order for a particular line of business</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Work Order</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>NoWork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Bar_Code__c.field-meta.xml
<CustomField>
    <fullName>Bar_Code__c</fullName>
    <formula>Asset.Bar_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bar Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Type_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Service__c</fullName>
    <label>Type of Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Work_Order_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Location</label>
    <referenceTo>Work_Order_Room__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WorkOrderLocationTriggerHelper.cls
/**
 * @FileName: WorkOrderLocationTriggerHelper
 * @Description: Helper methods for Work Order Location trigger
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       2/9/2020         Created
 *-----------------------------------------------------------  
 */
public inherited sharing class WorkOrderLocationTriggerHelper {

    public static List<Asset> getAssets(Set<String> scannedInBarCodes, Set<String> scannedOutBarCodes) {
        return [
                SELECT Id, AccountId, Status, Product2Id, Bar_Code__c, InstallDate
                FROM Asset
                WHERE Bar_Code__c != NULL
                AND (Bar_Code__c IN :scannedInBarCodes
                    OR Bar_Code__c IN :scannedOutBarCodes)
        ];
    }

    public static List<WorkOrderLineItem> getWorkOrderLineItems(Set<Id> workOrderRoomIds) {
        System.debug('In getWorkOrderLineItems these are wol ids'+workOrderRoomIds);
        return [
                SELECT Id, Work_Order_Location__c, Work_Order_Location__r.Work_Order__r.Line_of_Business__c, Status,
                        Completed_Date__c, PricebookEntry.Product2.Family,
                        PricebookEntry.Product2.Does_not_require_scanning__c
                FROM WorkOrderLineItem
                WHERE Status != :QueryUtils.fieldServiceSettings.Work_Order_Line_Item_Completed_Status__c
                AND Work_Order_Location__c IN :workOrderRoomIds
                AND ((PricebookEntry.Product2.Family = :QueryUtils.fieldServiceSettings.Pest_LOB__c
                        OR PricebookEntry.Product2.Does_not_require_scanning__c = TRUE)
                    OR (Work_Order_Location__r.Work_Order__r.Line_of_Business__c = :QueryUtils.fieldServiceSettings.Pest_LOB__c
                        AND Work_Order_Location__r.PestAuditable__c = FALSE))
        ];
    }

    public static List<Work_Order_Room__c> getWorkOrderRooms(Set<Id> workOrderRoomIds) {
        return [
                SELECT Id, Work_Order__r.Line_of_Business__c, Work_Order__r.Site_Survey__c, Survey_Location__c,
                        PestAuditable__c, Work_Order__r.Type__c, Work_Order__r.AccountId,
                        Scanned_In_Excess_Bar_Codes__c, Scanned_In_Unknown_Barcodes__c,
                        Scanned_Out_Excess_Bar_Codes__c, Scanned_Out_Unknown_Barcodes__c, Status__c, (
                        SELECT Id, Bar_Code__c, Status, AssetId, Asset.IsReallocated__c, Asset.Last_Scanned_Date__c,
                                Asset.Last_Scanned_Work_Order__c, Asset.Last_Scanned_By__c, WorkOrderId, Product2Id,
                                Type_of_Service__c
                        FROM Work_Order_Line_Items__r
                        WHERE Status != :QueryUtils.fieldServiceSettings.Work_Order_Line_Item_Completed_Status__c
                        OR Type_of_Service__c = :QueryUtils.fieldServiceSettings.Label_for_Replace_Work_Order_Type__c
                        ORDER BY AssetId NULLS LAST
                )
                FROM Work_Order_Room__c
                WHERE Id IN :workOrderRoomIds
        ];
    }
}