force-app/main/default/objects/Asset/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Site_Survey__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Duration_Adjustment_Time__c.field-meta.xml
<CustomField>
    <fullName>Duration_Adjustment_Time__c</fullName>
    <formula>IF(Security_Sign_in_out__c,7,0) + 
IF(Key_Card_Required__c,4,0) +
IF(Escort_Required__c,5,0) + 
IF(Meet_with_Contact_Prior_to_Work__c,10,0) +
IF(Remove_Equipment_from_Vehicle__c,5,0) + 
IF(Signature_Required__c,5,0) +
IF(Reload_Van__c,5,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration Adjustment Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Pest_Duration_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Pest_Duration_Calculation__c</fullName>
    <inlineHelpText>In Minutes</inlineHelpText>
    <label>Pest Duration Calculation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Signature_Required_For__c.field-meta.xml
<CustomField>
    <fullName>Signature_Required_For__c</fullName>
    <inlineHelpText>The system always checks Pest Control SAs for signatures, even if Pest line of business is not selected here.  Additionally, system always checks if signature was captured for: 

-Deliveries

-VMI Account SAs

-SAs with Products Consumed</inlineHelpText>
    <label>Signature Required For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServicePlanUtils.cls
/**
 * @FileName: ServicePlanUtils
 * @Description: Utility methods for Service Plan and Fixed Routing logic
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       11/27/2019      Created
 *-----------------------------------------------------------  
 */
public inherited sharing class ServicePlanUtils {
    // flag to bypass order and order product trigger errors when updating active orders
    public static Boolean allowActiveOrderUpdates = false;

    /*
     * @Name        getSiteSurveyMap
     * @Description Get a map of site survey records by id that contains all of the fields required to evaluate
     *              site survey adjustments
     * @Author      Graeme Ward
     * @Params      siteSurveyIds: set of site survey ids to be queried
     * @Return      Map<Id,Site_Survey__c: map of site survey records by id
     */
    public static Map<Id,Site_Survey__c> getSiteSurveyMap(Set<Id> siteSurveyIds) {
        String siteSurveyQuery = 'SELECT Id, Pest_Duration_Calculation__c, Signature_Required_For__c, Duration_Adjustment_Time__c';

        for(List<String> fields : ServicePlanConstants.ADJUSTMENT_FIELDS.values()) {
            for(String field : fields) {
                siteSurveyQuery += ', ' + field;
            }
        }

        siteSurveyQuery += ' FROM Site_Survey__c WHERE Id IN :siteSurveyIds';

        return new Map<Id,Site_Survey__c>((List<Site_Survey__c>) Database.query(siteSurveyQuery));
    }

    /*
     * @Name        getSiteSurveyAdjustments
     * @Description Get the adjustment value for a survey compared against order item families and quantities
     * @Author      Graeme Ward
     * @Params      survey: the site survey record to be evaluated
     *              assetCountByFamily: a count of assets by product family
     * @Return      Decimal: adjustment value for the specified survey and assets
     */
    public static Decimal getSiteSurveyAdjustments(Site_Survey__c survey, Map<String,Double> assetCountByFamily) {
        Decimal adjustments = 0;

        SObject surveyObj = (SObject) survey;

        adjustments += (Decimal) surveyObj.get('Duration_Adjustment_Time__c');

        // add the adjustment values for specified product families and quantities
        for(String family : assetCountByFamily.keySet()) {
            String signatureRequired = (String) surveyObj.get('Signature_Required_For__c');

            // for each product family that requires a signature, add 5 minutes
            if(String.isNotBlank(signatureRequired) && signatureRequired.contains(family)) {
                adjustments += 5;
            }

            List<String> familyFields = ServicePlanConstants.ADJUSTMENT_FIELDS.get(family);

            if(familyFields != null) {
                if(family != QueryUtils.fieldServiceSettings.Pest_LOB__c) {
                    // all families except pest control add the work order adjustment only if the asset count reaches a certain number
                    if(surveyObj.get(familyFields[0]) != null
                            && assetCountByFamily.get(family) >= (Double) surveyObj.get(familyFields[1]))
                    {
                        adjustments += (Decimal) surveyObj.get(familyFields[0]);
                    }
                }

                if(family == QueryUtils.fieldServiceSettings.Pest_LOB__c) {
                    // pest control adds the work order adjustment regardless of the asset count
                    if(surveyObj.get(familyFields[0]) != null) {
                        adjustments += (Decimal) surveyObj.get(familyFields[0]);
                    }

                    // pest control has an additional duration adjustment
                    if(surveyObj.get('Pest_Duration_Calculation__c') != null) {
                        adjustments += (Decimal) surveyObj.get('Pest_Duration_Calculation__c');
                    }
                }
            }
        }

        return adjustments;
    }
}