force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/CPQ2_ContractPrice__c/CPQ2_ContractPrice__c.object-meta.xml
<CustomObject>
    <label>Core List Price</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Core List Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core List Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CPQ2_ContractPrice__c/fields/CPQ2_Price__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Price__c</fullName>
    <description>Core list price $ amount</description>
    <label>Core Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Amortization__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Amortization__c</fullName>
    <label>Amortization</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Capital_Cost__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Capital_Cost__c</fullName>
    <label>Capital Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Cost__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Cost__c</fullName>
    <label>Material Cost Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Price_Model__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Price_Model__c</fullName>
    <label>Price Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPQ_Price_Model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Products (Service Work Type)</relationshipLabel>
    <relationshipName>ServiceProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CPQ_Price_Model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hygiene Pricing Model</fullName>
    </customValue>
    <masterLabel>Price Model</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractServiceTest.cls
/**
 * @description
 *
 * Created by timothychiang on 2020-05-29.
 *
 */
@IsTest
public with sharing class ContractServiceTest {

	@TestSetup static void setup(){
		CPQ2_Service.isOppServiceActive = false;

		Id pBook = Test.getStandardPricebookId();

		List<WorkType> workTypesToInsert = new List<WorkType>();
		WorkType workType1 = new WorkType(
			Name = 'TestWorkType1',
			DurationType = 'Minutes',
			EstimatedDuration = 1.7
		);

		WorkType workType2 = new WorkType(
			Name = 'TestWorkType2',
			DurationType = 'Minutes',
			EstimatedDuration = 1
		);

		WorkType workType3 = new WorkType(
			Name = 'TestWorkType3',
			DurationType = 'Minutes',
			EstimatedDuration = 0.11
		);
		workTypesToInsert.add(workType1);
		workTypesToInsert.add(workType2);
		workTypesToInsert.add(workType3);
		insert workTypesToInsert;

		Product2 product1 = new Product2(
			Name = 'TestProduct1',
			Allowable_Frequencies__c = 'One-Time;Monthly;Weekly;Annually',
			IsActive = TRUE,
			Family = 'Hygiene',
			ExternalId__c = 'TestProduct1',
			CPQ_Price_Model__c = 'Hygiene Pricing Model',
			Item_Type__c = 'Service',
			Service_Work_Type__c = workType1.Id,
			CPQ_Cost__c = 0.93,
			CPQ_Amortization__c = 4,
			CPQ_Capital_Cost__c = 0
		);

		Product2 product2 = new Product2(
			Name = 'TestProduct2',
			Allowable_Frequencies__c = 'One-Time;Monthly;Weekly;Annually',
			IsActive = TRUE,
			Family = 'Hygiene',
			ExternalId__c = 'TestProduct2',
			CPQ_Price_Model__c = 'Hygiene Pricing Model',
			Item_Type__c = 'Service',
			Service_Work_Type__c = workType2.Id,
			CPQ_Cost__c = 57.33,
			CPQ_Amortization__c = 4,
			CPQ_Capital_Cost__c = 0
		);

		Product2 product3 = new Product2(
			Name = 'TestProduct3',
			Allowable_Frequencies__c = 'One-Time;Monthly;Weekly;Annually',
			IsActive = TRUE,
			Family = 'Hygiene',
			ExternalId__c = 'TestProduct3',
			CPQ_Price_Model__c = 'Hygiene Pricing Model',
			Item_Type__c = 'Service',
			Service_Work_Type__c = workType3.Id,
			CPQ_Cost__c = 0.97,
			CPQ_Amortization__c = 4,
			CPQ_Capital_Cost__c = 0
		);

		TestDataFactory.products.add(product1);
		TestDataFactory.products.add(product2);
		TestDataFactory.products.add(product3);
		insert TestDataFactory.products;

		PricebookEntry pbe1 = new PricebookEntry(
			Pricebook2Id = pBook,
			Product2Id = product1.Id,
			UnitPrice = 1.0,
			IsActive = TRUE
		);

		PricebookEntry pbe2 = new PricebookEntry(
			Pricebook2Id = pBook,
			Product2Id = product2.Id,
			UnitPrice = 1.0,
			IsActive = TRUE
		);

		PricebookEntry pbe3 = new PricebookEntry(
			Pricebook2Id = pBook,
			Product2Id = product3.Id,
			UnitPrice = 1.0,
			IsActive = TRUE
		);
		TestDataFactory.pEntries.add(pbe1);
		TestDataFactory.pEntries.add(pbe2);
		TestDataFactory.pEntries.add(pbe3);
		insert TestDataFactory.pEntries;

		TestDataFactory.crtCPQSettings();
		TestDataFactory.crtFieldSettings();
		//TestDataFactory.crtFieldServiceSetting();

		//TestDataFactory.crtProdWithPE(4);
		TestDataFactory.crtAcctContact(1, 1);

	}

	@IsTest
	static void testCreateAndUpdateContract() {

		Account account = [SELECT Id FROM Account];
		Contract newContract = ContractService.createNewContract(account.Id, Date.today(), 12);
		Database.SaveResult[] results = ContractService.insertContracts(new List<Contract>{newContract}, false);
		System.assertEquals(true, results[0].isSuccess());

		newContract.ContractTerm = 24;
		Database.SaveResult[] results2 = ContractService.updateContracts(new List<Contract>{newContract}, false);
		System.assertEquals(true, results2[0].isSuccess());
	}

	@IsTest
	static void testGetContractsByAccountIds() {

		Account account = [SELECT Id FROM Account];
		Contract newContract = ContractService.createNewContract(account.Id, Date.today(), 12);
		Database.SaveResult[] results = ContractService.insertContracts(new List<Contract>{newContract}, false);
		System.assertEquals(true, results[0].isSuccess());

		Map<Id, Contract> accountToContractMap = ContractService.getContractsByAccountIds(new Set<Id>{account.Id});
		System.assertEquals(1, accountToContractMap.size());
	}

	@IsTest
	static void testCreateContractPricingAndRetrieval() {

		Account account = [SELECT Id FROM Account];
		Contract newContract = ContractService.createNewContract(account.Id, Date.today(), 12);
		Database.SaveResult[] results = ContractService.insertContracts(new List<Contract>{newContract}, false);
		System.assertEquals(true, results[0].isSuccess());

		newContract.Status = 'Activated';
		Database.SaveResult[] results2 = ContractService.updateContracts(new List<Contract>{newContract}, false);
		System.assertEquals(true, results2[0].isSuccess());

		Product2 prod = [SELECT Id FROM Product2 WHERE Name='TestProduct3'];
		CPQ2_ContractPrice__c cp = ContractService.createNewContractPrice(prod.Id, 12, newContract.Id);
		System.assertEquals(12, cp.CPQ2_Price__c);

		Database.UpsertResult[] results3 = ContractService.insertContractPrices(new List<CPQ2_ContractPrice__c>{cp}, false);
		System.assertEquals(true, results3[0].isSuccess());

		Map<Id, CPQ2_ContractPrice__c> mapContractPrice =  ContractService.getContractPricingByContractIdsAndStatus(new Set<Id>{newContract.Id}, 'Activated');
		System.assertEquals(1, mapContractPrice.size());

		Map<Id, ContractService.ContractPricingSummary> contractPricingMap = ContractService.getContractPricing(account.Id);
		System.assertEquals(1, contractPricingMap.size());
	}
}