force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/Frequency__c/fields/Occurrences_In_Year__c.field-meta.xml
<CustomField>
    <fullName>Occurrences_In_Year__c</fullName>
    <label>Occurrences In Year</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Family)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Parent_Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Plan__c.field-meta.xml
<CustomField>
    <fullName>Service_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Service Plan record that services this Order Product.</description>
    <inlineHelpText>Lookup to Service Plan record that services this Order Product.</inlineHelpText>
    <label>Service Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Plan__c.Frequency__c</field>
            <operation>equals</operation>
            <valueField>$Source.Frequency__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Plan__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <description>Parent object for Service Plans. Links Service Plans to a Technician.</description>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Route Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Type__c/Schedule_Type__c.object-meta.xml
<CustomObject>
    <description>Describes a subset of frequency on recurring Order Products. For example, if an Order Product has a frequency of weekly, Schedule Type may further refine this frequency to Every 7 Days - Monday.</description>
    <label>Schedule Type</label>
    <nameField>
        <label>Schedule Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Type__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Service frequency for recurring Order Products.</description>
    <inlineHelpText>Service frequency for recurring Order Products.</inlineHelpText>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Plan__c/Service_Plan__c.object-meta.xml
<CustomObject>
    <description>Object to summarize recurring Order Products serviced by a Technician.</description>
    <label>Service Plan</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Service Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Associated account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Plans</relationshipLabel>
    <relationshipName>Service_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Plan__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Service frequency for recurring Order Products.</description>
    <inlineHelpText>Service frequency for recurring Order Products.</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Plan__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring Service</fullName>
            </value>
            <value>
                <fullName>Recurring Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Plan__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Job_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene/Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Plan__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Route to which this Service Plan is associated</description>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Service Plans</relationshipLabel>
    <relationshipName>Service_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Plan__c/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Schedule Type record. Used to refine the frequency of this Service Plan. For example, if frequency is 7 days, schedule type may be Every 7 Days - Monday.</description>
    <inlineHelpText>Used to further refine the frequency of this Service Plan.For example, if frequency is 7 days, schedule type may be Every 7 Days - Monday.</inlineHelpText>
    <label>Schedule Type</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The schedule type must have the same frequency as the service plan.</errorMessage>
        <filterItems>
            <field>$Source.Frequency__c</field>
            <operation>equals</operation>
            <valueField>Schedule_Type__c.Frequency__c</valueField>
        </filterItems>
        <infoMessage>The schedule type must have the same frequency as the service plan.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Type__c</referenceTo>
    <relationshipLabel>Service Plans</relationshipLabel>
    <relationshipName>Service_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Service_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>14 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>28 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>56 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Semi-Annually</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <customValue>
        <fullName>112 Days</fullName>
    </customValue>
    <customValue>
        <fullName>2X Per Year</fullName>
    </customValue>
    <customValue>
        <fullName>2X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>3X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>5X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>6X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>42 Days</fullName>
    </customValue>
    <customValue>
        <fullName>84 Days</fullName>
    </customValue>
    <customValue>
        <fullName>120 Days</fullName>
    </customValue>
    <customValue>
        <fullName>168 Days</fullName>
    </customValue>
    <customValue>
        <fullName>182 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Weekly</fullName>
        <isActive>false</isActive>
        <label>Fixed Weekly</label>
    </customValue>
    <customValue>
        <fullName>364 Days</fullName>
        <isActive>false</isActive>
        <label>364 Days</label>
    </customValue>
    <description>Service frequency for recurring Order Products.</description>
    <masterLabel>Service Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServicePlanCtrlTest.cls
/**
 * @FileName: ServicePlanCtrlTest
 * @Description: Test methods for ServicePlanCtrl
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       12/10/2019         Created
 *-----------------------------------------------------------  
 */
@IsTest
private class ServicePlanCtrlTest {
    private static Integer NUM_OF_PRODUCTS = 20;

    @TestSetup
    static void setupTest() {
        setupHelper();
    }

    @IsTest
    static void checkPermissionsNone() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        String permissionLevel;

        System.runAs(testUser) {
            Test.startTest();
            permissionLevel = ServicePlanCtrl.checkPermissions();
            Test.stopTest();
        }

        System.assertEquals('None', permissionLevel);
    }

    @IsTest
    static void checkPermissionsReadOnly() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];
        PermissionSet readOnly = [SELECT Id FROM PermissionSet WHERE Name = 'Service_Plan_Manager_Read_Only' LIMIT 1];

        TestUtils.createSObject(new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = readOnly.Id), true);

        String permissionLevel;

        System.runAs(testUser) {
            Test.startTest();
            permissionLevel = ServicePlanCtrl.checkPermissions();
            Test.stopTest();
        }

        System.assertEquals('Read Only', permissionLevel);
    }

    @IsTest
    static void checkPermissionsReadWrite() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];
        PermissionSet readWrite = [SELECT Id FROM PermissionSet WHERE Name = 'Service_Plan_Manager_Read_Write' LIMIT 1];

        TestUtils.createSObject(new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = readWrite.Id), true);

        String permissionLevel;

        System.runAs(testUser) {
            Test.startTest();
            permissionLevel = ServicePlanCtrl.checkPermissions();
            Test.stopTest();
        }

        System.assertEquals('Read/Write', permissionLevel);
    }

    @IsTest
    static void getAccountData() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];
        Account a = [SELECT Id FROM Account LIMIT 1];

        ServicePlanCtrlHelper.DataWrapper wrapper;

        System.runAs(testUser){
            Test.startTest();
            wrapper = (ServicePlanCtrlHelper.DataWrapper)
                    JSON.deserialize(ServicePlanCtrl.getAccountData(a.Id), ServicePlanCtrlHelper.DataWrapper.class);
            Test.stopTest();
        }

        String jobTypes = JSON.serialize(ApexUtils.getFieldPicklistValues('Service_Plan__c', 'Job_Type__c', true));
        String linesOfBusiness = JSON.serialize(ApexUtils.getFieldPicklistValues('Service_Plan__c', 'Line_of_Business__c', true));

        List<ApexUtils.OptionWrapper> frequencies = new List<ApexUtils.OptionWrapper>();

        for(ApexUtils.OptionWrapper option : ApexUtils.getFieldPicklistValues('Service_Plan__c', 'Frequency__c', true)) {
            if(option.key != 'One-Time') frequencies.add(option);
        }

        String frequencyString = JSON.serialize(frequencies);

        System.assertEquals(jobTypes, JSON.serialize(wrapper.picklistOptions.jobTypes), 'Job type picklist values should match');
        System.assertEquals(linesOfBusiness, JSON.serialize(wrapper.picklistOptions.linesOfBusiness), 'Line of business picklist values should match');
        System.assertEquals(frequencyString, JSON.serialize(wrapper.picklistOptions.frequencies), 'Frequency picklist values should match');
    }

    @IsTest
    static void getAccountDataError() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        String errorMessage;

        System.runAs(testUser){
            Test.startTest();
            try {
                ServicePlanCtrl.getAccountData('Error');
            } catch(Exception e) {
                errorMessage = e.getMessage();
            }
            Test.stopTest();
        }

        System.assert(String.isNotBlank(errorMessage));
    }

    @IsTest
    static void getServicePlan() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        Service_Plan__c plan;

        System.runAs(testUser) {
            Test.startTest();
            plan = (Service_Plan__c) JSON.deserialize(ServicePlanCtrl.getServicePlan(), Service_Plan__c.class);
            Test.stopTest();
        }

        System.assertNotEquals(null, plan);
    }

    @IsTest
    static void getOrderItemsAutoAssignRecurringService() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        Account a = [SELECT Id FROM Account LIMIT 1];
        Service_Plan__c sp = [
                SELECT Id, Job_Type__c, Line_of_Business__c, Frequency__c,
                (SELECT Id
                FROM Order_Products__r)
                FROM Service_Plan__c
                LIMIT 1
        ];

        Integer assignedItemsBefore = sp.Order_Products__r.size();

        for(OrderItem item : sp.Order_Products__r) {
            item.Service_Plan__c = null;
        }

        update sp.Order_Products__r;

        ServicePlanCtrlHelper.FilterWrapper wrapper = new ServicePlanCtrlHelper.FilterWrapper();
        wrapper.dataWrapper = new ServicePlanCtrlHelper.DataWrapper(a.Id);
        wrapper.variety = 'Auto Assign';
        wrapper.accountId = a.Id;
        wrapper.servicePlanId = sp.Id;
        wrapper.jobType = sp.Job_Type__c;
        wrapper.lineOfBusiness = sp.Line_of_Business__c;
        wrapper.frequency = sp.Frequency__c;

        Map<String,ServicePlanAssetWrapper> filteredAssets;

        System.runAs(testUser){
            Test.startTest();
            filteredAssets = (Map<String,ServicePlanAssetWrapper>) JSON.deserialize(
                    ServicePlanCtrl.getOrderItems(JSON.serialize(wrapper)),
                    Map<String,ServicePlanAssetWrapper>.class
            );
            Test.stopTest();
        }

        Integer availableItemsAfter = 0;

        for(ServicePlanAssetWrapper assetWrapper : filteredAssets.values()) {
            availableItemsAfter += assetWrapper.items.size();
        }

        System.assertEquals(assignedItemsBefore, availableItemsAfter);
    }

    @IsTest
    static void getOrderItemsError() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        String errorMessage;

        System.runAs(testUser){
            Test.startTest();
            try {
                ServicePlanCtrl.getOrderItems('Error');
            } catch(Exception e) {
                errorMessage = e.getMessage();
            }
            Test.stopTest();
        }

        System.assert(String.isNotBlank(errorMessage));
    }

    @IsTest
    static void checkForDuplicateServicePlan() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        Service_Plan__c sp = [SELECT Id, Route__c, Account__c, Job_Type__c, Line_of_Business__c, Frequency__c, Schedule_Type__c FROM Service_Plan__c LIMIT 1];

        ServicePlanCtrlHelper.ServicePlanWrapper wrapper = new ServicePlanCtrlHelper.ServicePlanWrapper();
        wrapper.servicePlan = sp.clone(false, true);

        List<Service_Plan__c> plans;

        System.runAs(testUser){
            Test.startTest();
            plans = (List<Service_Plan__c>) JSON.deserialize(
                    ServicePlanCtrl.checkForDuplicateServicePlans(JSON.serialize(wrapper)),
                    List<Service_Plan__c>.class
            );
            Test.stopTest();
        }

        System.assert(!plans.isEmpty());
    }

    @IsTest
    static void checkForDuplicateServicePlansError() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        String errorMessage;

        System.runAs(testUser){
            Test.startTest();
            try {
                ServicePlanCtrl.checkForDuplicateServicePlans('Error');
            } catch(Exception e) {
                errorMessage = e.getMessage();
            }
            Test.stopTest();
        }

        System.assert(String.isNotBlank(errorMessage));
    }

    @IsTest
    static void upsertServicePlanKeyFieldChange() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        Service_Plan__c sp = [
                SELECT Id, Job_Type__c, Line_of_Business__c, Frequency__c, Account__c, Route__c,
                (SELECT Id
                FROM Order_Products__r)
                FROM Service_Plan__c
                LIMIT 1
        ];

        ServicePlanCtrlHelper.ServicePlanWrapper wrapper = new ServicePlanCtrlHelper.ServicePlanWrapper();
        wrapper.servicePlan = sp;
        wrapper.assets = new List<ServicePlanAssetWrapper>();
        wrapper.keyFieldChange = true;

        System.runAs(testUser){
            Test.startTest();
            ServicePlanCtrl.upsertServicePlan(JSON.serialize(wrapper));
            Test.stopTest();
        }

        List<OrderItem> itemsAfter = [SELECT Id FROM OrderItem WHERE Service_Plan__c = :sp.Id];

        System.assert(!sp.Order_Products__r.isEmpty());
        System.assert(itemsAfter.isEmpty());
    }

    @IsTest
    static void upsertServicePlanItemDeselected() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        Account a = [SELECT Id FROM Account LIMIT 1];
        Service_Plan__c sp = [
                SELECT Id, Job_Type__c, Line_of_Business__c, Frequency__c, Account__c, Route__c,
                (SELECT Id
                FROM Order_Products__r)
                FROM Service_Plan__c
                LIMIT 1
        ];

        ServicePlanCtrlHelper.FilterWrapper filterWrapper = new ServicePlanCtrlHelper.FilterWrapper();
        filterWrapper.dataWrapper = new ServicePlanCtrlHelper.DataWrapper(a.Id);
        filterWrapper.variety = 'Manage';
        filterWrapper.accountId = a.Id;
        filterWrapper.servicePlanId = sp.Id;
        filterWrapper.jobType = sp.Job_Type__c;
        filterWrapper.lineOfBusiness = sp.Line_of_Business__c;
        filterWrapper.frequency = sp.Frequency__c;

        Map<String,ServicePlanAssetWrapper> filteredAssets = (Map<String,ServicePlanAssetWrapper>) JSON.deserialize(
                ServicePlanCtrl.getOrderItems(JSON.serialize(filterWrapper)),
                Map<String,ServicePlanAssetWrapper>.class
        );

        filteredAssets.values()[0].items[0].selected = false;

        ServicePlanCtrlHelper.ServicePlanWrapper wrapper = new ServicePlanCtrlHelper.ServicePlanWrapper();
        wrapper.servicePlan = sp;
        wrapper.assets = filteredAssets.values();
        wrapper.keyFieldChange = true;

        System.runAs(testUser){
            Test.startTest();
            ServicePlanCtrl.upsertServicePlan(JSON.serialize(wrapper));
            Test.stopTest();
        }

        List<OrderItem> itemsAfter = [SELECT Id, Service_Plan__c FROM OrderItem WHERE Id IN :sp.Order_Products__r AND Service_Plan__c = NULL];

        System.assertEquals(1, itemsAfter.size());
    }

    @IsTest
    static void upsertServicePlanError() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        String errorMessage;

        System.runAs(testUser){
            Test.startTest();
            try {
                ServicePlanCtrl.upsertServicePlan('Error');
            } catch(Exception e) {
                errorMessage = e.getMessage();
            }
            Test.stopTest();
        }
    }

    @IsTest
    static void assignOrderItems() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        Account a = [SELECT Id FROM Account LIMIT 1];
        Service_Plan__c sp = [
                SELECT Id, Job_Type__c, Line_of_Business__c, Frequency__c,
                (SELECT Id
                FROM Order_Products__r)
                FROM Service_Plan__c
                LIMIT 1
        ];

        ServicePlanCtrlHelper.FilterWrapper wrapper = new ServicePlanCtrlHelper.FilterWrapper();
        wrapper.dataWrapper = new ServicePlanCtrlHelper.DataWrapper(a.Id);
        wrapper.variety = 'Manage';
        wrapper.accountId = a.Id;
        wrapper.servicePlanId = sp.Id;
        wrapper.jobType = sp.Job_Type__c;
        wrapper.lineOfBusiness = sp.Line_of_Business__c;
        wrapper.frequency = sp.Frequency__c;

        Map<String,ServicePlanAssetWrapper> filteredAssets = (Map<String,ServicePlanAssetWrapper>) JSON.deserialize(
                ServicePlanCtrl.getOrderItems(JSON.serialize(wrapper)),
                Map<String,ServicePlanAssetWrapper>.class
        );

        for(OrderItem item : sp.Order_Products__r) {
            item.Service_Plan__c = null;
        }

        update sp.Order_Products__r;

        System.runAs(testUser){
            Test.startTest();
            ServicePlanCtrl.assignOrderItems(JSON.serialize(filteredAssets.values()));
            Test.stopTest();
        }

        List<OrderItem> itemsAfter = [SELECT Id, Service_Plan__c FROM OrderItem WHERE Id IN :sp.Order_Products__r];

        Boolean itemsAssigned = true;

        for(OrderItem oi : itemsAfter) {
            if(oi.Service_Plan__c != sp.Id) itemsAssigned = false;
        }

        System.assert(itemsAssigned);
    }

    @IsTest
    static void assignOrderItemsError() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        String errorMessage;

        System.runAs(testUser){
            Test.startTest();
            try {
                ServicePlanCtrl.assignOrderItems('Error');
            } catch(Exception e) {
                errorMessage = e.getMessage();
            }
            Test.stopTest();
        }
    }

    // HELPER METHODS
    static void setupHelper() {
        TestUtils.createSObject(new User(
                ProfileId = QueryUtils.profileMap.get('Field Service Dispatcher').Id,
                Email = 'testdispatcher@test.com'
        ), true);

        TestUtils.createSObject(new Field_Service_Settings__c(), true);

        List<Frequency__c> frequencies = new List<Frequency__c>{
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = 'Weekly', Occurrences_In_Year__c = 52)),
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = 'Monthly', Occurrences_In_Year__c = 12)),
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = 'Bi-Monthly', Occurrences_In_Year__c = 6)),
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = 'Quarterly', Occurrences_In_Year__c = 4)),
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = '14 Days', Occurrences_In_Year__c = 26))
        };

        insert frequencies;

        TestUtilsWrapperPricebook pricebookWrapper = new TestUtilsWrapperPricebook(NUM_OF_PRODUCTS);
        TestUtilsWrapperAccount accountWrapper = new TestUtilsWrapperAccount();
        TestUtilsWrapperOrder orderWrapper = new TestUtilsWrapperOrder(accountWrapper, pricebookWrapper);
        TestUtilsWrapperServiceResource resourceWrapper = new TestUtilsWrapperServiceResource(accountWrapper);
        new TestUtilsWrapperServicePlan(accountWrapper.account, resourceWrapper.serviceResource, orderWrapper.orderItems);
    }
}