force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Customer_eNewsletters__c.field-meta.xml
<CustomField>
    <fullName>Customer_eNewsletters__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer eNewsletters</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Opinion_eSurveys__c.field-meta.xml
<CustomField>
    <fullName>Customer_Opinion_eSurveys__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Opinion eSurveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Satisfaction_eSurveys__c.field-meta.xml
<CustomField>
    <fullName>Customer_Satisfaction_eSurveys__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Satisfaction eSurveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Promotional_Mailings__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Mailings__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promotional Mailings</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Promotional_Offer_Emails__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Offer_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promotional Offer Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_Login__c.field-meta.xml
<CustomField>
    <fullName>Contact_Login__c</fullName>
    <label>Contact Login</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Customer_eNewsletters__c.field-meta.xml
<CustomField>
    <fullName>Customer_eNewsletters__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Customer eNewsletters</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Customer_Opinion_eSurveys__c.field-meta.xml
<CustomField>
    <fullName>Customer_Opinion_eSurveys__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Customer Opinion eSurveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Customer_Satisfaction_eSurveys__c.field-meta.xml
<CustomField>
    <fullName>Customer_Satisfaction_eSurveys__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Customer Satisfaction eSurveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Promotional_Mailings__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Mailings__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Promotional Mailings</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Promotional_Offer_Emails__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Offer_Emails__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Promotional Offer Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestContactObjectTriggers.cls
@isTest
public class TestContactObjectTriggers {
    
    static testMethod void insertUpdateContact(){
        
        TestDataFactory.crtAcctContact(1,1);
        Account a = TestDataFactory.accounts[0];
        Contact c = TestDataFactory.contacts[0];
        /*
        Contact c = new Contact(
            FirstName = 'TestFirstName', 
            LastName = 'TestLastName', 
            Email = 'testUser@UserCommunity.com', 
            AccountId = a.Id, 
            Title = 'title',
            Phone = '12345678',
            Fax = '12345678',
            MobilePhone = '12345678',
            Customer_Satisfaction_eSurveys__c = FALSE,
            Customer_Opinion_eSurveys__c = TRUE,
            Customer_eNewsletters__c = FALSE,
            Promotional_Offer_Emails__c = TRUE,
            Promotional_Mailings__c = FALSE
            
        );
        insert c;
*/
        
        User newUser = getCommunityUser(c); 
        c.Customer_Opinion_eSurveys__c = FALSE;
        update c;
    }
    
    public static User getCommunityUser(Contact newContact) {
        
        Profile communityProfile = [SELECT Id FROM Profile WHERE Usertype='PowerCustomerSuccess' LIMIT 1]; 
        User newUser = new User(
            Alias = 'testA', 
            Email = newContact.Email, 
            EmailEncodingKey = 'ISO-8859-1', 
            FirstName = newContact.FirstName,
            LastName = newContact.LastName, 
            LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_CA', 
            ProfileId = UserInfo.getProfileId(),
            TimeZoneSidKey = 'America/New_York', 
            UserName = newContact.Email, 
            //ContactId=newContact.Id, 
            CommunityNickname=newContact.FirstName, 
            Contact_Login__c=newContact.Email, 
            Employee_Number__c = 'ABCD123TESTCOMMUNITY'
        );
        insert newUser;
        
        return newUser;
    }
}