force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/PricebookEntry/fields/CPQ2_Installation_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Installation_Unit_Price__c</fullName>
    <label>Installation Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/CPQ2_Margin_Threshold_2__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Margin_Threshold_2__c</fullName>
    <label>Margin Threshold Level 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/CPQ2_Margin_Threshold__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Margin_Threshold__c</fullName>
    <label>Margin Threshold Level 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/CPQ2_Removal_Price__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Removal_Price__c</fullName>
    <label>Removal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/CPQ2_Replacement_Price__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Replacement_Price__c</fullName>
    <label>Replacement Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/CPQ2_Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Total_Cost__c</fullName>
    <formula>CPQ2_Vendor_Contract_Cost__c +  CPQ2_Cost_Variance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Category_Description__c</fullName>
    <label>Category Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ2_Enable_Additional_Pest_Fields__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Enable_Additional_Pest_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To manage UI controls for Pest Services. Note, made it a drop down to account for future scalability as opposed to a checkbox</description>
    <label>Enable Additional Pest Fields</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Amortization__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Amortization__c</fullName>
    <label>Amortization</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Capital_Cost__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Capital_Cost__c</fullName>
    <label>Capital Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Cost__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Cost__c</fullName>
    <label>Material Cost Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Duration_In_Minutes__c</fullName>
    <formula>Service_Work_Type__r.DurationInMinutes</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration In Minutes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Price_Model__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Price_Model__c</fullName>
    <label>Price Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPQ_Price_Model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/GL_Title__c.field-meta.xml
<CustomField>
    <fullName>GL_Title__c</fullName>
    <label>GL Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Is_Inventory_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates (checked) that this product is an inventory item. This is the ICITEM.STOCKITEM field in Accpac.</description>
    <inlineHelpText>Indicates (checked) that this product is an inventory item. This is the ICITEM.STOCKITEM field in Accpac.</inlineHelpText>
    <label>Is Inventory Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Never_Generate_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Never_Generate_Work_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Never Generate Work Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Feminine Hygiene</fullName>
            </value>
            <value>
                <fullName>Air Freshener</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_URL__c</fullName>
    <formula>if((Product_Image_Id__c != &apos;&apos; || Product_Image_Id__c != null),LEFT($Api.Enterprise_Server_URL_290, FIND( &quot;/services&quot;, $Api.Enterprise_Server_URL_290) -1) + &apos;/servlet/servlet.FileDownload?file=&apos; + Product_Image_Id__c,&apos;/resource/1489574201000/CitronLogo&apos;)</formula>
    <label>Product Image URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <description>Unit of measure when product is issued or sold.</description>
    <label>Unit of Measure Issued</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UN</fullName>
                <default>true</default>
                <label>UN</label>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>10L</fullName>
            </value>
            <value>
                <fullName>10PK</fullName>
            </value>
            <value>
                <fullName>12PK</fullName>
            </value>
            <value>
                <fullName>1M</fullName>
            </value>
            <value>
                <fullName>20L</fullName>
            </value>
            <value>
                <fullName>2PK</fullName>
            </value>
            <value>
                <fullName>3.25kg</fullName>
            </value>
            <value>
                <fullName>3kg</fullName>
            </value>
            <value>
                <fullName>4L</fullName>
            </value>
            <value>
                <fullName>5L</fullName>
            </value>
            <value>
                <fullName>BAG</fullName>
            </value>
            <value>
                <fullName>BAG/12</fullName>
            </value>
            <value>
                <fullName>BAG1</fullName>
            </value>
            <value>
                <fullName>BAG12</fullName>
            </value>
            <value>
                <fullName>BAG6</fullName>
            </value>
            <value>
                <fullName>BG18</fullName>
            </value>
            <value>
                <fullName>BOX</fullName>
            </value>
            <value>
                <fullName>BOX/5LB</fullName>
            </value>
            <value>
                <fullName>BOX10</fullName>
            </value>
            <value>
                <fullName>BOX100</fullName>
            </value>
            <value>
                <fullName>BOX12</fullName>
            </value>
            <value>
                <fullName>BOX144</fullName>
            </value>
            <value>
                <fullName>BOX200</fullName>
            </value>
            <value>
                <fullName>BOX24</fullName>
            </value>
            <value>
                <fullName>BOX300</fullName>
            </value>
            <value>
                <fullName>BOX32</fullName>
            </value>
            <value>
                <fullName>BOX36</fullName>
            </value>
            <value>
                <fullName>BOX48</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/VMI_Product__c.field-meta.xml
<CustomField>
    <fullName>VMI_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VMI Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VMI_Product__c/VMI_Product__c.object-meta.xml
<CustomObject>
    <label>VMI Product</label>
    <nameField>
        <label>VMI Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VMI Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/CPQ_Price_Model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hygiene Pricing Model</fullName>
    </customValue>
    <masterLabel>Price Model</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductService.cls
/**
 * @description Service class to handle SOQL and DML for the Product SObject and related SObjects
 */
public with sharing class ProductService {

    private static Map<Id, Product2> product2Map;

    /**
     * @description wrapper class to house product details
     */
    public class ProductWrapper {
        @AuraEnabled public PricebookEntry priceBookEntry;
        @AuraEnabled public ProductItem productItem;
        @AuraEnabled public ContractService.ContractPricingSummary contractPriceSummary;
        @AuraEnabled public Map<String, OrderService.OrderProductFrequencyDetails> orderFrequencyMap;

        /**
		 * @description defined constructor
		 *
		 * @param priceBookEntry - pricebook entry referencing product
		 * @param productItem - product item used for quantity available
		 * @param contractPriceSummary - summary of product's contract price
		 * @param orderFrequencyMap - existing orders
		 */
        public ProductWrapper(PricebookEntry priceBookEntry,
                            ProductItem productItem,
                            ContractService.ContractPricingSummary contractPriceSummary,
                            Map<String, OrderService.OrderProductFrequencyDetails> orderFrequencyMap) {
            this.priceBookEntry = priceBookEntry;
            this.productItem = productItem;
            this.contractPriceSummary = contractPriceSummary;
            this.orderFrequencyMap = orderFrequencyMap;
        }
    }

    /**
     * @description get product filtered by price model
     *
     * @param model - target price model
     *
     * @return list of products under defined price model
     */
    public static List<Product2> getProduct2FilteredByModel(String model){
        return [SELECT Id,
                        Name,
                        CPQ_Duration_In_Minutes__c,
                        CPQ_Price_Model__c,
                        CPQ_Cost__c,
                        CPQ_Capital_Cost__c,
                        CPQ_Amortization__c
                FROM Product2
                WHERE CPQ_Price_Model__c =: model
        ];
    }

    /**
     * @description get map of products based on price model
     *
     * @param model - target price model
     *
     * @return map of products under target price model
     */
    public static Map<Id, Product2> getProduct2MapByIdsFilteredByModel(String model){
        if(product2Map == null){
            product2Map = new Map<Id, Product2>();
            product2Map.putAll(getProduct2FilteredByModel(model));
        }

        return product2Map;
    }

    /**
     * @description get product by names and filter
     *
     * @param value - string to fuzzy search
     * @param priceBook - price book to filter on
     * @param typeFilter - type to filter on
     * @param categoryFilter - category to filter on
     * @param lobFilter - line of business to filter on
     *
     * @return list of products that was sosl'd
     */
    public static List<Product2> soslProductByNameAndFilters(String value, String priceBook, String typeFilter, String categoryFilter, String lobFilter) {

        List<String> whereConditions = new List<String>();
        if(String.isNotEmpty(typeFilter) && typeFilter !='All'){
            whereConditions.add('Item_Type__c = \'' + typeFilter + '\'');
        }
        if(String.isNotEmpty(categoryFilter) && categoryFilter !='All'){
            whereConditions.add('Product_Category__c = \'' + categoryFilter + '\'');
        }
        if(String.isNotEmpty(lobFilter) && lobFilter !='All'){
            whereConditions.add('Family = \'' + lobFilter + '\'');
        }

        String whereClause = '';
        if(!whereConditions.isEmpty()){
            whereClause = ' WHERE ' + String.join( whereConditions, ' AND ' );
        }
        
        String searchQuery = 'FIND \'*' + string.escapeSingleQuotes(value) + '*\' IN ALL FIELDS RETURNING Product2(Id' + whereClause + ') WITH PricebookId = \'' + priceBook + '\'';
        System.debug('Sanchivan searchQuery: ' + searchQuery);
        List<List <SObject>> searchList = Search.query(searchQuery);
        return ((List<Product2>)searchList[0]);
    }

    /**
     * @description get pricebook entry map based on Ids
     *
     * @param targetIds - target price book entry Ids
     *
     * @return Map of Pricebook entry Id-->pricebook entry
     */
    public static Map<Id, PricebookEntry> getPriceBookEntryMapByIds(Set<Id> targetIds){
        Map<Id, PricebookEntry> returnMap = new Map<Id, PricebookEntry>(
        [
            SELECT Id,
                Product2Id,
                Product2.ProductCode,
                Product2.Family,
                UnitPrice,
                CPQ2_Installation_Unit_Price__c,
                CPQ2_Removal_Price__c,
                CPQ2_Replacement_Price__c,
                CPQ2_Total_Cost__c,
                CPQ2_Margin_Threshold__c,
                CPQ2_Margin_Threshold_2__c,
                Product2.Name,
                Product2.Item_Type__c,
                Product2.Product_Image_URL__c,
                Product2.Allowable_Frequencies__c,
                Product2.CPQ_Price_Model__c,
                Product2.CPQ2_Enable_Additional_Pest_Fields__c,
                Product2.Unit__c,
                Product2.Category_Description__c,
                Product2.VMI_Product__c,
                Product2.GL_Title__c
            FROM PricebookEntry
            WHERE Id IN:targetIds
        ]);

        return returnMap;
    }

    /**
     * @description get price book entry by product Ids and pricebook Id
     *
     * @param targetIds - target product ids
     * @param priceBook - target pricebook id
     *
     * @return Map pricebook entry Id-->pricebook entry
     */
    public static Map<Id, PricebookEntry> getPricebookEntryByIdsAndPriceBook(Set<Id> targetIds, String priceBook) {
        return new Map<Id, PricebookEntry>([
            SELECT Id,
                Product2Id,
                Product2.ProductCode,
                Product2.Family,
                UnitPrice,
                CPQ2_Installation_Unit_Price__c,
                CPQ2_Removal_Price__c,
                CPQ2_Replacement_Price__c,
                CPQ2_Total_Cost__c,
                CPQ2_Margin_Threshold__c,
                CPQ2_Margin_Threshold_2__c,
                Product2.Name,
                Product2.Item_Type__c,
                Product2.Product_Image_URL__c,
                Product2.Allowable_Frequencies__c,
                Product2.CPQ_Price_Model__c,
                Product2.CPQ2_Enable_Additional_Pest_Fields__c,
                Product2.Unit__c,
                Product2.Category_Description__c,
                Product2.VMI_Product__c,
                Product2.GL_Title__c
            FROM PricebookEntry
            WHERE Product2Id IN:targetIds AND
                Pricebook2Id = :priceBook
            ]);
    }

    /**
     * @description get map of products by Id
     *
     * @param targetIds - target products to query
     *
     * @return map of products
     */
    public static Map<Id, Product2> getProduct2MapByIds(Set<Id> targetIds) {
        return new Map<Id, Product2>([
            SELECT Id,
                    Name,
                    Item_Type__c,
                    Never_Generate_Work_Order__c,
                    Is_Inventory_Item__c,
                    Product_Image_URL__c,
                    Allowable_Frequencies__c,
                    CPQ_Price_Model__c,
                    CPQ2_Enable_Additional_Pest_Fields__c,
                    Unit__c,
                    Category_Description__c,
                    VMI_Product__c,
                    GL_Title__c
            FROM Product2
            WHERE Id IN:targetIds
        ]);
    }


    /**
     * @description get product quantity by product Ids and location Id
     *
     * @param targetIds - target products
     * @param locationId - target location
     *
     * @return list of product items containing quantity available
     */
    // public static List<ProductItem> getProductQuantitiesByProductIdsAndLocationId(Set<Id> targetIds, Id locationId){
    //     return [SELECT Id, 
    //                     Product2Id,
    //                     Quantity_Available__c
    //                 FROM ProductItem
    //                 WHERE Product2Id IN: targetIds AND
    //                     LocationId =: locationId];
    // }

    /**
     * @description get combined product information (product, pricebook entry, core list pricing and existing services)
     *
     * @param productIds - target products
     * @param priceBook - target price book
     * @param accountId - target account
     *
     * @return list of combined product detail housed in wrappers based on target given.
     */
    public static List<ProductWrapper> getProductInformationByIds(Set<Id> productIds, String priceBook, String accountId,  String recordId){
        return getProductInformationByIds(productIds, priceBook, accountId, recordId, true);
    }

    /**
     * @description  get combined product information (product, pricebook entry, core list pricing and existing services)
     *
     * @param productIds - target products
     * @param priceBook  - target price book
     * @param accountId - target 
     * @param recordId - the record Id of either the Opportunity or Order record which this call was made from
     * @param getEnrichedProductInfo - determines if contract pricing and existing orders is required
     *
     * @return list of combined product detail housed in wrappers based on target given.
     */
    public static List<ProductWrapper> getProductInformationByIds(Set<Id> productIds, String priceBook, String accountId, String recordId, Boolean getEnrichedProductInfo){
        List<PricebookEntry> listPbe = ProductService.getPricebookEntryByIdsAndPriceBook(productIds, priceBook).values();
        Map<Id, PricebookEntry> mapProdToPbe = new Map<Id, PricebookEntry>();
        for(PricebookEntry pbe: listPbe){
            mapProdToPbe.put(pbe.Product2Id, pbe);
        }

        String type = Id.valueOf(recordId).getSObjectType().getDescribe().getName();

        //List<ProductItem> listPi;

        // if(type == CPQ2_Util.SOBJECT_NAME_OPP){
        //     Account account = AccountService.getAccountById(accountId);
        //     listPi = ProductService.getProductQuantitiesByProductIdsAndLocationId(productIds, account.Default_Warehouse_Location__c);            
        // }
        // else if(type == CPQ2_Util.SOBJECT_NAME_ORDER) {
        //     Order order = OrderService.getOrderById(recordId);
        //     listPi = ProductService.getProductQuantitiesByProductIdsAndLocationId(productIds, order.Warehouse_Location__c);
        // }

        //Map<Id, ProductItem> mapProdToPi = new Map<Id, ProductItem>();
        //for(ProductItem pi: listPi){
        //    mapProdToPi.put(pi.Product2Id, pi);
        //}

        Map<Id, ContractService.ContractPricingSummary> mapProdToContractPricing;
        Map<Id, Map<String, OrderService.OrderProductFrequencyDetails>> mapKeyToOrderLineItem;

        if(getEnrichedProductInfo){
            mapProdToContractPricing = ContractService.getContractPricing(accountId);
            mapKeyToOrderLineItem = OrderService.getExistingServicesMapByAccountIdAndProducts(accountId, productIds);
        }

        List<ProductWrapper> listPbeReturn = new List<ProductWrapper>();

        for(Id prodId: productIds){
            if(mapProdToPbe.containsKey(prodId)){
                PricebookEntry pbe = mapProdToPbe.get(prodId);
                ProductItem pi;
                ContractService.ContractPricingSummary cps;
                Map<String, OrderService.OrderProductFrequencyDetails> orderFrequencyMap;

                //if(mapProdToPi.containsKey(prodId)){
                //    pi = mapProdToPi.get(prodId);
                //}

                if(getEnrichedProductInfo) {
                    if (mapProdToContractPricing.containsKey(prodId)) {
                        cps = mapProdToContractPricing.get(prodId);
                    }

                    if (mapKeyToOrderLineItem.containsKey(prodId)) {
                        orderFrequencyMap = mapKeyToOrderLineItem.get(prodId);
                    }
                }

                listPbeReturn.add(new ProductWrapper(pbe,pi,cps,orderFrequencyMap));
            }
        }

        return listPbeReturn;        
    }

}