force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/Frequency__c/fields/Occurrences_In_Year__c.field-meta.xml
<CustomField>
    <fullName>Occurrences_In_Year__c</fullName>
    <label>Occurrences In Year</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Plan__c.field-meta.xml
<CustomField>
    <fullName>Service_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Service Plan record that services this Order Product.</description>
    <inlineHelpText>Lookup to Service Plan record that services this Order Product.</inlineHelpText>
    <label>Service Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Plan__c.Frequency__c</field>
            <operation>equals</operation>
            <valueField>$Source.Frequency__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Plan__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule_Type__c/Schedule_Type__c.object-meta.xml
<CustomObject>
    <description>Describes a subset of frequency on recurring Order Products. For example, if an Order Product has a frequency of weekly, Schedule Type may further refine this frequency to Every 7 Days - Monday.</description>
    <label>Schedule Type</label>
    <nameField>
        <label>Schedule Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Plan__c/Service_Plan__c.object-meta.xml
<CustomObject>
    <description>Object to summarize recurring Order Products serviced by a Technician.</description>
    <label>Service Plan</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Service Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Plan__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Service frequency for recurring Order Products.</description>
    <inlineHelpText>Service frequency for recurring Order Products.</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Plan__c/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Schedule Type record. Used to refine the frequency of this Service Plan. For example, if frequency is 7 days, schedule type may be Every 7 Days - Monday.</description>
    <inlineHelpText>Used to further refine the frequency of this Service Plan.For example, if frequency is 7 days, schedule type may be Every 7 Days - Monday.</inlineHelpText>
    <label>Schedule Type</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The schedule type must have the same frequency as the service plan.</errorMessage>
        <filterItems>
            <field>$Source.Frequency__c</field>
            <operation>equals</operation>
            <valueField>Schedule_Type__c.Frequency__c</valueField>
        </filterItems>
        <infoMessage>The schedule type must have the same frequency as the service plan.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Type__c</referenceTo>
    <relationshipLabel>Service Plans</relationshipLabel>
    <relationshipName>Service_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/Travel_Factor__c.field-meta.xml
<CustomField>
    <fullName>Travel_Factor__c</fullName>
    <defaultValue>0.20</defaultValue>
    <description>Percentage of time this Service Resource spends on travel. Defaults to 20%.</description>
    <inlineHelpText>Percentage of time this Service Resource spends on travel. Defaults to 20%.</inlineHelpText>
    <label>Travel Factor</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Service_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>14 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>28 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>56 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Semi-Annually</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <customValue>
        <fullName>112 Days</fullName>
    </customValue>
    <customValue>
        <fullName>2X Per Year</fullName>
    </customValue>
    <customValue>
        <fullName>2X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>3X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>5X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>6X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>42 Days</fullName>
    </customValue>
    <customValue>
        <fullName>84 Days</fullName>
    </customValue>
    <customValue>
        <fullName>120 Days</fullName>
    </customValue>
    <customValue>
        <fullName>168 Days</fullName>
    </customValue>
    <customValue>
        <fullName>182 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Weekly</fullName>
        <isActive>false</isActive>
        <label>Fixed Weekly</label>
    </customValue>
    <customValue>
        <fullName>364 Days</fullName>
        <isActive>false</isActive>
        <label>364 Days</label>
    </customValue>
    <description>Service frequency for recurring Order Products.</description>
    <masterLabel>Service Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TechCapacityCtrlTest.cls
/**
 * @FileName: TechCapacityCtrlTest
 * @Description: Test methods for TechCapacityCtrl
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       11/1/2019       Created
 *-----------------------------------------------------------  
 */
@IsTest
private class TechCapacityCtrlTest {

    @TestSetup
    static void setupTest() {
        setupHelper();
    }

    @IsTest
    static void getTechnician() {
        ServiceResource sr = [
                SELECT Id, Name, Travel_Factor__c,
                    (SELECT Id, Skill.MasterLabel, SkillLevel
                    FROM ServiceResourceSkills),
                    (SELECT Id, OperatingHoursId, OperatingHours.Name
                    FROM ServiceTerritories
                    WHERE TerritoryType = 'P'
                    ORDER BY EffectiveEndDate DESC NULLS FIRST)
                FROM ServiceResource
                LIMIT 1
        ];

        TechCapacityWrappers.TechWrapper wrapper = new TechCapacityWrappers.TechWrapper(sr);
        TechCapacityWrappers.TechWrapper res;

        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        System.runAs(testUser) {
            Test.startTest();
            res = (TechCapacityWrappers.TechWrapper) JSON.deserialize(
                    TechCapacityCtrl.getTechnician(sr.Id),
                    TechCapacityWrappers.TechWrapper.class
            );
            Test.stopTest();
        }

        System.assertEquals(wrapper.skills, res.skills);
        System.assertEquals(wrapper.averageShift, res.averageShift);
    }

    @IsTest
    static void getTechnicianError() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        String errorMessage;

        System.runAs(testUser) {
            Test.startTest();
            try {
                TechCapacityCtrl.getTechnician('Error');
            } catch (Exception e) {
                errorMessage = e.getMessage();
            }
            Test.stopTest();
        }

        System.assertNotEquals(null, errorMessage);
    }

    @IsTest
    static void getServicePlans() {
        TechCapacityWrappers.ServicePlanCriteria criteria = new TechCapacityWrappers.ServicePlanCriteria();

        ServiceResource sr = [
                SELECT Id, Name, Travel_Factor__c,
                    (SELECT Id, Skill.MasterLabel, SkillLevel
                    FROM ServiceResourceSkills),
                    (SELECT Id, OperatingHoursId, OperatingHours.Name
                    FROM ServiceTerritories
                    WHERE TerritoryType = 'P'
                    ORDER BY EffectiveEndDate DESC NULLS FIRST)
                FROM ServiceResource
                LIMIT 1
        ];

        TechCapacityWrappers.TechWrapper technician = new TechCapacityWrappers.TechWrapper(sr);

        criteria.technician = technician;

        List<TechCapacityWrappers.CalendarDay> days = new List<TechCapacityWrappers.CalendarDay>();

        Date knownMonday = Date.newInstance(1900, 1, 1);
        Integer daysAfterMonday = Math.mod(knownMonday.daysBetween(Date.today()), 7);
        Date monday = Date.today().addDays(-daysAfterMonday);

        for (Integer i = 0; i < 56; i++) {
            Date d = monday.addDays(i);

            TechCapacityWrappers.CalendarDay day = new TechCapacityWrappers.CalendarDay();
            day.d = d.year() + '-' + d.month() + '-' + d.day();
            day.num = d.day();
            day.month = String.valueOf(d.month());
            day.pastDay = '';

            days.add(day);
        }

        criteria.days = days;

        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        System.runAs(testUser) {
            Test.startTest();
            criteria = (TechCapacityWrappers.ServicePlanCriteria) JSON.deserialize(
                    TechCapacityCtrl.getServicePlans(JSON.serialize(criteria)),
                    TechCapacityWrappers.ServicePlanCriteria.class
            );
            Test.stopTest();
        }

        List<OrderItem> items = [
                SELECT Id, Service_Plan__r.Schedule_Type__r.Code__c
                FROM OrderItem
                WHERE Frequency__c = 'Weekly'
                AND Service_Plan__r.Schedule_Type__r.Code__c = 'W-1'
        ];

        System.assertEquals(1, criteria.days[0].calls);
        System.assertEquals(items.size(), criteria.days[0].assets);
    }

    @IsTest
    static void getServicePlansError() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testdispatcher@test.com'];

        String errorMessage;

        System.runAs(testUser) {
            Test.startTest();
            try {
                TechCapacityCtrl.getServicePlans('Error');
            } catch(Exception e) {
                errorMessage = e.getMessage();
            }
            Test.stopTest();
        }

        System.assertNotEquals(null, errorMessage);
    }

    // HELPER METHODS
    static void setupHelper() {
        TestUtils.createSObject(new User(
                ProfileId = QueryUtils.profileMap.get('Field Service Dispatcher').Id,
                Email = 'testdispatcher@test.com'
        ), true);

        TestUtils.createSObject(new Field_Service_Settings__c(), true);

        List<Frequency__c> frequencies = new List<Frequency__c>{
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = 'Weekly', Occurrences_In_Year__c = 52)),
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = 'Monthly', Occurrences_In_Year__c = 12)),
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = 'Bi-Monthly', Occurrences_In_Year__c = 6)),
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = 'Quarterly', Occurrences_In_Year__c = 4)),
                (Frequency__c) TestUtils.createSObject(new Frequency__c(Name = '14 Days', Occurrences_In_Year__c = 26))
        };

        insert frequencies;

        TestUtilsWrapperPricebook pricebookWrapper = new TestUtilsWrapperPricebook(20);
        TestUtilsWrapperAccount accountWrapper = new TestUtilsWrapperAccount();
        TestUtilsWrapperOrder orderWrapper = new TestUtilsWrapperOrder(accountWrapper, pricebookWrapper);
        TestUtilsWrapperServiceResource resourceWrapper = new TestUtilsWrapperServiceResource(accountWrapper);

        new TestUtilsWrapperServicePlan(
                accountWrapper.account,
                resourceWrapper.serviceResource,
                orderWrapper.orderItems
        );
    }
}