force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Order_Active_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Active_Stage__c</fullName>
    <label>Order Active Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>PricebookEntry.IsActive  &amp;&amp;  PricebookEntry.Product2.IsActive &amp;&amp;  Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <formula>PricebookEntry.Product2.Item_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Location</label>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Invoice_English_Description__c.field-meta.xml
<CustomField>
    <fullName>Invoice_English_Description__c</fullName>
    <label>Invoice English Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Not_Editable_in_Community__c.field-meta.xml
<CustomField>
    <fullName>Not_Editable_in_Community__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Prevents community users from editing frequency and quantity if set to True.</inlineHelpText>
    <label>Not Editable in Community</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Weighting__mdt/Value_Weighting__mdt.object-meta.xml
<CustomObject>
    <description>This is used to assign values to text (eg names). This helps facilitate comparisons and sorting on text that has to be sorted non-alphabetically.</description>
    <label>Value Weighting</label>
    <pluralLabel>Value Weightings</pluralLabel>
</CustomObject>

force-app/main/default/classes/OrderandServicesController.cls
/**
 * Controller Class for OrderandServices lightning component
 *
 * @author Citron - Tim Chiang
 * @date 2019
 *
 **/
public with sharing class OrderandServicesController {

    /**
    * Result wrapper class for this controller
    *
    * @author Citron - Tim Chiang
    * @date 2019
    *
    **/
    public class ViewData {
        public Map<Id, Room> roomMap;
        public Set<String> setOfRooms;
        public Set<String> setOfServices;
        @AuraEnabled public list<String> listOfRooms;
        @AuraEnabled public list<String> listOfServices;
        @AuraEnabled public List<Room> roomList;
        @AuraEnabled public Id currentUserContact;
        @AuraEnabled public Map<String, Decimal> frequencyWeightingMap;
        @AuraEnabled public Map<String, Decimal> serviceWeightingMap;
        @AuraEnabled public Map<String, Decimal> familyWeightingMap;

        public ViewData(){
            this.roomMap = new Map<Id, Room>();

            User user = [SELECT Id, ContactId FROM User WHERE Id=: UserInfo.getUserId() LIMIT 1];
            this.currentUserContact = user.ContactId;

            List<Value_Weighting__mdt> frequencyWeightingList = [SELECT Label, Type__c, Value__c FROM Value_Weighting__mdt WHERE Type__c='Frequency'];
            frequencyWeightingMap = new Map<String, Decimal>();

            for(Value_Weighting__mdt vw: frequencyWeightingList){
                frequencyWeightingMap.put(vw.Label, vw.Value__c);
            }

            List<Value_Weighting__mdt> serviceWeightingList = [SELECT Label, Type__c, Value__c FROM Value_Weighting__mdt WHERE Type__c='Service'];
            serviceWeightingMap = new Map<String, Decimal>();

            for(Value_Weighting__mdt vw: serviceWeightingList){
                serviceWeightingMap.put(vw.Label, vw.Value__c);
            }

            List<Value_Weighting__mdt> familyWeightingList = [SELECT Label, Type__c, Value__c FROM Value_Weighting__mdt WHERE Type__c='Family'];
            familyWeightingMap = new Map<String, Decimal>();

            for(Value_Weighting__mdt vw: familyWeightingList){
                familyWeightingMap.put(vw.Label, vw.Value__c);
            }



            setOfRooms = new Set<String>();
            setOfServices = new Set<String>();
            listOfRooms = new list<String>();
            listOfServices = new list<String>();
        }

        public void addSummaryLine(summaryLine summaryLine){
            if(!this.roomMap.containsKey(summaryLine.surveyLocation)){
                this.roomMap.put(summaryLine.surveyLocation, new Room(summaryLine));
            } else {
                this.roomMap.get(summaryLine.surveyLocation).addSummaryLine(summaryLine);
            }

            this.setOfRooms.add(summaryLine.surveyLocation);
            this.setOfServices.add(summaryLine.itemType);
        }

        public void convertAuraFriendly(){
            this.roomList = this.roomMap.values();
            this.listOfRooms.addAll(this.setOfRooms);
            this.listOfServices.addAll(this.setOfServices);

            for(Room room: this.roomList){
                room.convertAuraFriendly();
            }
        }         
    }

    /**
    * Room class to organize and handle Room related details
    *
    * @author Citron - Tim Chiang
    * @date 2019
    *
    **/
    public class Room {
        @AuraEnabled public String locationId;
        @AuraEnabled public String locationName;
        @AuraEnabled public List<Service> services;
        public Map<String, Service> serviceMap;

        public Room(SummaryLine summaryLine){
            this.locationId = summaryLine.surveyLocation;
            this.locationName = summaryLine.surveyLocationName;
            this.serviceMap = new Map<String, Service>();
            this.serviceMap.put(summaryLine.itemType, new Service(summaryLine));
        }

        public void addSummaryLine(SummaryLine summaryLine){
            if(this.serviceMap.containsKey(summaryLine.itemType)){
                this.serviceMap.get(summaryLine.itemType).AddSummaryLine(summaryLine);
            } else {
                this.serviceMap.put(summaryLine.itemType, new Service(summaryLine));
            }
        }

        public void convertAuraFriendly(){
            this.services = this.serviceMap.values();

            for(Service service: this.services){
                service.convertAuraFriendly();
            }
        } 
    }

    public class Service {
        @AuraEnabled public String serviceName;
        @AuraEnabled public List<Family> families;
        public Map<String, Family> familyMap;

        public Service(SummaryLine summaryLine){
            this.serviceName = summaryLine.itemType;
            this.familyMap = new Map<String, Family>();
            this.familyMap.put(summaryLine.productFamily, new Family(summaryLine));
        }

        public void AddSummaryLine(SummaryLine summaryLine){
            if(this.familyMap.containsKey(summaryLine.productFamily)){
                this.familyMap.get(summaryLine.productFamily).AddSummaryLine(summaryLine);
            } else {
                this.familyMap.put(summaryLine.productFamily, new Family(summaryLine));
            }
        }

        public void convertAuraFriendly(){
            this.families = this.familyMap.values();
        }        

    }

    public class Family {
        @AuraEnabled public String familyName;
        @AuraEnabled public List<SummaryLine> lineItems;

        public Family(SummaryLine summaryLine){
            this.familyName = summaryLine.productFamily;
            this.lineItems = new List<SummaryLine>();
            this.lineItems.add(summaryLine);
        }

        public void AddSummaryLine(SummaryLine summaryLine){
            this.lineItems.add(summaryLine);
        }
    }


    /**
    * Summary Line Class used as a line item
    *
    * @author Citron - Tim Chiang
    * @date 2019
    *
    **/
    public class SummaryLine {
        @AuraEnabled public String pEntry;
        @AuraEnabled public String itemType;
        @AuraEnabled public String productName;
        @AuraEnabled public String frequency;
        @AuraEnabled public String newFrequency;
        @AuraEnabled public Integer quantity;
        @AuraEnabled public Integer newQuantity;
        @AuraEnabled public String surveyLocation;
        @AuraEnabled public String surveyLocationName;
        @AuraEnabled public String productFamily;
        @AuraEnabled public String notes;
        @AuraEnabled public Boolean doNotAllowEdit;
        @AuraEnabled public List<String> allowableFreq;

        public SummaryLine(OrderItem aggOi){  
            this.productName = aggOi.Product2.Invoice_English_Description__c;
            this.quantity = (aggOi.Quantity != null) ? Integer.valueOf(aggOi.Quantity): 0; 
            this.newQuantity = this.quantity; 
            this.itemType = aggOi.Product2.Item_Type__c;   
            this.pEntry = aggOi.PricebookEntryId;   
            this.frequency = (aggOi.Frequency__c != null) ? aggOi.Frequency__c: ''; 
            this.newFrequency = this.frequency;
            this.productFamily = aggOi.Product2.Family;
            this.surveyLocation = aggOi.Survey_Location__c; 
            this.surveyLocationName = aggOi.Survey_Location__r.Name;
            this.doNotAllowEdit = aggOi.Product2.Not_Editable_in_Community__c;
            if(String.isNotEmpty(aggOi.Product2.Allowable_Frequencies__c)){
                this.allowableFreq = aggOi.Product2.Allowable_Frequencies__c.split(';');
            } else {
                this.allowableFreq = new List<String>();
            }
            
        }
    }

    @AuraEnabled
    public static Case saveTicket(Case newCase) {
        try{
            insert newCase;
        } catch(Exception e){
            throw new AuraHandledException('Error please contact your administrator. ' + e.getMessage());
        }
        
        return newCase; 
    }


    /**
     * main call to retrieve product summary
     *
     * @param   accountId       target account to get summary for
     * @return                  wrapper class containing service summary
     **/
    @AuraEnabled
    public static ViewData loadViewData(Id accountId) { 
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();

        // Create the rooms, services and summary lines based on aggregate data
        ViewData returnData = new ViewData();

        Map<String, OrderItem> sumOrderItemMap = new Map<String, OrderItem>();

        for(OrderItem oi: [SELECT Id,
                                    PricebookEntryId, 
                                    Product2.Name,
                                    Product2.Item_Type__c, 
                                    Product2.Family,
                                    Product2.Allowable_Frequencies__c,
                                    Product2.Invoice_English_Description__c,
                                    Product2.Not_Editable_in_Community__c,
                                    Survey_Location__c,
                                    Survey_Location__r.Name,
                                    Frequency__c, 
                                    Quantity
                            FROM OrderItem 
                            WHERE Order.AccountId=:accountId AND 
                                    Order.Status=:fssetting.Order_Active_Stage__c AND 
                                    IsActive__c = true
                        ]){
            
            String key = oi.PricebookEntryId + '-' + oi.Survey_Location__c + '-' + oi.Frequency__c;

            if(sumOrderItemMap.containsKey(key)){
                sumOrderItemMap.get(key).Quantity += oi.Quantity;
            } else {
                sumOrderItemMap.put(key, oi);
            }
        }

        for(OrderItem aggOi: sumOrderItemMap.values()){
            returnData.addSummaryLine(new SummaryLine(aggOi));
        }

        returnData.convertAuraFriendly();

        return returnData;        
    }
}