force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/ComplexReports__c/ComplexReports__c.object-meta.xml
<CustomObject>
    <label>ComplexReport</label>
    <nameField>
        <label>ComplexReports Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ComplexReports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ComplexReports__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>Account Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_DeleteComplexReports.cls
@istest
public class Test_DeleteComplexReports {
    
static List<complexReports__c> listcr = new List<ComplexREports__c>();

    @testSetup 
    static void setup() {
       
       
        for (Integer i=0;i<10;i++) {
            listcr.add(new complexReports__c(AccountName__c='Account '+i));
        }
        insert listcr;
        
    }
    static testmethod void test() {        
        Test.startTest();
       Delete_Complex_Report dcr = new Delete_Complex_Report();
        Id batchId = Database.executeBatch(dcr);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        System.assertEquals(0, listcr.size());
    }
    
}