force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/OpportunityCloneSettings__c/OpportunityCloneSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Clone Settings</label>
</CustomObject>

force-app/main/default/objects/OpportunityCloneSettings__c/fields/Field_Set_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Set_Name__c</fullName>
    <description>The name of the field set listing the fields to clone.</description>
    <label>Field Set Name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityCloneSettings__c/fields/Opp_Product_Field_Set__c.field-meta.xml
<CustomField>
    <fullName>Opp_Product_Field_Set__c</fullName>
    <label>Opp Product Field Set</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <formula>PricebookEntry.Product2.Item_Type__c</formula>
    <label>Item Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Service_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Service_Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_As_Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Available_As_Related_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available As Related Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OppCloneControllerTest.cls
/**
 * Unit tests for OppCloneController.
 * @author Ahsan Butt
 */
@isTest
private class OppCloneControllerTest {
    private static final String FIELD_SET_NAME_OPP = 'Clone_Fields';
    private static final String FIELD_SET_NAME_OLI = 'Clone_Fields';
    
    static testMethod void testClone() {
        // Create custom setting (field set names)
        OpportunityCloneSettings__c cloneSettings = new OpportunityCloneSettings__c();
        cloneSettings.Name = 'Opp Clone';
        cloneSettings.field_set_name__c = FIELD_SET_NAME_OPP;
        cloneSettings.Opp_Product_Field_Set__c = FIELD_SET_NAME_OLI;
        
        insert cloneSettings;
        
        // Create accounts
        TestDataFactory.crtAcctContact(2, 0); 
        List<Account> a = TestDataFactory.accounts;
        
        
        // Create Opp and OLI (as well as underlying product, etc.) 
		Product2 prod = new Product2(
            Name='TestProduct',
            Allowable_Frequencies__c='One-Time;Monthly;Weekly', 
            IsActive=TRUE, 
            Available_As_Related_Product__c=TRUE, 
            Family='Pest Control', 
            //Item_Type__c= (i==0) ? 'Consumables' : 'Service'
            Item_Type__c= 'Service'
        );
        
        insert prod;
        
        PricebookEntry pe = new PricebookEntry(
            Pricebook2Id=Test.getStandardPricebookId(), 
            Product2Id=prod.Id, 
            UnitPrice=1.0, 
            IsActive=TRUE
        );
        
        insert pe;
        
        Opportunity opp = new Opportunity();
        opp.Name =' Test opp';
        opp.AccountId = a[0].Id;
        opp.Amount = 100;
        opp.StageName = 'Prospect';
        opp.CloseDate = Date.today();
        opp.Pricebook2Id = Test.getStandardPricebookId();
        
        insert opp;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            Product2Id=pe.Id,  
            Service_Frequency__c= 'One-Time', 
            UnitPrice=1.0, 
            Service_Price_Per_Unit__c=1.0, 
            Quantity=1, 
            OpportunityId=opp.Id
        );
        
        insert oli;
        
        // Test successful clone
        OppCloneController.CloneResultMap resultMap = OppCloneController.cloneOpp(opp.Id, new List<String>{a[1].Id}, false);
        
        System.assertEquals(1, resultMap.successes.size(), 'Should be 1 successful clone result');
    }
    
    static testMethod void testGets() {
        //Insert acct and Opp to "get"
        TestDataFactory.crtAcctContact(1, 0); 
		Account a = TestDataFactory.accounts[0]; 
        
        Opportunity opp = new Opportunity();
        opp.Name =' Test opp';
        opp.AccountId = a.Id;
        opp.Amount = 100;
        opp.StageName = 'Prospect';
        opp.CloseDate = Date.today();
        
        insert opp;
        
        // Invoke getOpp()
        Opportunity actualOpp = OppCloneController.getOpp(opp.Id);
        
        System.assertEquals(opp.Id, actualOpp.Id, 'getOpp should return correct oppId');
        
        // Invoke getRecords()
        List<Account> actualAccts = OppCloneController.getRecords(new List<String>{a.Id});
        
        System.assertEquals(a.Id, actualAccts.get(0).Id, 'getRecords should return correct accts');
        
        // Invoke getErrorResult()
        OppCloneController.getErrorResult(new List<Database.Error>(), a);
    }
}