force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Site_Survey_Skills_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey_Skills_Prefix__c</fullName>
    <label>Site Survey Skills Prefix</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestInputLookup.cls
@isTest
public class TestInputLookup {
    
    static testmethod void testLoadDefault() {
        InputLookup.loadDefault(UserInfo.getUserId(), 'User');
    }
    
    static testmethod void testLoadDefaultException() {
        String Id;
        InputLookup.loadDefault(Id, 'Skill');
    }
    
    static testmethod void testSearchLookup() {
        InputLookup.searchLookup('Stuff', 'Account');
    }
    
    static testmethod void testSearchLookupSkill() {
        Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Site_Survey_Skills_Prefix__c = 'SSRS';
        insert fssetting;
        InputLookup.searchLookup('Stuff', 'Skill');
    }
    
    static testmethod void testSearchLookupException() {
        InputLookup.searchLookup('Stuff', 'TestObject');
    }
}