force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/CPQ2_Core_List_Price_Request__c/CPQ2_Core_List_Price_Request__c.object-meta.xml
<CustomObject>
    <label>Core List Price Request</label>
    <nameField>
        <displayFormat>CPR-{000000000}</displayFormat>
        <label>Core List Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core List Price Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CPQ2_Core_List_Price_Request__c/fields/CPQ2_Threshold_Triggered__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Threshold_Triggered__c</fullName>
    <label>Threshold Triggered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ2_Score_Multiplier__c/CPQ2_Score_Multiplier__c.object-meta.xml
<CustomObject>
    <label>Score Multiplier Table</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>Score Multiplier Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Multiplier Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CPQ_Multiplier_Table__c/CPQ_Multiplier_Table__c.object-meta.xml
<CustomObject>
    <label>Multiplier Table</label>
    <nameField>
        <displayFormat>MT-{0000000000}</displayFormat>
        <label>Multiplier Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Multiplier Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CPQ_Settings__c/CPQ_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CPQ Settings</label>
</CustomObject>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Requested_Price_Approved__c.field-meta.xml
<CustomField>
    <fullName>Requested_Price_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requested Price Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Valid_for_Install_Remove_Replace__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Install_Remove_Replace__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid for Install/Remove/Replace</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CPQ2_ScreenController.cls
/**
 * @description
 *
 * Created by timothychiang on 2020-05-08.
 *
 */

public with sharing class CPQ2_ScreenController {

	/**
	 * @description wrapper class for custom settings
	 */
	public class CustomSettings{
		@AuraEnabled public List<String> coreListPriceLobList;
		@AuraEnabled public CPQ_Settings__c cpqSettings;
		@AuraEnabled public Map<String, Frequency__c> frequencyMap;
	}

	/**
	 * @description wrapper class for the CPQ screen wrapper data
	 */
	public class InitData{
		@AuraEnabled public CPQ2_Wrapper.CpqEntity entity;
		@AuraEnabled public CustomSettings customSettings;
		@AuraEnabled public ScreenPermissions screenPermissions;
		@AuraEnabled public List<CPQ_Multiplier_Table__c> categoryMultiplier;
		@AuraEnabled public List<CPQ2_Score_Multiplier__c> scoreMultiplier;

		public InitData(){
			screenPermissions = new ScreenPermissions();
		}
	}

	public class ScreenPermissions{
		@AuraEnabled public Boolean canApproveOrders;

		public ScreenPermissions(){
			canApproveOrders = Schema.sObjectType.OrderItem.fields.Requested_Price_Approved__c.isUpdateable();
		}
	}

	/**
	 * @description gets the header and lineitems
	 *
	 * @param targetId of the header object
	 *
	 * @return wrapper object with header and line items
	 */
	@AuraEnabled
	public static InitData getInitData(Id targetId) {

		if (String.isEmpty(targetId)) {
			return null;
		}

		InitData initData = new InitData();
		initData.entity = CPQ2_Service.getHeaderAndLineItemsWithProductInfo(targetId);
		initData.customSettings = getCustomSettings();
		initData.categoryMultiplier = CPQ2_Service.getCatMultiplier();
		initData.scoreMultiplier = CPQ2_Service.getScoreMultiplier();
		return initData;
	}

	/**
	 * @description creates a new line item with product information enriched
	 *
	 * @param productId - target product associated with the line item
	 * @param pricebookId - target price book associated with the line item
	 * @param targetId
	 * @param accountId - account associated with the line item
	 *
	 * @return a "blank" line item associated with the proper product, pricebook and account
	 */
	@AuraEnabled(cacheable=false)
	public static List<CPQ2_Wrapper.LineItem> getNewLineItem(Id productId, Id pricebookId, Id targetId, Id accountId, Integer quantity) {
		return CPQ2_Service.getNewLineItem(productId, pricebookId, targetId, accountId, quantity);
	}

	/**
	 * @description get custom settings frequency map
	 *
	 * @return map from frequency name-->frequency object
	 */
	@AuraEnabled(cacheable=true)
	public static Map<String, Frequency__c> getFrequencyMap(){
		return CustomSettingsService.getFrequencyMap();
	}

	/**
	 * @description helper method to obtain all custom settings data
	 *
	 * @return custom settings wrapper with all relevant settings
	 */
	private static CustomSettings getCustomSettings(){
		CustomSettings customSettings = new CustomSettings();
		customSettings.frequencyMap = CustomSettingsService.getFrequencyMap();
		customSettings.cpqSettings = CustomSettingsService.getCpqSettings();
		customSettings.coreListPriceLobList = CustomSettingsService.getCoreListPriceRequestLobs();
		return customSettings;
	}

	/**
	 * @description save opportunity screen changes
	 *
	 * @param lineItems - JSON representation of line items return from the opportunity screen
	 *
	 * @return list of DML results in wrapper classes.
	 */
	@AuraEnabled
	public static List<CPQ2_Wrapper.DmlResult> saveChanges(String lineItems){
		System.debug('Sanchivan saveChanges');
		List<CPQ2_Wrapper.LineItem> saveItems = (List<CPQ2_Wrapper.LineItem>)System.JSON.deserialize(lineItems, List<CPQ2_Wrapper.LineItem>.class);
		return CPQ2_Service.saveChanges(saveItems);
	}

	/**
	 * @description used to simulate ship to score calculations given the entity wrapper
	 *
	 * @param entity - JSON representation of the entity wrapper - contains account, header and line items
	 *
	 * @return the entity enriched with simulated shipto score, simulated line score and simulated approval status
	 */
	@AuraEnabled
	public static CPQ2_Wrapper.CpqEntity calculateShipToScore(String entity){
		CPQ2_Wrapper.CpqEntity entityToCalculate = (CPQ2_Wrapper.CpqEntity)System.JSON.deserialize(entity, CPQ2_Wrapper.CpqEntity.class);
		entityToCalculate.header.coreListThresholdLevel = determineCoreListThresholdLevel(entityToCalculate);
		entityToCalculate.header.includeInPriceModel = true;
		List<CPQ2_Wrapper.LineItem> applicableItemList = new List<CPQ2_Wrapper.LineItem>();
		System.debug('Sanchivan entityToCalculate.lineItems: ' + entityToCalculate.lineItems);
		System.debug('Sanchivan entityToCalculate.lineItems.size(): ' + entityToCalculate.lineItems.size());
		for(CPQ2_Wrapper.LineItem li: entityToCalculate.lineItems){
			System.debug('**** isDeleted ' + li.isDeleted);
			System.debug('**** active ' + li.isActive);
			if(!li.isDeleted && li.isActive){
				li.isEdit = true;
				applicableItemList.add(li);
			}
		}

		entityToCalculate.lineItems = applicableItemList;
		List<CPQ2_Wrapper.CpqEntity> resultingEntity = CPQ2_ShipToCalculatorUtil.calculateShipToScore(new List<CPQ2_Wrapper.CpqEntity>{entityToCalculate}, true);

		return resultingEntity[0];
	}

	/**
	 * @description helper class to helper determine core list price thresholds.
	 * 				this is here instead of in the ship to calculator because core list price has to be determined independently from the calc.
	 *
	 * @param entity - contains the target account, header and line items
	 *
	 * @return the maximum threshold breached by the core list pricing
	 */
	private static Decimal determineCoreListThresholdLevel(CPQ2_Wrapper.CpqEntity entity){
		List<CPQ2_Core_List_Price_Request__c> listCoreListPriceRequests = new List<CPQ2_Core_List_Price_Request__c>();
		for(CPQ2_Wrapper.LineItem lineItem: entity.lineItems){
			if(lineItem.isCoreListSubmitted){
				listCoreListPriceRequests.add(lineItem.coreListPriceRequest.coreListPriceRequest);
			}
		}

		CPQ2_Service.evaluateCoreListPriceRequest(listCoreListPriceRequests);

		Decimal maxThresholdLevel = 0;

		for(CPQ2_Core_List_Price_Request__c clpr: listCoreListPriceRequests){
			maxThresholdLevel = (maxThresholdLevel < clpr.CPQ2_Threshold_Triggered__c)?clpr.CPQ2_Threshold_Triggered__c:maxThresholdLevel;
		}

		return maxThresholdLevel;
	}

	@AuraEnabled
	static public CPQ2_OrderValidationUtil.OrderValidationResult validateOrder(String entity){
		CPQ2_Wrapper.CpqEntity entityToCheck = (CPQ2_Wrapper.CpqEntity)System.JSON.deserialize(entity, CPQ2_Wrapper.CpqEntity.class);

		Set<Id> orderItemIds = new Set<Id>();
		
		// We need to get the latest value of Valid_for_Install_Remove_Replace__c because the latest value is not available on the UI since
		// it gets updated on the trigger. (CPQCN-405)
		for(CPQ2_Wrapper.LineItem lineItem : entityToCheck.lineItems) {
			if(lineItem.isActive && !lineItem.isDeleted && !String.isBlank(lineItem.id)){
				orderItemIds.add(lineItem.Id);
			}
		}

		Map<Id, OrderItem> orderItemMap = new Map<Id, OrderItem>(OrderService.getOrderProductsByIds(orderItemIds));

		for(CPQ2_Wrapper.LineItem lineItem : entityToCheck.lineItems) {
			if(lineItem.isActive && !lineItem.isDeleted && !String.isBlank(lineItem.id)){
				lineItem.orderItem.Valid_for_Install_Remove_Replace__c = orderItemMap.get(lineItem.Id).Valid_for_Install_Remove_Replace__c;
			}
		}

		return CPQ2_Service.validateOrder(entityToCheck);
	}
}