force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Order/fields/Order_Merge_Job_Message__c.field-meta.xml
<CustomField>
    <fullName>Order_Merge_Job_Message__c</fullName>
    <description>Used by the Order Merge batch job.</description>
    <inlineHelpText>Used by the Order Merge batch job.</inlineHelpText>
    <label>Order Merge Job Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Merge_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Merge_Job_Status__c</fullName>
    <description>Used by the Order Merge batch job. Set the value to ‘To be Processed’ to have the batch job pick this record up.</description>
    <inlineHelpText>Used by the Order Merge batch job. Set the value to ‘To be Processed’ to have the batch job pick this record up.</inlineHelpText>
    <label>Order Merge Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ready for Work Order Reparenting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prevent_Invoice_Change_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Invoice_Change_Ticket__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to prevent the Invoice Change Ticket from being created</description>
    <inlineHelpText>Used to prevent the Invoice Change Ticket from being created</inlineHelpText>
    <label>Prevent Invoice Change Ticket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Surviving_Order__c.field-meta.xml
<CustomField>
    <fullName>Surviving_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surviving Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Surviving Order must have same account</errorMessage>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Surviving Order)</relationshipLabel>
    <relationshipName>SurvivingOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderMergerTest.cls
/**
 * Test class for OrderMerger class.
 * @author Ahsan Butt
 */
@isTest
public class OrderMergerTest {

        static testMethod void testMerge() {
            // Create necessary FSS custom settings
            MergeTestUtils.createFSSCustomSettings();
            
            // Create account
            Account acct = MergeTestUtils.createAccount();
            
            // Create price book entries / products
            List<PricebookEntry> pbookEntries = MergeTestUtils.createPricebookEntries(1);
            
            // Create Order
            Order o = MergeTestUtils.createOrder(acct, pbookEntries, false);
            
            // Create surviving order and set on source order
            Order survivingOrder = MergeTestUtils.createOrder(acct, new List<PricebookEntry>(), false);
            
            o.Surviving_Order__c = survivingOrder.Id;
            
            update o;
            
            // Run merge
            List<Order> srcOrders = [SELECT Id, Surviving_Order__c, Status, Prevent_Invoice_Change_Ticket__c, Order_Merge_Job_Status__c, Order_Merge_Job_Message__c FROM Order WHERE Id = :o.Id];
            List<String> filters =  new List<String>{'FrequencyOrderItemFilter'};
            String oiFS = 'Clone_Fields';
            
            OrderMerger.doMerges(srcOrders, oiFS, filters, new List<String>());
            
            // Check end conditions
            o = [SELECT Id, Status, Order_Merge_Job_Status__c FROM Order WHERE Id = :o.Id LIMIT 1];
            survivingOrder  = [SELECT Id, Status FROM Order WHERE Id = :survivingOrder.Id LIMIT 1];
            
            System.assertNotEquals('Activated', o.Status, 'Source Order should be deactivated');
            System.assertEquals('Ready for Work Order Reparenting', o.Order_Merge_Job_Status__c, 'Source Order Merge job status should be ready for WO reparenting');
            System.assertEquals('Activated', survivingOrder.Status, 'Surviving Order should be activated');
        }
    
    	static testMethod void testRollback() {
            // Create necessary FSS custom settings
            MergeTestUtils.createFSSCustomSettings();
            
            // Create account
            Account acct = MergeTestUtils.createAccount();
            
            // Create price book entries / products
            List<PricebookEntry> pbookEntries = MergeTestUtils.createPricebookEntries(1);
            
            // Create Order -- with one-time frequency such that it fails filter
            Order o = MergeTestUtils.createOrder(acct, pbookEntries, true);
            
            // Create surviving order and set on source order
            Order survivingOrder = MergeTestUtils.createOrder(acct, new List<PricebookEntry>(), false);
            
            o.Surviving_Order__c = survivingOrder.Id;
            
            update o;
            
            // Run merge
            List<Order> srcOrders = [SELECT Id, Surviving_Order__c, Status, Prevent_Invoice_Change_Ticket__c, Order_Merge_Job_Status__c, Order_Merge_Job_Message__c FROM Order WHERE Id = :o.Id];
            List<String> filters =  new List<String>{'FrequencyOrderItemFilter'};
            String oiFS = 'Clone_Fields';
            
            OrderMerger.doMerges(srcOrders, oiFS, filters, new List<String>());
            
            // Check end conditions
            o = [SELECT Id, Status, Order_Merge_Job_Status__c FROM Order WHERE Id = :o.Id LIMIT 1];
            
            System.assertEquals('Error', o.Order_Merge_Job_Status__c, 'Source Order Merge job status should be error');
        }
}