force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/Order/fields/CPQ2_Include_in_Price_Model__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_Include_in_Price_Model__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Price Model</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <formula>PricebookEntry.Product2.Item_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <inlineHelpText>Indicate if the Customer is charged a Price for the Purchase of this item. Price Entered is per unit. If only Purchase Price is filled in, this would be considered as a One Time Delivery.</inlineHelpText>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Work_Type__c</fullName>
    <formula>PricebookEntry.Product2.Service_Work_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Work Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SurveyAssetCountChecker__c.field-meta.xml
<CustomField>
    <fullName>SurveyAssetCountChecker__c</fullName>
    <label>SurveyAssetCountChecker</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Amortization__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Amortization__c</fullName>
    <label>Amortization</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Capital_Cost__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Capital_Cost__c</fullName>
    <label>Capital Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Cost__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Cost__c</fullName>
    <label>Material Cost Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CPQ_Price_Model__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Price_Model__c</fullName>
    <label>Price Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPQ_Price_Model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Products (Service Work Type)</relationshipLabel>
    <relationshipName>ServiceProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CPQ_Price_Model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hygiene Pricing Model</fullName>
    </customValue>
    <masterLabel>Price Model</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CPQ2_OrderValidationUtilTest.cls
/**
 * @description
 *
 * Created by timothychiang on 2020-06-01.
 *
 */
@IsTest
public with sharing class CPQ2_OrderValidationUtilTest {
	@TestSetup static void setup() {
		Id pBook = Test.getStandardPricebookId();

		List<WorkType> workTypesToInsert = new List<WorkType>();
		WorkType workType1 = new WorkType(
			Name='TestWorkType1',
			DurationType='Minutes',
			EstimatedDuration=1.7
		);

		WorkType workType2 = new WorkType(
			Name='TestWorkType2',
			DurationType='Minutes',
			EstimatedDuration=1
		);

		WorkType workType3 = new WorkType(
			Name='TestWorkType3',
			DurationType='Minutes',
			EstimatedDuration=0.11
		);
		workTypesToInsert.add(workType1);
		workTypesToInsert.add(workType2);
		workTypesToInsert.add(workType3);
		insert workTypesToInsert;

		Product2 product1 = new Product2(
			Name='TestProduct1',
			Allowable_Frequencies__c='One-Time;Monthly;Weekly;Annually',
			IsActive=true,
			Family='Hygiene',
			ExternalID__c = 'TestProduct1',
			CPQ_Price_Model__c = 'Hygiene Pricing Model',
			Item_Type__c = 'Service',
			Service_Work_Type__c = workType1.Id,
			CPQ_Cost__c = 0.93,
			CPQ_Amortization__c = 4,
			CPQ_Capital_Cost__c = 0
		);

		Product2 product2 = new Product2(
			Name='TestProduct2',
			Allowable_Frequencies__c='One-Time;Monthly;Weekly;Annually',
			IsActive=true,
			Family='Hygiene',
			Item_Type__c = 'Service',
			ExternalID__c = 'TestProduct2',
			CPQ_Price_Model__c = 'Hygiene Pricing Model',
			Service_Work_Type__c = workType2.Id,
			CPQ_Cost__c =  57.33,
			CPQ_Amortization__c = 4,
			CPQ_Capital_Cost__c = 0
		);

		Product2 product3 = new Product2(
			Name='TestProduct3',
			Allowable_Frequencies__c='One-Time;Monthly;Weekly;Annually',
			IsActive=true,
			Family='Hygiene',
			ExternalID__c = 'TestProduct3',
			Item_Type__c = 'Consumable'
		);

		TestDataFactory.products.add(product1);
		TestDataFactory.products.add(product2);
		TestDataFactory.products.add(product3);
		insert TestDataFactory.products;

		PricebookEntry pbe1 = new PricebookEntry(
			Pricebook2Id = pBook,
			Product2Id = product1.Id,
			UnitPrice = 1.0,
			IsActive = true
		);

		PricebookEntry pbe2 = new PricebookEntry(
			Pricebook2Id = pBook,
			Product2Id = product2.Id,
			UnitPrice = 1.0,
			IsActive = true
		);

		PricebookEntry pbe3 = new PricebookEntry(
			Pricebook2Id = pBook,
			Product2Id = product3.Id,
			UnitPrice = 1.0,
			IsActive = true
		);
		TestDataFactory.pEntries.add(pbe1);
		TestDataFactory.pEntries.add(pbe2);
		TestDataFactory.pEntries.add(pbe3);
		insert TestDataFactory.pEntries;

		TestDataFactory.crtCPQSettings();
		TestDataFactory.crtFieldSettings();
		//TestDataFactory.crtFieldServiceSetting();

		//TestDataFactory.crtProdWithPE(4);
		TestDataFactory.crtAcctContact(1, 1);
        TestDataFactory.accounts[0].RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Bill To').getRecordTypeId();
		update TestDataFactory.accounts[0];
//		TestDataFactory.crtSiteSurvey(1);
//		TestDataFactory.crtOpportunities(1, TestDataFactory.accounts[0], TestDataFactory.contacts[0].Id, false);
	}

	/*2020-12-02 Darcy: CPQCN-434
		* validations are being disabled for now
		*/
	/*	
	@IsTest
	static void testValidation() {
		Account acct = [SELECT Id FROM Account LIMIT 1];

		List<PricebookEntry> priceBookEntries = [SELECT Id, Product2.Name FROM PricebookEntry];

		PricebookEntry pbe1;
		PricebookEntry pbe2;
		PricebookEntry pbe3;

		for(PricebookEntry priceBookEntry : priceBookEntries) {
			if (priceBookEntry.Product2.Name == 'TestProduct1') {
				pbe1 = priceBookEntry;
			}
			else if (priceBookEntry.Product2.Name == 'TestProduct2') {
				pbe2 = priceBookEntry;
			}
			else if (priceBookEntry.Product2.Name == 'TestProduct3') {
				pbe3 = priceBookEntry;
			}
		}


		Order order = (Order) TestUtils.createSObject(new Order(
			AccountId = acct.Id,
			CPQ2_Include_in_Price_Model__c = true
		));

		insert order;

		List<OrderItem> orderItems = (List<OrderItem>)TestUtils.createSObjectList(new OrderItem(), 3);

		orderItems[0].Product2Id = pbe1.Product2Id;
		orderItems[0].Frequency__c = 'Monthly';
		orderItems[0].UnitPrice = 12.0;
		orderItems[0].Service_Price_Per_Unit__c = 11.0;
		orderItems[0].Quantity = 10;
		orderItems[0].OrderId = order.Id;
		orderItems[0].SurveyAssetCountChecker__c = 1;

		orderItems[1].Product2Id = pbe2.Product2Id;
		orderItems[1].Frequency__c = 'Weekly';
		orderItems[1].UnitPrice = 12.0;
		orderItems[1].Service_Price_Per_Unit__c = 150.0;
		orderItems[1].Quantity = 10;
		orderItems[1].OrderId = order.Id;
		orderItems[1].SurveyAssetCountChecker__c = 1;

		orderItems[2].Product2Id = pbe3.Product2Id;
		orderItems[2].Frequency__c = 'One-Time';
		orderItems[2].Purchase_Price__c = 3.0;
		orderItems[2].Quantity = 10;
		orderItems[2].OrderId = order.Id;

		CPQ2_OrderValidationUtil.OrderValidationResult result = CPQ2_OrderValidationUtil.validateOrderLineItems(orderItems);
		System.assertEquals(false, result.isSuccess);
	}
	*/
	
	@IsTest
	static void testValidationPass() {
		Account acct = [SELECT Id FROM Account LIMIT 1];

		List<PricebookEntry> priceBookEntries = [SELECT Id, Product2.Name FROM PricebookEntry];

		PricebookEntry pbe1;
		PricebookEntry pbe2;
		PricebookEntry pbe3;

		for(PricebookEntry priceBookEntry : priceBookEntries) {
			if (priceBookEntry.Product2.Name == 'TestProduct1') {
				pbe1 = priceBookEntry;
			}
			else if (priceBookEntry.Product2.Name == 'TestProduct2') {
				pbe2 = priceBookEntry;
			}
			else if (priceBookEntry.Product2.Name == 'TestProduct3') {
				pbe3 = priceBookEntry;
			}
		}


		Order order = (Order) TestUtils.createSObject(new Order(
			AccountId = acct.Id,
			CPQ2_Include_in_Price_Model__c = true
		));

		insert order;

		List<OrderItem> orderItems = (List<OrderItem>)TestUtils.createSObjectList(new OrderItem(), 2);

		orderItems[0].Product2Id = pbe1.Product2Id;
		orderItems[0].Frequency__c = 'Monthly';
		orderItems[0].UnitPrice = 12.0;
		orderItems[0].Service_Price_Per_Unit__c = 11.0;
		orderItems[0].Quantity = 10;
		orderItems[0].OrderId = order.Id;
		orderItems[0].SurveyAssetCountChecker__c = 1;

		orderItems[1].Product2Id = pbe2.Product2Id;
		orderItems[1].Frequency__c = 'Weekly';
		orderItems[1].UnitPrice = 12.0;
		orderItems[1].Service_Price_Per_Unit__c = 150.0;
		orderItems[1].Quantity = 10;
		orderItems[1].OrderId = order.Id;
		orderItems[1].SurveyAssetCountChecker__c = 1;

		CPQ2_OrderValidationUtil.OrderValidationResult result = CPQ2_OrderValidationUtil.validateOrderLineItems(orderItems);
		System.assertEquals(true, result.isSuccess);
	}

}