force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Integration_User_Profile__c.field-meta.xml
<CustomField>
    <fullName>Integration_User_Profile__c</fullName>
    <description>Profile to be excluded from validation rules</description>
    <label>Integration User Profile</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Operating_Hours_Type_Account__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type_Account__c</fullName>
    <label>Operating Hours Type - Account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Order_Active_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Active_Stage__c</fullName>
    <label>Order Active Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OperatingHours/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OperatingHours/fields/Operating_Hours_Type__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type__c</fullName>
    <label>Operating Hours Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Operating Hours</fullName>
            </value>
            <value>
                <fullName>Employee Operating Hours</fullName>
            </value>
            <value>
                <fullName>Territory Operating Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ServiceTypeRollupBatchJobImplTest.cls
/**
 * Test for Service Type Rollups.
 * 
 * @author Ahsan Butt
 */
@isTest
public class ServiceTypeRollupBatchJobImplTest {
	
    @TestSetup static void setup() {
        Field_Service_Settings__c fss = new Field_Service_Settings__c();
        fss.Order_Active_Stage__c = 'Activated';
        fss.Operating_Hours_Type_Account__c = 'Account Operating Hours';
        insert fss;
        
        /*OperatingHours oh = new OperatingHours(
          Name='TestHours', 
            Operating_Hours_Type__c='Account Operating Hours', 
            TimeZone='America/New_York'
        );
        
        OperatingHours territoryHours = new OperatingHours(
            Name='TestHoursTerritory', 
            Operating_Hours_Type__c='Territory Operating Hours', 
            TimeZone='America/New_York'
        );
        
        insert new List<OperatingHours>{oh, territoryHours};
        
        ServiceTerritory st1 = new ServiceTerritory(
            IsActive=TRUE,
            Street='Street', 
            City = 'City', 
            State = 'State', 
            PostalCode = 'PostalCode',
            Country = 'Country', 
            OperatingHoursId=territoryHours.Id, 
            Name='TerritoryForCaseTestScenarios1'
            
        );
        insert st1;
        ServiceTerritory st = new ServiceTerritory(
            IsActive=TRUE,
            Street='Street', 
            City = 'City', 
            State = 'State', 
            PostalCode = 'PostalCode',
            Country = 'Country', 
            OperatingHoursId=territoryHours.Id, 
            Name='TerritoryForCaseTestScenarios',
            ParentTerritoryId = st1.Id
            
        );
        insert st;*/
        
        
        // Insert test records
        TestDataFactory.crtBillToAcctContact(1, 1);
        
        // Create order
        List<Product2> products = new List<Product2>();
        Id pBook = Test.getStandardPricebookId();
        
        // Need to create product(s) first
		for(Integer i=0; i < 2; i++){
            products.add(
                new Product2(
                    Name = 'TEST_PROD' + i,
					ProductCode = Math.mod(i, 2) == 0 ? '1-03' : '1-04',
                    ExternalId__c = '3-55-7-02-1' + i
                )       
            );
        }
        
        insert products;
        
        List<PricebookEntry> pEntries = new List<PricebookEntry>();
        
        for(Integer i=0; i < 2; i++) {
            pEntries.add(
                new PricebookEntry(
                    Pricebook2Id = pBook, 
                    Product2Id = products.get(i).Id, 
                    UnitPrice = 1.0, 
                    IsActive = true
                )
            );
        }
        
        insert pEntries; 
        
        // Create Order
        Order o = new Order(
        	AccountId = TestDataFactory.accounts[0].Id, 
            Status = 'Draft', 
            EffectiveDate = System.today(), 
            Pricebook2Id = pEntries.get(0).Pricebook2Id
        ); 
        
        insert o;
        
        // Create order line items
        List<OrderItem> orderItems = new List<OrderItem>();
        
        for(Integer i = 0; i < pEntries.size(); i++) {
            orderItems.add(
                new OrderItem(
                    Description='',
                    Product2Id=pEntries.get(i).Id,  
                    UnitPrice=1.0, 
                    Service_Price_Per_Unit__c=1.0, 
                    Quantity=1, 
                    OrderId=o.Id
                )
            );
        }
        
		insert orderItems;
    }
    
    static testMethod void testRollup() {
        Field_Service_Settings__c fss = Field_Service_Settings__c.getOrgDefaults();
        fss.Order_Active_Stage__c = 'Draft'; // Hack
        fss.Integration_User_Profile__c = userinfo.getProfileId();
        update fss;
        
        List<Order> orders = [SELECT Id FROM Order];
        
        OrderServiceTypeRollupBatchJobImpl orderRollup = new OrderServiceTypeRollupBatchJobImpl('test', 10);
        orderRollup.start(null);
        orderRollup.execute(null, orders);
        orderRollup.finish(null);
        
        Set<Id> acctIds = new Set<Id>();
        Map<Id, Account> accts = new Map<Id,Account>([SELECT Id FROM Account]);
        
        AccountServiceTypeRollupBatchJobImpl acctRollup = new AccountServiceTypeRollupBatchJobImpl('test', accts.keySet());
        acctRollup.start(null);
        acctRollup.execute(null, accts.values());
        acctRollup.finish(null);
    }
}