force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/BatchJobSchedulerSettings__c/BatchJobSchedulerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used by the Custom Scheduler to map Batch Jobs to their custom settings entries.</description>
    <label>Batch Job Scheduler Settings</label>
</CustomObject>

force-app/main/default/objects/BatchJobSchedulerSettings__c/fields/Custom_Setting_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Custom_Setting_Object_Name__c</fullName>
    <description>The name of the custom Setting object itself (e.g., &quot;Custom_Setting_Obj__c&quot;).</description>
    <inlineHelpText>The name of the custom Setting object itself (e.g., &quot;Custom_Setting_Obj__c&quot;).</inlineHelpText>
    <label>Custom Setting Object Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchJobSchedulerSettings__c/fields/Scheduler_Class__c.field-meta.xml
<CustomField>
    <fullName>Scheduler_Class__c</fullName>
    <description>The Batch job specific schedulable to schedule.</description>
    <label>Scheduler Class</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupBatchSettings__c/RollupBatchSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for Rollup Batch jobs.</description>
    <label>Rollup Batch Settings</label>
</CustomObject>

force-app/main/default/objects/RollupBatchSettings__c/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <description>A filter to apply to the source records being queried (e.g., Type = &apos;Email&apos; OR Type = &apos;Call&apos;).</description>
    <inlineHelpText>A filter to apply to the source records being queried (e.g., Type = &apos;Email&apos; OR Type = &apos;Call&apos;).</inlineHelpText>
    <label>Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupBatchSettings__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <description>The roll-up function to apply. Valid values are: &apos;COUNT&apos;, &apos;AVG&apos;, &apos;LAST&apos; (i.e., most recent).</description>
    <inlineHelpText>The roll-up function to apply. Valid values are: &apos;COUNT&apos;, &apos;AVG&apos;, &apos;LAST&apos; (i.e., most recent).</inlineHelpText>
    <label>Function</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupBatchSettings__c/fields/Merge_Field__c.field-meta.xml
<CustomField>
    <fullName>Merge_Field__c</fullName>
    <description>The field on the source object that looks up to the target object (i.e., the parent object). For instance, if a field on Opportunity is being rolled up to a field on an Account, the merge field would be &apos;AccountId.&apos;</description>
    <inlineHelpText>The field on the source object that looks up to the target object (i.e., the parent object). For instance, if a field on Opportunity is being rolled up to a field on an Account, the merge field would be &apos;AccountId.&apos;</inlineHelpText>
    <label>Merge Field</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupBatchSettings__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <description>The field on which the roll-up is being performed.</description>
    <inlineHelpText>The field on which the roll-up is being performed.</inlineHelpText>
    <label>Source Field</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupBatchSettings__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>The object whose field is being rolled up.</description>
    <inlineHelpText>The object whose field is being rolled up (in other words, the child object).</inlineHelpText>
    <label>Source Object</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupBatchSettings__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <description>The field on the target in which we&apos;re storing the rolled up value.</description>
    <inlineHelpText>The field on the target in which we&apos;re storing the rolled up value.</inlineHelpText>
    <label>Target Field</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RollupBatchSettings__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <description>The object on which we are storing the roll-up (i.e., the parent object).</description>
    <inlineHelpText>The object on which we are storing the roll-up (i.e., the parent object).</inlineHelpText>
    <label>Target Object</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomSchedulerControllerTest.cls
/**
 * Unit test for CustomSchedulerController.
 * 
 * @author: Ahsan Butt
 */
@isTest
private class CustomSchedulerControllerTest {

    static testMethod void testGetCurrentlyRunningJobs() {
        String jobName = 'Test';
        
        // Insert custom settings
        RollupBatchSettings__c rollupSettings = createTestBatchSettings();
        insert rollupSettings;
        
        ICustomSchedulable sched = (ICustomSchedulable) new RollupSchedulableImpl(jobName, rollupSettings.Name);
        
        // Create cron string 
        String cron = '0 0 0 * * ?';
        
        // Schedule job
        System.schedule(jobName, cron, sched);    
        
        // Test getCurrentlyRunningJobs
        List<CustomSchedulerController.BatchJobState> runningJobs = CustomSchedulerController.getCurrentlyRunningJobs(new List<String>{jobName});
        
        System.assertEquals(1, runningJobs.size(), '1 job should be running!');
    }
    
    static testMethod void testScheduleJob() {
        // Insert custom settings
        RollupBatchSettings__c rollupSettings = createTestBatchSettings();
        insert rollupSettings;
        
        BatchJobSchedulerSettings__c schedSettings = createTestSchedulerSettings();
        insert schedSettings;
        
        // Invoke schedule job   
        CustomSchedulerController.ScheduleJobResult result = CustomSchedulerController.scheduleJob(schedSettings.Name, rollupSettings.Name, '00');
        
        System.assert(result.success, 'Schedule Job result should be true.');
        
        // Assert it's running
		List<CustomSchedulerController.BatchJobState> runningJobs = CustomSchedulerController.getCurrentlyRunningJobs(new List<String>{schedSettings.Name});
        
        System.assertEquals(1, runningJobs.size(), 'Should be 1 running job.');
        
        // Delete the job
        runningJobs = CustomSchedulerController.deleteJob(runningJobs.get(0).id, new List<String>{schedSettings.Name});
        
        // Assert it's not
        System.assertEquals(0, runningJobs.size(), 'Should be 0 running jobs.');
    }
    
    static testMethod void testGetInitialState() {
        // Insert custom settings
        RollupBatchSettings__c rollupSettings = createTestBatchSettings();
        insert rollupSettings;
        
        BatchJobSchedulerSettings__c schedSettings = createTestSchedulerSettings();
        insert schedSettings;
        
        // Invoke schedule job   
        CustomSchedulerController.ScheduleJobResult result = CustomSchedulerController.scheduleJob(schedSettings.Name, rollupSettings.Name, '00');
        
        // Get initial State
        CustomSchedulerController.SchedulerState state = CustomSchedulerController.getInitialState();
        
        // Assert running jobs
        System.assertEquals(1, state.runningJobs.size(), 'Should be 1 running jobs.');
        
        // Assert configured batchJob is returned
        System.assertEquals(1, state.batchJobs.size(), 'Should be 1 batch job configured.');
    }
    
    private static RollupBatchSettings__c createTestBatchSettings() {
        RollupBatchSettings__c rollupSettings = new RollupBatchSettings__c();
        rollupSettings.Name = 'Amount Rollup';
        rollupSettings.Source_Object__c = 'Opportunity';
        rollupSettings.Source_Field__c = 'Amount';
        rollupSettings.Merge_Field__c = 'AccountId';
        rollupSettings.Target_Object__c = 'Account';
        rollupSettings.Target_Field__c = 'AnnualRevenue';
        rollupSettings.Filter__c = '';
        rollupSettings.Function__c = 'SUM';

        return rollupSettings;
    }
    
    private static BatchJobSchedulerSettings__c createTestSchedulerSettings() {
        BatchJobSchedulerSettings__c schedSettings = new BatchJobSchedulerSettings__c();
		schedSettings.Name = 'Test Sched Setting';
        schedSettings.Scheduler_Class__c = 'RollupSchedulableImpl';
        schedSettings.Custom_Setting_Object_Name__c = 'RollupBatchSettings__c';
        
        return schedSettings;
    }
}