force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Plan__c.field-meta.xml
<CustomField>
    <fullName>Service_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Service Plan record that services this Order Product.</description>
    <inlineHelpText>Lookup to Service Plan record that services this Order Product.</inlineHelpText>
    <label>Service Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Plan__c.Frequency__c</field>
            <operation>equals</operation>
            <valueField>$Source.Frequency__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Plan__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <description>Parent object for Service Plans. Links Service Plans to a Technician.</description>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Route Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the Service Resource to whom this Route is assigned.</description>
    <inlineHelpText>Reference to the Service Resource to whom this Route is assigned.</inlineHelpText>
    <label>Service Resource</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active service resources may be assigned to a route.</errorMessage>
        <filterItems>
            <field>ServiceResource.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active service resources may be assigned to a route.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule_Type__c/Schedule_Type__c.object-meta.xml
<CustomObject>
    <description>Describes a subset of frequency on recurring Order Products. For example, if an Order Product has a frequency of weekly, Schedule Type may further refine this frequency to Every 7 Days - Monday.</description>
    <label>Schedule Type</label>
    <nameField>
        <label>Schedule Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Type__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Used to determine the schedule of Service Plans in code.</description>
    <inlineHelpText>Used to determine the schedule of Service Plans in code. Value must be unique and follow a specified structure. Review schedule code documentation before entering new values.</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Schedule_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>User friendly description of what the Schedule Type code means. ie. W-1 = Every 7 Days - Monday.</description>
    <inlineHelpText>User friendly description of what the Schedule Type code means. ie. W-1 = Every 7 Days - Monday.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Schedule_Type__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Service frequency for recurring Order Products.</description>
    <inlineHelpText>Service frequency for recurring Order Products.</inlineHelpText>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Plan__c/Service_Plan__c.object-meta.xml
<CustomObject>
    <description>Object to summarize recurring Order Products serviced by a Technician.</description>
    <label>Service Plan</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Service Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Associated account record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Plans</relationshipLabel>
    <relationshipName>Service_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Plan__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Service frequency for recurring Order Products.</description>
    <inlineHelpText>Service frequency for recurring Order Products.</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Plan__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Route to which this Service Plan is associated</description>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Service Plans</relationshipLabel>
    <relationshipName>Service_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Plan__c/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Schedule Type record. Used to refine the frequency of this Service Plan. For example, if frequency is 7 days, schedule type may be Every 7 Days - Monday.</description>
    <inlineHelpText>Used to further refine the frequency of this Service Plan.For example, if frequency is 7 days, schedule type may be Every 7 Days - Monday.</inlineHelpText>
    <label>Schedule Type</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The schedule type must have the same frequency as the service plan.</errorMessage>
        <filterItems>
            <field>$Source.Frequency__c</field>
            <operation>equals</operation>
            <valueField>Schedule_Type__c.Frequency__c</valueField>
        </filterItems>
        <infoMessage>The schedule type must have the same frequency as the service plan.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_Type__c</referenceTo>
    <relationshipLabel>Service Plans</relationshipLabel>
    <relationshipName>Service_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Service_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>14 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>28 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>56 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Semi-Annually</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <customValue>
        <fullName>112 Days</fullName>
    </customValue>
    <customValue>
        <fullName>2X Per Year</fullName>
    </customValue>
    <customValue>
        <fullName>2X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>3X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>5X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>6X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>42 Days</fullName>
    </customValue>
    <customValue>
        <fullName>84 Days</fullName>
    </customValue>
    <customValue>
        <fullName>120 Days</fullName>
    </customValue>
    <customValue>
        <fullName>168 Days</fullName>
    </customValue>
    <customValue>
        <fullName>182 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Weekly</fullName>
        <isActive>false</isActive>
        <label>Fixed Weekly</label>
    </customValue>
    <customValue>
        <fullName>364 Days</fullName>
        <isActive>false</isActive>
        <label>364 Days</label>
    </customValue>
    <description>Service frequency for recurring Order Products.</description>
    <masterLabel>Service Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestUtilsWrapperServicePlan.cls
/**
 * @FileName: TestUtilsWrapperServicePlan
 * @Description: Wrapper class for default Service Plan test data
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       11/8/2019         Created
 *-----------------------------------------------------------  
 */
public inherited sharing class TestUtilsWrapperServicePlan {
    public Route__c route;
    public List<Service_Plan__c> servicePlans;
    public List<Schedule_Type__c> scheduleTypes;
    public List<OrderItem> orderItems;

    public TestUtilsWrapperServicePlan(Account a, ServiceResource sr, List<OrderItem> items) {
        this(a, sr, items, true);
    }

    public TestUtilsWrapperServicePlan(Account a, ServiceResource sr, List<OrderItem> items, Boolean doInsert) {
        createTestData(a, sr, items, doInsert);
    }

    private void createTestData(Account a, ServiceResource sr, List<OrderItem> items, Boolean doInsert) {
        createSchedules();

        route = (Route__c) TestUtils.createSObject(new Route__c(Service_Resource__c = sr.Id));

        servicePlans = (List<Service_Plan__c>) TestUtils.createSObjectList(
                new Service_Plan__c(
                        Account__c = a.Id
                ),
                scheduleTypes.size()
        );

        orderItems = items;

        if (doInsert) doInsert();
    }

    private void createSchedules() {
        scheduleTypes = new List<Schedule_Type__c>();

        scheduleTypes.add((Schedule_Type__c)TestUtils.createSObject(new Schedule_Type__c(
                Name = 'Weekly - Monday',
                Description__c = 'Weekly - Monday',
                Frequency__c = 'Weekly',
                Code__c = 'W-1'
        )));

        scheduleTypes.add((Schedule_Type__c)TestUtils.createSObject(new Schedule_Type__c(
                Name = 'Monthly - First Friday',
                Description__c = 'Monthly - First Friday',
                Frequency__c = 'Monthly',
                Code__c = 'M-5-1'
        )));

        scheduleTypes.add((Schedule_Type__c)TestUtils.createSObject(new Schedule_Type__c(
                Name = 'Bimonthly - FEB/APR/JUN/AUG/OCT/DEC-1st Fri',
                Description__c = 'Bimonthly - FEB/APR/JUN/AUG/OCT/DEC-1st Fri',
                Frequency__c = 'Bi-Monthly',
                Code__c = 'B-2-5-1'
        )));

        scheduleTypes.add((Schedule_Type__c)TestUtils.createSObject(new Schedule_Type__c(
                Name = 'Quarterly - FEB/MAY/AUG/NOV-1st Wed',
                Description__c = 'Quarterly - FEB/MAY/AUG/NOV-1st Wed',
                Frequency__c = 'Quarterly',
                Code__c = 'Q-2-3-1'
        )));

        scheduleTypes.add((Schedule_Type__c)TestUtils.createSObject(new Schedule_Type__c(
                Name = 'Every 14 Days - Tuesday',
                Description__c = 'Every 14 Days - Tuesday',
                Frequency__c = '14 Days',
                Code__c = '14-2'
        )));
    }

    public void doInsert() {
        insert scheduleTypes;
        insert route;

        Map<String,Service_Plan__c> servicePlanMap = new Map<String,Service_Plan__c>();

        for(Integer i = 0; i < scheduleTypes.size(); i++) {
            servicePlans[i].Route__c = route.Id;
            servicePlans[i].Schedule_Type__c = scheduleTypes[i].Id;
            servicePlans[i].Frequency__c = scheduleTypes[i].Frequency__c;

            servicePlanMap.put(scheduleTypes[i].Frequency__c, servicePlans[i]);
        }

        insert servicePlans;

        for (OrderItem item : orderItems) {
            Service_Plan__c plan = servicePlanMap.get(item.Frequency__c);

            if(plan != null) {
                item.Service_Plan__c = plan.Id;
            }
        }

        update orderItems;
    }
}