force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/Order/fields/Season_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Season_End_Date__c</fullName>
    <formula>IF(
DATE(YEAR(TODAY()),  SeasonEndMonthValue__c ,  SeasonEndDayValue__c ) &lt;=   Season_Start_Date__c ,
DATE(YEAR(TODAY())+1, SeasonEndMonthValue__c, SeasonEndDayValue__c ),
DATE(YEAR(TODAY()), SeasonEndMonthValue__c, SeasonEndDayValue__c )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Season End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Season_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Season_Start_Date__c</fullName>
    <formula>IF(  SeasonStartMonthValue__c  &gt; MONTH( TODAY() )  &amp;&amp;    SeasonEndMonthValue__c  &gt;= MONTH( TODAY() )  &amp;&amp; (SeasonEndMonthValue__c &lt; SeasonStartMonthValue__c || (SeasonEndMonthValue__c = SeasonStartMonthValue__c &amp;&amp; SeasonStartDayValue__c &gt; SeasonEndDayValue__c)
), DATE(YEAR(TODAY())-1, SeasonStartMonthValue__c,  SeasonStartDayValue__c ), DATE(YEAR(TODAY()), SeasonStartMonthValue__c, SeasonStartDayValue__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Season Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Installation_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Status__c</fullName>
    <inlineHelpText>Indicate if this is a new Asset Install, Removing(for seasonality purposes), Replacing(an old asset is replaced with a new one)</inlineHelpText>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Install/Repair Completed</fullName>
                <isActive>false</isActive>
                <label>Install/Repair Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Inventory_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inventory Allocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>This field is System Generated during the nightly Work Order Generation batch job. Changing this would have implications on Work Order Generation Logic</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <label>Last InFlight WO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Valid_for_Install_Remove_Replace__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Install_Remove_Replace__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid for Install/Remove/Replace</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/Work_Order_Generation_Status_Staging__c.object-meta.xml
<CustomObject>
    <description>Duplicate Object</description>
    <label>Work Order Generation Status Staging</label>
    <nameField>
        <label>Work Order Generation Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Generation Status Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Expected_WO_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_WO_Start_Date__c</fullName>
    <label>Expected WO Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Last_Automation_Created_Date_stamp__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date_stamp__c</fullName>
    <label>Last Automation Created Date stamp</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Last_InFlight_WO_Date_stamp__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date_stamp__c</fullName>
    <label>Last InFlight WO Date stamp</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Order_Account_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Order_Account_Inactive__c</fullName>
    <label>Order Account Inactive?</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Order_Account_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Order_Account_On_Hold__c</fullName>
    <label>Order Account On Hold?</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Order_Inventory_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Order_Inventory_Allocated__c</fullName>
    <label>Order Inventory Allocated</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Work Order Generation Status</relationshipLabel>
    <relationshipName>Work_Order_Generation_Status1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Order_Product_Active__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_Active__c</fullName>
    <label>Order Product Active</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Order_Product_IsActive__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_IsActive__c</fullName>
    <label>Order Product IsActive</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Order_Product_Valid_for_Install_Replace__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_Valid_for_Install_Replace__c</fullName>
    <label>Order Product Valid for Install/Replace</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Order_Status_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Order_Status_Stamp__c</fullName>
    <label>Order Status Stamp</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status_Staging__c/fields/Reasons_for_failures__c.field-meta.xml
<CustomField>
    <fullName>Reasons_for_failures__c</fullName>
    <label>Reasons for failures</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateWOGenerationBatchFinalStaging.cls
global class UpdateWOGenerationBatchFinalStaging implements Database.Batchable<SObject>{
    
     global Database.QueryLocator Start(Database.BatchableContext bc){                      
        return Database.getQueryLocator([Select Id,Status__c from Work_Order_Generation_Status_Staging__c where status__c = '']);                     
    }
    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        system.debug('a3a3a3a3a3a3');
        Set<Id> listWOGSL = new Set<Id>();
        List<Work_Order_Generation_Status_Staging__c> updateWogs = new List<Work_Order_Generation_Status_Staging__c>();
        List<Work_Order_Generation_Status_Staging__c> deleteWogs = new List<Work_Order_Generation_Status_Staging__c>();
        
        for(SObject s : scope){
            listWOGSL.add(s.Id);
        }
    
        for(Work_Order_Generation_Status_Staging__c wogs : [Select Expected_WO_Start_Date__c,Order_Product__r.Order.Season_Start_Date__c,Order_Product__r.Order.Season_End_Date__c,Status__c,Order_Product__r.Order.Inventory_Allocated__c,Order_Product__r.Last_Automation_Created_Date__c,Order_Product__r.Valid_for_Install_Remove_Replace__c,
                                                    Order_Product__r.Installation_Status__c,Order_Product__r.Frequency__c,Order_Product__r.Product2.Allowable_Frequencies__c,Order_Product__r.Last_InFlight_WO_Date__c,
                                                    Order_Account_Inactive__c,Order_Account_On_Hold__c,Order_Inventory_Allocated__c, Order_Product_Active__c,
                                                    Order_Product_Installation_Status__c,Order_Product_Inventory_Allocated__c,Order_Product_IsActive__c,
                                                    Order_Product_Valid_for_Install_Replace__c,Order_Status_Stamp__c from Work_Order_Generation_Status_Staging__c where id in : listWOGSL]){
                 
                system.debug('a4a4a4a4a4a4' + wogs);
                List<String> freqList = new List<String>();    
                freqList = wogs.Order_Product__r.Product2.Allowable_Frequencies__c.split(';');
                       
                String stamp = ''; 
                
                List<String> listMultiSelect = new List<String>();
                if(((wogs.Expected_WO_Start_Date__c >= wogs.Order_Product__r.Order.Season_Start_Date__c && wogs.Expected_WO_Start_Date__c <= wogs.Order_Product__r.Order.Season_End_Date__c) && (wogs.Order_Product__r.Order.Season_Start_Date__c <> null && wogs.Order_Product__r.Order.Season_End_Date__c <> null)) ||
                    (wogs.Order_Product__r.Order.Season_Start_Date__c == null && wogs.Order_Product__r.Order.Season_End_Date__c == null)){
                    if(wogs.Order_Account_Inactive__c == 'True'){listMultiSelect.add('Account Inactive |'); }    
                    if(wogs.Order_Account_On_Hold__c == 'True'){listMultiSelect.add('Account On Hold |'); }  
                    if(wogs.Order_Product_Active__c == 'False'){listMultiSelect.add('Order Product not Active |'); }
                    if(wogs.Order_Status_Stamp__c == 'Draft'){listMultiSelect.add('Order is not active |'); }
                    if(wogs.Order_Product_IsActive__c == 'false'){listMultiSelect.add('Either Price Book Entry or Product or Order Product is inactive |'); }
                    if(wogs.Order_Product__r.Valid_for_Install_Remove_Replace__c == false && (wogs.Order_Product__r.Installation_Status__c == 'Install' || wogs.Order_Product__r.Installation_Status__c == 'Remove' || wogs.Order_Product__r.Installation_Status__c == 'Replace')
                        && wogs.Order_Product__r.Last_Automation_Created_Date__c == null){listMultiSelect.add('Pending Install/Remove/Replace|'); }
                    if(!freqList.contains(wogs.Order_Product__r.Frequency__c)){listMultiSelect.add('Order Product’s frequency Not in Allowable frequency |'); }
                    if(wogs.Order_Inventory_Allocated__c == 'False' && wogs.Order_Product_Inventory_Allocated__c == 'false'){listMultiSelect.add('Order Product and Order Inventory not allocated |'); }
                    
                    wogs.Reasons_for_failures__c = String.join(listMultiSelect,';');
                    wogs.Status__c = 'WORK ORDER NOT GENERATED';
                    wogs.Last_InFlight_WO_Date_stamp__c = String.valueOf(wogs.Order_Product__r.Last_InFlight_WO_Date__c);
                    wogs.Last_Automation_Created_Date_stamp__c = String.valueOf(wogs.Order_Product__r.Last_Automation_Created_Date__c);
                    updateWogs.add(wogs);
                    system.debug('a5a5a5a5a5a'  + updateWogs);
                }else{
                    deleteWogs.add(wogs);
                    system.debug('a6a6a6a6a6a'  + deleteWogs);
                }
                
                                                        
        }
        Database.SaveResult[] WogsStagingErrorFinalUpdate = Database.update(updateWogs,false);
        system.debug('sysysysysysy' + WogsStagingErrorFinalUpdate);
        //Database.update(updateWogs,false);
        //Database.delete(deleteWogs,false);
        Database.DeleteResult[] WogsStagingErrorFinalDelete = Database.delete(deleteWogs,false);
        system.debug('sxsxsxsxsxsx' + WogsStagingErrorFinalDelete);
    }
     global void finish(Database.BatchableContext bc){}
}