force-app/main/default/objects/Assign_Resource_History__c/Assign_Resource_History__c.object-meta.xml
<CustomObject>
    <label>Assigned Resource History</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assigned Resource History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Resource History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assign_Resource_History__c/fields/Service_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Id__c</fullName>
    <label>Service Appointment Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Are_Service_Crews_Active__c.field-meta.xml
<CustomField>
    <fullName>Are_Service_Crews_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Are Service Crews Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/CitronDoNotReply__c.field-meta.xml
<CustomField>
    <fullName>CitronDoNotReply__c</fullName>
    <label>CitronDoNotReply</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Operating_Hours_Type_Employee__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type_Employee__c</fullName>
    <label>Operating Hours Type - Employee</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Pest_LOB__c.field-meta.xml
<CustomField>
    <fullName>Pest_LOB__c</fullName>
    <label>Pest LOB</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Service_Appointment_Completed_Status__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Completed_Status__c</fullName>
    <label>Service Appointment Completed Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Working_Hour_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Working_Hour_End_Time__c</fullName>
    <inlineHelpText>This field has to be in the formal &quot;hh:mm&quot;</inlineHelpText>
    <label>Working Hour End Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OperatingHours/fields/Operating_Hours_Type__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type__c</fullName>
    <label>Operating Hours Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Operating Hours</fullName>
            </value>
            <value>
                <fullName>Employee Operating Hours</fullName>
            </value>
            <value>
                <fullName>Territory Operating Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Cannot_Complete_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cannot_Complete_Reason__c</fullName>
    <label>Cannot Complete Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broken Unit</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Construction / Renovation</fullName>
            </value>
            <value>
                <fullName>Misc. / Other</fullName>
            </value>
            <value>
                <fullName>Missing Unit</fullName>
            </value>
            <value>
                <fullName>No Access</fullName>
            </value>
            <value>
                <fullName>No Bar Code</fullName>
            </value>
            <value>
                <fullName>Not ready</fullName>
            </value>
            <value>
                <fullName>Refused Service</fullName>
            </value>
            <value>
                <fullName>Scanner Malfunction</fullName>
            </value>
            <value>
                <fullName>Stall Locked</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Could not find unit</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Locked from Inside</fullName>
            </value>
            <value>
                <fullName>Pet in Unit</fullName>
            </value>
            <value>
                <fullName>COVID 19 Related</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAssignResourceTriggerHandler.cls
@isTest
public class TestAssignResourceTriggerHandler {
    @isTest
    static void testAssignResourceHistory(){
        
        Field_Service_Settings__c dataSets = new Field_Service_Settings__c(Service_Appointment_Completed_Status__c = 'Completed', Operating_Hours_Type_Employee__c = 'Employee Operating Hours', Are_Service_Crews_Active__c = true, CitronDoNotReply__c = 'donotreply@citronhygiene.com', Pest_LOB__c = 'Pest Control');
        dataSets.Working_Hour_End_Time__c = String.valueOf(DateTime.now()).split(' ')[1].left(5);
        insert dataSets;
        
        Contact c = new Contact(LastName = 'TestNoReply', Email = 'donotreply@citronhygiene.com');
        insert c;
        
        OperatingHours empHours = new OperatingHours(Operating_Hours_Type__c = 'Employee Operating Hours', Name = 'Test Hours');
        insert empHours;
        
        OperatingHours terrHours = new OperatingHours(Operating_Hours_Type__c = 'Territory Operating Hours', Name = 'Test Hours 2', TimeZone = 'America/New_York');
        insert terrHours;
        
        ServiceTerritory st = new ServiceTerritory(OperatingHoursId = terrHours.Id, Name = 'Test Territory', IsActive = true);
        insert st;
        
        WorkOrder wo2 = new WorkOrder(Completed_Date__c = System.today().addDays(1),Status='New',Cannot_Complete_Reason__c='Closed');
        insert wo2;
        
        ServiceResource resource = new ServiceResource(RelatedRecordId = UserInfo.getUserId(), IsActive = true, Name = UserInfo.getName());
        insert resource;
        
        ServiceCrew crew = new ServiceCrew(Name = 'Test Crew', CrewSize = 1);
        insert crew;
        
        ServiceCrewMember crewMember = new ServiceCrewMember(ServiceCrewId = crew.Id, ServiceResourceId = resource.Id, StartDate = System.today());
        insert crewMember;
        
        ServiceTerritoryMember member = new ServiceTerritoryMember(ServiceResourceId = resource.Id, EffectiveStartDate = System.today(), ServiceTerritoryId = st.Id);
        insert member;
        
        ServiceAppointment appt = new ServiceAppointment(EarliestStartTime = System.now(), DueDate = System.now(), SchedStartTime = System.now(), SchedEndTime = System.now(), Status = 'New', ServiceTerritoryId = st.Id);
        appt.ParentRecordId = wo2.Id; 
        insert appt;
        
        AssignedResource ARS = new AssignedResource(ServiceAppointmentId = appt.Id, ServiceResourceId = resource.Id, ServiceCrewId = crew.Id);
        insert ARS;
        
		User newUser = new User(
            Alias = 'testA', 
            Email = 'testUser@UserTechnicianForTest.com', 
            EmailEncodingKey = 'ISO-8859-1', 
            FirstName = 'TestFirstName',
            LastName = 'TestLastName', 
            LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_CA', 
            ProfileId = UserInfo.getProfileId(),
            TimeZoneSidKey = 'America/New_York', 
            UserName = 'testUser456@UserTechnicianForTest.com', 
            Employee_Number__c = 'ABCD123TEST'
        );
        insert newUser;
        
        ServiceResource res1 = new ServiceResource(RelatedRecordId=newUser.Id,IsActive = true,Name=UserInfo.getName());
        insert res1;
        
        ServiceCrew crew1 = new ServiceCrew(Name = 'Test Crew', CrewSize = 1);
        insert crew1;
        
        ServiceCrewMember crewMember1 = new ServiceCrewMember(ServiceCrewId = crew1.Id, ServiceResourceId = res1.Id, StartDate = System.today());
        insert crewMember1;
        
        ServiceTerritoryMember member1 = new ServiceTerritoryMember(ServiceResourceId = res1.Id, EffectiveStartDate = System.today(), ServiceTerritoryId = st.Id);
        insert member1;
		
        Test.startTest();
        ARS.ServiceResourceId = res1.Id;
        ARS.ServiceCrewId = crew1.Id;
        update ARS;
        List<Assign_Resource_History__c> listARH = [select id from Assign_Resource_History__c where Service_Appointment_Id__c =: appt.Id];
        system.assertEquals(listARH.size(),3);
        
        delete ARS;
        listARH = [select id from Assign_Resource_History__c where Service_Appointment_Id__c =: appt.Id];
        system.assertEquals(listARH.size(),4);
        Test.stopTest();
        
    }
}