force-app/main/default/objects/Standing_Order_Line_Item__c/Standing_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Standing Order Line Item</label>
    <nameField>
        <label>Standing Order Line Item No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standing Order Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Standing_Order_Line_Item__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If the record is in Accpac, it is considered Active.</description>
    <inlineHelpText>If the record is in Accpac, it is considered Active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/StandingOrderLineItem.cls
public class StandingOrderLineItem{
   
    public static void setActive() {
       
        for (Standing_Order_Line_Item__c[] solis:[SELECT Active__c from Standing_Order_Line_Item__c WHERE Upsert_Date__c > LAST_WEEK AND Active__c = FALSE LIMIT 10000])
        {
            for (Standing_Order_Line_Item__c s:solis){
               s.Active__c = TRUE;
            }
            Update(solis);
        }
        
    }
    
    public static void setInActive() {
       
        for (Standing_Order_Line_Item__c[] solis:[SELECT Active__c from Standing_Order_Line_Item__c WHERE (Upsert_Date__c <= LAST_WEEK or Upsert_Date__c = null) AND Active__c = TRUE LIMIT 10000])
        {
            for (Standing_Order_Line_Item__c s:solis){
               s.Active__c = FALSE;
            }
            Update(solis);
        }
        
    }

}