force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/Frequency__c/fields/Occurrences_In_Year__c.field-meta.xml
<CustomField>
    <fullName>Occurrences_In_Year__c</fullName>
    <label>Occurrences In Year</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <formula>PricebookEntry.Product2.Item_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_Service_Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Plan_Name__c</fullName>
    <description>Name of the last service plan to which this product was associated</description>
    <formula>Last_Service_Plan__r.Name</formula>
    <inlineHelpText>Name of the last service plan to which this product was associated</inlineHelpText>
    <label>Last Service Plan Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Plan__c.field-meta.xml
<CustomField>
    <fullName>Service_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Service Plan record that services this Order Product.</description>
    <inlineHelpText>Lookup to Service Plan record that services this Order Product.</inlineHelpText>
    <label>Service Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Plan__c.Frequency__c</field>
            <operation>equals</operation>
            <valueField>$Source.Frequency__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Plan__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Survey_Locations__c.field-meta.xml
<CustomField>
    <fullName>Survey_Locations__c</fullName>
    <description>Add the name of the location and the building name to this field ..</description>
    <formula>IF(NOT( ISBLANK( Survey_Location__c ) ), 
Survey_Location__r.Name  +  &apos; : &apos; + Survey_Location__r.Building__c + &apos;:&apos; +  Survey_Location__r.Floor__c  + &apos;:&apos; + TEXT(Survey_Location__r.Location_Type__c) + IF(NOT( ISBLANK( TEXT(Survey_Location__r.Location_SubType__c))), &apos;:&apos; +  TEXT(Survey_Location__r.Location_SubType__c), &apos;&apos;) , 
&apos;&apos;)</formula>
    <label>Survey Locations</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Plan__c/Service_Plan__c.object-meta.xml
<CustomObject>
    <description>Object to summarize recurring Order Products serviced by a Technician.</description>
    <label>Service Plan</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Service Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Plan__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Service frequency for recurring Order Products.</description>
    <inlineHelpText>Service frequency for recurring Order Products.</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Service_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>14 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Twice Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>28 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>56 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Semi-Annually</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <customValue>
        <fullName>112 Days</fullName>
    </customValue>
    <customValue>
        <fullName>2X Per Year</fullName>
    </customValue>
    <customValue>
        <fullName>2X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>3X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>5X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>6X Per Week</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>42 Days</fullName>
    </customValue>
    <customValue>
        <fullName>84 Days</fullName>
    </customValue>
    <customValue>
        <fullName>120 Days</fullName>
    </customValue>
    <customValue>
        <fullName>168 Days</fullName>
    </customValue>
    <customValue>
        <fullName>182 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Weekly</fullName>
        <isActive>false</isActive>
        <label>Fixed Weekly</label>
    </customValue>
    <customValue>
        <fullName>364 Days</fullName>
        <isActive>false</isActive>
        <label>364 Days</label>
    </customValue>
    <description>Service frequency for recurring Order Products.</description>
    <masterLabel>Service Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServicePlanAssetWrapper.cls
/**
 * @FileName: ServicePlanAssetWrapper
 * @Description: Wrapper class for service plan asset details
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       11/28/2019      Created
 *-----------------------------------------------------------  
 */
public inherited sharing class ServicePlanAssetWrapper implements Comparable {
    public String assetId;
    public OrderItem item;
    public List<ItemWrapper> items;
    public String schedule;
    public String suggestedServicePlanName;
    public Boolean selected;
    public Double selectedQuantity;

    public ServicePlanAssetWrapper(OrderItem item) {
        this.item = item.clone(false);
        this.items = new List<ItemWrapper>{new ItemWrapper(item)};
        this.selected = false;
        this.selectedQuantity = 0;
    }

    public ServicePlanAssetWrapper(OrderItem item, String schedule) {
        this.item = item.clone(false);
        this.schedule = schedule;
    }

    public Integer compareTo(Object compareTo) {
        ServicePlanAssetWrapper compareItem = (ServicePlanAssetWrapper) compareTo;

        if(item.Product2.Item_Type__c > compareItem.item.Product2.Item_Type__c) return 1;
        if(item.Product2.Item_Type__c < compareItem.item.Product2.Item_Type__c) return -1;

        Frequency__c itemFrequency = QueryUtils.yearlyFrequencies.get(item.Frequency__c);
        Frequency__c compareFrequency = QueryUtils.yearlyFrequencies.get(compareItem.item.Frequency__c);

        if(itemFrequency != null && compareFrequency != null) {
            if(itemFrequency.Occurrences_In_Year__c > compareFrequency.Occurrences_In_Year__c) return -1;
            if(itemFrequency.Occurrences_In_Year__c < compareFrequency.Occurrences_In_Year__c) return 1;
        }

        if(item.Product2.ExternalID__c > compareItem.item.Product2.ExternalID__c) return 1;
        if(item.Product2.ExternalID__c < compareItem.item.Product2.ExternalID__c) return -1;

        return 0;
    }

    // only wrap required fields to accommodate lightning message character limits
    public class ItemWrapper {
        public Id id;
        public Id servicePlanId;
        public String surveyLocations;
        public Double quantity;
        public Boolean selected;
        public String LastSPName;
        

        public ItemWrapper(OrderItem item) {
            this.id = item.Id;
            this.servicePlanId = item.Service_Plan__c;
            this.surveyLocations = item.Survey_Locations__c;
            this.quantity = item.Quantity;
            this.LastSPName = item.Last_Service_Plan_Name__c;
            selected = String.isNotBlank(item.Service_Plan__c);
        }
    }
}