force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Installation_Price__c.field-meta.xml
<CustomField>
    <fullName>Installation_Price__c</fullName>
    <inlineHelpText>Indicates if an Installation Price is charged for Installing an item. Price entered is per unit. Filling in this field would result in a one time Installation Work Order.</inlineHelpText>
    <label>Installation Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <inlineHelpText>Indicate if the Customer is charged a Price for the Purchase of this item. Price Entered is per unit. If only Purchase Price is filled in, this would be considered as a One Time Delivery.</inlineHelpText>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Related_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AddOrderProduct.cls
public class AddOrderProduct {

    public class ColumnRecord {
        @AuraEnabled public String label { get; set; }
        @AuraEnabled public String name { get; set; }

        public ColumnRecord(String label, String name) {
            this.label = label;
            this.name = name;
        }
    }

    @AuraEnabled
    public static List<ColumnRecord> getColumns(List<String> columnAPINames) {
        List<ColumnRecord> columns = new List<ColumnRecord>();

        for (String s : columnAPINames) {
            List<String> ss = s.split('\\.');

            columns.add(new ColumnRecord(
                    Schema.getGlobalDescribe().get(ss[0]).getDescribe().fields.getMap().get(ss[1]).getDescribe().getLabel(),
                    ss[1]));
        }

        return columns;
    }

    @AuraEnabled
    public static List<String> addOrderItem(OrderItem record) {
        List<String> result = new List<String>{'', '', ''};
        PricebookEntry pEntry;

        try {
            if (record != null) {
                Order o = [
                        SELECT Id, Pricebook2Id
                        FROM Order
                        WHERE Id = :record.OrderId
                ];

                pEntry = [
                        SELECT Id, UnitPrice, Name
                        FROM PricebookEntry
                        WHERE Pricebook2Id = :o.Pricebook2Id
                        AND Product2Id = :record.Product2Id
                ];

                if (pEntry != null) {
                    OrderItem newOrderItem = new OrderItem(
                            OrderId = record.OrderId,
                            PricebookEntryId = pEntry.Id,
                            Quantity = 1,
                            UnitPrice = 0.0,
                            ServiceDate = System.today(),
                            Service_Price_Per_Unit__c = record.Service_Price_Per_Unit__c,
                            Installation_Price__c = record.Installation_Price__c,
                            Purchase_Price__c = record.Purchase_Price__c,
                            Frequency__c = record.Frequency__c,
                            Related_Product__c = record.Related_Product__c,
                            Active__c = true

                    );

                    insert newOrderItem;

                    result[0] = Label.Site_Survey_Save_Success_Title;
                    result[1] = 'success';
                    result[2] = Label.Record_Creation_Success;
                }
                else {
                    result[0] = Label.Record_Creation_Caution;
                    result[1] = 'caution';
                    result[2] = Label.Record_Creation_Failure;
                }
            }
        } catch (DmlException de) {
            System.debug('DML ' + de.getMessage() + ' ' + de.getLineNumber());
            result[0] = Label.Site_Survey_Save_Error_Title;
            result[1] = 'error';
            result[2] = Label.Record_Creation_Exception;
        } catch (Exception e) {
            System.debug('Exception ' + e.getMessage() + ' ' + e.getLineNumber());
            result[0] = Label.Site_Survey_Save_Error_Title;
            result[1] = 'error';
            result[2] = Label.Record_Creation_Exception;
        }

        return result;
    }
}