force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Infestation_Level__c.field-meta.xml
<CustomField>
    <fullName>Infestation_Level__c</fullName>
    <label>Infestation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Actisol</fullName>
            </value>
            <value>
                <fullName>Actisol / Heavy</fullName>
            </value>
            <value>
                <fullName>Any</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Block Inspection</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Chemical / BTOXF</fullName>
            </value>
            <value>
                <fullName>Chemical / Follow Up</fullName>
            </value>
            <value>
                <fullName>Chute</fullName>
            </value>
            <value>
                <fullName>Clean Out</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Common Areas</fullName>
            </value>
            <value>
                <fullName>Conventional</fullName>
            </value>
            <value>
                <fullName>Drill</fullName>
            </value>
            <value>
                <fullName>Exclusion</fullName>
            </value>
            <value>
                <fullName>Exterior</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Gel / Dust - Block</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Heat</fullName>
            </value>
            <value>
                <fullName>Heavy</fullName>
            </value>
            <value>
                <fullName>High</fullName>
                <isActive>false</isActive>
                <label>High</label>
            </value>
            <value>
                <fullName>IGR</fullName>
            </value>
            <value>
                <fullName>Inclusive Gel/Dust – No Charge</fullName>
            </value>
            <value>
                <fullName>Inclusive Spray – No Charge</fullName>
            </value>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Interior</fullName>
            </value>
            <value>
                <fullName>K9</fullName>
            </value>
            <value>
                <fullName>Light</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Number_of_Rooms__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Rooms__c</fullName>
    <label>Number of Rooms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Number_of_Rooms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Treatment_Type__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Type__c</fullName>
    <label>Treatment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Any</fullName>
            </value>
            <value>
                <fullName>Bats</fullName>
            </value>
            <value>
                <fullName>Beavers</fullName>
            </value>
            <value>
                <fullName>Bed Bug</fullName>
            </value>
            <value>
                <fullName>Beetle</fullName>
            </value>
            <value>
                <fullName>Birds</fullName>
            </value>
            <value>
                <fullName>Black Field Ant</fullName>
            </value>
            <value>
                <fullName>Carpenter Ant</fullName>
            </value>
            <value>
                <fullName>Carpet Beetle</fullName>
            </value>
            <value>
                <fullName>Centipede/Millipede</fullName>
            </value>
            <value>
                <fullName>Clothes Moth</fullName>
            </value>
            <value>
                <fullName>Clover Mite</fullName>
            </value>
            <value>
                <fullName>Cluster Fly</fullName>
            </value>
            <value>
                <fullName>Cockroach</fullName>
            </value>
            <value>
                <fullName>Coyotes</fullName>
            </value>
            <value>
                <fullName>Drain Fly</fullName>
            </value>
            <value>
                <fullName>Earwig</fullName>
            </value>
            <value>
                <fullName>Fleas</fullName>
            </value>
            <value>
                <fullName>Fruit Fly</fullName>
            </value>
            <value>
                <fullName>Grasshopper/Cricket</fullName>
            </value>
            <value>
                <fullName>Groundhogs</fullName>
            </value>
            <value>
                <fullName>House Fly</fullName>
            </value>
            <value>
                <fullName>Indian Meal Moths</fullName>
            </value>
            <value>
                <fullName>Insects</fullName>
            </value>
            <value>
                <fullName>Mice</fullName>
            </value>
            <value>
                <fullName>Mite</fullName>
            </value>
            <value>
                <fullName>Moles</fullName>
            </value>
            <value>
                <fullName>Mosquito</fullName>
            </value>
            <value>
                <fullName>Moth</fullName>
            </value>
            <value>
                <fullName>Outside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Number_of_Rooms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Blank</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>Apartment</fullName>
    </customValue>
    <customValue>
        <fullName>Garden Home</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>Town Home</fullName>
    </customValue>
    <customValue>
        <fullName>Villa</fullName>
    </customValue>
    <masterLabel>Number of Rooms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestProductTriggers.cls
@isTest
public class TestProductTriggers {
    @isTest
    static void testCreateAndUpdateProduct() {
        Product2 product = new Product2();
        product.Allowable_Frequencies__c = 'One-Time';
        product.Family = 'Pest Control';
        product.Item_Type__c = 'Service';
        product.Treatment_Type__c = 'Bed Bug';
        product.Number_of_Rooms__c = '3';
        product.IsActive = true;
        product.Infestation_Level__c = 'Medium';
        product.Name = 'Test Product';
        
        Test.startTest();
        
        insert product;
        
        product.Number_of_Rooms__c = '4';
        
        update product;
        
        Test.stopTest();
    }
    
    @isTest
    static void testCreateNonPEstProduct() {
        Product2 product = new Product2();
        product.Allowable_Frequencies__c = 'One-Time';
        product.Family = 'Hygiene';
        product.Item_Type__c = 'Service';
        product.Treatment_Type__c = 'Bed Bug';
        product.Number_of_Rooms__c = '3';
        product.IsActive = true;
        product.Infestation_Level__c = 'Medium';
        product.Name = 'Test Product';
        
        Test.startTest();
        
        insert product;
        
        product.Number_of_Rooms__c = '4';
        
        update product;
        
        Test.stopTest();
    }
}