force-app/main/default/objects/OrderItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>This field is System Generated during the nightly Work Order Generation batch job. Changing this would have implications on Work Order Generation Logic</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <label>Last InFlight WO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Order Item cannot have the custom Order field set as it&apos;s Inactive.</errorMessage>
        <filterItems>
            <field>$Source.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Active Order Products without PO Number</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/Work_Order_Generation_Status__c.object-meta.xml
<CustomObject>
    <label>Work Order Generation Status</label>
    <nameField>
        <label>Work Order Generation Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Generation Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <formula>Order_Product__r.Last_Automation_Created_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Last_Automation_Created_Date_stamp__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date_stamp__c</fullName>
    <label>Last Automation Created Date stamp</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <formula>Order_Product__r.Last_InFlight_WO_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last InFlight WO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Last_InFlight_WO_Date_stamp__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date_stamp__c</fullName>
    <label>Last InFlight WO Date stamp</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Order Generation Status</relationshipLabel>
    <relationshipName>Work_Order_Generation_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Work Order Generation Status</relationshipLabel>
    <relationshipName>Work_Order_Generation_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/WOLI_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>WOLI_Start_Date__c</fullName>
    <label>Work Order Line Item Start Date Stamp</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Work Order Generation Status</relationshipLabel>
    <relationshipName>Work_Order_Generation_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Work_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Id__c</fullName>
    <label>Work Order Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Work Order Generation Status</relationshipLabel>
    <relationshipName>Work_Order_Generation_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Work_Order_Line_Item_End_Date_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item_End_Date_Stamp__c</fullName>
    <label>Work Order Line Item End Date Stamp</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_Generation_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Generation_Status__c</fullName>
    <label>Work Order Generation Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>System field that is filled in by the nightly batch job generating Work Orders, modifying this field would affect the Service Schedule</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <formula>TEXT(Order_Product__r.Last_InFlight_WO_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last InFlight WO Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateWorkOrderStatusSecondBatch.cls
global class UpdateWorkOrderStatusSecondBatch implements Database.Batchable<SObject>, Database.Stateful{
    
    List<Id> listUnmatchedWOLIs = new List<ID>() ;
    global UpdateWorkOrderStatusSecondBatch(List<Id> listUnmatchedWOLIIds){
        this.listUnmatchedWOLIs = listUnmatchedWOLIIds;
    }
    
    global Database.QueryLocator Start(Database.BatchableContext bc){
        List<Id> listUnmatchedWOLIs2 = new List<ID>() ;
        listUnmatchedWOLIs2.addAll(listUnmatchedWOLIs);
        return Database.getQueryLocator([Select Id,WorkOrderId,StartDate,Order_Product__c,WorkOrder.StartDate,WorkOrder.WorkOrderNumber,WorkOrder.Work_Order_Generation_Status__c from WorkOrderLineItem where Id in: listUnmatchedWOLIs2 ]);
    }
           
    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        Set<Id> setWOLIds = new Set<Id>();
        Map<Id,Id> mapWOToOP = new Map<Id,Id>();
        Map<Id,List<WorkOrderLineItem>> mapOrderProductToWoliStartDate = new Map<Id,List<WorkOrderLineItem>>();
        
        for(SObject woli: scope){
            setWOLIds.add(woli.Id);
        }
        for(WorkOrderLineItem woli : [Select Id,OrderId,WorkOrderId,StartDate,EndDate,Order_Product__c,WorkOrder.StartDate,WorkOrder.WorkOrderNumber from WorkOrderLineItem where Id in: setWOLIds ]){
            if(mapOrderProductToWoliStartDate.containsKey(woli.Order_Product__c)){ 
                mapOrderProductToWoliStartDate.get(woli.Order_Product__c).add(new WorkOrderLineItem(Id = woli.Id,StartDate = woli.StartDate));
            }else{    
                mapOrderProductToWoliStartDate.put(woli.Order_Product__c,new List<WorkOrderLineItem>{new WorkOrderLineItem(Id = woli.Id,StartDate = woli.StartDate)});
            }
            mapWOToOP.put(woli.Id,woli.Order_Product__c);
        }

        Map<Id,List<Work_Order_Generation_Status__c>> mapOrderProductToWogslRecord = new map<Id,List<Work_Order_Generation_Status__c>>();
        
         for(Work_Order_Generation_Status__c wogsl : [Select Id,Work_Order_Line_Item__c,WOLI_Start_Date__c,Work_Order__c,Order_Product__c,Work_Order_Line_Item_End_Date_Stamp__c,Expected_WO_Start_Date__c,Expected_WO_End_Date__c,Status__c,Work_Order_Id__c,Work_Order_Start_Date__c from Work_Order_Generation_Status__c 
                                                        where Order_Product__c in: mapOrderProductToWoliStartDate.keyset() AND Status__c = ''] ){ 
            if(mapOrderProductToWogslRecord.containsKey(wogsl.Order_Product__c)){ 
                mapOrderProductToWogslRecord.get(wogsl.Order_Product__c).add(wogsl);   
            }else{
                mapOrderProductToWogslRecord.put(wogsl.Order_Product__c,new List<Work_Order_Generation_Status__c>{wogsl});
            }
        }
        Map<Id,List<String>> mapWOGSLStatus = new Map<Id,List<String>>();
        Set<Id> woliIds = new Set<Id>();
        for(OrderItem oItem : [Select Id from OrderItem where id in: mapOrderProductToWoliStartDate.keyset()]){
            
            List<Work_Order_Generation_Status__c> listWOGSL = new List<Work_Order_Generation_Status__c>();
            if( mapOrderProductToWogslRecord.get(oItem.Id) != null){
                listWOGSL = mapOrderProductToWogslRecord.get(oItem.Id);
            }

            for(WorkOrderLineItem woli : mapOrderProductToWoliStartDate.get(oItem.Id)){
                    if(listWOGSL.size() >0){
                        String WOLIDate = String.valueOf(woli.StartDate);
                        String WOLIEndDate = String.valueOf(woli.EndDate);
                        
                         if(listWOGSL[0].Status__c == '' || listWOGSL[0].Status__c == null){
                                    mapWOGSLStatus.put(listWOGSL[0].Id,new List<String>{'APPROXIMATE MATCH INSIDE GENERATION WINDOW (GREATER THAN +/- 3)',woli.Id,WOLIDate,woli.WorkOrderId,WOLIEndDate,''}); 
                                }
                                else if(listWOGSL.size() > 1 && (listWOGSL[1].Status__c == '' || listWOGSL[1].Status__c == null)){
                                    mapWOGSLStatus.put(listWOGSL[1].Id,new List<String>{'APPROXIMATE MATCH INSIDE GENERATION WINDOW (GREATER THAN +/- 3)',woli.Id,WOLIDate,woli.WorkOrderId,WOLIEndDate,''}); 
                                }
                                else if(listWOGSL.size() > 2 && (listWOGSL[2].Status__c == '' || listWOGSL[2].Status__c == null)){
                                    mapWOGSLStatus.put(listWOGSL[2].Id,new List<String>{'APPROXIMATE MATCH INSIDE GENERATION WINDOW (GREATER THAN +/- 3)',woli.Id,WOLIDate,woli.WorkOrderId,WOLIEndDate,''}); 
                                }
                    }else{
                        woliIds.add(woli.id);
                    }
            }
        }
        List<Work_Order_Generation_Status__c> listUpdateWOGSL = new List<Work_Order_Generation_Status__c>();
        for(Work_Order_Generation_Status__c wogsl : [Select Id,Work_Order__c,Work_Order_Line_Item_End_Date_Stamp__c,Work_Order_Line_Item__c,WOLI_Start_Date__c,Status__c,Work_Order_Id__c,Work_Order_Start_Date__c from Work_Order_Generation_Status__c where id in : mapWOGSLStatus.keySet()]){
                
                wogsl.Status__c = mapWOGSLStatus.get(wogsl.Id)[0];
                wogsl.Work_Order_Line_Item__c = mapWOGSLStatus.get(wogsl.Id)[1];
                wogsl.WOLI_Start_Date__c = mapWOGSLStatus.get(wogsl.Id)[2];
                wogsl.Work_Order__c = mapWOGSLStatus.get(wogsl.Id)[3];
                wogsl.Work_Order_Line_Item_End_Date_Stamp__c = mapWOGSLStatus.get(wogsl.Id)[4];
                listUpdateWOGSL.add(wogsl);

        }    
        database.update(listUpdateWOGSL,false);
                   
        List<Work_Order_Generation_Status__c> listWOGSLCreated = new List<Work_Order_Generation_Status__c>();
        for(WorkOrderLineItem woli: [Select Id,WorkOrderId,StartDate,EndDate,Order_Product__c,OrderId,Order_Product__r.Last_InFlight_WO_Date__c,Order_Product__r.Last_Automation_Created_Date__c from WorkOrderLineItem where Id in: woliIds ]){
            
            String WOLIDate = String.valueOf(woli.StartDate);
            String WOLIEndDate = String.valueOf(woli.EndDate);
            
            listWOGSLCreated.add(new Work_Order_Generation_Status__c( 
                                                                        Status__c = 'EXTRA WO INSIDE GENERATION WINDOW',
                                                                        Work_Order_Line_Item__c = woli.Id,
                                                                        Order_Product__c = mapWOToOP.get(woli.id),
                                                                        WOLI_Start_Date__c = WOLIDate,
                                                                        Work_Order__c = woli.WorkOrderId,
                                                                        Order__c = woli.OrderId,
                                                                        Work_Order_Line_Item_End_Date_Stamp__c = WOLIEndDate,
                                                                        Last_InFlight_WO_Date_stamp__c = String.valueOf(woli.Order_Product__r.Last_InFlight_WO_Date__c),
                                                                        Last_Automation_Created_Date_stamp__c = String.valueOf(woli.Order_Product__r.Last_Automation_Created_Date__c)
                                                                        //Order__c = OrderId
                                                                    ));
        }       
        if(listWOGSLCreated.size() > 0){
            Database.insert(listWOGSLCreated,false);
        }
        
    }
    global void finish(Database.BatchableContext bc){
     UpdateWorkOrderGenerationBatchFinal uwogbf = new UpdateWorkOrderGenerationBatchFinal();
     database.executebatch(uwogbf,200);
    }
}