force-app/main/default/objects/Account/fields/A_P_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>A_P_Contact_Name__c</fullName>
    <inlineHelpText>Please enter First and Last Name</inlineHelpText>
    <label>A/P Contact Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Check__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check__c</fullName>
    <label>Credit Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Checked</fullName>
                <default>true</default>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Chemical_LOB__c.field-meta.xml
<CustomField>
    <fullName>Chemical_LOB__c</fullName>
    <label>Chemical LOB</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/DeInstall_Work_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>DeInstall_Work_Order_Type__c</fullName>
    <label>DeInstall Work Order Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Emergency_Service_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Service_End_Time__c</fullName>
    <label>Emergency Service End Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Emergency_Service_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Service_Start_Time__c</fullName>
    <label>Emergency Service Start Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Hygiene_LOB__c.field-meta.xml
<CustomField>
    <fullName>Hygiene_LOB__c</fullName>
    <label>Hygiene LOB</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Item_Type_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Item_Type_of_Services__c</fullName>
    <label>Item Type of Services</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Life_Safety_LOB__c.field-meta.xml
<CustomField>
    <fullName>Life_Safety_LOB__c</fullName>
    <label>Life Safety LOB</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Operating_Hours_Type_Account__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type_Account__c</fullName>
    <label>Operating Hours Type - Account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Order_Active_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Active_Stage__c</fullName>
    <label>Order Active Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Pest_LOB__c.field-meta.xml
<CustomField>
    <fullName>Pest_LOB__c</fullName>
    <label>Pest LOB</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Regular_Order_Draft_Stage__c.field-meta.xml
<CustomField>
    <fullName>Regular_Order_Draft_Stage__c</fullName>
    <label>Regular Order Draft Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Regular_Order_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Regular_Order_Record_Type_Id__c</fullName>
    <label>Regular Order Record Type Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Scanned_In_Status__c.field-meta.xml
<CustomField>
    <fullName>Scanned_In_Status__c</fullName>
    <label>Scanned In Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Scanned_Out_Status__c.field-meta.xml
<CustomField>
    <fullName>Scanned_Out_Status__c</fullName>
    <label>Scanned Out Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Service_Start__c.field-meta.xml
<CustomField>
    <fullName>Service_Start__c</fullName>
    <inlineHelpText>For completely new Orders (eg: Signed today), how many buffer days are allocated before work can start</inlineHelpText>
    <label>Service Start</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Shopping_Cart_Order_Draft_Stage__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart_Order_Draft_Stage__c</fullName>
    <label>Shopping Cart Order Draft Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Status_Value_for_Install_of_a_Product__c.field-meta.xml
<CustomField>
    <fullName>Status_Value_for_Install_of_a_Product__c</fullName>
    <label>Status Value for Install of a Product</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Status_Value_for_Replace_of_a_Product__c.field-meta.xml
<CustomField>
    <fullName>Status_Value_for_Replace_of_a_Product__c</fullName>
    <label>Status Value for Replace of a Product</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/System_Administrator_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Administrator_Profile_Id__c</fullName>
    <label>System Administrator Profile Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Work_Order_Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Completion_Status__c</fullName>
    <label>Work Order Completion Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Work_Order_Line_Item_Completed_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item_Completed_Status__c</fullName>
    <label>Work Order Line Item Completed Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Work_Orders_In_Advance__c.field-meta.xml
<CustomField>
    <fullName>Work_Orders_In_Advance__c</fullName>
    <inlineHelpText>How many days in advance to schedule to work orders</inlineHelpText>
    <label>Work Orders In Advance</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OperatingHours/fields/Operating_Hours_Type__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type__c</fullName>
    <label>Operating Hours Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Operating Hours</fullName>
            </value>
            <value>
                <fullName>Employee Operating Hours</fullName>
            </value>
            <value>
                <fullName>Territory Operating Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/Province_Time_Zones_Operating_Hours__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A table to map each province to appropriate time zones, for Citron users to only associate Accounts to appropriate time zones.</description>
    <label>Province Time Zones - Operating Hours</label>
</CustomObject>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/fields/Province_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_Territory_Code__c</fullName>
    <label>Province/Territory Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/Survey_Asset_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Asset Location</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>Survey Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Asset Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Survey_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISBLANK(Survey_Location__c ), &quot;Unallocated&quot;, &quot;Allocated&quot;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Site_Survey__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestSurveyLocationsBatchable.cls
@isTest
public class TestSurveyLocationsBatchable {
    
    @TestSetup static void setup() {
        List<Product2> products = new List<Product2>();
        List<Survey_Asset_Location__c> surveyAssetLocations = new List<Survey_Asset_Location__c>();
        
        Id pBook = Test.getStandardPricebookId();
        Id devRecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Regular Order').getRecordTypeId();
        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Invoice Information').getRecordTypeId();
        
        Province_Time_Zones_Operating_Hours__c setting = new Province_Time_Zones_Operating_Hours__c();
        setting.Name = 'ON';
        setting.Province_Territory_Code__c = 'ON';
        setting.TimeZone__c = 'America/New_York';
        insert setting;
        
        Field_Service_Settings__c fssetting = new Field_Service_Settings__c(Service_Start__c = 4);
        fssetting.Status_Value_for_Install_of_a_Product__c = 'Install';
        fssetting.Status_Value_for_Replace_of_a_Product__c = 'Replace';
        fssetting.Operating_Hours_Type_Account__c = 'Account Operating Hours';
        fssetting.Service_Start__c = 3;
        fssetting.Item_Type_of_Services__c='Service';
        fssetting.Hygiene_LOB__c = 'Hygiene';
        fssetting.Chemical_LOB__c = 'Chemical';
        fssetting.Pest_LOB__c = 'Pest Control';
        fssetting.Life_Safety_LOB__c = 'Life Safety';
        fssetting.Work_Order_Completion_Status__c = 'Completed';
        fssetting.Scanned_In_Status__c = 'Installed';
        fssetting.Work_Order_Line_Item_Completed_Status__c = 'Completed';
        fssetting.DeInstall_Work_Order_Type__c = 'DeInstall';
        fssetting.Scanned_Out_Status__c = 'Remove';
        fssetting.Order_Active_Stage__c = 'Activated';
        fssetting.Regular_Order_Draft_Stage__c = 'Draft';
        fssetting.Shopping_Cart_Order_Draft_Stage__c = 'Shopping Cart';
        fssetting.Work_Orders_In_Advance__c = 20;
        fssetting.Item_Type_of_Services__c='Service';
        fssetting.Emergency_Service_Start_Time__c = '4:30';
        fssetting.Emergency_Service_End_Time__c = '4:31';
        fssetting.System_Administrator_Profile_Id__c = UserInfo.getProfileId();
        fssetting.Regular_Order_Record_Type_Id__c = devRecordTypeId;
        insert fssetting;
        
        OperatingHours oh = new OperatingHours(
        	Name='TestHours', 
            Operating_Hours_Type__c='Account Operating Hours', 
            TimeZone='America/New_York'
        );
        insert new List<OperatingHours>{oh};
            
        TimeSlot testSlot = new TimeSlot(
        	DayOfWeek='Monday', 
            StartTime = Time.newInstance(07, 00, 00, 00), 
            EndTime = Time.newInstance(17, 00, 00, 00),
            OperatingHoursId = oh.Id
        );
        insert testSlot;
        
        Account a = new Account(
            Name='TestAccount', 
            AccPac_Account__c='1234-', 
            A_P_Contact_Name__c='TestContactName', 
            Credit_Check__c='Completed', 
            Industry='Institutions', 
            Industry_Code_Accpac__c='000-00 UNKNOWN', 
            Invoice_Preference__c='Email',
            Invoicing_Email_Address__c='Test@test.com', 
            LEED_Customer__c='No', 
            On_Hold__c=FALSE, 
            Inactive__c=FALSE,
            Type='Customer', 
            Phone='123456789',
            OperatingHoursId = oh.Id,
            Billing_Suite_Number__c='1', 
            BillingStreet='Street', 
            BillingCity = 'City', 
            BillingState = 'State', 
            BillingPostalCode = 'PostalCode',
            BillingCountry = 'Country',
            Shipping_Suite_Number__c = '1',
            ShippingStreet = 'Street', 
            ShippingCity = 'City', 
            ShippingState = 'State', 
            ShippingPostalCode = 'PostalCode', 
            ShippingCountry = 'Country'
        );
        insert a;
        
        Site_Survey__c ss = new Site_Survey__c(
            Account__c=a.Id, 
            Survey_Date__c = System.today(),
            Status__c = 'Draft'
        );
        insert ss;
        
        Survey_Location__c location = new Survey_Location__c(
            Site_Survey__c=ss.Id, 
            Building__c = 'Building',
            Floor__c = 'Floor', 
            Location_Type__c='Washroom', 
            Location_SubType__c='Unisex',
            Name='Location'
        );
        insert location;
        
        a.Site_Survey__c = ss.Id;
        update a;
        
        for(Integer i=0; i<5; i++){
            products.add(
                new Product2(
                    Name='TestProduct'+i,
                    Allowable_Frequencies__c='One-Time;Monthly;Weekly', 
                    IsActive=TRUE, 
                    Available_As_Related_Product__c=TRUE, 
                    Family= (i==0) ? 'Hygiene' : 'Pest Control', 
                    Item_Type__c= (i==0) ? 'Consumables' : 'Service',
                    ExternalId__c = 'test'+i
                )       
            );
        }
        
        insert products;
        
        for(Integer i=0; i<3; i++) {
            surveyAssetLocations.add(
                new Survey_Asset_Location__c(
                    Product__c=products.get(i).Id, 
                    Quantity__c=1, 
                    Site_Survey__c=ss.Id, 
                    Survey_Location__c = location.Id
                )
            );
        } 
        insert surveyAssetLocations;
    }
    
    static testMethod void testAllRecords() {
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        
        Test.startTest();
        
        SurveyLocationsBatchable testRun = new SurveyLocationsBatchable();
        Database.executeBatch(testRun);
        
        Test.stopTest();
    }
    
    static testMethod void testOneRecord() {
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        Account a = [SELECT Id, Site_Survey__c FROM Account WHERE Name='TestAccount' LIMIT 1].get(0);
        Survey_Location__c sl = [SELECT Id FROM Survey_Location__c WHERE Site_Survey__c= :a.Site_Survey__c LIMIT 1].get(0);
        
        Test.startTest();
        
        SurveyLocationsBatchable testRun = new SurveyLocationsBatchable(sl.Id);
        Database.executeBatch(testRun);
        
        Test.stopTest();
    }

}