force-app/main/default/objects/Account/fields/A_P_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>A_P_Contact_Name__c</fullName>
    <inlineHelpText>Please enter First and Last Name</inlineHelpText>
    <label>A/P Contact Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Suite_Number__c</fullName>
    <label>Billing Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Check__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check__c</fullName>
    <label>Credit Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Checked</fullName>
                <default>true</default>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Code_Accpac__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code_Accpac__c</fullName>
    <description>Select the appropriate Accpac Industry Code for this customer</description>
    <inlineHelpText>Industry Code is mandatory.</inlineHelpText>
    <label>Industry Code for Accpac</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000-00 UNKNOWN</fullName>
            </value>
            <value>
                <fullName>100-01 PROPERTY MANAGEMENT-Owner Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-02 PROPERTY MANAGEMENT-Owner Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-03 PROPERTY MANAGEMENT-Owner Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-04 PROPERTY MANAGEMENT-Owner Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-05 PROPERTY MANAGEMENT-Owner Managed - Residential</fullName>
            </value>
            <value>
                <fullName>100-21 PROPERTY MANAGEMENT-Third Party Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-22 PROPERTY MANAGEMENT-Third Party Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-23 PROPERTY MANAGEMENT-Third Party Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-24 PROPERTY MANAGEMENT-Third Party Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-25 PROPERTY MANAGEMENT-Third Party Managed - Residential</fullName>
            </value>
            <value>
                <fullName>200-01 HOSPITALITY-Convention Centres</fullName>
            </value>
            <value>
                <fullName>200-02 HOSPITALITY-Fitness Clubs</fullName>
            </value>
            <value>
                <fullName>200-03 HOSPITALITY-Golf&apos;s Club</fullName>
            </value>
            <value>
                <fullName>200-04 HOSPITALITY-Hotels, Motels</fullName>
            </value>
            <value>
                <fullName>200-05 HOSPITALITY-Independent Restaurants</fullName>
            </value>
            <value>
                <fullName>200-06 HOSPITALITY-Multi-chain Restaurants</fullName>
            </value>
            <value>
                <fullName>200-07 HOSPITALITY-Private Athletic Clubs</fullName>
            </value>
            <value>
                <fullName>200-08 HOSPITALITY-Ski Resorts</fullName>
            </value>
            <value>
                <fullName>200-09 HOSPITALITY-Sports Centers</fullName>
            </value>
            <value>
                <fullName>200-10 HOSPITALITY-Entertainment</fullName>
            </value>
            <value>
                <fullName>300-01 MANUFACTURING-Automotive</fullName>
            </value>
            <value>
                <fullName>300-02 MANUFACTURING-Food</fullName>
            </value>
            <value>
                <fullName>300-03 MANUFACTURING-Pharmaceutical</fullName>
            </value>
            <value>
                <fullName>300-04 MANUFACTURING-Textiles</fullName>
            </value>
            <value>
                <fullName>300-05 MANUFACTURING-Others</fullName>
            </value>
            <value>
                <fullName>400-01 GOVERNMENT-Municipal</fullName>
            </value>
            <value>
                <fullName>400-02 GOVERNMENT-Provincial</fullName>
            </value>
            <value>
                <fullName>400-03 GOVERNMENT-Federal</fullName>
            </value>
            <value>
                <fullName>500-01 HEALTH CARE-Hospitals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Preference__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Preference__c</fullName>
    <label>Invoice Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoicing_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email_Address__c</fullName>
    <label>Invoicing Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/LEED_Customer__c.field-meta.xml
<CustomField>
    <fullName>LEED_Customer__c</fullName>
    <inlineHelpText>Indicate whether the Customer is LEED Certified or not</inlineHelpText>
    <label>LEED Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Suite_Number__c</fullName>
    <label>Shipping Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Default_Order_Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_Order_Price_Book_ID__c</fullName>
    <label>Default Order Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Always_Billable__c.field-meta.xml
<CustomField>
    <fullName>Always_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Citron Custom Field</description>
    <label>Always Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_As_Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Available_As_Related_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available As Related Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder/fields/LEED_Customer__c.field-meta.xml
<CustomField>
    <fullName>LEED_Customer__c</fullName>
    <formula>TEXT(Account.LEED_Customer__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LEED Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestProductConsumedObjectTriggers.cls
@isTest
public class TestProductConsumedObjectTriggers {
    
    @TestSetup static void setup() {
        Id pBook = Test.getStandardPricebookId();
        List<Product2> products = new List<Product2>();
        List<PricebookEntry> pEntries = new List<PricebookEntry>();
        TestDataFactory.crtCPQSettings();
        Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Default_Order_Price_Book_ID__c = pBook;
        insert fssetting;
        
        Account a = new Account(
            Name='TestAccount', 
            AccPac_Account__c='1234-', 
            A_P_Contact_Name__c='TestContactName', 
            Credit_Check__c='Completed', 
            Industry='Institutions', 
            Industry_Code_Accpac__c='000-00 UNKNOWN', 
            Invoice_Preference__c='Email',
            Invoicing_Email_Address__c='Test@test.com', 
            LEED_Customer__c='No', 
            On_Hold__c=FALSE, 
            Type='Customer', 
            Phone='123456789',
            Billing_Suite_Number__c='1', 
            BillingStreet='Street', 
            BillingCity = 'City', 
            BillingState = 'State', 
            BillingPostalCode = 'PostalCode',
            BillingCountry = 'Country',
            Shipping_Suite_Number__c = '1',
            ShippingStreet = 'Street', 
            ShippingCity = 'City', 
            ShippingState = 'State', 
            ShippingPostalCode = 'PostalCode', 
            ShippingCountry = 'Country'
        );
        insert a;
        
        WorkOrder testWorkOrder = new WorkOrder(
        	AccountId=a.Id,
            Status='New',
            StartDate=System.today(), 
            Pricebook2Id=pBook
        );
        insert testWorkOrder;
        
        for(Integer i=0; i<2; i++){
            products.add(
                new Product2(
                    Name='TestProduct'+i,
                    Allowable_Frequencies__c='One-Time;Monthly;Weekly', 
                    IsActive=TRUE, 
                    Item_Type__c = 'Consumables',
                    Available_As_Related_Product__c=TRUE, 
                    Always_Billable__c=TRUE
                )       
            );
        }
        
        insert products;
        
        for(Integer i=0; i<2; i++) {
            pEntries.add(
                new PricebookEntry(
                    Pricebook2Id=pBook, 
                    Product2Id=products.get(i).Id, 
                    UnitPrice=1.0, 
                    IsActive=TRUE
                )
            );
        }
        insert pEntries;         
    }
    
    static testMethod void insertProductConsumed() {
        
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        
        PricebookEntry pEntry = [SELECT Id, Pricebook2Id FROM PricebookEntry WHERE Pricebook2Id=:fssetting.Default_Order_Price_Book_ID__c LIMIT 1].get(0);
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount'];
        WorkOrder testWorkOrder = [SELECT Id, Status, AccountId FROM WorkOrder WHERE AccountId=:a.Id LIMIT 1].get(0);
        
        ProductConsumed testProdConsumed = new ProductConsumed(
            PricebookEntryId=pEntry.Id, 
            QuantityConsumed=1,
            WorkOrderId=testWorkOrder.Id
        );
        insert testProdConsumed;
        
    }

}