force-app/main/default/objects/Account/fields/A_P_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>A_P_Contact_Name__c</fullName>
    <inlineHelpText>Please enter First and Last Name</inlineHelpText>
    <label>A/P Contact Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Suite_Number__c</fullName>
    <label>Billing Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Chemical_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Chemical_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chemical Operating Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Accounts (Chemical Operating Hours)</relationshipLabel>
    <relationshipName>Accounts_Chemical</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Check__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check__c</fullName>
    <label>Credit Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Checked</fullName>
                <default>true</default>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Detailing_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Detailing_Reporting__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked customer would be able to see both Work Order and Line Items on the portal. If not customer would only see the Work Order as a proof of work completed</inlineHelpText>
    <label>Reporting Detail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hygiene_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Hygiene_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hygiene Operating Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Code_Accpac__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code_Accpac__c</fullName>
    <description>Select the appropriate Accpac Industry Code for this customer</description>
    <inlineHelpText>Industry Code is mandatory.</inlineHelpText>
    <label>Industry Code for Accpac</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000-00 UNKNOWN</fullName>
            </value>
            <value>
                <fullName>100-01 PROPERTY MANAGEMENT-Owner Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-02 PROPERTY MANAGEMENT-Owner Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-03 PROPERTY MANAGEMENT-Owner Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-04 PROPERTY MANAGEMENT-Owner Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-05 PROPERTY MANAGEMENT-Owner Managed - Residential</fullName>
            </value>
            <value>
                <fullName>100-21 PROPERTY MANAGEMENT-Third Party Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-22 PROPERTY MANAGEMENT-Third Party Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-23 PROPERTY MANAGEMENT-Third Party Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-24 PROPERTY MANAGEMENT-Third Party Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-25 PROPERTY MANAGEMENT-Third Party Managed - Residential</fullName>
            </value>
            <value>
                <fullName>200-01 HOSPITALITY-Convention Centres</fullName>
            </value>
            <value>
                <fullName>200-02 HOSPITALITY-Fitness Clubs</fullName>
            </value>
            <value>
                <fullName>200-03 HOSPITALITY-Golf&apos;s Club</fullName>
            </value>
            <value>
                <fullName>200-04 HOSPITALITY-Hotels, Motels</fullName>
            </value>
            <value>
                <fullName>200-05 HOSPITALITY-Independent Restaurants</fullName>
            </value>
            <value>
                <fullName>200-06 HOSPITALITY-Multi-chain Restaurants</fullName>
            </value>
            <value>
                <fullName>200-07 HOSPITALITY-Private Athletic Clubs</fullName>
            </value>
            <value>
                <fullName>200-08 HOSPITALITY-Ski Resorts</fullName>
            </value>
            <value>
                <fullName>200-09 HOSPITALITY-Sports Centers</fullName>
            </value>
            <value>
                <fullName>200-10 HOSPITALITY-Entertainment</fullName>
            </value>
            <value>
                <fullName>300-01 MANUFACTURING-Automotive</fullName>
            </value>
            <value>
                <fullName>300-02 MANUFACTURING-Food</fullName>
            </value>
            <value>
                <fullName>300-03 MANUFACTURING-Pharmaceutical</fullName>
            </value>
            <value>
                <fullName>300-04 MANUFACTURING-Textiles</fullName>
            </value>
            <value>
                <fullName>300-05 MANUFACTURING-Others</fullName>
            </value>
            <value>
                <fullName>400-01 GOVERNMENT-Municipal</fullName>
            </value>
            <value>
                <fullName>400-02 GOVERNMENT-Provincial</fullName>
            </value>
            <value>
                <fullName>400-03 GOVERNMENT-Federal</fullName>
            </value>
            <value>
                <fullName>500-01 HEALTH CARE-Hospitals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Preference__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Preference__c</fullName>
    <label>Invoice Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoicing_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email_Address__c</fullName>
    <label>Invoicing Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/LEED_Customer__c.field-meta.xml
<CustomField>
    <fullName>LEED_Customer__c</fullName>
    <inlineHelpText>Indicate whether the Customer is LEED Certified or not</inlineHelpText>
    <label>LEED Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Life_Safety_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Life_Safety_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Life Safety Operating Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Accounts (Life Safety Operating Hours)</relationshipLabel>
    <relationshipName>Accounts_LifeSafety</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pest_Control_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Pest_Control_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pest Control Operating Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Accounts (Pest Control Operating Hours)</relationshipLabel>
    <relationshipName>Accounts_PestControl</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Suite_Number__c</fullName>
    <label>Shipping Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Billing_Queue__c.field-meta.xml
<CustomField>
    <fullName>Billing_Queue__c</fullName>
    <label>Billing Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Customer_Service_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Profile_Id__c</fullName>
    <label>Customer Service Profile Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Invoice_Information_Case_RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Information_Case_RecordTypeId__c</fullName>
    <label>Invoice Information Case RecordTypeId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Operating_Hours_Type_Account__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type_Account__c</fullName>
    <label>Operating Hours Type - Account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/System_Administrator_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Administrator_Profile_Id__c</fullName>
    <label>System Administrator Profile Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OperatingHours/fields/Operating_Hours_Type__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type__c</fullName>
    <label>Operating Hours Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Operating Hours</fullName>
            </value>
            <value>
                <fullName>Employee Operating Hours</fullName>
            </value>
            <value>
                <fullName>Territory Operating Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/Province_Time_Zones_Operating_Hours__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A table to map each province to appropriate time zones, for Citron users to only associate Accounts to appropriate time zones.</description>
    <label>Province Time Zones - Operating Hours</label>
</CustomObject>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/fields/Province_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_Territory_Code__c</fullName>
    <label>Province/Territory Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAccountObjectTriggers.cls
@IsTest
public class TestAccountObjectTriggers {
    
    @TestSetup static void setup() {
        Date todaysDate = System.today();
        List<Account> accounts = new List<Account>();
        List<Site_Survey__c> siteSurveys = new List<Site_Survey__c>();
        
        String sysAdminProfileId = [SELECT Id FROM Profile WHERE Name ='System Administrator' LIMIT 1].Id;
        String randomProfileId = [SELECT Id, UserType FROM Profile WHERE Id !=:sysAdminProfileId AND UserType != 'PowerCustomerSuccess' LIMIT 1].Id;
        String customerSuccessProfileId = [SELECT Id FROM Profile WHERE Id!=:sysAdminProfileId AND Id!=:randomProfileId LIMIT 1].Id;
        
        Group testGroup = new Group(Name='Billing_Team', type='Queue');
        insert testGroup;
        
        QueueSobject mappingObject = new QueueSobject(QueueId = testGroup.Id, SObjectType = 'Case');
        
        System.runAs(new User(Id = UserInfo.getUserId())) {
        	insert mappingObject;
        }
        
        Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.System_Administrator_Profile_Id__c = sysAdminProfileId;
        fssetting.Customer_Service_Profile_Id__c = customerSuccessProfileId;
        fssetting.Operating_Hours_Type_Account__c = 'Account Operating Hours';
        fssetting.Invoice_Information_Case_RecordTypeId__c = '012f1000000PUJKAA4';
        fssetting.Billing_Queue__c = testGroup.Id;
        insert fssetting;
        
        TestDataFactory.crtAcctContact(4, 1);
        accounts = TestDataFactory.accounts;
        
        /*for(Integer i=1; i<4; i++) {
            accounts.add(
                new Account(
                    Name='TestAccount'+i, 
                    //AccPac_Account__c='1234-'+i, 
                    AccPac_Account__c='1234'+i, 
                    A_P_Contact_Name__c='TestContactName', 
                    Credit_Check__c='Completed', 
                    Industry='Institutions', 
                    Industry_Code_Accpac__c='000-00 UNKNOWN', 
                    Invoice_Preference__c='Email',
                    Invoicing_Email_Address__c='Test@test.com', 
                    LEED_Customer__c='No', 
                    On_Hold__c=FALSE, 
                    Type='Customer', 
                    Phone='123456789',
                    Billing_Suite_Number__c='1', 
                    BillingStreet='Street', 
                    BillingCity = 'City', 
                    BillingState = 'State', 
                    BillingPostalCode = 'PostalCode',
                    BillingCountry = 'Country',
                    Shipping_Suite_Number__c = '1',
                    ShippingStreet = 'Street', 
                    ShippingCity = 'City', 
                    ShippingState = 'State', 
                    ShippingPostalCode = 'PostalCode', 
                    ShippingCountry = 'Country'
                )
            );
        }
        insert accounts; */  
    }
    
       
    static testMethod void updateAccountException1() {
        Province_Time_Zones_Operating_Hours__c setting = new Province_Time_Zones_Operating_Hours__c();
        setting.Name = 'ON';
        setting.Province_Territory_Code__c = 'ON';
        setting.TimeZone__c = 'America/New_York';
        insert setting;
        
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        /*Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Operating_Hours_Type_Account__c = 'Account Operating Hours';
        insert fssetting;*/
        
        Date todaysDate = System.today();
        List<Account> accounts = new List<Account>([SELECT Id, Name, OperatingHoursId, Hygiene_Operating_Hours__c, Chemical_Operating_Hours__c, Life_Safety_Operating_Hours__c, 
                                                    Pest_Control_Operating_Hours__c, ShippingState FROM Account]);
        
        OperatingHours oh = new OperatingHours(
            Name='TestHours', 
            Operating_Hours_Type__c='Territory Operating Hours', 
            TimeZone='America/New_York'
        );
        
        insert oh;
        
        Account a1 = accounts.get(1);
        Account a2 = accounts.get(2);
        
        a1.OperatingHoursId = oh.Id;
        a2.OperatingHoursId = oh.Id;
        a1.Hygiene_Operating_Hours__c = oh.Id;
        a2.Hygiene_Operating_Hours__c = oh.Id;
        a1.Chemical_Operating_Hours__c = oh.Id;
        a2.Chemical_Operating_Hours__c = oh.Id;
        a1.Life_Safety_Operating_Hours__c = oh.Id;
        a2.Life_Safety_Operating_Hours__c = oh.Id;
        a1.Pest_Control_Operating_Hours__c = oh.Id;
        a2.Pest_Control_Operating_Hours__c = oh.Id;
        try {
            update new List<Account>{a1, a2};
                } catch (Exception e) {
            System.assert(e.getMessage().contains('Account Operating Hours'), 'message=' + e.getMessage());
        }
    }
    
    static testMethod void updateAccountException2() {
        Province_Time_Zones_Operating_Hours__c setting = new Province_Time_Zones_Operating_Hours__c();
        setting.Name = 'ON';
        setting.Province_Territory_Code__c = 'ON';
        setting.TimeZone__c = 'America/Los_Angeles';
        insert setting;
        
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        /*Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Operating_Hours_Type_Account__c = 'Account Operating Hours';
        insert fssetting;*/
        
        Date todaysDate = System.today();
        List<Account> accounts = new List<Account>([SELECT Id, Name, OperatingHoursId, Hygiene_Operating_Hours__c, Chemical_Operating_Hours__c, Life_Safety_Operating_Hours__c, 
                                                    Pest_Control_Operating_Hours__c, ShippingState FROM Account]);
       
        OperatingHours oh = new OperatingHours(
            Name='TestHours', 
            Operating_Hours_Type__c='Account Operating Hours', 
            TimeZone='America/New_York'
        );
        
        insert oh;
        
        Account a1 = accounts.get(1);
        Account a2 = accounts.get(2);
        
        a1.ShippingState = 'ON';
        a2.ShippingState = 'ON';
        a1.OperatingHoursId = oh.Id;
        a2.OperatingHoursId = oh.Id;
        a1.Hygiene_Operating_Hours__c = oh.Id;
        a2.Hygiene_Operating_Hours__c = oh.Id;
        a1.Chemical_Operating_Hours__c = oh.Id;
        a2.Chemical_Operating_Hours__c = oh.Id;
        a1.Life_Safety_Operating_Hours__c = oh.Id;
        a2.Life_Safety_Operating_Hours__c = oh.Id;
        a1.Pest_Control_Operating_Hours__c = oh.Id;
        a2.Pest_Control_Operating_Hours__c = oh.Id;
        //update new List<Account>{a1, a2};
        try {
            update new List<Account>{a1, a2};
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Operating Hours TimeZone'), 'message=' + e.getMessage());
        }
    }
    
    static testMethod void updateAccountException3() {
        Province_Time_Zones_Operating_Hours__c setting = new Province_Time_Zones_Operating_Hours__c();
        setting.Name = 'ON';
        setting.Province_Territory_Code__c = 'ON';
        setting.TimeZone__c = 'America/New_York';
        insert setting;
        
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        /*Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Operating_Hours_Type_Account__c = 'Account Operating Hours';
        insert fssetting;*/
        
        Date todaysDate = System.today();
        List<Account> accounts = new List<Account>([SELECT Id, Name, OperatingHoursId, Hygiene_Operating_Hours__c, Chemical_Operating_Hours__c, Life_Safety_Operating_Hours__c, 
                                                    Pest_Control_Operating_Hours__c, ShippingState FROM Account]);
        
        OperatingHours oh = new OperatingHours(
            Name='TestHours', 
            Operating_Hours_Type__c='Account Operating Hours', 
            TimeZone='America/New_York'
        );
        
        insert oh;
        
        Account a1 = accounts.get(1);
        Account a2 = accounts.get(2);
        
        a1.ShippingState = null;
        a2.ShippingState = null;
        a1.OperatingHoursId = oh.Id;
        a2.OperatingHoursId = oh.Id;
        a1.Hygiene_Operating_Hours__c = oh.Id;
        a2.Hygiene_Operating_Hours__c = oh.Id;
        a1.Chemical_Operating_Hours__c = oh.Id;
        a2.Chemical_Operating_Hours__c = oh.Id;
        a1.Life_Safety_Operating_Hours__c = oh.Id;
        a2.Life_Safety_Operating_Hours__c = oh.Id;
        a1.Pest_Control_Operating_Hours__c = oh.Id;
        a2.Pest_Control_Operating_Hours__c = oh.Id;
        //update new List<Account>{a1, a2};
        try {
            update new List<Account>{a1, a2};
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Please complete Shipping'), 'message=' + e.getMessage());
        }
    }
    
    static testMethod void updateAccountNoException() {
        Province_Time_Zones_Operating_Hours__c setting = new Province_Time_Zones_Operating_Hours__c();
        setting.Name = 'ON';
        setting.Province_Territory_Code__c = 'ON';
        setting.TimeZone__c = 'America/New_York';
        insert setting;
        
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        /*Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.SetupOwnerId=UserInfo.getOrganizationId();
        fssetting.Operating_Hours_Type_Account__c = 'Account Operating Hours';
        insert fssetting;*/
        
        Date todaysDate = System.today();
        List<Account> accounts = new List<Account>([SELECT Id, Name, OperatingHoursId FROM Account]);
        
        OperatingHours oh = new OperatingHours(
            Name='TestHours', 
            Operating_Hours_Type__c='Account Operating Hours', 
            TimeZone='America/New_York'
        );
        
        insert oh;
        
        Account a1 = accounts.get(1);
        Account a2 = accounts.get(2);        
        a1.OperatingHoursId = oh.Id;
        a2.OperatingHoursId = oh.Id;
        update new List<Account>{a1, a2};
    }
    
    static testMethod void updateAccountNoExceptionAddressCheck() {
        Province_Time_Zones_Operating_Hours__c setting = new Province_Time_Zones_Operating_Hours__c();
        setting.Name = 'ON';
        setting.Province_Territory_Code__c = 'ON';
        setting.TimeZone__c = 'America/New_York';
        insert setting;
        
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        /*Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Operating_Hours_Type_Account__c = 'Account Operating Hours';
        insert fssetting;*/
        
        Date todaysDate = System.today();
        List<Account> accounts = new List<Account>([SELECT Id, Name, OperatingHoursId FROM Account]);
        
        OperatingHours oh = new OperatingHours(
            Name='TestHours', 
            Operating_Hours_Type__c='Account Operating Hours', 
            TimeZone='America/New_York'
        );
        
        insert oh;
        
        Account a1 = accounts.get(1);
        Account a2 = accounts.get(2);        
        a1.OperatingHoursId = oh.Id;
        a2.OperatingHoursId = oh.Id;
        update new List<Account>{a1, a2};
    }
    
    static testMethod void updateAccountChangeReporting() {
        Date todaysDate = System.today();
        List<Account> accounts = new List<Account>([SELECT Id, Name, OperatingHoursId FROM Account]);
       
        for(Account a : accounts) {
            a.Detailing_Reporting__c = true;
        }
        
        update accounts;
    }
    
    static testMethod void updateAccountInvoiceAddressNoException(){
        String sysAdminProfileId = [SELECT Id FROM Profile WHERE Name ='System Administrator' LIMIT 1].Id;
        String randomProfileId = [SELECT Id, UserType FROM Profile WHERE Id !=:sysAdminProfileId AND UserType != 'PowerCustomerSuccess' LIMIT 1].Id;
        
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        
        /*Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.System_Administrator_Profile_Id__c = sysAdminProfileId;
        fssetting.Customer_Service_Profile_Id__c = randomProfileId;
        insert fssetting;*/
        
        Account a = [SELECT Id, ShippingState, BillingStreet, Invoice_Frequency__c, AccPac_Account__c FROM Account LIMIT 1];
        
        a.AccPac_Account__c = null;
        a.Invoice_Frequency__c = 'M - Monthly';
        a.ShippingState = 'ON';
        a.BillingStreet = 'New Street';
        update a;
    }
    
    static testMethod void testAccountOwnerChange() {        
        test.StartTest();
        // Setup test data
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User dcf = [SELECT Id FROM User WHERE Id='005j000000C24pMAAR']; 
        User u = new User(Alias = 'standt', Email='standarduser1@cannonservices.ca', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser1@cannonservices.ca', Employee_Number__c = 'ABCD123TEST');
        
        insert u;
        System.debug('User u: ' + u.Id);
        
		Field_Service_Settings__c fss = new Field_Service_Settings__c();
       	fss.Integration_User_Id__c = dcf.Id;
        
        insert fss;
        
        System.runAs(dcf) {
            // The following code runs as user 'u' 
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('Current Profile: ' + UserInfo.getProfileId()); 
            
            Account a = [SELECT Id, ShippingState, BillingStreet, Invoice_Frequency__c, AccPac_Account__c FROM Account LIMIT 1];
            a.OwnerId=dcf.Id;
            /*a.Lead_Source__c='Blitz Day';
            a.BillingCountry='CA';
            a.BillingState='ON';
            a.BillingCity='Toronto';
            a.Phone = '9051231234';*/
            update a;
            Opportunity o = new Opportunity(Name=a.Name + ' Opportunity ', 
                                StageName='Presentation', CloseDate=System.today().addMonths(1),
                                AccountId=a.Id, OwnerId=dcf.Id);
            insert o;
                        
            System.debug('Created Account Owner: ' + a.OwnerId);
            System.debug('Created Opportunity Owner: ' + o.OwnerId);
            System.debug('Changing to User: ' + u.Id);
            
            a.OwnerId = u.Id;
            update a;
            
            //fetch updated version
            Opportunity oUp = [SELECT Id, OwnerId FROM Opportunity WHERE Id=:o.Id];
            
            System.debug('Updated Account Owner: ' + a.OwnerId);
            System.debug('Updated Opportunity Owner: ' + oUp.OwnerId);
            
            System.assertEquals(oUp.OwnerId, u.Id);
            test.StopTest();
        }
    }

    static testMethod void testFSAStampingPositive() {  
        Account resultAccount = [SELECT Id, FSA_Mapping__r.FSA__c FROM Account LIMIT 1];
        System.assertEquals('L3R', resultAccount.FSA_Mapping__r.FSA__c);
    }

    static testMethod void testFSAStampingNegative() {  

        Account resultAccount = [SELECT Id, FSA_Mapping__r.FSA__c FROM Account LIMIT 1];

        resultAccount.ShippingPostalCode = null;
        update resultAccount;
        resultAccount = [SELECT Id, FSA_Mapping__c FROM Account WHERE Id=:resultAccount.Id];
        System.assertEquals(null, resultAccount.FSA_Mapping__c);        
    }    

    static testMethod void testBillingToShipping(){
        TestDataFactory.crtAcctContact(1, 1, 5, false);
        List<Account> accounts = TestDataFactory.accounts;

        Account resultAccount = [SELECT Id, 
                                BillingStreet, 
                                BillingCity, 
                                BillingState, 
                                BillingPostalCode, 
                                BillingCountry,
                                ShippingStreet,
                                ShippingCity,
                                ShippingState,
                                ShippingPostalCode,
                                ShippingCountry 
                        FROM Account 
                        WHERE Id=:accounts[0].Id];

        System.assertEquals(resultAccount.BillingStreet, resultAccount.ShippingStreet); 
        System.assertEquals(resultAccount.BillingCity, resultAccount.ShippingCity); 
        System.assertEquals(resultAccount.BillingState, resultAccount.ShippingState); 
        System.assertEquals(resultAccount.BillingPostalCode, resultAccount.ShippingPostalCode); 
        System.assertEquals(resultAccount.BillingCountry, resultAccount.ShippingCountry); 
    }
}