force-app/main/default/objects/Account/fields/A_P_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>A_P_Contact_Name__c</fullName>
    <inlineHelpText>Please enter First and Last Name</inlineHelpText>
    <label>A/P Contact Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Suite_Number__c</fullName>
    <label>Billing Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Check__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check__c</fullName>
    <label>Credit Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Checked</fullName>
                <default>true</default>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Code_Accpac__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code_Accpac__c</fullName>
    <description>Select the appropriate Accpac Industry Code for this customer</description>
    <inlineHelpText>Industry Code is mandatory.</inlineHelpText>
    <label>Industry Code for Accpac</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000-00 UNKNOWN</fullName>
            </value>
            <value>
                <fullName>100-01 PROPERTY MANAGEMENT-Owner Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-02 PROPERTY MANAGEMENT-Owner Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-03 PROPERTY MANAGEMENT-Owner Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-04 PROPERTY MANAGEMENT-Owner Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-05 PROPERTY MANAGEMENT-Owner Managed - Residential</fullName>
            </value>
            <value>
                <fullName>100-21 PROPERTY MANAGEMENT-Third Party Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-22 PROPERTY MANAGEMENT-Third Party Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-23 PROPERTY MANAGEMENT-Third Party Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-24 PROPERTY MANAGEMENT-Third Party Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-25 PROPERTY MANAGEMENT-Third Party Managed - Residential</fullName>
            </value>
            <value>
                <fullName>200-01 HOSPITALITY-Convention Centres</fullName>
            </value>
            <value>
                <fullName>200-02 HOSPITALITY-Fitness Clubs</fullName>
            </value>
            <value>
                <fullName>200-03 HOSPITALITY-Golf&apos;s Club</fullName>
            </value>
            <value>
                <fullName>200-04 HOSPITALITY-Hotels, Motels</fullName>
            </value>
            <value>
                <fullName>200-05 HOSPITALITY-Independent Restaurants</fullName>
            </value>
            <value>
                <fullName>200-06 HOSPITALITY-Multi-chain Restaurants</fullName>
            </value>
            <value>
                <fullName>200-07 HOSPITALITY-Private Athletic Clubs</fullName>
            </value>
            <value>
                <fullName>200-08 HOSPITALITY-Ski Resorts</fullName>
            </value>
            <value>
                <fullName>200-09 HOSPITALITY-Sports Centers</fullName>
            </value>
            <value>
                <fullName>200-10 HOSPITALITY-Entertainment</fullName>
            </value>
            <value>
                <fullName>300-01 MANUFACTURING-Automotive</fullName>
            </value>
            <value>
                <fullName>300-02 MANUFACTURING-Food</fullName>
            </value>
            <value>
                <fullName>300-03 MANUFACTURING-Pharmaceutical</fullName>
            </value>
            <value>
                <fullName>300-04 MANUFACTURING-Textiles</fullName>
            </value>
            <value>
                <fullName>300-05 MANUFACTURING-Others</fullName>
            </value>
            <value>
                <fullName>400-01 GOVERNMENT-Municipal</fullName>
            </value>
            <value>
                <fullName>400-02 GOVERNMENT-Provincial</fullName>
            </value>
            <value>
                <fullName>400-03 GOVERNMENT-Federal</fullName>
            </value>
            <value>
                <fullName>500-01 HEALTH CARE-Hospitals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Preference__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Preference__c</fullName>
    <label>Invoice Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoicing_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email_Address__c</fullName>
    <label>Invoicing Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/LEED_Customer__c.field-meta.xml
<CustomField>
    <fullName>LEED_Customer__c</fullName>
    <inlineHelpText>Indicate whether the Customer is LEED Certified or not</inlineHelpText>
    <label>LEED Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ServiceTerritory.ParentTerritoryId</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>ServiceTerritory.IsActive</field>
            <operation>notEqual</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Suite_Number__c</fullName>
    <label>Shipping Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/CitronDoNotReply__c.field-meta.xml
<CustomField>
    <fullName>CitronDoNotReply__c</fullName>
    <label>CitronDoNotReply</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Org_Wide_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Org_Wide_Email_Address__c</fullName>
    <label>Org-Wide Email Address</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/ServiceReportTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ServiceReportTemplateId__c</fullName>
    <label>ServiceReportTemplateId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OperatingHours/fields/Operating_Hours_Type__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type__c</fullName>
    <label>Operating Hours Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Operating Hours</fullName>
            </value>
            <value>
                <fullName>Employee Operating Hours</fullName>
            </value>
            <value>
                <fullName>Territory Operating Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business__c</fullName>
    <label>Line Of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/LEED_Customer__c.field-meta.xml
<CustomField>
    <fullName>LEED_Customer__c</fullName>
    <formula>TEXT(Account.LEED_Customer__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LEED Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Suite_Number__c</fullName>
    <label>Suite Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testServiceAppointmentFutureCalls.cls
@isTest//(SeeAllData=true)
public class testServiceAppointmentFutureCalls {
    
    static testMethod void testFutureCalls() {
        Field_Service_Settings__c datasets = new Field_Service_Settings__c(ServiceReportTemplateId__c='00X2C000000M6czUAC', Org_Wide_Email_Address__c='0D22C0000008OiISAU');
        Id pBook = Test.getStandardPricebookId();
        OperatingHours oh = new OperatingHours(
            Name='TestHours', 
            Operating_Hours_Type__c='Account Operating Hours', 
            TimeZone='America/New_York'
        );
        insert oh;
        ServiceTerritory st = new ServiceTerritory(
            IsActive=TRUE,
            Street='Street', 
            City = 'City', 
            State = 'State', 
            PostalCode = 'PostalCode',
            Country = 'Country', 
            OperatingHoursId=oh.Id, 
            Name='TerritoryForCaseTestScenarios'
        );
        insert st;
        Account a = new Account(
            Name='TestAccount', 
            AccPac_Account__c='223412-', 
            A_P_Contact_Name__c='TestContactName', 
            Credit_Check__c='Completed', 
            Industry='Institutions', 
            Industry_Code_Accpac__c='000-00 UNKNOWN', 
            Invoice_Preference__c='Email',
            Invoicing_Email_Address__c='Test@test.com', 
            LEED_Customer__c='No', 
            On_Hold__c=FALSE, 
            Type='Customer', 
            Phone='123456789',
            //OperatingHoursId = oh.Id,
            //Service_Territory__c = st.Id,
            Billing_Suite_Number__c='1', 
            BillingStreet='Street', 
            BillingCity = 'City', 
            BillingState = 'State', 
            BillingPostalCode = 'PostalCode',
            BillingCountry = 'Country',
            Shipping_Suite_Number__c = '1',
            ShippingStreet = 'Street', 
            ShippingCity = 'City', 
            ShippingState = 'State', 
            ShippingPostalCode = 'PostalCode', 
            ShippingCountry = 'Country'
        );
        insert a;
        WorkOrder testWorkOrder = new WorkOrder(
            AccountId=a.Id,
            StartDate=System.today(), 
            Line_of_Business__c='Hygiene', 
            Pricebook2Id=pBook, 
            Suite_Number__c='1', 
            Street='Street', 
            City = 'City', 
            State = 'State', 
            PostalCode = 'PostalCode',
            Country = 'Country'
        );
        insert testWorkOrder;
        ServiceAppointment testSA = new ServiceAppointment(
            ParentRecordId=testWorkOrder.Id, 
            DueDate=System.today().addDays(2), 
            EarliestStartTime=System.today().addDays(-1), 
            Status='New', 
            ServiceTerritoryId=testWorkOrder.ServiceTerritoryId
        );
        insert testSA;
        Contact cnt = new Contact(
            lastName='test',
            AccountId = a.Id
        );
        insert cnt;
        Set<String> saIds = new set<String>();
        Set<Id> saFutureIds = new Set<Id>();
        Set<Id> woIds = new set<Id>();
        woIds.add(testWorkOrder.Id);
        saIds.add(testSA.Id);
        saFutureIds.add(testSA.Id);
        //ServiceAppointmentFutureCalls.statusSyncMethod(saIds);
        //ServiceAppointmentFutureCalls.lastInFlightDateUpdates(woIds);
        Test.setMock(HttpCalloutMock.class, new ExampleCalloutMock(testSA.Id));
        
        Test.startTest();
        
        ServiceAppointmentFutureCalls.createSendServiceReport(saFutureIds, woIds, UserInfo.getSessionId());
        
        Test.stopTest();
        
        //ServiceAppointmentFutureCalls.createServiceReport(datasets.HygieneDetailedReportingId__c, testSA.Id, userinfo.getSessionId(), cnt.Id, datasets.ServiceReportTemplateId__c, datasets.CitronDoNotReply__c, true);
        //ServiceAppointmentFutureCalls.createServiceReport(datasets.HygieneDetailedReportingId__c, testSA.Id, userinfo.getSessionId(), null, datasets.ServiceReportTemplateId__c, datasets.CitronDoNotReply__c, true);
    }
    
    public class ExampleCalloutMock implements HttpCalloutMock{
        private Id saId;
        
        public ExampleCalloutMock(Id saId) {
            this.saId = saId;
        }
        
        public HttpResponse respond(HTTPRequest req){
            /*ServiceReport sr = [SELECT Id FROM ServiceReport LIMIT 1];
            HttpResponse res = new HttpResponse();
            res.setStatus('OK');
            res.setStatusCode(200);
            res.setBody('"serviceReportId":"' + sr.Id + '","contentVersionId"');
            return res;*/
            
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json;charset=UTF-8');
            res.setBody('{"example":"test", "contentVersionId":"' + saId + '","entityId":"' + saId + '"}');
            res.setStatusCode(200);
            return res;
        }
    }
}