force-app/main/default/objects/Account/fields/A_P_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>A_P_Contact_Name__c</fullName>
    <inlineHelpText>Please enter First and Last Name</inlineHelpText>
    <label>A/P Contact Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Suite_Number__c</fullName>
    <label>Billing Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Check__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check__c</fullName>
    <label>Credit Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Checked</fullName>
                <default>true</default>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Code_Accpac__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code_Accpac__c</fullName>
    <description>Select the appropriate Accpac Industry Code for this customer</description>
    <inlineHelpText>Industry Code is mandatory.</inlineHelpText>
    <label>Industry Code for Accpac</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000-00 UNKNOWN</fullName>
            </value>
            <value>
                <fullName>100-01 PROPERTY MANAGEMENT-Owner Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-02 PROPERTY MANAGEMENT-Owner Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-03 PROPERTY MANAGEMENT-Owner Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-04 PROPERTY MANAGEMENT-Owner Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-05 PROPERTY MANAGEMENT-Owner Managed - Residential</fullName>
            </value>
            <value>
                <fullName>100-21 PROPERTY MANAGEMENT-Third Party Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-22 PROPERTY MANAGEMENT-Third Party Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-23 PROPERTY MANAGEMENT-Third Party Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-24 PROPERTY MANAGEMENT-Third Party Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-25 PROPERTY MANAGEMENT-Third Party Managed - Residential</fullName>
            </value>
            <value>
                <fullName>200-01 HOSPITALITY-Convention Centres</fullName>
            </value>
            <value>
                <fullName>200-02 HOSPITALITY-Fitness Clubs</fullName>
            </value>
            <value>
                <fullName>200-03 HOSPITALITY-Golf&apos;s Club</fullName>
            </value>
            <value>
                <fullName>200-04 HOSPITALITY-Hotels, Motels</fullName>
            </value>
            <value>
                <fullName>200-05 HOSPITALITY-Independent Restaurants</fullName>
            </value>
            <value>
                <fullName>200-06 HOSPITALITY-Multi-chain Restaurants</fullName>
            </value>
            <value>
                <fullName>200-07 HOSPITALITY-Private Athletic Clubs</fullName>
            </value>
            <value>
                <fullName>200-08 HOSPITALITY-Ski Resorts</fullName>
            </value>
            <value>
                <fullName>200-09 HOSPITALITY-Sports Centers</fullName>
            </value>
            <value>
                <fullName>200-10 HOSPITALITY-Entertainment</fullName>
            </value>
            <value>
                <fullName>300-01 MANUFACTURING-Automotive</fullName>
            </value>
            <value>
                <fullName>300-02 MANUFACTURING-Food</fullName>
            </value>
            <value>
                <fullName>300-03 MANUFACTURING-Pharmaceutical</fullName>
            </value>
            <value>
                <fullName>300-04 MANUFACTURING-Textiles</fullName>
            </value>
            <value>
                <fullName>300-05 MANUFACTURING-Others</fullName>
            </value>
            <value>
                <fullName>400-01 GOVERNMENT-Municipal</fullName>
            </value>
            <value>
                <fullName>400-02 GOVERNMENT-Provincial</fullName>
            </value>
            <value>
                <fullName>400-03 GOVERNMENT-Federal</fullName>
            </value>
            <value>
                <fullName>500-01 HEALTH CARE-Hospitals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Preference__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Preference__c</fullName>
    <label>Invoice Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoicing_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email_Address__c</fullName>
    <label>Invoicing Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/LEED_Customer__c.field-meta.xml
<CustomField>
    <fullName>LEED_Customer__c</fullName>
    <inlineHelpText>Indicate whether the Customer is LEED Certified or not</inlineHelpText>
    <label>LEED Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Suite_Number__c</fullName>
    <label>Shipping Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Product2/fields/VMI_Product__c.field-meta.xml
<CustomField>
    <fullName>VMI_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VMI Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Survey_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Date__c</fullName>
    <label>Survey Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VMI_Product__c/VMI_Product__c.object-meta.xml
<CustomObject>
    <label>VMI Product</label>
    <nameField>
        <label>VMI Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VMI Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VMI_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>VMI Products</relationshipLabel>
    <relationshipName>VMI_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VMI_Product__c/fields/Par_Level__c.field-meta.xml
<CustomField>
    <fullName>Par_Level__c</fullName>
    <label>Par Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VMI_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Product selected is not a VMI Product</errorMessage>
        <filterItems>
            <field>Product2.VMI_Product__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>VMI Products</relationshipLabel>
    <relationshipName>VMI_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestSiteSurveyVMIController.cls
@isTest
public class TestSiteSurveyVMIController {
    
	static testMethod void testVMI() {
         Account a = new Account(
                    Name='TestAccount', 
                    AccPac_Account__c='1234-', 
                    A_P_Contact_Name__c='TestContactName', 
                    Credit_Check__c='Completed', 
                    Industry='Institutions', 
                    Industry_Code_Accpac__c='000-00 UNKNOWN', 
                    Invoice_Preference__c='Email',
                    Invoicing_Email_Address__c='Test@test.com', 
                    LEED_Customer__c='No', 
                    On_Hold__c=FALSE, 
                    Type='Customer', 
                    Phone='123456789',
                    Billing_Suite_Number__c='1', 
                    BillingStreet='Street', 
                    BillingCity = 'City', 
                    BillingState = 'State', 
                    BillingPostalCode = 'PostalCode',
                    BillingCountry = 'Country',
                    Shipping_Suite_Number__c = '1',
                    ShippingStreet = 'Street', 
                    ShippingCity = 'City', 
                    ShippingState = 'State', 
                    ShippingPostalCode = 'PostalCode', 
                    ShippingCountry = 'Country'
                );
        insert a;
        Site_Survey__c ss = new Site_Survey__c(
                    Account__c=a.Id, 
                    Survey_Date__c = System.today(),
                    Status__c = 'Draft'
                );
        insert ss;
		Product2 prd = new Product2(name='testProd', VMI_Product__c = true);
		insert prd;        
        VMI_Product__c vmi = new VMI_Product__c(Par_Level__c = 1, Notes__c='test', Account__c=a.Id, Product__c = prd.Id);
        insert vmi;
        List<VMI_Product__c> vmiProds = SiteSurveyVMIController.getVMIProducts(ss.Id);
        SiteSurveyVMIController.saveNewProduct(vmi);
        List<SiteSurveyVMIController.vmiFlaggedProduct> vmiflagged = SiteSurveyVMIController.getVMIFlaggedProducts(vmiProds);
        SiteSurveyVMIController.deleteSingleVMI(vmi);
        List<String> cols = new List<String>{'VMI_Product__c.Product__c'};
        SiteSurveyVMIController.getColumns(cols); 
        SiteSurveyVMIController.saveNewVMIProduct(JSON.serialize(vmiflagged), vmiProds, ss.Id);
    }
}