force-app/main/default/objects/Account/fields/A_P_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>A_P_Contact_Name__c</fullName>
    <inlineHelpText>Please enter First and Last Name</inlineHelpText>
    <label>A/P Contact Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Suite_Number__c</fullName>
    <label>Billing Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Check__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check__c</fullName>
    <label>Credit Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Checked</fullName>
                <default>true</default>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Code_Accpac__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code_Accpac__c</fullName>
    <description>Select the appropriate Accpac Industry Code for this customer</description>
    <inlineHelpText>Industry Code is mandatory.</inlineHelpText>
    <label>Industry Code for Accpac</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000-00 UNKNOWN</fullName>
            </value>
            <value>
                <fullName>100-01 PROPERTY MANAGEMENT-Owner Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-02 PROPERTY MANAGEMENT-Owner Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-03 PROPERTY MANAGEMENT-Owner Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-04 PROPERTY MANAGEMENT-Owner Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-05 PROPERTY MANAGEMENT-Owner Managed - Residential</fullName>
            </value>
            <value>
                <fullName>100-21 PROPERTY MANAGEMENT-Third Party Managed - Office</fullName>
            </value>
            <value>
                <fullName>100-22 PROPERTY MANAGEMENT-Third Party Managed - Retail</fullName>
            </value>
            <value>
                <fullName>100-23 PROPERTY MANAGEMENT-Third Party Managed - Industrial</fullName>
            </value>
            <value>
                <fullName>100-24 PROPERTY MANAGEMENT-Third Party Managed - Banks</fullName>
            </value>
            <value>
                <fullName>100-25 PROPERTY MANAGEMENT-Third Party Managed - Residential</fullName>
            </value>
            <value>
                <fullName>200-01 HOSPITALITY-Convention Centres</fullName>
            </value>
            <value>
                <fullName>200-02 HOSPITALITY-Fitness Clubs</fullName>
            </value>
            <value>
                <fullName>200-03 HOSPITALITY-Golf&apos;s Club</fullName>
            </value>
            <value>
                <fullName>200-04 HOSPITALITY-Hotels, Motels</fullName>
            </value>
            <value>
                <fullName>200-05 HOSPITALITY-Independent Restaurants</fullName>
            </value>
            <value>
                <fullName>200-06 HOSPITALITY-Multi-chain Restaurants</fullName>
            </value>
            <value>
                <fullName>200-07 HOSPITALITY-Private Athletic Clubs</fullName>
            </value>
            <value>
                <fullName>200-08 HOSPITALITY-Ski Resorts</fullName>
            </value>
            <value>
                <fullName>200-09 HOSPITALITY-Sports Centers</fullName>
            </value>
            <value>
                <fullName>200-10 HOSPITALITY-Entertainment</fullName>
            </value>
            <value>
                <fullName>300-01 MANUFACTURING-Automotive</fullName>
            </value>
            <value>
                <fullName>300-02 MANUFACTURING-Food</fullName>
            </value>
            <value>
                <fullName>300-03 MANUFACTURING-Pharmaceutical</fullName>
            </value>
            <value>
                <fullName>300-04 MANUFACTURING-Textiles</fullName>
            </value>
            <value>
                <fullName>300-05 MANUFACTURING-Others</fullName>
            </value>
            <value>
                <fullName>400-01 GOVERNMENT-Municipal</fullName>
            </value>
            <value>
                <fullName>400-02 GOVERNMENT-Provincial</fullName>
            </value>
            <value>
                <fullName>400-03 GOVERNMENT-Federal</fullName>
            </value>
            <value>
                <fullName>500-01 HEALTH CARE-Hospitals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Preference__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Preference__c</fullName>
    <label>Invoice Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoicing_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email_Address__c</fullName>
    <label>Invoicing Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/LEED_Customer__c.field-meta.xml
<CustomField>
    <fullName>LEED_Customer__c</fullName>
    <inlineHelpText>Indicate whether the Customer is LEED Certified or not</inlineHelpText>
    <label>LEED Customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Suite_Number__c</fullName>
    <label>Shipping Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Emergency.recordType-meta.xml
<RecordType>
    <fullName>Emergency</fullName>
    <active>true</active>
    <businessProcess>Emergency</businessProcess>
    <description>For Customer Emergency Services</description>
    <label>Emergency</label>
</RecordType>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/Emergency_Dispatch_Wizard_Setttings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Emergency Dispatch Wizard Setttings</label>
</CustomObject>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/fields/Maximum_Number_of_Resources__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Number_of_Resources__c</fullName>
    <inlineHelpText>The maximum number of resources a user can specify on a Work Order</inlineHelpText>
    <label>Maximum Number of Resources</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/fields/Order_Item_Batch_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_Batch_Threshold__c</fullName>
    <inlineHelpText>The number of records being processed in the Emergency Dispatch Wizard before a batch class is required to handle the volume of Order Product records. The purpose of batching is to guard against SOQL query limits.</inlineHelpText>
    <label>Order Item Batch Threshold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/fields/Order_Name__c.field-meta.xml
<CustomField>
    <fullName>Order_Name__c</fullName>
    <inlineHelpText>The name of the Order for Orders created in the Emergency Dispatch Wizard</inlineHelpText>
    <label>Order Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/fields/Work_Order_Multi_Res_Advance_Days__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Multi_Res_Advance_Days__c</fullName>
    <label>Work Order Multi-Res Advance Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Account_Ship_To_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Ship_To_Record_Type_Id__c</fullName>
    <label>Account Ship To Record Type Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Customer_Success_Queue__c.field-meta.xml
<CustomField>
    <fullName>Customer_Success_Queue__c</fullName>
    <label>Customer Success Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Non_Recurring_Frequency_Value__c.field-meta.xml
<CustomField>
    <fullName>Non_Recurring_Frequency_Value__c</fullName>
    <label>Non Recurring Frequency Value</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Pest_LOB__c.field-meta.xml
<CustomField>
    <fullName>Pest_LOB__c</fullName>
    <label>Pest LOB</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Regular_Order_Draft_Stage__c.field-meta.xml
<CustomField>
    <fullName>Regular_Order_Draft_Stage__c</fullName>
    <label>Regular Order Draft Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Standard_Pricebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Standard_Pricebook_Id__c</fullName>
    <label>Standard Pricebook Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Ticket_Emergency_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Emergency_Record_Type__c</fullName>
    <label>Ticket Emergency Record Type</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Billing_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Suite_Number__c</fullName>
    <label>Billing Suite Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Suite_Number__c</fullName>
    <label>Shipping Suite Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Site_Survey__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Survey_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EDW_SelectCustomerControllerTest.cls
@isTest
public class EDW_SelectCustomerControllerTest {
	@testSetup
    static void setup() {
        Group testGroup = new Group(Name='Customer_Success', type='Queue');
        insert testGroup;
        
        QueueSObject mappingObject = new QueueSobject(QueueId = testGroup.Id, SObjectType = 'Case');
        
        System.runAs(new User(Id = UserInfo.getUserId())) {
        	insert mappingObject;
        }
        
        Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Account_Ship_To_Record_Type_Id__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Ship To').getRecordTypeId();
        fssetting.Ticket_Emergency_Record_Type__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Emergency').getRecordTypeId();
        fssetting.Customer_Success_Queue__c = testGroup.Id;
        fssetting.Standard_Pricebook_Id__c = Test.getStandardPricebookId();
        fssetting.Regular_Order_Draft_Stage__c = 'Draft';
        fssetting.Pest_LOB__c = 'Pest Control';
        fssetting.Non_Recurring_Frequency_Value__c = 'One-Time';
        
        insert fssetting;
        
        Emergency_Dispatch_Wizard_Setttings__c edws = new Emergency_Dispatch_Wizard_Setttings__c();
        edws.Order_Name__c = 'test order ';
        edws.Maximum_Number_of_Resources__c = 10;
        edws.Order_Item_Batch_Threshold__c = 10;
        edws.Work_Order_Multi_Res_Advance_Days__c = 40;
        
        insert edws;
        
        Account a = new Account(
            Name='TestAccount', 
            AccPac_Account__c='1234-', 
            A_P_Contact_Name__c='TestContactName', 
            Credit_Check__c='Completed', 
            Industry='Institutions', 
            Industry_Code_Accpac__c='000-00 UNKNOWN', 
            Invoice_Preference__c='Email',
            Invoicing_Email_Address__c='Test@test.com', 
            LEED_Customer__c='No', 
            On_Hold__c=FALSE, 
            Type='Customer', 
            Phone='123456789',
            Billing_Suite_Number__c='1', 
            BillingStreet='Street', 
            BillingCity = 'City', 
            BillingState = 'State', 
            BillingPostalCode = 'PostalCode',
            BillingCountry = 'Country',
            Shipping_Suite_Number__c = '1',
            ShippingStreet = 'Street', 
            ShippingCity = 'City', 
            ShippingState = 'State', 
            ShippingPostalCode = 'PostalCode', 
            ShippingCountry = 'Country'
        );
        insert a;
        
        Contact c = new Contact();
        c.LastName = 'test';
        c.Email = 'test@example.com';
        c.AccountId = a.Id;
        
        insert c;
        
        Site_Survey__c ss = new Site_Survey__c(
            Account__c=a.Id, 
            Survey_Date__c = System.today(),
            Status__c = 'Draft'
        );
        insert ss;
        
        Survey_Location__c location = new Survey_Location__c(
            Site_Survey__c=ss.Id, 
            Building__c = 'Building',
            Floor__c = 'Floor', 
            Location_Type__c='Washroom', 
            Location_SubType__c='Unisex',
            Name='Location'
        );
        insert location;
        
        a.Site_Survey__c = ss.Id;
        update a;
        
        Product2 product = new Product2();
        product.Name = 'test product';
        product.Allowable_Frequencies__c = 'One-Time';
        product.Family = 'Pest Control';
        product.ExternalID__c = '01-10-10-01';
        product.Item_Type__c = 'Service';
        product.Infestation_Level__c = 'General';
        product.Treatment_Type__c = 'Bed Bug';
        product.Number_of_Rooms__c = '1';
        product.IsActive = true;
        
        insert product;
        
        PricebookEntry pbe = new PricebookEntry();
        pbe.UnitPrice = 5;
        pbe.Pricebook2Id = fssetting.Standard_Pricebook_Id__c;
        pbe.ExternalID__c = 'fgds';
        pbe.Product2Id = product.Id;
        pbe.IsActive = true;
        
        insert pbe;
        
        Case theCase = new Case();
        theCase.AccountId = c.AccountId;
        theCase.ContactId = c.Id;
        theCase.Type = 'Pest Control';
        theCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Emergency').getRecordTypeId();
        theCase.Subject = 'test case';
        
        insert theCase;
    }
    
    @isTest
    static void testSelectCustomerScreenInitializationFromGlobalTab() {
        Test.startTest();
        
        EDW_SelectCustomerController.initializeSelectCustomer(null);
        
        Test.stopTest();
    }
    
    @isTest
    static void testSelectCustomerScreenInitializationFromAccount() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        
        Test.startTest();
        
        EDW_SelectCustomerController.initializeSelectCustomer(account.Id);
        
        Test.stopTest();
    }
    
    @isTest
    static void testSelectCustomerScreenInitializationFromTicket() {
        Contact contact = [SELECT Id, AccountId FROM Contact LIMIT 1];
        Case theCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        
        EDW_SelectCustomerController.initializeSelectCustomer(theCase.Id);
        
        Test.stopTest();
    }
}