force-app/main/default/objects/Account/fields/Account_at_Risk__c.field-meta.xml
<CustomField>
    <fullName>Account_at_Risk__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account at Risk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Tiers__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tiers__c</fullName>
    <description>Fields in this picklist must correspond to values in the Work Order &quot;Custom Priority&quot; formula.</description>
    <inlineHelpText>This will impact scheduling of work orders</inlineHelpText>
    <label>Customer Tiers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/ServiceAppointment/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Priority_Weights__c/Work_Order_Priority_Weights__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Work Order Priority Weights</label>
</CustomObject>

force-app/main/default/objects/Work_Order_Priority_Weights__c/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <inlineHelpText>The value of the customer tier to check against. &quot;Platinum&quot;, &quot;Gold&quot;, &quot;Silver&quot;, &quot;Bronze&quot; or empty are valid values.</inlineHelpText>
    <label>Customer Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Priority_Weights__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>The number of days between the current date and the due date of the Service Appointment. Use 0-13 for the two week window, and &quot;14+&quot; for anything greater.</inlineHelpText>
    <label>Due Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Priority_Weights__c/fields/Priority_Ranking__c.field-meta.xml
<CustomField>
    <fullName>Priority_Ranking__c</fullName>
    <inlineHelpText>The final priority value that will be stamped onto the Work Order on the Priority (Derived) field.</inlineHelpText>
    <label>Priority Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Account_at_Risk__c.field-meta.xml
<CustomField>
    <fullName>Account_at_Risk__c</fullName>
    <formula>Account.Account_at_Risk__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account at Risk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <formula>TEXT(Service_Appointment__r.Account__r.Customer_Tiers__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Service_Appointment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Due_Date__c</fullName>
    <formula>Service_Appointment__r.DueDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Appointment Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Service_Appointment_Duration__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Duration__c</fullName>
    <formula>Service_Appointment__r.Duration</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Appointment Duration (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WorkOrderPriorityFactoryTest.cls
@IsTest
public class WorkOrderPriorityFactoryTest {

    @TestSetup
    static void setupTest() {
        setupHelper();
    }

    @IsTest
    static void testWorkOrderPriorityFactory() {
        Account a = [SELECT Id, Account_at_Risk__c, Customer_Tiers__c FROM Account LIMIT 1];

        ServiceAppointment sa = [
                SELECT Id, Account__c, Duration, Account__r.Account_at_Risk__c, Account__r.Customer_Tiers__c
                FROM ServiceAppointment
                WHERE Account__c = :a.Id
                LIMIT 1
        ];

        WorkOrder wo = [
                SELECT Id, Service_Appointment__c, Customer_Tier__c, Account_at_Risk__c,
                        Service_Appointment_Duration__c, Service_Appointment_Due_Date__c ,
                        Service_Appointment__r.Account__r.Customer_Tiers__c,
                        Service_Appointment__r.Account__r.Account_at_Risk__c
                FROM WorkOrder LIMIT 1
        ];

        Test.startTest();
        wo.Service_Appointment__c = sa.Id;
        update wo;
        Test.stopTest();

        WorkOrder woAfter = [
                SELECT Service_Appointment__r.Account__r.Customer_Tiers__c
                FROM WorkOrder
                WHERE Service_Appointment__c = :sa.Id LIMIT 1
        ];

        System.assert(woAfter.Service_Appointment__r.Account__r.Customer_Tiers__c == a.Customer_Tiers__c);
    }

    // HELPER METHODS
    static void setupHelper() {
        TestUtils.createSObject(new Field_Service_Settings__c(), true);

        TestUtilsWrapperPricebook pricebookWrapper = new TestUtilsWrapperPricebook(20);
        TestUtilsWrapperAccount accountWrapper = new TestUtilsWrapperAccount(false);
        accountWrapper.account.Account_at_Risk__c = true;
        accountWrapper.doInsert();

        TestUtilsWrapperOrder orderWrapper = new TestUtilsWrapperOrder(accountWrapper, pricebookWrapper);
        TestUtilsWrapperWorkOrder workOrderWrapper = new TestUtilsWrapperWorkOrder(accountWrapper, orderWrapper);
        new TestUtilsWrapperServiceResource(accountWrapper);

        TestUtils.createSObject(new Contact(AccountId = accountWrapper.account.Id));

        List<Work_Order_Priority_Weights__c> weights = (List<Work_Order_Priority_Weights__c>) TestUtils.createSObjectList(
                new Work_Order_Priority_Weights__c(),
                10
        );

        for (Integer i = 0; i < 10; i++) {
            Work_Order_Priority_Weights__c w = weights[i];
            w.Due_Date__c = String.valueOf(i);
            w.Priority_Ranking__c = i;
        }

        insert weights;

        TestUtils.createSObject(new ServiceAppointment(
                ServiceTerritoryId = accountWrapper.serviceTerritories[0].Id,
                ParentRecordId = workOrderWrapper.workOrder.Id,
                Account__c = accountWrapper.account.Id
        ), true);
    }
}