force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recurring_SO__c.field-meta.xml
<CustomField>
    <fullName>Recurring_SO__c</fullName>
    <description>Are there recurring Order Items associated with this Account?</description>
    <formula>Recurring_SO_Count__c  &gt; 0</formula>
    <inlineHelpText>Are there recurring Order Items associated with this Account?</inlineHelpText>
    <label>Recurring SO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/classes/SearchAndSelectController.cls
/**
 * Controller for SearchAndSelect lightning component.
 * 
 * @author Ahsan Butt
 */
public class SearchAndSelectController {

    @AuraEnabled
    public static List<SearchResult> search(String searchTerm) {
        List<SearchResult> searchResults = new List<SearchResult>();
        
        List<List<sObject>> resultsList = [FIND :searchTerm IN ALL FIELDS RETURNING 
           Account (Id, Name, Parent.Name, AccPac_Account__c, Recurring_SO__c, On_Hold__c, BillingAddress, Type, Owner.Name)];
        
        if (resultsList != null && resultsList.size() == 1) {
            List<Account> accts = (List<Account>) resultsList.get(0);
            
            for (Account acct : accts) {
                SearchResult sr = new SearchResult();
                sr.acct = acct;
                sr.isSelected = false;
                searchResults.add(sr);
            }
        }
        
        return searchResults;
    }
    
    public class SearchResult {
        @AuraEnabled public Boolean isSelected;
        @AuraEnabled public Account acct;
    }
}

/*
    @AuraEnabled
    public static String getPluralLabel(String objectName) {
        List<Schema.DescribeSobjectResult> results = Schema.describeSObjects(new List<String>{objectName});

        if (results == null || results.size() != 1) return null;
        
        return results.get(0).getLabelPlural();
    }
*/

        /*
        // For non-OrderItem cases, use SOSL
        String query = composeSearchQuery(objName, searchTerm);
        
        List<List<sObject>> resultsList = search.query(query);

        if (resultsList != null && resultsList.size() == 1) {
            List<sObject> results = resultsList.get(0);

            for (sObject result : results) {
                resultIds.put(result.Id, true);
            }
        }

        */

    /*
    private static String composeSearchQuery(String objName, String searchTerm) {
        return 'FIND {' + searchTerm + '} IN ALL FIELDS RETURNING ' + objName + ' ( Id WHERE ID IN :ids )';
    }
    */