force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>NOT( Inactive__c  ||  On_Hold__c || Parent.Inactive__c || Parent.On_Hold__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <formula>ShippingStreet &amp; &quot; &quot; &amp; ShippingCity &amp; &quot; &quot; &amp;  ShippingState &amp; &quot; &quot; &amp;  ShippingPostalCode &amp; &quot; &quot; &amp;  ShippingCountry</formula>
    <label>Shipping Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/ComplexReports__c/ComplexReports__c.object-meta.xml
<CustomObject>
    <label>ComplexReport</label>
    <nameField>
        <label>ComplexReports Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ComplexReports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ComplexReports__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>Account Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/AccpacAcountNo__c.field-meta.xml
<CustomField>
    <fullName>AccpacAcountNo__c</fullName>
    <label>Accpac Acount No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Actual_Occurance__c.field-meta.xml
<CustomField>
    <fullName>Actual_Occurance__c</fullName>
    <label>Actual Occurance</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <label>Order Product Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/ExpectedOccurance__c.field-meta.xml
<CustomField>
    <fullName>ExpectedOccurance__c</fullName>
    <label>Expected Occurance</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <label>OrderNumber</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Product_Last_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Product_Last_Service_Date__c</fullName>
    <label>Product Last Service Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Number__c</fullName>
    <label>Product Number</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Season_Start__c.field-meta.xml
<CustomField>
    <fullName>Season_Start__c</fullName>
    <label>Season Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Seasonal_Order__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seasonal Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ComplexReports__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>(EffectiveDate &lt;= (Today() +  $Setup.Field_Service_Settings__c.Work_Orders_In_Advance__c )) &amp;&amp; ISPICKVAL(Status, &quot;Activated&quot;) &amp;&amp;  (EndDate &gt; Today() || ISBLANK(EndDate))</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Season_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Season_End_Date__c</fullName>
    <formula>IF(
DATE(YEAR(TODAY()),  SeasonEndMonthValue__c ,  SeasonEndDayValue__c ) &lt;=   Season_Start_Date__c ,
DATE(YEAR(TODAY())+1, SeasonEndMonthValue__c, SeasonEndDayValue__c ),
DATE(YEAR(TODAY()), SeasonEndMonthValue__c, SeasonEndDayValue__c )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Season End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Season_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Season_Start_Date__c</fullName>
    <formula>IF(  SeasonStartMonthValue__c  &gt; MONTH( TODAY() )  &amp;&amp;    SeasonEndMonthValue__c  &gt;= MONTH( TODAY() )  &amp;&amp; (SeasonEndMonthValue__c &lt; SeasonStartMonthValue__c || (SeasonEndMonthValue__c = SeasonStartMonthValue__c &amp;&amp; SeasonStartDayValue__c &gt; SeasonEndDayValue__c)
), DATE(YEAR(TODAY())-1, SeasonStartMonthValue__c,  SeasonStartDayValue__c ), DATE(YEAR(TODAY()), SeasonStartMonthValue__c, SeasonStartDayValue__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Season Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FrequencyInDays__c.field-meta.xml
<CustomField>
    <fullName>FrequencyInDays__c</fullName>
    <formula>CASE(Frequency__c,
&apos;One-Time&apos;, 0, 
&apos;Daily&apos;, 1,
&apos;6X Per Week&apos;, 2,
&apos;5X Per Week&apos;, 3,
&apos;4X Per Week&apos;, 4,
&apos;3X Per Week&apos;, 5,
&apos;2X Per Week&apos;, 6,
&apos;Weekly&apos;, 7, 
&apos;Fixed Weekly&apos;, 7,
&apos;14 Days&apos;, 14,
&apos;Twice Monthly&apos;, 15, 
&apos;28 Days&apos;, 28,
&apos;Monthly&apos;, 30, 
&apos;42 Days&apos;, 42,
&apos;56 Days&apos;, 56,
&apos;Bi-Monthly&apos;, 60,
&apos;84 Days&apos;, 84,
&apos;Quarterly&apos;, 90,
&apos;112 Days&apos;, 112,
&apos;120 Days&apos;, 120,
&apos;168 Days&apos;, 168,
&apos;Semi-Annually&apos;, 182,
&apos;2X Per Year&apos;, 182, 
&apos;182 Days&apos;, 182,
&apos;Annually&apos;, 365, 
0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FrequencyInDays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>IF(PricebookEntry.Product2.Never_Generate_Work_Order__c, FALSE, IF(PricebookEntry.Product2.Heavy_Equipment__c, 
Inventory_Allocated__c &amp;&amp; NOT( ISBLANK(Serial_Number__c) ), 
Order.Inventory_Allocated__c || Order.Emergency__c || Inventory_Allocated__c))</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>This field is System Generated during the nightly Work Order Generation batch job. Changing this would have implications on Work Order Generation Logic</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Family)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>(Last_Batch_Updated_Date__c = TODAY() || Last_Batch_Updated_Date__c = TODAY() + (-1)) &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Completed&apos; &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Cannot Complete&apos; &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Dispatched&apos;</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of Work Order, whether it is a delivery or a work order for a particular line of business</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Work Order</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>NoWork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>System field that is filled in by the nightly batch job generating Work Orders, modifying this field would affect the Service Schedule</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ComplexReports.cls
global class ComplexReports implements Database.Batchable<sObject>, Database.Stateful {

     
    WorkOrderLineItem[] woliList = new list<WorkOrderLineItem>(); 
	Datetime myDate = Datetime.newInstance(2018, 01, 1, 12, 00, 00);
	Datetime upsertDate = Datetime.newInstance(2019, 02, 15, 12, 00, 00);
    Datetime sdate = Datetime.newInstance(2018, 01, 1, 12, 00, 00);
    date goUnactive=system.today();
	workorder[] wo= new list<workorder>();
	orderitem [] oliList= new list<orderitem>();
	integer int1=0;
    integer unactivedays=0;
	ComplexReports__c[] crlist = new list<ComplexReports__c>();
	integer No_Days=0;
    integer activedays=0;
	list <string> wono= new list<string>();
	Map<String, Integer> wonoUnique= new Map<string, Integer>();
    list<workorderlineitem> woli= new list<workorderlineitem>();
    list<orderitemhistory> oli_his= new list<orderitemhistory>();
    list<orderitemhistory> oli_his_active= new list<orderitemhistory>();
	Boolean IsSeasonal=false;
   	integer int0=0;
    integer j=0;
    integer oli_hisSize=0;
    string oldvalue;
    string newvalue;
    datetime hiscreateddate;
    list<date> sys= new list<date>();
    list<datetime> createdat= new list<datetime>();
    string hisvalue;
    orderitemhistory his= new orderitemhistory();
    list<datetime> seasonstart=new list<datetime>();
    list<datetime> seasonend= new list<datetime>();
    list<datetime> Upsertdates= new list<datetime>();
    
 // Batch job start method
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator (
           'select id from orderitem  where ( Active__c=true AND orderitem.order.isValid__c=TRUE AND orderitem.Order.Account.isValid__c=TRUE AND orderitem.order.Emergency__c=FALSE  ) '
            ); 
   }
   
    global void execute(Database.BatchableContext bc, List<orderitem> scope){ 
        list<Id> orderitems = new list<Id>();
        
       for(Orderitem oi : (List<Orderitem>) scope){
            orderitems.add(oi.Id);
        }     
        AnalyseOrderItem(orderitems);
    }
    
    global void AnalyseOrderItem(list<Id> orderitems) {
 
        //For loop for orderitems   
     
 	for(orderitem oli: [select orderitem.order.ordernumber, orderitem.order.account.AccPac_Account__c, orderitem.order.account.name, Product_name__c, 
                    frequency__c, Line_of_Business__c, Last_Automation_created_date__c,frequencyindays__c, createddate, orderitem.order.Season_Start_Date__c, 
                    orderitem.order.effectivedate, orderitem.order.isvalid__c, orderitem.order.account.shipping_Address__c , orderitem.order.Season_End_Date__c, lastmodifieddate, id, OrderItemNumber 
                    from orderitem  where (  orderitem.order.isValid__c=TRUE AND 
                    orderitem.Order.Account.isValid__c=TRUE AND orderitem.order.Emergency__c=FALSE AND id IN : orderitems) ] ){
   //system.debug('oli.createddate'+oli.createddate);
      	    woli=  [select id, workorderlineitem.workorder.status, createddate, 
                  workorderlineitem.workorder.createddate, workorderlineitem.workorder.ServiceTerritory.address, workorderlineitem.workorder.type__c, 
    	  		  workorderlineitem.workorder.workordernumber, workorderlineitem.workorder.Completed_Date__c from workorderlineitem
                  where((workorderlineitem.workorder.type__c='service' or workorderlineitem.workorder.type__c='delivery'
                  or workorderlineitem.workorder.type__c='installation')AND (workorderlineitem.workorder.status!='new'
                  or workorderlineitem.workorder.status!='Cannot Complete' )and workorderlineitem.order_product__c=:oli.id) ] ;
    // History or orderproduct                    
            oli_his=[select id, CreatedDate, Field, OldValue, NewValue FROM OrderItemHistory where (field='frequency__c'  and orderitemid=:oli.id) ];
            oli_his_active=[select id, CreatedDate, Field, OldValue, NewValue FROM OrderItemHistory where (field='active__c'  and orderitemid=:oli.id) ];            

   // system.debug('oli' + oli.id + oli.order.isvalid__c);
           
         //system.debug('oli   ' + oli.id+'  ' + oli.order.isvalid__c);
    if(woli.size()==0){ No_days=0;}
    if(woli.size() >0){
    system.debug('oli' + oli.id + oli.order.isvalid__c);
       
  // For Loop on workorderline items to put them in a list and sort
         
    for(workorderlineitem wol : woli ){
         
        if(wol.workorder.type__c=='installation' && wol.workorder.Completed_Date__c!=null)
        {sdate= oli.CreatedDate;
        // system.debug('oli.createddate'+oli.createddate);
        }
         else{
             sdate=oli.CreatedDate;
         }
       if(wol.workorder.status !='new' && wol.workorder.status !='Cannot Complete' && wol.workorder.status !='Dispatched'){
        //system.debug('workorder number' + woli.workorder.id);
        wono.add(wol.workorder.workordernumber);
          //  system.debug('Status = ' + woli.workorder.status);
    }
   }
    
    wono.sort();
        
     }//else {sdate=oli.createddate;}
  // Nested for loop on workorderline items to get the number of Actual occurances of a workorder
    for(string key :wono){
        
        if(!wonoUnique.containsKey(key)){
            wonoUnique.put(key,0);
            
        }
        Integer countInt=wonoUnique.get(key)+1;
        wonoUnique.put(key,countInt);
       } 
  sdate=oli.CreatedDate;
 if(oli.order.season_start_date__c !=null){goUnactive=date.valueof(oli.order.season_end_date__c);}
  // check for the active deactive history only one time
 if(oli_his_active.size()>0){ for(orderitemhistory ah:oli_his_active){if(ah.OldValue==false){goUnactive=date.valueof(ah.CreatedDate);}if (ah.oldvalue==true ) {unactivedays=(Date.ValueOf(ah.createddate)).daysBetween((goUnactive));}}}  
  
    oli_hisSize=oli_his.size();
 //To caluculate change of frequency from the history
                        
if(oli_hisSize>0){
    j=2;
    
   for(orderitemhistory hi: oli_his){
   oldvalue= (string)hi.OldValue;
   newvalue=(string)hi.NewValue;
   hiscreateddate= hi.CreatedDate ;
   system.debug('hiscreateddate = ' +hiscreateddate);}
}
        else{j=1;}                    
                 

         for(integer i=0; i < j; i++){
             
       // system.debug('New Value ' + his.newvalue +' Oldvalue '+ his.oldvalue +'  createddate ='+ his.createddate);
    //**************caclulate for No_days after freq change**************
   // calculate the Expected Occurance from the created date of Orderitems (to be modified)
   // Check for Seasonal Order
  
    if(oli_hisSize==0){sys.add(system.today());
    createdat.add(sdate);
    hisvalue=oli.Frequency__c;
    seasonstart.add(oli.order.season_start_date__c);
    seasonend.add(oli.order.season_end_date__c);
    upsertdates.add(upsertdate);}
             
   if(oli_hisSize>0 && i==0){
   createdat.add(sdate);
   sys.add(Date.valueof(hiscreateddate));
   hisvalue=OldValue; 
   seasonstart.add(oli.order.season_start_date__c);
   seasonend.add(hiscreateddate);
   upsertdates.add(upsertdate);} 

    else if(oli_hisSize>0 && i==1){ 
    createdat.add(hiscreateddate); 
    sys.add(system.today());
    hisvalue=NewValue;   
    seasonstart.add(hiscreateddate);
    seasonend.add(oli.order.season_end_date__c);
    upsertdates.add(hiscreateddate);}
   
      if(oli.order.season_start_date__c !=null){
             IsSeasonal=True;
             // system.debug('season start date ' + oli.order.season_start_date__c);
             // system.debug('season end date ' + oli.order.season_end_date__c);
   //if season_start_date and season_end_date is less than today.date  
             if(oli.order.season_start_date__c <system.today() && oli.order.season_end_date__c<system.today()){
             No_Days=(Date.ValueOf(seasonstart[i])).daysBetween(Date.ValueOf(seasonend[i]));
             //system.debug('No_days 1' +No_days);
                }
             
 //if season_start_Date is less than today and season end date is greater than today
              if(oli.order.season_start_date__c <system.today() && oli.order.season_end_date__c>system.today()){
                  integer No_Days2=0;
             // if oli.createddate is greater than season start date
                  if(sdate>oli.order.season_start_date__c){
                 No_Days2=(Date.ValueOf(createdat[i])).daysBetween(sys[i]);
               // System.debug('No_days2   ' + no_days2);
                  }
                  else if (sdate<oli.order.season_start_date__c){
                       No_Days2=(Date.ValueOf(seasonstart[i])).daysBetween(sys[i]);
                  
                  }
                  
                   if(sdate<oli.order.season_end_date__c.addyears(-1) ){
                      if(oli.order.season_end_date__c.addyears(-1)>system.today()){
                          No_Days=(Date.ValueOf(createdat[i])).daysBetween(sys[i])+ No_days2;
                      }
                      else if(oli.order.season_end_date__c.addyears(-1)<system.today()){
                          No_Days=(Date.ValueOf(createdat[i])).daysBetween(Date.ValueOf(seasonend[i].addyears(-1))) +No_days2;
                      }
                      
                  }
                  else if(sdate>oli.order.season_end_date__c.addyears(-1) )
                  {No_Days=No_days2;
                
              } }
 
               
          // season start date is greater than today
              if(oli.order.season_start_date__c >system.today()){         
                // end date year is equal to this year(No activity previous year)
                  if (oli.order.season_end_date__c.year()==system.today().year()){
                      No_days=0;   
                  }
               else if (oli.order.season_end_date__c.year()>system.today().year()){
                   if(oli.order.season_end_date__c.addyears(-1)<=system.today()){
                       No_Days=(Date.ValueOf(upsertdates[i])).daysBetween(Date.ValueOf(seasonend[i]));    }
                   else if(oli.order.season_end_date__c.addyears(-1)>system.today()){
                        No_Days=(Date.ValueOf(upsertdates[i])).daysBetween(Date.ValueOf(sys[i].addyears(1))); 
                   }
                   else if(oli.order.season_start_date__c.year()>system.today().year()){
                       No_Days=(Date.ValueOf(seasonstart[i])).daysBetween(Date.ValueOf(seasonend[i]));    
                   }
               }
             }
         }
                
         else{
             No_Days=(Date.ValueOf(createdat[i])).daysBetween(sys[i]);
            system.debug('oli.createddate  '+sdate);
           }
 //  system.debug('No of days 4 '+ No_Days);
   no_days=no_days-Unactivedays;    
                     
  //  system.debug('frequency =' + hisvalue);
    if(his.newvalue=='One-Time'){
        int1=0;
      //  system.debug('Expected Occurance= '+ int1 );
    }
    else  if(hisvalue=='Weekly'){
       int1=No_Days/7;
       //system.debug('Expected Occurance= '+ int1 );
    }
    else  if(hisvalue=='Fixed Weekly'){
       int1=No_Days/7;
       //system.debug('Expected Occurance= '+ int1 );
    }
    else  if(hisvalue=='Twice Monthly' ){
        int1=No_Days/15;
        //system.debug('Expected Occurance= '+ int1 );
    } else  if(hisvalue=='14 Days' ){
        int1=No_Days/14;
       // system.debug('Expected Occurance= '+ int1 );
    }
             else  if(hisvalue=='28 Days'){
      int1=No_Days/28;
      // system.debug('Expected Occurance= '+ int1 );
    }
             else  if(hisvalue=='120 Days'){
      int1=No_Days/120;
      // system.debug('Expected Occurance= '+ int1 );
    } else  if(hisvalue=='Semi-Annually'){
      int1=No_Days/182;
      // system.debug('Expected Occurance= '+ int1 );
    }
             else  if(hisvalue=='Quarterly'){
      int1=No_Days/90;
      // system.debug('Expected Occurance= '+ int1 );
    }
             else  if(hisvalue=='Annually'){
      int1=No_Days/365;
      // system.debug('Expected Occurance= '+ int1 );
    }
    else  if(hisvalue=='Monthly'){
      int1=No_Days/30;
      // system.debug('Expected Occurance= '+ int1 );
    }
   
    
    else  if(hisvalue=='Bi-Monthly' ){
    
   		 int1=No_Days/60;
      //system.debug('Expected Occurance= '+ int1 );
    }
    int0+=int1;
    int1=0;
           
    
    }
    //Simple No_days calculation
      integer size=wonounique.size();
    
     ComplexReports__c cr= new ComplexReports__c(AccountName__c=oli.order.account.name,
                                                 AccpacAcountNo__c= oli.order.account.AccPac_Account__c, 
                                                 ExpectedOccurance__c=int0,
                                                 OrderNumber__c=oli.order.ordernumber, 
                                                 Actual_Occurance__c=size,
                                                 frequency__c=oli.frequency__c,
                                                 Date_Created__c= oli.createddate,
                                                 Product_Name__c=oli.Product_Name__c,
                                                 Product_Number__c=oli.OrderItemNumber,
                                                 Product_Id__c=oli.Id,
                                                 Product_Last_Service_Date__c=oli.Last_Automation_Created_Date__c,
                                                 Line_of_business__c=oli.Line_of_Business__c,
                                                 Seasonal_order__c= Isseasonal,
                                                 Season_start__c= oli.order.season_start_date__c,
                                                 Season_end__c= oli.order.season_end_date__c,
                                                 Shipping_Address__c=oli.order.account.shipping_Address__c 
                                                  );
 	 crList.add(cr);   
    //system.debug(cr); */
    // system.debug('Actual Occurances = ' + size);
    wonoUnique.clear();
    wono.clear();
    IsSeasonal=false;
    orderitems.clear();
    Int0=0; 
    sys.clear();
    createdat.clear();
    seasonstart.clear();
    seasonend.clear();
    upsertdates.clear();
    oli_his_active.clear();
    unactivedays=0;
    oli_his.clear();
    no_days=0;
    
    
   }//FirstForLoop ends
  
	insert crList; 
   crList.clear();      
        
 }  // Method AnalyseOrderItems End
        
    global void finish(Database.BatchableContext bc){
     
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        //system.debug('AsyncApexJog' + job);
       
    }
}