force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Multi_Res__c.field-meta.xml
<CustomField>
    <fullName>Is_Multi_Res__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Multi-Res</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PO_Required_on_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>PO_Required_on_Line_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Required on Line Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Account_Ship_To_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Ship_To_Record_Type_Id__c</fullName>
    <label>Account Ship To Record Type Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Ticket_Closed_Status__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Closed_Status__c</fullName>
    <label>Ticket Closed Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Ticket_Emergency_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Emergency_Record_Type__c</fullName>
    <label>Ticket Emergency Record Type</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Number_of_Rooms__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Rooms__c</fullName>
    <label>Number of Rooms</label>
    <summaryForeignKey>Survey_Location__c.Site_Survey__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Survey_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EDW_InputLookup.cls
/**
* Name: EDW_InputLookup
* Author: PwC
* Date Created: January 7, 2019
* Purpose: To act as the controller for the EDW_InputLookup lightning component
*/ 
public with sharing class EDW_InputLookup {
    static Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
    private static final Integer LIMIT_SIZE = 10;
    private static final String QUERY_SEPARATOR = ',';
    
    /**
     * Finds and returns the record selected
     *
     * @param id  the Id of the record to be returned
     * @param sObjectType  the API name of the object to be queried
     */
    @AuraEnabled
    public static SObject loadDefault(String id, String sObjectType) {
        //selecting the record
        try {
            String query = 'SELECT Id, ';
            
            if (sObjectType == 'Account') {
                query += 'Name, AccPac_Account__c, Site_Survey__r.Name, Site_Survey__c, PO_Required_on_Line_Item__c, Is_Multi_Res__c FROM {1} WHERE Id={0}';
            } else if (sObjectType == 'Contact') {
                //sObjectType = 'AccountContactRelation';
                //query += 'Contact.Name FROM {1} WHERE Id={0}';
            	query += 'Name FROM {1} WHERE Id={0}';
			} else if (sObjectType == 'Case') {
                query += 'CaseNumber, Account.Is_Multi_Res__c, Status FROM {1} WHERE Id={0}';
            } else if (sObjectType == 'Survey_Location__c') {
                return Database.query(QueryGenerator.querySurveyLocations('Id = :id'));
            }
            
            return Database.query(String.format(query, new List<String> { '\'' + id + '\'', sObjectType }));
        } catch (Exception e) {
            System.debug(e);
        }     
        return null;
    }
    
    /**
     * Searches for all records on the specified object that match a search criteria
     *
     * @param filterCriteria  the search text used to filter results
     * @param sObjectType  the API name of the object to be queried
     * @param filterId  the Id of a relationship to further filter results
     * @param numberOfRoomsFilter  a filter on Survey_Location__c for Number of Rooms
     */
    @AuraEnabled
    public static List<SObject> searchLookup(String filterCriteria, String sObjectType, String filterId, String numberOfRoomsFilter) {
        //listing out records to select
        String query = 'SELECT Id, ';
        
        if (sObjectType == 'Account') {
            query += 'Name FROM ' + sObjectType + ' WHERE Name LIKE \'' + filterCriteria + '%\' AND RecordTypeId=\'' + dataSets.Account_Ship_To_Record_Type_Id__c + '\'';
        } else if (sObjectType == 'Contact') {
            //query += 'Contact.Name, ContactId FROM AccountContactRelation WHERE Contact.Name LIKE \'' + s + '%\' AND AccountId=\'' + filterId + '\'';
        	query += 'Name FROM ' + sObjectType + ' WHERE Name LIKE \'' + filterCriteria + '%\' AND AccountId=\'' + filterId + '\'';
        } else if (sObjectType == 'Case') {
            query += 'CaseNumber FROM ' + sObjectType + ' WHERE CaseNumber LIKE \'' + filterCriteria + '%\' AND AccountId=\'' + filterId + '\' AND RecordTypeId=\'' + dataSets.Ticket_Emergency_Record_Type__c + '\' AND Status != \'' + dataSets.Ticket_Closed_Status__c + '\'';
        } else if (sObjectType == 'Survey_Location__c') {
            query += 'Name FROM ' + sObjectType + ' WHERE Name LIKE \'%' + filterCriteria + '%\' AND Site_Survey__c=\'' + filterId + '\'';
                
            //if (!String.isBlank(numberOfRoomsFilter)) {
            //    query += ' AND Number_of_Rooms__c =\'' + numberOfRoomsFilter + '\'';
            //}
        }
        
        query += ' LIMIT ' + LIMIT_SIZE;
        
        System.debug(query);
        
        return Database.query(query);
    }
}