force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Chemical_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Chemical_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chemical Operating Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Accounts (Chemical Operating Hours)</relationshipLabel>
    <relationshipName>Accounts_Chemical</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Tiers__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tiers__c</fullName>
    <description>Fields in this picklist must correspond to values in the Work Order &quot;Custom Priority&quot; formula.</description>
    <inlineHelpText>This will impact scheduling of work orders</inlineHelpText>
    <label>Customer Tiers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hygiene_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Hygiene_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hygiene Operating Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pest_Control_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Pest_Control_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pest Control Operating Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Accounts (Pest Control Operating Hours)</relationshipLabel>
    <relationshipName>Accounts_PestControl</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <formula>CASESAFEID(Order.AccountId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Order Item cannot have the custom Order field set as it&apos;s Inactive.</errorMessage>
        <filterItems>
            <field>$Source.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Active Order Products without PO Number</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Parent_Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Plan__c.field-meta.xml
<CustomField>
    <fullName>Service_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Service Plan record that services this Order Product.</description>
    <inlineHelpText>Lookup to Service Plan record that services this Order Product.</inlineHelpText>
    <label>Service Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Plan__c.Frequency__c</field>
            <operation>equals</operation>
            <valueField>$Source.Frequency__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Plan__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Plan__c/Service_Plan__c.object-meta.xml
<CustomObject>
    <description>Object to summarize recurring Order Products serviced by a Technician.</description>
    <label>Service Plan</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Service Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceResource/fields/Travel_Factor__c.field-meta.xml
<CustomField>
    <fullName>Travel_Factor__c</fullName>
    <defaultValue>0.20</defaultValue>
    <description>Percentage of time this Service Resource spends on travel. Defaults to 20%.</description>
    <inlineHelpText>Percentage of time this Service Resource spends on travel. Defaults to 20%.</inlineHelpText>
    <label>Travel Factor</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technician_Utilization_Setting__mdt/Technician_Utilization_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for applying colour to the tech capacity calendar based on utilization</description>
    <label>Technician Utilization Setting</label>
    <pluralLabel>Technician Utilization Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Technician_Utilization_Setting__mdt/fields/Maximum_Percent__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Percent__c</fullName>
    <description>Maximum utilization percent for this colour</description>
    <label>Maximum Percent</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Technician_Utilization_Setting__mdt/fields/Minimum_Percent__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Percent__c</fullName>
    <description>Minimum utilization percent for this colour</description>
    <label>Minimum Percent</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/TechCapacityWrappers.cls
/**
 * @FileName: TechCapacityWrappers
 * @Description: Wrapper classes for TechCapacityCtrl
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       10/24/2019      Created
 *-----------------------------------------------------------  
 */
public inherited sharing class TechCapacityWrappers {

    public class TechWrapper {
        public ServiceResource tech;
        public String shift;
        public Integer travelTime;
        public List<String> skills;
        public List<Technician_Utilization_Setting__mdt> utilizations;
        public Integer averageShift;

        public TechWrapper(ServiceResource tech) {
            if(tech.Travel_Factor__c == null) tech.Travel_Factor__c = 0;

            this.tech = tech;
            setShift(tech);
            setSkills(tech);
            setUtilizations();
            getAverageShift(tech);
        }

        private void setShift(ServiceResource tech) {
            if(!tech.ServiceTerritories.isEmpty() && String.isNotBlank(tech.ServiceTerritories[0].OperatingHoursId)) {
                this.shift = tech.ServiceTerritories[0].OperatingHours.Name;
            } else {
                this.shift = 'No Primary Service Territory Found';
            }
        }

        private void setSkills(ServiceResource tech) {
            List<String> skillList = new List<String>();

            for(ServiceResourceSkill skill : tech.ServiceResourceSkills) {
                skillList.add(skill.Skill.MasterLabel + ' (' + skill.SkillLevel + ')');
            }

            this.skills = skillList;
        }

        private void setUtilizations() {
            List<Technician_Utilization_Setting__mdt> utilizations = [
                    SELECT Id, MasterLabel, DeveloperName, Minimum_Percent__c, Maximum_Percent__c
                    FROM Technician_Utilization_Setting__mdt
                    WHERE Minimum_Percent__c != NULL
                    ORDER BY Maximum_Percent__c DESC
            ];

            for (Technician_Utilization_Setting__mdt utilization : utilizations) {
                if (utilization.Maximum_Percent__c == null) {
                    utilization.MasterLabel += ' (+' + (utilization.Minimum_Percent__c - 1).setScale(0, RoundingMode.HALF_UP) + '%)';
                } else if (utilization.DeveloperName != 'No_Utilization') {
                    utilization.MasterLabel += ' (' + utilization.Minimum_Percent__c.setScale(0, RoundingMode.HALF_UP) + '% - ' + utilization.Maximum_Percent__c.setScale(0, RoundingMode.HALF_UP) + '%)';
                }
            }

            this.utilizations = utilizations;
        }

        private void getAverageShift(ServiceResource tech) {
            this.averageShift = 0;
            this.travelTime = 0;

            List<ServiceTerritoryMember> serviceTerritories = tech.ServiceTerritories;

            if(serviceTerritories.isEmpty()) return;

            OperatingHours hours = [
                    SELECT Id,
                    (SELECT Id, DayOfWeek, StartTime, EndTime
                    FROM TimeSlots)
                    FROM OperatingHours
                    WHERE Id = :tech.ServiceTerritories[0].OperatingHoursId
            ];

            if(hours.TimeSlots.isEmpty()) return;

            Set<Integer> daysOfWeek = new Set<Integer>();
            Long totalTime = 0;
            Time dayBreakPoint = Time.newInstance(5,0,0,0);

            for(TimeSlot ts : hours.TimeSlots) {
                Datetime st = Datetime.newInstanceGmt(Date.today(), ts.StartTime);
                Datetime et;

                if(ts.EndTime == Time.newInstance(0,0,0,0)) {
                    et = Datetime.newInstanceGmt(Date.today(), ts.EndTime).addDays(1);
                } else {
                    et = Datetime.newInstanceGmt(Date.today(), ts.EndTime);
                }

                Integer dayInt = ServicePlanConstants.DAY_OF_WEEK_INTEGERS.get(ts.DayOfWeek);

                if(ts.StartTime < dayBreakPoint && ts.EndTime > dayBreakPoint) {
                    daysOfWeek.add(dayInt - 1);
                    daysOfWeek.add(dayInt);
                } else if(ts.StartTime < dayBreakPoint && ts.EndTime < dayBreakPoint) {
                    daysOfWeek.add(dayInt - 1);
                } else {
                    daysOfWeek.add(dayInt);
                }

                Long shiftLength = et.getTime() - st.getTime();

                if(shiftLength != 0) {
                    totalTime += shiftLength / 60000;
                }
            }

            if(!daysOfWeek.isEmpty()) {
                this.averageShift = Integer.valueOf(totalTime) / daysOfWeek.size();
                this.travelTime = Integer.valueOf((averageShift * (tech.Travel_Factor__c / 100)).setScale(0, RoundingMode.HALF_UP));
            }
        }
    }

    public class ServicePlanCriteria {
        public TechWrapper technician;
        public List<CalendarDay> days;
    }

    public class SiteSurveyWrapper {
        public Map<Id,Account> accountMap;
        public Map<Id,Site_Survey__c> siteSurveyMap;

        public SiteSurveyWrapper(List<Service_Plan__c> sps) {
            getAccountMap(sps);
            getSiteSurveyMap();
        }

        private void getAccountMap(List<Service_Plan__c> sps) {
            Set<Id> accountIds = new Set<Id>();

            for(Service_Plan__c sp : sps) {
                accountIds.addAll(getAccountIds(sp));
            }

            accountMap = new Map<Id,Account>([
                    SELECT Id, Name, Customer_Tiers__c, Site_Survey__c, AccPac_Account__c, ShippingStreet, ShippingCity,
                            ShippingPostalCode, OperatingHours.Name, Hygiene_Operating_Hours__r.Name,
                            Chemical_Operating_Hours__r.Name, Pest_Control_Operating_Hours__r.Name
                    FROM Account
                    WHERE Id IN :accountIds
                    ORDER BY ShippingPostalCode ASC
            ]);
        }

        /*
         * @Name        getAccountIds
         * @Description Get all Account Ids associated to the specified Service Plan order items
         * @Author      Graeme Ward
         * @Params      sp: Service Plan record
         * @Return      Set<Id>: Set of Account ids
         */
        private Set<Id> getAccountIds(Service_Plan__c sp) {
            Set<Id> accountIds = new Set<Id>();

            for(OrderItem oi : sp.Order_Products__r) {
                accountIds.add(oi.Account_Id__c);
            }

            return accountIds;
        }

        private void getSiteSurveyMap() {
            Set<Id> siteSurveyIds = ApexUtils.getIdsFromField(
                    (List<SObject>) accountMap.values(),
                    'Site_Survey__c'
            );

            siteSurveyMap = ServicePlanUtils.getSiteSurveyMap(siteSurveyIds);
        }
    }

    public class CalendarDay {
        public String d;
        public Integer num;
        public String dayName;
        public String month;
        public Integer calls;
        public Double assets;
        public Decimal minutes;
        public Decimal travelTime;
        public Decimal rR;
        public String utilization;
        public String pastDay;
        public Map<Id,AccountWrapper> accounts;

        public CalendarDay() {
            this.calls = 0;
            this.assets = 0;
            this.minutes = 0;
            this.travelTime = 0;
            this.rR = 0;
        }
    }

    public class AccountWrapper {
        public Account acc;
        public String operatingHours;
        public String operatingHoursId;
        public Site_Survey__c survey;
        public Decimal duration;
        public Decimal adjustments;
        public Double assetCount;
        public Map<String,Double> assetCountByFamily;
        public Map<String,ServicePlanAssetWrapper> assetMap;
        public List<ServicePlanAssetWrapper> assets;
        public Set<Id> productIds;

        public AccountWrapper(Account a, Site_Survey__c ss) {
            this.acc = a;
            this.survey = ss;
            this.duration = 0;
            this.adjustments = 0;
            this.assetCount = 0;
            this.assetCountByFamily = new Map<String,Double>();
            this.assetMap = new Map<String,ServicePlanAssetWrapper>();
            this.assets = new List<ServicePlanAssetWrapper>();
            this.productIds = new Set<Id>();
        }
    }
}