force-app/main/default/objects/Account/fields/AccPac_Account__c.field-meta.xml
<CustomField>
    <fullName>AccPac_Account__c</fullName>
    <externalId>true</externalId>
    <label>AccPac Account #</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Multi_Res__c.field-meta.xml
<CustomField>
    <fullName>Is_Multi_Res__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Multi-Res</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pest_Control_OperatingHoursId__c.field-meta.xml
<CustomField>
    <fullName>Pest_Control_OperatingHoursId__c</fullName>
    <formula>BLANKVALUE( Pest_Control_Operating_Hours__c , OperatingHoursId )</formula>
    <label>Pest Control OperatingHoursId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PO_Required_for_Orders__c.field-meta.xml
<CustomField>
    <fullName>PO_Required_for_Orders__c</fullName>
    <label>PO Required for Orders</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PO Required Before</fullName>
            </value>
            <value>
                <fullName>PO Required After</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PO_Required_on_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>PO_Required_on_Line_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Required on Line Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Community.recordType-meta.xml
<RecordType>
    <fullName>Community</fullName>
    <active>true</active>
    <businessProcess>General Inquiry</businessProcess>
    <description>Ticket record type specific to customer community.</description>
    <label>Community</label>
</RecordType>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EDW_SelectCustomerController.cls
public with sharing class EDW_SelectCustomerController {
    
    @AuraEnabled
    public static EDW_ViewModels.MainViewModel initializeSelectCustomer(String recordId) {
        EDW_ViewModels.MainViewModel initModel = new EDW_ViewModels.MainViewModel();
        
        initModel.isCommunity = EDW_UtilityClass.isCommunity();
        
        if (!initModel.isCommunity) {
            if (String.isBlank(recordId)) {
                return initModel;
            } else if (recordId.left(3) == EDW_UtilityClass.ACCOUNT_PREFIX) {
                initModel.account = [SELECT Id, Name, Site_Survey__c, Site_Survey__r.Name, AccPac_Account__c, PO_Required_for_Orders__c, PO_Required_on_Line_Item__c, Is_Multi_Res__c, OperatingHoursId, Pest_Control_OperatingHoursId__c FROM Account WHERE Id = :recordId];
            } else if (recordId.left(3) == EDW_UtilityClass.CASE_PREFIX) {
                initModel.ticket = [SELECT Id, CaseNumber, AccountId, Account.Name, Account.Site_Survey__c, Account.Site_Survey__r.Name, Account.PO_Required_on_Line_Item__c, Account.AccPac_Account__c, Account.PO_Required_for_Orders__c, Account.OperatingHoursId, Account.Pest_Control_OperatingHoursId__c, Contact.FirstName, Contact.LastName, ContactId, Account.Is_Multi_Res__c, Status, Order__c FROM Case WHERE Id = :recordId];
                initModel.account = new Account(Id=initModel.ticket.AccountId, Name=initModel.ticket.Account.Name, Site_Survey__c=initModel.ticket.Account.Site_Survey__c, PO_Required_for_Orders__c=initModel.ticket.Account.PO_Required_for_Orders__c, PO_Required_on_Line_Item__c=initModel.ticket.Account.PO_Required_on_Line_Item__c, AccPac_Account__c=initModel.ticket.Account.AccPac_Account__c, Is_Multi_Res__c=initModel.ticket.Account.Is_Multi_Res__c);
                initModel.contact = initModel.ticket.ContactId == null 
                    ? null 
                    : new Contact(Id=initModel.ticket.ContactId, FirstName=initModel.ticket.Contact.FirstName, LastName=initModel.ticket.Contact.LastName);
            }
            
            initModel.recordId = recordId;
        } else {
            //TODO configure how you want to handle initialization of EDW_SelectCustomerComponent in a community
        }
        return initModel;
    }
}