force-app/main/default/objects/Account/fields/Billing_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Suite_Number__c</fullName>
    <label>Billing Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Frequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Q2 - Quarterly, Invoiced Feb, May, Aug, Nov</fullName>
            </value>
            <value>
                <fullName>M - Monthly</fullName>
                <default>true</default>
                <label>M - Monthly</label>
            </value>
            <value>
                <fullName>Q1 - Quarterly, Invoiced Jan, Apr, Jul, Oct</fullName>
            </value>
            <value>
                <fullName>WN - When Needed</fullName>
            </value>
            <value>
                <fullName>Q3 - Quarterly, Invoiced Mar, Jun, Sep, Dec</fullName>
            </value>
            <value>
                <fullName>M4O - Seasonal Apr-Oct</fullName>
            </value>
            <value>
                <fullName>A12 - Annual - December</fullName>
            </value>
            <value>
                <fullName>A11 - Annual - November</fullName>
            </value>
            <value>
                <fullName>A10 - Annual - October</fullName>
            </value>
            <value>
                <fullName>M93 - Seasonal Sep-Mar</fullName>
            </value>
            <value>
                <fullName>M94 - Seasonal Sep-Apr</fullName>
            </value>
            <value>
                <fullName>M5O - Seasonal May-Oct</fullName>
            </value>
            <value>
                <fullName>SA1 - Semi-Annually, Jan/Jul</fullName>
            </value>
            <value>
                <fullName>A05 - Annual - May</fullName>
            </value>
            <value>
                <fullName>M4D - Seasonal Apr-Dec</fullName>
            </value>
            <value>
                <fullName>A06 - Annual - June</fullName>
            </value>
            <value>
                <fullName>M59 - Seasonal May-Sep</fullName>
            </value>
            <value>
                <fullName>M5N - Seasonal May-Nov</fullName>
            </value>
            <value>
                <fullName>A04 - Annual - April</fullName>
            </value>
            <value>
                <fullName>B1 - Bi-Monthly Odd Months</fullName>
            </value>
            <value>
                <fullName>M68 - Seasonal Jun-Aug</fullName>
            </value>
            <value>
                <fullName>M4N - Seasonal Apr-Nov</fullName>
            </value>
            <value>
                <fullName>M96 - Seasonal Sep-Jun</fullName>
            </value>
            <value>
                <fullName>M12 - Seasonal Jan-Feb</fullName>
            </value>
            <value>
                <fullName>MN4 - Seasonal Nov-Apr</fullName>
            </value>
            <value>
                <fullName>B2 - Bi-Monthly Even Months</fullName>
            </value>
            <value>
                <fullName>M55 - Seasonal May</fullName>
            </value>
            <value>
                <fullName>M44 - Seasonal April</fullName>
            </value>
            <value>
                <fullName>MN3 - Seasonal Nov-Mar</fullName>
            </value>
            <value>
                <fullName>MO4 - Seasonal Oct-Apr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SalesPricebookId__c.field-meta.xml
<CustomField>
    <fullName>SalesPricebookId__c</fullName>
    <formula>BLANKVALUE( Sales_Pricebook__c,  $Setup.Field_Service_Settings__c.Default_Opportunity_Price_Book_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Pricebook Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ServiceTerritory.ParentTerritoryId</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>ServiceTerritory.IsActive</field>
            <operation>notEqual</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ServicePricebookId__c.field-meta.xml
<CustomField>
    <fullName>ServicePricebookId__c</fullName>
    <formula>BLANKVALUE(  Service_Pricebook__c ,  $Setup.Field_Service_Settings__c.Default_Order_Price_Book_ID__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Pricebook Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Suite_Number__c</fullName>
    <label>Shipping Suite Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case_Created__c.field-meta.xml
<CustomField>
    <fullName>Case_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Community_Contact__c.field-meta.xml
<CustomField>
    <fullName>Community_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Populate to create a new community user, when the opportunity is won.</inlineHelpText>
    <label>Community Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CPQ2_HC__c.field-meta.xml
<CustomField>
    <fullName>CPQ2_HC__c</fullName>
    <label>Hygiene Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Order_to_be_Emergency__c.field-meta.xml
<CustomField>
    <fullName>Is_Order_to_be_Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Order to be Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isConverted__c.field-meta.xml
<CustomField>
    <fullName>isConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PO_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Expiry_Date__c</fullName>
    <label>PO Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO #</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seasonal_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_Requirements__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked indicates the presence of a Seasonal Order with the customer, this would create a Internal Ticket requesting the creation of an Order to meet with such requirements. If not there will not be Seasonal Order with the customer.</inlineHelpText>
    <label>Seasonal Requirements</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Billing_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Suite_Number__c</fullName>
    <label>Billing Suite Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ServiceTerritory.ParentTerritoryId</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>ServiceTerritory.IsActive</field>
            <operation>notEqual</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Suite_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Suite_Number__c</fullName>
    <label>Shipping Suite Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Category_Description__c</fullName>
    <label>Category Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isConsumable__c.field-meta.xml
<CustomField>
    <fullName>isConsumable__c</fullName>
    <formula>Item_Type__c  =  $Setup.Field_Service_Settings__c.Item_Type_for_Consumables__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isConsumable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerDataWrapper.cls
/**
 * @FileName: OpportunityTriggerDataWrapper
 * @Description:
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       3/20/2020         Created
 * Darcy             5/18/2021         caseByOpportunityId now returns existing
 *                                     case for frequency change
 *----------------------------------------------------------------------------- 
 */
public inherited sharing class OpportunityTriggerDataWrapper {
    // Trigger Data
    private List<Opportunity> opportunityRecords;
    private Map<Id, Opportunity> oldMap;

    public OpportunityTriggerDataWrapper(List<Opportunity> opportunityRecords, Map<Id,Opportunity> oldMap) {
        this.opportunityRecords = opportunityRecords;
        this.oldMap = oldMap;
    }

    public Map<Id,Opportunity> opportunityMap {get {
        if (opportunityMap == null) {
            opportunityMap = new Map<Id, Opportunity>([
                    SELECT Id, Name, AccountId, OwnerId, SyncedQuoteId, SyncedQuote.ContactId, CloseDate, Site_Survey__c,
                            PO_Number__c, PO_Expiry_Date__c, Seasonal_Requirements__c, Description, Community_Contact__c,
                            Community_Contact__r.Email, Community_Contact__r.FirstName, Community_Contact__r.LastName,
                            Account.OperatingHours.TimeZone, Account.ServicePricebookId__c, Account.Invoice_Frequency__c,RecordTypeId,
                            Is_Order_to_be_Emergency__c, Order__c, Order__r.Id, Order__r.EffectiveDate, Order__r.EndDate,
                            Order__r.Status, Order__r.RecordTypeId, Order__r.OpportunityId, StageName, isConverted__c, CPQ2_HC__c,
                        (SELECT Id, ContactId
                        FROM OpportunityContactRoles
                        WHERE IsPrimary = TRUE),
                        (SELECT Id, Line_of_Business__c, Product2.IsActive, Product2.isConsumable__c, PricebookEntryId,
                                Quantity, UnitPrice, Service_Frequency__c, Service_Price_Per_Unit__c,
                                Opportunity.Account.ServicePricebookId__c, OpportunityId, Installation_Price__c,
                                Purchase_Price__c, Description, Category_Description__c, isPurchaseOnly__c,
                                Installation_Status__c, Installation_Notes__c, Service_Notes__c,Related_Product__c,
                                Related_Product__r.IsActive
                        FROM OpportunityLineItems),
                        (SELECT Id, ContactId
                        FROM Quotes
                        WHERE Status = 'Accepted'
                        ORDER BY QuoteNumber DESC
                        LIMIT 1)
                    FROM Opportunity
                    WHERE Id IN :opportunityRecords
            ]);
        }

        return opportunityMap;
    } set;}

    public Map<Id, Case> caseByOpportunityId {get {
        if (caseByOpportunityId == null) {
            caseByOpportunityId = new Map<Id, Case>();

            Set<Id> oppIds = new Set<Id>();

            for(Opportunity opp : opportunityRecords) {
                Opportunity oldRec = oldMap.get(opp.Id);
                
                if (opp.Case_Created__c
                    && opp.StageName != oldRec.StageName
                    && (opp.StageName == QueryUtils.fieldServiceSettings.Opportunity_Case_Creation_Stage_Name__c
                    || opp.StageName == QueryUtils.fieldServiceSettings.Opportunity_Frequency_Change_Stage_Name__c))
                {
                    oppIds.add(opp.Id);
                }
            }

            List<Case> cases = [SELECT Id, Status, OwnerId, Opportunity__c FROM Case WHERE Opportunity__c = :oppIds];

            for (Case c : cases) {
                caseByOpportunityId.put(c.Opportunity__c, c);
            }
        }

        return caseByOpportunityId;
    } set;}


    public Map<Id, Account> accountMap {get {
        if (accountMap == null) {
            Set<Id> accountIds = ApexUtils.getIdsFromField(opportunityRecords, 'AccountId');

            accountMap = new Map<Id, Account>([
                    SELECT Id, Billing_Suite_Number__c, BillingStreet, BillingCity, BillingState, BillingPostalCode,
                            BillingCountry, Shipping_Suite_Number__c, ShippingStreet, ShippingCity, ShippingState,
                            ShippingPostalCode, ShippingCountry, Site_Survey__c, ParentId, Parent.Billing_Suite_Number__c,
                            Parent.BillingStreet, Parent.BillingCity, Parent.BillingState, Parent.BillingPostalCode,
                            Parent.BillingCountry, Parent.Shipping_Suite_Number__c, Parent.ShippingStreet,
                            Parent.ShippingCity, Parent.ShippingState, Parent.ShippingPostalCode, Parent.ShippingCountry,
                            OperatingHoursId, Service_Territory__c, SalesPricebookId__c
                    FROM Account
                    WHERE Id IN :accountIds
            ]);
        }

        return accountMap;
    } set;}
}