force-app/main/default/objects/Account/fields/Contact_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Address__c</fullName>
    <inlineHelpText>Used for storing additional contact email address in Accpac</inlineHelpText>
    <label>A/P Contact Email Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Check__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check__c</fullName>
    <label>Credit Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Checked</fullName>
                <default>true</default>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Check_Case__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Check Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <defaultValue>$Setup.Quote_Settings__c.Default_Credit_Limit__c</defaultValue>
    <label>Credit Limit</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <inlineHelpText>Choose the language the customer prefers for any form of communication. It determines the quote pdf language preference.</inlineHelpText>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <label>Credit Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Account_Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Credit_Status__c</fullName>
    <formula>( Opportunity.Account.Inactive__c || Opportunity.Account.On_Hold__c || Opportunity.Account.Parent.Inactive__c || Opportunity.Account.Parent.On_Hold__c )</formula>
    <label>Account Credit Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Account_Owner_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_ID__c</fullName>
    <formula>Opportunity.Account.OwnerId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Status field that is updated as per the Approval Process</description>
    <inlineHelpText>Indicates whether the Discount Percentage is approved or rejected</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Approval Not Required</fullName>
                <isActive>false</isActive>
                <label>Approval Not Required</label>
            </value>
            <value>
                <fullName>Recalled</fullName>
                <isActive>false</isActive>
                <label>Recalled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Contact_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Address__c</fullName>
    <formula>Contact.Email</formula>
    <label>Contact Email Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <formula>CASESAFEID(ContactId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DocuSign_Subject__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Subject__c</fullName>
    <description>Merges the following to be used as the email subject for Quotes sent via DocuSign:
&apos;Citron Hygiene Documents for your DocuSign Signature - ACCOUNT ACCPAC OR QUOTE NUMBER - ACCOUNT NAME - QUOTE NAME&apos;</description>
    <formula>LEFT(&apos;Citron Hygiene Documents for your DocuSign Signature - &apos; + 
IF(
ISBLANK(Opportunity.Account.AccPac_Account__c),
QuoteNumber, 
Opportunity.Account.AccPac_Account__c) + &quot; - &quot; +
Opportunity.Account.Name + &quot; - &quot; + Name,
100)</formula>
    <label>DocuSign Subject</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/HasChemicalEquipment__c.field-meta.xml
<CustomField>
    <fullName>HasChemicalEquipment__c</fullName>
    <formula>INCLUDES(Applicable_T_C_s__c,&apos;4&apos;)</formula>
    <label>HasChemicalEquipment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <formula>Opportunity.Language_Preference__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Language Preference</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Maximum_Line_Item_Discount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Line_Item_Discount__c</fullName>
    <label>Maximum Line Item Discount</label>
    <summarizedField>QuoteLineItem.Discount</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_of_Business__c</fullName>
    <formula>TEXT( Opportunity.Opportunity_Type__c )</formula>
    <label>Opportunity Line of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Quote_With_Annual_Totals__c.field-meta.xml
<CustomField>
    <fullName>Quote_With_Annual_Totals__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote With Annual Totals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Monthly_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Revenue__c</fullName>
    <label>Total Monthly Revenue</label>
    <summarizedField>QuoteLineItem.Total_Monthly_Revenue__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/Quote_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains custom settings and configuration used on quotes, such as pre-defined quote templates used in Conga and Docusign buttons.</description>
    <label>Quote Settings</label>
</CustomObject>

force-app/main/default/objects/Quote_Settings__c/fields/Check_Account_Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_Account_Credit_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Account Credit Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/Check_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_Approval_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Approval Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/Check_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Check_Contact_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Contact Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/Credit_Check_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check_Threshold__c</fullName>
    <label>Credit Check Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/Default_Credit_Check_Case_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_Credit_Check_Case_Owner__c</fullName>
    <inlineHelpText>Default case owner (User or Queue) Id</inlineHelpText>
    <label>Default Credit Check Case Owner</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/Default_Credit_Check_Record_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_Credit_Check_Record_Type_ID__c</fullName>
    <inlineHelpText>Record Type ID for credit check cases</inlineHelpText>
    <label>Default Credit Check Record Type ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/Demo__c.field-meta.xml
<CustomField>
    <fullName>Demo__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is DocuSign issued using live credentials or Demo (Sandbox)?</inlineHelpText>
    <label>Demo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/E_Credit_Form_Template__c.field-meta.xml
<CustomField>
    <fullName>E_Credit_Form_Template__c</fullName>
    <label>(E) Credit Form Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/E_Products_Template__c.field-meta.xml
<CustomField>
    <fullName>E_Products_Template__c</fullName>
    <label>(E) Products Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/E_Services_Template__c.field-meta.xml
<CustomField>
    <fullName>E_Services_Template__c</fullName>
    <label>(E) Services Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/F_Credit_Form_Template__c.field-meta.xml
<CustomField>
    <fullName>F_Credit_Form_Template__c</fullName>
    <label>(F) Credit Form Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/F_Products_Template__c.field-meta.xml
<CustomField>
    <fullName>F_Products_Template__c</fullName>
    <label>(F) Products Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Settings__c/fields/F_Services_Template__c.field-meta.xml
<CustomField>
    <fullName>F_Services_Template__c</fullName>
    <label>(F) Services Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteTemplateActions.cls
public class QuoteTemplateActions {
    Quote rec { get; private set; }
    Quote_Settings__c qSettings { get; private set; }
    
    public QuoteTemplateActions(ApexPages.StandardController controller) {
        qSettings = Quote_Settings__c.getOrgDefaults();
        if (qSettings == null) {
            qSettings = new Quote_Settings__c();
        }
        rec = [SELECT Id, 
                Opportunity_Line_of_Business__c, Language_Preference__c, AccountId, Account_Name__c, Account_Owner_ID__c, Account_Credit_Status__c, Account.Credit_Check__c, Account.Name, Account.Credit_Limit__c, Account.Credit_Check_Case__c, Contact_Email_Address__c, Quote_With_Annual_Totals__c, DocuSign_Subject__c, Contact_ID__c, Maximum_Line_Item_Discount__c, Total_Monthly_Revenue__c, HasChemicalEquipment__c, Approval_Status__c 
              FROM Quote 
              WHERE Id = :controller.getRecord().Id];
    }

    public PageReference SelectTemplateRedirect() {
        if (validateQuote()) {
            String formattedDate = System.now().format('YYYY-MM-DD');
            String fileName = rec.Account_Name__c + '%20-%20' + rec.Opportunity_Line_of_Business__c + '%20Proposal%20-%20' + formattedDate;
            return new PageReference('/apex/APXTConga4__Conga_Composer?id=' + rec.Id + '&DefaultPDF=1&TemplateGroup=' + rec.Language_Preference__c + '&OFN=' + fileName);
        } else {
            return null;
        }
    }
    
    public PageReference AutoPdfRedirect() {
        if (validateQuote()) {
            String templateId = this.generateTemplateIdString();
            if (templateId == null) {
                rec.addError('Unable to select templates.  Please contact a system administrator.');
                return null;
            }
            
            return new PageReference('/apex/APXTConga4__Conga_Composer?id=' + rec.Id + '&FP0=1&DefaultPDF=1&DS7=5&TemplateId=' + templateId);
        } else {
            return null;
        }
    }
    
    public PageReference SendDocusignRedirect() {
        if (validateQuote()) {
            String templateId = this.generateTemplateIdString();
            System.debug('ValidateQuote: ' + templateId);
            if (templateId == null) {
                rec.addError('Unable to select templates.  Please contact a system administrator.');
                return null;
            }
            // sandbox return new PageReference('/apex/APXTConga4__Conga_Composer?id=' + rec.Id + '&TemplateId=' + templateId + '&FP0=1&DefaultPDF=1&DS7=5&APDF=0&DocuSignEmailSubject=' + EncodingUtil.urlEncode(rec.DocuSign_Subject__c,'UTF-8') + '&DocuSignVisible=1&DocuSignR1ID=' + rec.Contact_ID__c + '&DocuSignR1Type=Signer&DocuSignR1Role=Signer+1&DocuSignR1RoutingOrder=2&DocuSignR2ID=' + rec.Account_Owner_ID__c + '&DocuSignR2Type=Signer&DocuSignR2Role=Signer+2&DocuSignR2RoutingOrder=1' + (!qSettings.Demo__c ? '&DocuSignEndpoint=Demo' : EncodingUtil.urlEncode('','UTF-8')));
            return new PageReference('/apex/APXTConga4__Conga_Composer?id=' + rec.Id + '&TemplateId=' + templateId + '&FP0=1&DefaultPDF=1&DS7=17&APDF=0&DocuSignEmailSubject=' + EncodingUtil.urlEncode(rec.DocuSign_Subject__c,'UTF-8') + '&DocuSignVisible=1&DocuSignR1ID=' + rec.Contact_ID__c + '&DocuSignR1Type=Signer&DocuSignR1Role=Signer+1&DocuSignR1RoutingOrder=2&DocuSignR2ID=' + rec.Account_Owner_ID__c + '&DocuSignR2Type=Signer&DocuSignR2Role=Signer+2&DocuSignR2RoutingOrder=1'); 
        } else {
            return null;
        }
    }
    
    private Boolean validateQuote() {
        if (rec != null && qSettings.Check_Contact_Email__c && rec.Contact_Email_Address__c == null) {
            rec.addError('Quote cannot be generated. Contact record does not have an email address.');
            return false;
        } else if (rec != null && qSettings.Check_Account_Credit_Status__c && rec.Account_Credit_Status__c) {
            rec.addError('Quote cannot be generated.  Please check the Account Credit Status.');
            return false;
        } else if (rec != null && qSettings.Check_Approval_Status__c && (rec.Maximum_Line_Item_Discount__c >= 30 && !rec.Approval_Status__c.equalsIgnoreCase('Approved'))) {
            rec.addError('Quote cannot be generated. Please get Manager Approval for the Discounts.');
            return false;
        } 
        return true;
    }
    
    private String generateTemplateIdString() {
        String formattedDate = System.now().format('YYYY-MM-dd');
        String templateId = (rec.Language_Preference__c=='French' ? (rec.Quote_With_Annual_Totals__c ? qSettings.F_Services_Template__c : qSettings.F_Products_Template__c) : (rec.Quote_With_Annual_Totals__c ? qSettings.E_Services_Template__c : qSettings.E_Products_Template__c));
        String fileName = rec.Account_Name__c + ' - ' + rec.Opportunity_Line_of_Business__c + ' Proposal - ' + formattedDate;
        String retVal = '[' + fileName + ']' + templateId;
        
        //Credit Form logic - Commented out because not part of deployment
        //retVal += createCreditCheckCase();
        retVal = retVal.replaceAll('\\s','%20');
        System.debug('generated Template Id String: ' + retVal);
        return retVal;
    }
    
    private String createCreditCheckCase() {
        System.debug('running credit check logic');
        System.debug('credit threshold: ' + qSettings.Credit_Check_Threshold__c);
        System.debug('quote monthly revenue: ' + rec.Total_Monthly_Revenue__c);
        System.debug('quote chem equipment: ' + rec.HasChemicalEquipment__c);
        
        if (
            (qSettings.Credit_Check_Threshold__c != null && rec.Total_Monthly_Revenue__c > qSettings.Credit_Check_Threshold__c) ||
            rec.HasChemicalEquipment__c
        ) {
            System.debug('credit form required');
            String creditFormId = (rec.Language_Preference__c=='French' ? qSettings.F_Credit_Form_Template__c : qSettings.E_Credit_Form_Template__c);
            String creditFileName = (rec.Language_Preference__c=='French' ? 'Formulaire Ouverture de compte' : 'Credit Application Form');

            //If a credit check case already exists, don't create another
            System.debug('Account credit state: ' + rec.Account.Credit_Check__c);
            System.debug('Existing credit case: ' + rec.Account.Credit_Check_Case__c);
            if (rec.Account.Credit_Check_Case__c == null && rec.Account.Credit_Check__c == 'Not Checked') {
                Case c = new Case(
                    RecordTypeId = qSettings.Default_Credit_Check_Record_Type_Id__c,
                    OwnerId = qSettings.Default_Credit_Check_Case_Owner__c,
                    Subject = 'Credit Check: ' + rec.Account.Name + ' [' + System.now().format('YYYY-MM-dd') + ']',
                    Status = 'New',
                    Origin = 'Email',
                    AccountId = rec.AccountId,
                    Credit_Limit__c = rec.Account.Credit_Limit__c
                );
                System.debug('creating case: ' + c);
                insert c;
                
                Account acc = new Account(
                    Id = rec.AccountId,
                    Credit_Check_Case__c = c.Id,
                    Credit_Check__c = 'In Progress'
                );
                System.debug('updating account: ' + acc);
                update acc;
            }
            return ',[' + creditFileName + ']' + creditFormId;
        }
        System.debug('credit form not required');
        return '';
    }
}