force-app/main/default/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <formula>IF(

Inactive__c = TRUE, 

IMAGE(&apos;/resource/Customer_Status_Inactive_image2&apos;, &quot;Inactive&quot;), 

IF(

AND(On_Hold__c = TRUE) , 

IMAGE(&apos;/resource/Customer_Status_OnHold_image2&apos;, &quot;On Hold&quot;),

IF(

AND( PestPac__c = TRUE,ISPICKVAL(Use_Distributor__c,&apos;Yes&apos;)),

&quot; &quot;,

IF(

AND( PestPac__c = TRUE, VMI__c = FALSE),

IMAGE(&apos;/resource/ActivePestPac&apos;,&quot;Active PestPac&quot;),

IF(

AND(ISPICKVAL(Use_Distributor__c,&apos;Yes&apos;), VMI__c = false), 

IMAGE(&apos;/resource/ActiveDist&apos;,&quot;Active Dist&quot;),

IF(

AND(ISPICKVAL(Use_Distributor__c,&apos;Yes&apos;), VMI__c = TRUE),

IMAGE(&apos;/resource/Customer_Status_Active_DIST_VMI&apos;,&quot;Active DIST VMI&quot;),

IF(

AND(VMI__c = TRUE, PestPac__c = FALSE), 

IMAGE(&apos;/resource/Customer_Status_Active_VMI&apos; ,&quot;Active VMI&quot;),

IF(

AND(PestPac__c = TRUE, VMI__c = TRUE), 

IMAGE(&apos;/resource/Customer_Status_Active_VMI_PestPac&apos;,&quot;Active VMI PestPac&quot;),

IMAGE(&apos;/resource/Customer_Status_Active_image5&apos;, &quot;Active&quot;)))))))))</formula>
    <label>Customer Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>NOT( Inactive__c  ||  On_Hold__c || Parent.Inactive__c || Parent.On_Hold__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Order/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>(EffectiveDate &lt;= (Today() +  $Setup.Field_Service_Settings__c.Work_Orders_In_Advance__c )) &amp;&amp; ISPICKVAL(Status, &quot;Activated&quot;) &amp;&amp;  (EndDate &gt; Today() || ISBLANK(EndDate))</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/ScheduledDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDate__c</fullName>
    <description>Maximum of Scheduled Date rolled up from Order Products</description>
    <label>ScheduledDate</label>
    <summarizedField>OrderItem.Next_Scheduled_Date__c</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Season_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Season_End_Date__c</fullName>
    <formula>IF(
DATE(YEAR(TODAY()),  SeasonEndMonthValue__c ,  SeasonEndDayValue__c ) &lt;=   Season_Start_Date__c ,
DATE(YEAR(TODAY())+1, SeasonEndMonthValue__c, SeasonEndDayValue__c ),
DATE(YEAR(TODAY()), SeasonEndMonthValue__c, SeasonEndDayValue__c )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Season End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Season_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Season_Start_Date__c</fullName>
    <formula>IF(  SeasonStartMonthValue__c  &gt; MONTH( TODAY() )  &amp;&amp;    SeasonEndMonthValue__c  &gt;= MONTH( TODAY() )  &amp;&amp; (SeasonEndMonthValue__c &lt; SeasonStartMonthValue__c || (SeasonEndMonthValue__c = SeasonStartMonthValue__c &amp;&amp; SeasonStartDayValue__c &gt; SeasonEndDayValue__c)
), DATE(YEAR(TODAY())-1, SeasonStartMonthValue__c,  SeasonStartDayValue__c ), DATE(YEAR(TODAY()), SeasonStartMonthValue__c, SeasonStartDayValue__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Season Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/First_Installation_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Installation_Completed_Date__c</fullName>
    <label>First Installation Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FrequencyInDays__c.field-meta.xml
<CustomField>
    <fullName>FrequencyInDays__c</fullName>
    <formula>CASE(Frequency__c,
&apos;One-Time&apos;, 0, 
&apos;Daily&apos;, 1,
&apos;6X Per Week&apos;, 2,
&apos;5X Per Week&apos;, 3,
&apos;4X Per Week&apos;, 4,
&apos;3X Per Week&apos;, 5,
&apos;2X Per Week&apos;, 6,
&apos;Weekly&apos;, 7, 
&apos;Fixed Weekly&apos;, 7,
&apos;14 Days&apos;, 14,
&apos;Twice Monthly&apos;, 15, 
&apos;28 Days&apos;, 28,
&apos;Monthly&apos;, 30, 
&apos;42 Days&apos;, 42,
&apos;56 Days&apos;, 56,
&apos;Bi-Monthly&apos;, 60,
&apos;84 Days&apos;, 84,
&apos;Quarterly&apos;, 90,
&apos;112 Days&apos;, 112,
&apos;120 Days&apos;, 120,
&apos;168 Days&apos;, 168,
&apos;Semi-Annually&apos;, 182,
&apos;2X Per Year&apos;, 182, 
&apos;182 Days&apos;, 182,
&apos;Annually&apos;, 365, 
0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FrequencyInDays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Installation_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Status__c</fullName>
    <inlineHelpText>Indicate if this is a new Asset Install, Removing(for seasonality purposes), Replacing(an old asset is replaced with a new one)</inlineHelpText>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Install/Repair Completed</fullName>
                <isActive>false</isActive>
                <label>Install/Repair Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Inventory_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inventory Allocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Is_Never_Generate_Work_order__c.field-meta.xml
<CustomField>
    <fullName>Is_Never_Generate_Work_order__c</fullName>
    <formula>IF(PricebookEntry.Product2.Never_Generate_Work_Order__c = true, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Never Generate Work order?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>PricebookEntry.IsActive  &amp;&amp;  PricebookEntry.Product2.IsActive &amp;&amp;  Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>IF(PricebookEntry.Product2.Never_Generate_Work_Order__c, FALSE, IF(PricebookEntry.Product2.Heavy_Equipment__c, 
Inventory_Allocated__c &amp;&amp; NOT( ISBLANK(Serial_Number__c) ), 
Order.Inventory_Allocated__c || Order.Emergency__c || Inventory_Allocated__c))</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>This field is System Generated during the nightly Work Order Generation batch job. Changing this would have implications on Work Order Generation Logic</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <label>Last InFlight WO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Family)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateWorkOrderStatusBatch.cls
global class CreateWorkOrderStatusBatch implements Database.Batchable<SObject>{
          
    global Database.QueryLocator Start(Database.BatchableContext bc){
        Date compareDate = date.today();    
        string query = 'Select Id,isValid__c,IsActive__c,Last_Automation_Created_Date__c,Last_InFlight_WO_Date__c,Product2Id,Product2.Allowable_Frequencies__c,Order.AccountId,Order.Account.Customer_Status__c,Order.ScheduledDate__c,Order.Status,OrderId,Order.Emergency__c,Order.Inventory_Allocated__c,Line_of_Business__c,Active__c,FrequencyInDays__c,Frequency__c,Is_Never_Generate_Work_order__c,'+
                        'Order.Season_Start_Date__c ,Order.Season_End_Date__c,Order.EffectiveDate,Order.EndDate,Service_Price_Per_Unit__c,Installation_Status__c,First_Installation_Completed_Date__c,Inventory_Allocated__c,Valid_for_Install_Remove_Replace__c,Purchase_Price__c,ServiceDate from OrderItem where   Active__c = true  AND Order.Emergency__c = false AND Is_Never_Generate_Work_order__c = False AND' + 
                        '(((Order.Season_End_Date__c >=:compareDate AND Order.Season_Start_Date__c <= : compareDate) AND (Order.Season_End_Date__c <> null AND Order.Season_Start_Date__c <> null)) OR (Order.Season_Start_Date__c = null AND Order.Season_End_Date__c = null))' + 
                        'AND Service_Price_Per_Unit__c != Null AND FrequencyInDays__c != 0 AND Valid_for_Install_Remove_Replace__c = False';
                                
        return Database.getQueryLocator(query);                     

    }
    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        
        CreateWorkOrderGenerationStatus.CreateGenerationStatus(scope);
   
    }
    
    global void finish(Database.BatchableContext bc){
        UpdateWorkOrderGenerationStatusBatch uwogsb = new UpdateWorkOrderGenerationStatusBatch();
          database.executebatch(uwogsb,50);
    }
}