force-app/main/default/objects/Account/fields/Is_Multi_Res__c.field-meta.xml
<CustomField>
    <fullName>Is_Multi_Res__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Multi-Res</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Is_Pest_Emergency__c.field-meta.xml
<CustomField>
    <fullName>Is_Pest_Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If TRUE, the Order generated from the Site Survey being approved will be flagged as emergency to allow usage in the Emergency Dispatch Wizard.</inlineHelpText>
    <label>Is Pest Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Emergency.recordType-meta.xml
<RecordType>
    <fullName>Emergency</fullName>
    <active>true</active>
    <businessProcess>Emergency</businessProcess>
    <description>For Customer Emergency Services</description>
    <label>Emergency</label>
</RecordType>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/Emergency_Dispatch_Wizard_Setttings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Emergency Dispatch Wizard Setttings</label>
</CustomObject>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/fields/Default_Scheduling_Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Scheduling_Policy_Id__c</fullName>
    <inlineHelpText>The Id of the default Scheduling Policy for Pest Emergency Service Appointments</inlineHelpText>
    <label>Default Scheduling Policy Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/fields/SSRS_Multi_Res_Pest_Skill_Id__c.field-meta.xml
<CustomField>
    <fullName>SSRS_Multi_Res_Pest_Skill_Id__c</fullName>
    <label>SSRS-Multi Res Pest Skill Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/fields/SSRS_Pest_Commercial_Skill_Id__c.field-meta.xml
<CustomField>
    <fullName>SSRS_Pest_Commercial_Skill_Id__c</fullName>
    <label>SSRS-Pest-Commercial Skill Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Duration_Type_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Type_Minutes__c</fullName>
    <label>Duration Type Minutes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Non_Recurring_Frequency_Value__c.field-meta.xml
<CustomField>
    <fullName>Non_Recurring_Frequency_Value__c</fullName>
    <label>Non Recurring Frequency Value</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Work_Order_Cancelled_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Cancelled_Status__c</fullName>
    <label>Work Order Cancelled Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Number_of_Resources__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Resources__c</fullName>
    <label>Number of Resources</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pest_Emergency_Required_Skill__mdt/Pest_Emergency_Required_Skill__mdt.object-meta.xml
<CustomObject>
    <label>Pest Emergency Required Skill</label>
    <pluralLabel>Pest Emergency Required Skills</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pest_Emergency_Required_Skill__mdt/fields/Skill_Id__c.field-meta.xml
<CustomField>
    <fullName>Skill_Id__c</fullName>
    <label>Skill Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/EID__c.field-meta.xml
<CustomField>
    <fullName>EID__c</fullName>
    <externalId>true</externalId>
    <label>EID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSL__Emergency__c.field-meta.xml
<CustomField>
    <fullName>FSL__Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSL__Scheduling_Policy_Used__c.field-meta.xml
<CustomField>
    <fullName>FSL__Scheduling_Policy_Used__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduling Policy Used</label>
    <referenceTo>FSL__Scheduling_Policy__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Is_Pest_Emergency__c.field-meta.xml
<CustomField>
    <fullName>Is_Pest_Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Pest Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business__c</fullName>
    <label>Line Of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Pest_Emergency_Dedicated_Count__c.field-meta.xml
<CustomField>
    <fullName>Pest_Emergency_Dedicated_Count__c</fullName>
    <label>Pest Emergency Dedicated Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Status_UnSync_WO_SA__c.field-meta.xml
<CustomField>
    <fullName>Status_UnSync_WO_SA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to check if the Status_WO_SA field on the FSL mobile app should be used to Sync the status of Work Orders &amp; Service Appointments or not</description>
    <inlineHelpText>When checked, Changing the status of the Status or Status (WO/SA) fields on the Service Appointment will not sync the status of a WO &amp; SA</inlineHelpText>
    <label>Status UnSync (WO/SA)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Service Appointment</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Min_Pest_Work_Order_Lines__c.field-meta.xml
<CustomField>
    <fullName>Min_Pest_Work_Order_Lines__c</fullName>
    <label>Min Pest Work Order Lines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Pest_WorkOrder_Calculation_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Pest_WorkOrder_Calculation_Adjustment__c</fullName>
    <label>Pest WorkOrder Calculation Adjustment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SkillRequirement/fields/EID__c.field-meta.xml
<CustomField>
    <fullName>EID__c</fullName>
    <externalId>true</externalId>
    <label>EID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of Work Order, whether it is a delivery or a work order for a particular line of business</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Work Order</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>NoWork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SpawnPestEmergencyServiceAppointments.cls
/**
* Name: SpawnPestEmergencyServiceAppointments
* Author: PwC
* Date Created: April 23, 2019
* Purpose: To generate the Pest Emergency Service Appointments from the Emergency Dispatch Wizard app
*/
public class SpawnPestEmergencyServiceAppointments {
    private static Emergency_Dispatch_Wizard_Setttings__c edwSettings = Emergency_Dispatch_Wizard_Setttings__c.getOrgDefaults();
    private static Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
    private static final String DELIMITER = '-';
    private static final Integer MINIMUM_SA_COUNT_FOR_STATUS_UNSYNC = 1;
    
    /**
     * Generates Pest Emergency Service Appointments as specified
     * 
     * @param workOrderIds  represents all Work Orders to have Service Appointments be generated 
     * @param totalDuration  the total duration to be spread between all generated Service Appointments
     */
    public static Set<Id> generatePestEmergencyServiceAppointments(Set<Id> workOrderIds, Decimal totalDuration) {
        Map<Id, List<ServiceAppointment>> appointments = new Map<Id, List<ServiceAppointment>>();
        Map<String, SkillRequirement> skillRequirements = new Map<String, SkillRequirement>();
        Map<String, SkillRequirement> alreadyExistingRequirements = new Map<String, SkillRequirement>();
        List<ServiceAppointment> appointmentsToUpsert = new List<ServiceAppointment>();
        Set<Id> siteSurveyIds = new Set<Id>();
        Set<String> skillIds = new Set<String>();
        
        for (Pest_Emergency_Required_Skill__mdt skill : [SELECT Skill_Id__c FROM Pest_Emergency_Required_Skill__mdt]) {
            skillIds.add(skill.Skill_Id__c);
        }
        
        Map<Id, Skill> pestEmergencySkills = new Map<Id, Skill>([SELECT Id FROM Skill WHERE Id IN :skillIds]);
        
        Map<Id, WorkOrder> workOrders = new Map<Id, WorkOrder>([SELECT Id, ServiceTerritoryId, StartDate, EndDate, Order__c, AccountId, Account.Is_Multi_Res__c, Emergency__c, Line_of_Business__c, ContactId, Type__c, Status, Order__r.Number_of_Resources__c, Site_Survey__r.Pest_WorkOrder_Calculation_Adjustment__c, Site_Survey__r.Min_Pest_Work_Order_Lines__c,
                             (SELECT Id, EID__c, Status, Duration, Pest_Emergency_Dedicated_Count__c FROM ServiceAppointments ORDER BY Pest_Emergency_Dedicated_Count__c DESC),
                             (SELECT Id, SkillId, SkillLevel FROM SkillRequirements WHERE SkillId IN :pestEmergencySkills.keySet())
                             FROM WorkOrder WHERE Id IN :workOrderIds]);
        
        for (WorkOrder wo : workOrders.values()) {
            siteSurveyIds.add(wo.Site_Survey__c);
        }
        
        for (WorkOrder wo : workOrders.values()) {
            Integer numberOfNonCancelledServiceAppointments = 0;
            
            if (!wo.ServiceAppointments.isEmpty()) {
                for (ServiceAppointment sa : wo.ServiceAppointments) {
                    if (sa.Status != dataSets.Work_Order_Cancelled_Status__c) {
                        numberOfNonCancelledServiceAppointments++;
                    }
                }
            }
            
            if (numberOfNonCancelledServiceAppointments > wo.Order__r.Number_of_Resources__c) {
                //do nothing and skip - deletion will take care of any recalculation of the duration
                continue;
            }
            
            Datetime earliestStartDate = Datetime.newInstance(wo.StartDate.year(), wo.StartDate.month(), wo.StartDate.day(), wo.StartDate.hour(), wo.StartDate.minute(), wo.StartDate.second());
            Datetime dueDate = Datetime.newInstance(wo.EndDate.year(), wo.EndDate.month(), wo.EndDate.day(), 23, 59, 59);
            
            Decimal numberOfResourcesRequested = wo.Order__r.Number_of_Resources__c;
            
            if (!appointments.containsKey(wo.Id)) {
                appointments.put(wo.Id, new List<ServiceAppointment>());
            }
            
            Decimal durationPerAppointment = EDW_UtilityClass.calculateDurationPerServiceAppointment(totalDuration, wo.Order__r.Number_of_Resources__c);
            
            Integer dedicatedCount = 0;
            
            if (!wo.ServiceAppointments.isEmpty()) {
                for (ServiceAppointment sa : wo.ServiceAppointments) {
                    sa.ContactId = wo.ContactId;//ensure the contact always matches in case of a change
                    
                    if (sa.Pest_Emergency_Dedicated_Count__c != null && sa.Pest_Emergency_Dedicated_Count__c > dedicatedCount) {
                        dedicatedCount = Integer.valueOf(sa.Pest_Emergency_Dedicated_Count__c) + 1;
                    }
                }
            }
            
            appointmentsToUpsert = EDW_UtilityClass.recalculateDurationsAndSetServiceWindows(wo, durationPerAppointment);
            
            String eId = dueDate.year() + DELIMITER + dueDate.month() + DELIMITER + dueDate.day() + DELIMITER + wo.Id;
            
            for (Integer index = numberOfNonCancelledServiceAppointments; index < numberOfResourcesRequested; index++) {
                dedicatedCount++;
                
                appointments.get(wo.Id).add(new ServiceAppointment(
                    ParentRecordId = wo.Id,
                    ContactId = wo.ContactId,
                    Account__c = wo.AccountId,
                    Line_Of_Business__c = wo.Line_of_Business__c,
                    FSL__Emergency__c = wo.Emergency__c,
                    DurationType = dataSets.Duration_Type_Minutes__c,
                    FSL__GanttLabel__c = dataSets.Non_Recurring_Frequency_Value__c,
                    Type__c = wo.Type__c,
                    EID__c = eId + DELIMITER + dedicatedCount,
                    EarliestStartTime = earliestStartDate,
                    DueDate = dueDate,
                	Status = wo.Status,
                    Duration = EDW_UtilityClass.setServiceAppointmentDuration(durationPerAppointment),
                    FSL__Scheduling_Policy_Used__c = edwSettings.Default_Scheduling_Policy_Id__c,
                    Is_Pest_Emergency__c = true,
                    Pest_Emergency_Dedicated_Count__c = dedicatedCount,
                    Status_UnSync_WO_SA__c = wo.Order__r.Number_of_Resources__c > MINIMUM_SA_COUNT_FOR_STATUS_UNSYNC
                ));
            }
            
            appointments.remove(null);
            appointmentsToUpsert.addAll(appointments.get(wo.Id));
            
            /* Skill Requirements */
            SkillRequirement sr;
            Skill skill;
            String srKey;
            
            if (wo.Account.Is_Multi_Res__c) {
                skill = pestEmergencySkills.get(edwSettings.SSRS_Multi_Res_Pest_Skill_Id__c);
                srKey = skill.Id + '|' + wo.Id;
            } else {
                skill = pestEmergencySkills.get(edwSettings.SSRS_Pest_Commercial_Skill_Id__c);
                srKey = skill.Id + '|' + wo.Id;                
            }
            
            alreadyExistingRequirements.putAll(wo.SkillRequirements);
            skillRequirements.put(srKey, new SkillRequirement(RelatedRecordId = wo.Id, SkillId = skill.Id, SkillLevel = 1, EID__c = srKey));
        }
        
        skillRequirements.remove(null);
        alreadyExistingRequirements.remove(null);
        
        List<SkillRequirement> newSkillRequirements = new List<SkillRequirement>();
        
        for (SkillRequirement sr : skillRequirements.values()) {
            SkillRequirement alreadyExistingSkillRequirement = alreadyExistingRequirements.get(sr.EID__c);
            
            if (alreadyExistingSkillRequirement == null) {
                newSkillRequirements.add(sr);
            }
        }
        
        Database.insert(newSkillRequirements, false);
        
        if (appointments.size() > 0) {
            upsert appointmentsToUpsert;
            
            Set<Id> serviceAppointmentIds = new Set<Id>();
            
            for (ServiceAppointment sa : appointmentsToUpsert) {
                serviceAppointmentIds.add(sa.Id);
            }
            
            return serviceAppointmentIds;
        }
        
        return null;
    }
}