force-app/main/default/objects/Account/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>NOT( Inactive__c  ||  On_Hold__c || Parent.Inactive__c || Parent.On_Hold__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Batch_Errors__c/Batch_Errors__c.object-meta.xml
<CustomObject>
    <label>Batch Errors</label>
    <nameField>
        <label>TEMP ERRORS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Errors__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>EndTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Batch_Errors__c/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Errors__c/fields/Failed_Batch__c.field-meta.xml
<CustomField>
    <fullName>Failed_Batch__c</fullName>
    <label>Failed Batch</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Errors__c/fields/OperatingHoursId__c.field-meta.xml
<CustomField>
    <fullName>OperatingHoursId__c</fullName>
    <label>OperatingHoursId</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Errors__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>OrderId</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Errors__c/fields/OrderProductId__c.field-meta.xml
<CustomField>
    <fullName>OrderProductId__c</fullName>
    <label>OrderProductId</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Errors__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>StartTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>(EffectiveDate &lt;= (Today() +  $Setup.Field_Service_Settings__c.Work_Orders_In_Advance__c )) &amp;&amp; ISPICKVAL(Status, &quot;Activated&quot;) &amp;&amp;  (EndDate &gt; Today() || ISBLANK(EndDate))</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>PricebookEntry.IsActive  &amp;&amp;  PricebookEntry.Product2.IsActive &amp;&amp;  Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>IF(PricebookEntry.Product2.Never_Generate_Work_Order__c, FALSE, IF(PricebookEntry.Product2.Heavy_Equipment__c, 
Inventory_Allocated__c &amp;&amp; NOT( ISBLANK(Serial_Number__c) ), 
Order.Inventory_Allocated__c || Order.Emergency__c || Inventory_Allocated__c))</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Family)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Order Item cannot have the custom Order field set as it&apos;s Inactive.</errorMessage>
        <filterItems>
            <field>$Source.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Active Order Products without PO Number</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Work_Type__c</fullName>
    <formula>PricebookEntry.Product2.Service_Work_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Work Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Follow_up_After_N_Days__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_After_N_Days__c</fullName>
    <label>Follow-up After N Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Follow_up_Product__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Follow-up Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Products (Service Work Type)</relationshipLabel>
    <relationshipName>ServiceProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Follow_Up_Created__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Follow Up Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSL__VisitingHours__c.field-meta.xml
<CustomField>
    <fullName>FSL__VisitingHours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visiting Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>(Last_Batch_Updated_Date__c = TODAY() || Last_Batch_Updated_Date__c = TODAY() + (-1)) &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Completed&apos; &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Cannot Complete&apos; &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Dispatched&apos;</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Last_Batch_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Updated_Date__c</fullName>
    <label>Last Batch Updated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of Work Order, whether it is a delivery or a work order for a particular line of business</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Work Order</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>NoWork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Valid_For_FollowUp__c.field-meta.xml
<CustomField>
    <fullName>Valid_For_FollowUp__c</fullName>
    <formula>NOT(Follow_Up_Created__c) &amp;&amp;  TEXT( StatusCategory ) = &apos;Completed&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid For FollowUp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Follow_Up_Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Follow Up Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Follow_Up_Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Spawn_Follow_Up_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Spawn_Follow_Up_Work_Order__c</fullName>
    <formula>ISBLANK(Follow_Up_Work_Order_Line_Item__c) &amp;&amp; !ISBLANK( Product2.Follow_up_Product__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spawn Follow-Up Work Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SpawnFollowUpWorkOrders.cls
global class SpawnFollowUpWorkOrders implements Database.Batchable<SObject> {
    public String queryString { get; set; }
    
    global SpawnFollowUpWorkOrders() {}

    global SpawnFollowUpWorkOrders(String s) {
        queryString = 'SELECT Id, Valid_For_FollowUp__c ' +
                'FROM WorkOrder WHERE Id=\'' + s + '\' ' +
                'AND Valid_For_FollowUp__c = TRUE';
    }
        
    global Database.QueryLocator start(Database.BatchableContext bc){
        if (String.isBlank(queryString)) {
            return Database.getQueryLocator([
                    SELECT Id
                    FROM WorkOrder
                    WHERE Account.isValid__c = TRUE
                    AND Valid_For_FollowUp__c=TRUE
            ]);
        } else {
            return Database.getQueryLocator(queryString);
        }        
    }

    global void execute(Database.BatchableContext bc, List<SObject> batch){
        Set<Id> workOrderIds = new Set<Id>();
        
        for(WorkOrder wo : (List<WorkOrder>) batch) {
            workOrderIds.add(wo.Id);
        }

        processWorkOrders(workOrderIds); 
    }
    
    global void processWorkOrders(Set<Id> workOrderIds) {
       
        Datetime todaysDateTime = Datetime.now();
        Date todaysDate = Date.today();
        
        Set<Id> woIds = new Set<Id>();
        Map<Id, Map<Id, Id>> pbe_pb_p2Map = new Map<Id, Map<Id, Id>>();
        Map<Id, OperatingHours> workOrderOperatingHours = new Map<Id, OperatingHours>();
        List<WorkOrder> updateParentWorkOrders = new List<WorkOrder>();
        List<WorkOrder> workOrderInsert = new List<WorkOrder>();
        
        List<WorkOrder> workOrders = new List<WorkOrder>([
                SELECT Id, WorkOrderNumber, Pricebook2Id, Opportunity__c, StartDate, Valid_For_FollowUp__c, WorkTypeId,
                        FSL__VisitingHours__c, Follow_Up_Created__c, ServiceTerritoryId, AccountId, ContactId, Priority,
                        Emergency__c, Order__c, Line_of_Business__c, Last_Batch_Updated_Date__c
                FROM WorkOrder
                WHERE Id IN :workOrderIds
        ]);
        
        for(WorkOrder wo : workOrders){
            woIds.add(wo.Id);
            pbe_pb_p2Map.put(wo.Pricebook2Id, new Map<Id,Id>());
            workOrderOperatingHours.put(wo.FSL__VisitingHours__c, null);  
        }
        
        workOrderOperatingHours.remove(null);

        workOrderOperatingHours = new Map<Id, OperatingHours>([
                SELECT Id, Name, TimeZone,
                        (SELECT Id, DayOfWeek, StartTime, EndTime
                        FROM TimeSlots
                        ORDER BY DayOfWeek, StartTime, EndTime)
                FROM OperatingHours
                WHERE Id IN :workOrderOperatingHours.keySet()
        ]);
        
        //existing line item to cloned line itemmap
        Map<Id, WorkOrderLineItem> updLineItem = new Map<Id,WorkOrderLineItem>();
        
        //existing parentworkorder+productId to cloned work order line items
        Map<String,List<WorkOrderLineItem>> woLineItemsMap = new Map<String,List<WorkOrderLineItem>>();
        
        //existing parentworkorder+productId to cloned work order
        Map<String,WorkOrder> woMap = new Map<String,WorkOrder>();
        
        if(!pbe_pb_p2Map.isEmpty()) {
            for(PricebookEntry pbe : [SELECT Id, Product2Id, Pricebook2Id FROM PricebookEntry WHERE Pricebook2Id IN :pbe_pb_p2Map.keySet()]) {
                pbe_pb_p2Map.get(pbe.Pricebook2Id).put( pbe.Product2Id, pbe.Id);
            }
        }
        
        Map<Id,List<WorkOrderLineItem>> existingWOLiMap = new Map<Id,List<WorkOrderLineItem>>();
        //Begin:11-21-2019:Irfan:Do not clone workorderlineitem with inactive order products
        List<WorkOrderLineItem> lis = [
                SELECT Id, WorkOrderId, WorkOrder.Pricebook2Id, PricebookEntry.Product2.Follow_up_After_N_Days__c,
                        PricebookEntry.Product2.Follow_up_Product__c, OrderId, Order_Product__c,
                        PricebookEntry.Product2.Follow_up_Product__r.Service_Work_Type__c, AssetId
                FROM WorkOrderLineItem
                WHERE Spawn_Follow_Up_Work_Order__c = TRUE
                AND Order_Product__r.IsActive__c = TRUE
                AND WorkOrderId = :woIds
        ];

        for (WorkOrderLineItem li: lis) {
            List<WorkOrderLineItem> lli = existingWOLiMap.get(li.WorkOrderId) == null ? new List<WorkOrderLineItem>() : existingWOLiMap.get(li.WorkOrderId);
            lli.add(li);
            existingWOLiMap.put(li.WorkOrderId, lli); 
            
        }
        //End

        for (WorkOrder wo: workOrders) {
            Map<Id, List<WorkOrderLineItem>> groupLineItemByProduct = new Map<Id,List<WorkOrderLineItem>>();            
            Map<Id,Integer> productFollowUpDays = new Map<Id,Integer>();  

            updateParentWorkOrders.add(new WorkOrder(Id = wo.Id, Follow_Up_Created__c = true));

            if (existingWOLiMap.get(wo.Id) != null) {
                for (WorkOrderLineItem li: existingWOLiMap.get(wo.Id)) {
                    
                    WorkOrderLineItem cli = li.clone(false, false, false, false);
                    cli.ParentWorkOrderLineItemId = li.Id;
                    Id followUpProd = li.PricebookEntry.Product2.Follow_up_Product__c;
                    cli.Status='New';
                    cli.Product__c = followUpProd;                     
                    cli.WorkTypeId = li.PricebookEntry.Product2.Follow_up_Product__r.Service_Work_Type__c;
                    cli.PricebookEntryId = pbe_pb_p2Map.get(wo.Pricebook2Id).get(followUpProd);
                    cli.Quantity = 1;   
                    
                    List<WorkOrderLineItem> wolis = groupLineItemByProduct.get(followUpProd) == null ? new List<WorkOrderLineItem>(): groupLineItemByProduct.get(followUpProd);
                    wolis.add(cli);
                    groupLineItemByProduct.put(followUpProd,wolis);
                    updLineItem.put(li.Id,cli);
                    
                    //maintain map for followup days for prod
                    productFollowUpDays.put(followUpProd,(Integer)li.PricebookEntry.Product2.Follow_up_After_N_Days__c);
                }
            }
            
            if (!groupLineItemByProduct.isEmpty()) {
                for (Id i: groupLineItemByProduct.keySet()) {
                    WorkOrder clonedWo = wo.clone(false,false,false,false);
                    clonedWo.Status = 'New';
                    clonedWo.Type__c = 'Follow-Up';
                    clonedWo.ParentWorkOrderId = wo.Id;
                    clonedWo.Last_Batch_Updated_Date__c = todaysDate;

                    Date startDate = wo.StartDate.addDays(productFollowUpDays.get(i)).date();
                    Datetime startDateTime =  Datetime.newInstance(startDate.year(), startDate.month(), startDate.day(), 00, 00, 00);
                    OperatingHours oh = workOrderOperatingHours.get(wo.FSL__VisitingHours__c);
                    DatetimeRecord woDates = new DatetimeRecord(startDateTime, startDateTime);

                    if(oh != null) {
                        woDates.opHours = oh;
                        woDates.emergency = wo.Emergency__c;
                        woDates.hasPestControlMonthly = false;
                        woDates = DatetimeRecord.getWODates(woDates, todaysDateTime);
                    }

                    clonedWo.StartDate = woDates.startDate;
                    clonedWo.EndDate = woDates.endDate;

                    //add wo, and corresponding line items to the map
                    String key = (String) wo.Id + (String) i;

                    woLineItemsMap.put(key, groupLineItemByProduct.get(i)); 
                    woMap.put(key, clonedWo); 
                }
            }
        }

        workOrderInsert.addAll(woMap.values());
        Database.SaveResult[] insertWOSR = Database.insert(workOrderInsert, false);
        
        if (!updateParentWorkOrders.isEmpty()) {
            update updateParentWorkOrders;
        }

        List<WorkOrderLineItem> insertLineItems = new List<WorkOrderLineItem>();

        //link new work order to cloned line items
        for (String s: woLineItemsMap.keySet()) {
            Id workOrderId = woMap.get(s).Id;

            for (WorkOrderLineItem li: woLineItemsMap.get(s)) {
                li.WorkOrderId = workOrderId;
                li.ParentWorkOrderLineItemId = null;
                insertLineItems.add(li);
            }
        }
        
        //now insert cloned line items
        Database.SaveResult[] insertWOLISR = Database.insert(insertLineItems, false);

        //update existing line items with the new cloned followup ids
        List<WorkOrderLineItem> updExistingLineItems = new List<WorkOrderLineItem>();
        
        //loop to update follow-up and new line item
        for (Id i : updLineItem.keySet()) {
            updExistingLineItems.add(new WorkOrderLineItem( Id=i, Follow_Up_Work_Order_Line_Item__c = updLineItem.get(i).Id ));
        }
        
        List<Batch_Errors__c> tErrorsList = new List<Batch_Errors__c>();

        //update existing line items
        if (!updExistingLineItems.isEmpty()) {
            //Begin:Shashi:10-21-2019: Changing this because upsert error is rolling back the batch
            Database.UpsertResult[] upsertExistinWOLineItems = Database.upsert(updExistingLineItems, false);
            
            for (Integer i = 0; i < upsertExistinWOLineItems.size(); i++) {
                if (!upsertExistinWOLineItems[i].isSuccess()) {//only look at failures, or NOT Successes
                    String errors = '';

                    for (Database.Error err : upsertExistinWOLineItems[i].getErrors()) {
                        errors = errors + err.getMessage();
                    }

                    WorkOrderLineItem woli = updExistingLineItems[i];

                    tErrorsList.add(new Batch_Errors__c(
                        Name=String.valueOf(System.today()), 
                        Error_Messages__c=errors, 
                        OrderId__c = woli.Id, 
                        OrderProductId__c = woli.Follow_Up_Work_Order_Line_Item__c, 
                        Failed_Batch__c = 'SpawnFollowUpWorkOrders'
                    ));
                }
        	}
            //End
        }
        
        for (Integer i = 0; i < insertWOSR.size(); i++) {
            if(!insertWOSR[i].isSuccess()){//only look at failures, or NOT Successes
                String errors = '';

                for (Database.Error err : insertWOSR[i].getErrors()) {
                    errors = errors + err.getMessage();
                }

                WorkOrder wo = workOrderInsert[i];

                tErrorsList.add(new Batch_Errors__c(
                    Name=String.valueOf(System.today()), 
                    Error_Messages__c = errors, 
                    StartTime__c = wo.StartDate, 
                    EndTime__c = wo.EndDate, 
                    OrderId__c = wo.Order__c, 
                    OperatingHoursId__c = wo.FSL__VisitingHours__c, 
                    Failed_Batch__c = 'SpawnFollowUpWorkOrders'
                ));
            }
        }
        
        for (Integer i = 0;i < insertWOLISR.size(); i++) {
            if (!insertWOLISR[i].isSuccess()) {//only look at failures, or NOT Successes
                String errors = '';

                for (Database.Error err : insertWOLISR[i].getErrors()) {
                    errors = errors + err.getMessage();
                }

                WorkOrderLineItem woli = insertLineItems[i];

                tErrorsList.add(new Batch_Errors__c(
                    Name=String.valueOf(System.today()), 
                    Error_Messages__c= errors, 
                    OrderId__c = woli.OrderId, 
                    OrderProductId__c = woli.Order_Product__c, 
                    Failed_Batch__c = 'SpawnFollowUpWorkOrders'
                ));
            }
        }
        
        insert tErrorsList;
    }

    global void finish(Database.BatchableContext bc){
        if(!Test.isRunningTest()){
            Database.executeBatch(new SpawnWorkOrderRooms(), 30);
        }
    }
}