force-app/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FrequencyInDays__c.field-meta.xml
<CustomField>
    <fullName>FrequencyInDays__c</fullName>
    <formula>CASE(Frequency__c,
&apos;One-Time&apos;, 0, 
&apos;Daily&apos;, 1,
&apos;6X Per Week&apos;, 2,
&apos;5X Per Week&apos;, 3,
&apos;4X Per Week&apos;, 4,
&apos;3X Per Week&apos;, 5,
&apos;2X Per Week&apos;, 6,
&apos;Weekly&apos;, 7, 
&apos;Fixed Weekly&apos;, 7,
&apos;14 Days&apos;, 14,
&apos;Twice Monthly&apos;, 15, 
&apos;28 Days&apos;, 28,
&apos;Monthly&apos;, 30, 
&apos;42 Days&apos;, 42,
&apos;56 Days&apos;, 56,
&apos;Bi-Monthly&apos;, 60,
&apos;84 Days&apos;, 84,
&apos;Quarterly&apos;, 90,
&apos;112 Days&apos;, 112,
&apos;120 Days&apos;, 120,
&apos;168 Days&apos;, 168,
&apos;Semi-Annually&apos;, 182,
&apos;2X Per Year&apos;, 182, 
&apos;182 Days&apos;, 182,
&apos;Annually&apos;, 365, 
0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FrequencyInDays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Installation_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Status__c</fullName>
    <inlineHelpText>Indicate if this is a new Asset Install, Removing(for seasonality purposes), Replacing(an old asset is replaced with a new one)</inlineHelpText>
    <label>Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Install/Repair Completed</fullName>
                <isActive>false</isActive>
                <label>Install/Repair Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Inventory_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inventory Allocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>PricebookEntry.IsActive  &amp;&amp;  PricebookEntry.Product2.IsActive &amp;&amp;  Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>This field is System Generated during the nightly Work Order Generation batch job. Changing this would have implications on Work Order Generation Logic</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <label>Last InFlight WO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Family)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Order Item cannot have the custom Order field set as it&apos;s Inactive.</errorMessage>
        <filterItems>
            <field>$Source.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Active Order Products without PO Number</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Valid_for_Install_Remove_Replace__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Install_Remove_Replace__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid for Install/Remove/Replace</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/Work_Order_Generation_Status__c.object-meta.xml
<CustomObject>
    <label>Work Order Generation Status</label>
    <nameField>
        <label>Work Order Generation Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Generation Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Installation_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Status__c</fullName>
    <formula>TEXT(Order_Product__r.Installation_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <formula>Order_Product__r.Last_Automation_Created_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Last_Automation_Created_Date_stamp__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date_stamp__c</fullName>
    <label>Last Automation Created Date stamp</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <formula>Order_Product__r.Last_InFlight_WO_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last InFlight WO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Last_InFlight_WO_Date_stamp__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date_stamp__c</fullName>
    <label>Last InFlight WO Date stamp</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Order Generation Status</relationshipLabel>
    <relationshipName>Work_Order_Generation_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order_Account_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Order_Account_Inactive__c</fullName>
    <label>Order Account Inactive</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order_Account_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Order_Account_On_Hold__c</fullName>
    <label>Order Account On Hold</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Work Order Generation Status</relationshipLabel>
    <relationshipName>Work_Order_Generation_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order_Product_Installation_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_Installation_Status__c</fullName>
    <label>Order Product Installation Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order_Product_Inventory_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_Inventory_Allocated__c</fullName>
    <label>Order Product Inventory Allocated</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order_Product_IsActive__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_IsActive__c</fullName>
    <label>Order Product IsActive</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Generation_Status__c/fields/Order_Product_Valid_for_Install_Replace__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_Valid_for_Install_Replace__c</fullName>
    <label>Order_Product Valid for Install Replace</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateWorkOrderGenerationStatus.cls
/*
    @Purpose : To generate WOGSL records on a daily basis and compare the start date of these WOGSL with 
              Work Orders.
    @Author  : Aieleeta      
*/
/*****************************************************NEW NEW NEW****************************/

public class CreateWorkOrderGenerationStatus{
    
    public static void CreateGenerationStatus(List<OrderItem> orderItemList){
        
        Integer noOfWogsl; // to hold the count of wogsl to be created
        List<Work_Order_Generation_Status__c> listCreateWOGSL = new List<Work_Order_Generation_Status__c>();

        /**** PART 1 : For all the incoming OrderItem, create the number of WOGSL based on Frequency*****/
        for(OrderItem oItem : orderItemList)
        {   
           system.debug('aaaaaaaaaaaa');
           Date ExpectedDate;
            // Taking the bigger of LACD / LIFD
            Date lastServicedDate = (oItem.Last_Automation_Created_Date__c > oItem.Last_InFlight_WO_Date__c)? oItem.Last_Automation_Created_Date__c :oItem.Last_InFlight_WO_Date__c ;           
            // Date to hold LSD+Frequency+Swing. This date will decide whethere Order Product will be considered or not
            if(lastServicedDate != null){
                ExpectedDate = lastServicedDate.addDays((oItem.FrequencyInDays__c).intValue());
                system.debug('bbbbbbbbb'+ ExpectedDate);
            }
                if(ExpectedDate != null){
                    system.debug('cccccccccccccccc');
                    if( ExpectedDate < System.Today().addDays(20)){
                        system.debug('ddddddddddd');
                        if(oItem.Frequency__c != null ){
                            system.debug('eeeeeeeeeeee');
                            if(oItem.FrequencyInDays__c >0){
                                noOfWogsl = GetCountofWOGSL(oItem.FrequencyInDays__c.intValue(),oItem);
                                system.debug('ffffffffff' + noOfWogsl);
                            }
                            if(noOfWogsl > 0){ // If WOGSL needs to be created
                                listCreateWOGSL.addAll(CreateWorkOrderGenerationStatusList(noOfWogsl,oItem,oItem.Order.AccountId)); // Create WOGSL via CreateWorkOrderGenerationStatusList()
                                system.debug('gggggggggg' + listCreateWOGSL);
                            }
                        }else{
                            continue;
                        }   
                    }
                }else{
                    continue;
                }
       
        }
        if(listCreateWOGSL.size() > 0){
            system.debug('hhhhhhhhhhhhh');
            //database.insert(listCreateWOGSL,false); // insert WOGSL.
            Database.SaveResult[] insertWOGS = Database.insert(listCreateWOGSL, false);
            system.debug('111111111111' + insertWOGS);
        }

    }
        /** METHOD TO CREATE WOGSL***/
    public static List<Work_Order_Generation_Status__c> CreateWorkOrderGenerationStatusList (Integer noOfWOGSL,OrderItem oItem, Id AccountId){
        system.debug('iiiiiiiiiiii');
        List<Work_Order_Generation_Status__c> listWorkOrderGenerationStatus = new List<Work_Order_Generation_Status__c>();
        List<Integer> listSwingNumber = new List<Integer>();
        listSwingNumber = GetFrequencySwing(oItem.Frequency__c,oItem.Line_of_Business__c);
        //Greater of LACD/LIFD
        Date lastServicedDate = (oItem.Last_Automation_Created_Date__c > oItem.Last_InFlight_WO_Date__c)? oItem.Last_Automation_Created_Date__c :oItem.Last_InFlight_WO_Date__c ; 
        // Date to hold LSD+Frequency+Swing. This date will decide whethere Order Product will be considered or not
        Date ExpectedDate = lastServicedDate.addDays((-listSwingNumber[0]) + ((oItem.FrequencyInDays__c).intValue()));
        Date CurrentDate = System.today();
        Map<Id,Id> mapOrderProductToAccount = new Map<Id,Id>();
        Map<Id,List<Boolean>> mapAccountDetails = new Map<Id,List<Boolean>>();
        
        if(listSwingNumber.size()>0 && ExpectedDate != null){
            system.debug('jjjjjjjjjjjjj' + ExpectedDate);
            for(Account a : [Select Inactive__c,On_Hold__c from Account where id =: AccountId]){
                mapAccountDetails.put(a.id,new List<Boolean>{a.On_Hold__c,a.Inactive__c});
                system.debug('kkkkkkkkkkkk' + mapAccountDetails);
            }
            for(integer i = 1; i <= noOfWOGSL; i++){
                    system.debug('lllllllllllllll');
                    Date ExpectedWOStartDate;
                    if(ExpectedDate < System.Today()){
                        ExpectedWOStartDate = (i == 1) ? CurrentDate : (CurrentDate.addDays((-listSwingNumber[0]) +(((oItem.FrequencyInDays__c).intValue())*(i-1))));
                    }else{
                        ExpectedWOStartDate = lastServicedDate.addDays((-listSwingNumber[0])+ (((oItem.FrequencyInDays__c).intValue())*(i)));
                    }
                    system.debug('mmmmmmmmmmmmmm' + ExpectedWOStartDate);
                    Work_Order_Generation_Status__c wogsl = new Work_Order_Generation_Status__c(
                                                                Order_Product__c = oItem.Id,
                                                                Order__c = oItem.OrderId,
                                                                Expected_WO_Start_Date__c = ExpectedWOStartDate,
                                                                Last_InFlight_WO_Date_stamp__c = String.valueOf(oItem.Last_InFlight_WO_Date__c),
                                                                Last_Automation_Created_Date_stamp__c = String.valueOf(oItem.Last_Automation_Created_Date__c),
                                                                Order_Status_Stamp__c = String.valueOf(oItem.Order.Status),
                                                                Order_Account_On_Hold__c = String.valueOf(mapAccountDetails.get(AccountId)[0]),
                                                                Order_Account_Inactive__c = String.valueOf(mapAccountDetails.get(AccountId)[1]),
                                                                Order_Product_Installation_Status__c = oItem.Installation_Status__c,
                                                                Order_Product_Valid_for_Install_Replace__c = String.valueOf(oItem.Valid_for_Install_Remove_Replace__c),
                                                                Order_Product_Active__c = String.valueOf(oItem.Active__c),
                                                                Order_Product_IsActive__c = String.valueOf(oItem.IsActive__c),
                                                                Order_Product_Inventory_Allocated__c = String.valueOf(oItem.Inventory_Allocated__c),
                                                                Order_Inventory_Allocated__c = String.valueOf(oItem.Order.Inventory_Allocated__c)
                                                                //Order_Product_Allowable_Frequency__c = oItem.Product2.Allowable_Frequencies__c
                                                                );
                                            
                    listWorkOrderGenerationStatus.add(wogsl);      
                    system.debug('nnnnnnnnnnnnnn' + listWorkOrderGenerationStatus);
            }
            
        }
        return listWorkOrderGenerationStatus; 
    }  
    
    
    /** METHOD TO GET THE COUNT OF WOGSL**/
    public static Integer GetCountofWOGSL(Integer frequency,OrderItem oItem){
        //Greater of LACD/LIFD
        Date lastServicedDate = (oItem.Last_Automation_Created_Date__c > oItem.Last_InFlight_WO_Date__c)? oItem.Last_Automation_Created_Date__c :oItem.Last_InFlight_WO_Date__c ; 
        List<Integer> listSwingNumber = new List<Integer>(); 
        listSwingNumber = GetFrequencySwing(oItem.Frequency__c,oItem.Line_of_Business__c);  
        // Date to hold LSD+Frequency+Swing. This date will decide whethere Order Product will be considered or not
        Date ExpectedDate = lastServicedDate.addDays((oItem.FrequencyInDays__c).intValue());
        //Final Date to decide number of WOGSL.
        Date FinalDateToDetermineCountWOGSL;
        Integer noOfWOGSL; // Integer to hold count of WOGS
        if(ExpectedDate < System.Today()){
            FinalDateToDetermineCountWOGSL = System.Today();
        }else{
            FinalDateToDetermineCountWOGSL = ExpectedDate;
        }       
        system.debug('oooooooooooooooo' + FinalDateToDetermineCountWOGSL);
        if(oItem.Last_InFlight_WO_Date__c > oItem.Last_Automation_Created_Date__c && !(oItem.Last_InFlight_WO_Date__c < System.Today())){
            noOfWOGSL = math.abs((System.Today().addDays(19).daysBetween(FinalDateToDetermineCountWOGSL))/frequency )+ 2;
        }else{
            noOfWOGSL = math.abs((System.Today().addDays(19).daysBetween(FinalDateToDetermineCountWOGSL))/frequency )+ 1;
        }   
        system.debug('ppppppppppppp' + noOfWOGSL);      
        return noOfWOGSL;    
    } 
    
    /** method to get frequency**/
    public static List<Integer> GetFrequencySwing(String frequency, String lob){
        Map<string, frequency__c> mapFrequencySwing = new map<string, frequency__c>();
        mapFrequencySwing = Frequency__c.getAll();
        if(lob == null){
            return null;
        } else if(lob == 'Chemical'){
            Frequency__c f = mapFrequencySwing.get(frequency);
            return new List<Integer>{(Integer)f.Chemical_Minus_Days__c, (Integer)f.Chemical_Plus_Days__c};  
        } else if(lob == 'Life Safety'){
            Frequency__c f = mapFrequencySwing.get(frequency);
            return new List<Integer>{ (Integer)f.Life_Safety_Minus_Days__c, (Integer)f.Life_Safety_Plus_Days__c };
        }else if(lob == 'Pest Control'){
            Frequency__c f = mapFrequencySwing.get(frequency);
            return new List<Integer>{ (Integer)f.Pest_Minus_Days__c, (Integer)f.Pest_Plus_Days__c };
        }else if (lob == 'Hygiene') {
            Frequency__c f = mapFrequencySwing.get(frequency);
            return new List<Integer>{ (Integer)f.Hygiene_Minus_Days__c, (Integer)f.Hygiene_Plus_Days__c };
        }else {
            return null;
        }
    }
}