force-app/main/default/objects/Account/fields/Pest_Control_OperatingHoursId__c.field-meta.xml
<CustomField>
    <fullName>Pest_Control_OperatingHoursId__c</fullName>
    <formula>BLANKVALUE( Pest_Control_Operating_Hours__c , OperatingHoursId )</formula>
    <label>Pest Control OperatingHoursId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PO_Required_for_Orders__c.field-meta.xml
<CustomField>
    <fullName>PO_Required_for_Orders__c</fullName>
    <label>PO Required for Orders</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PO Required Before</fullName>
            </value>
            <value>
                <fullName>PO Required After</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ServiceTerritory.ParentTerritoryId</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>ServiceTerritory.IsActive</field>
            <operation>notEqual</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Pest_Emergency_Order_Draft_Override__c.field-meta.xml
<CustomField>
    <fullName>Pest_Emergency_Order_Draft_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pest Emergency Order Draft Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Emergency.recordType-meta.xml
<RecordType>
    <fullName>Emergency</fullName>
    <active>true</active>
    <businessProcess>Emergency</businessProcess>
    <description>For Customer Emergency Services</description>
    <label>Emergency</label>
</RecordType>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/Emergency_Dispatch_Wizard_Setttings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Emergency Dispatch Wizard Setttings</label>
</CustomObject>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/fields/Service_Appointment_Minimum_Duration__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Minimum_Duration__c</fullName>
    <label>Service Appointment Minimum Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/fields/Work_Order_Multi_Res_Advance_Days__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Multi_Res_Advance_Days__c</fullName>
    <label>Work Order Multi-Res Advance Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Duration_Type_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Type_Minutes__c</fullName>
    <label>Duration Type Minutes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Label_for_Service_Work_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Label_for_Service_Work_Order_Type__c</fullName>
    <label>Label for Service Work Order Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Pest_LOB__c.field-meta.xml
<CustomField>
    <fullName>Pest_LOB__c</fullName>
    <label>Pest LOB</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Ticket_Closed_Status__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Closed_Status__c</fullName>
    <label>Ticket Closed Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Work_Order_Medium_Priority__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Medium_Priority__c</fullName>
    <label>Work Order Medium Priority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Work_Order_New_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_New_Status__c</fullName>
    <label>Work Order New Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Work_Order_Scheduled_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Scheduled_Status__c</fullName>
    <label>Work Order Scheduled Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Is_PO_Provided_by_Customer__c.field-meta.xml
<CustomField>
    <fullName>Is_PO_Provided_by_Customer__c</fullName>
    <formula>OR ( 
AND ( 
ISPICKVAL(Account.PO_Required_for_Orders__c, &quot;PO Required Before&quot;), 
Account.PO_Required_on_Line_Item__c = false, 
NOT(ISBLANK(PoNumber)) 
), 
AND ( 
ISPICKVAL(Account.PO_Required_for_Orders__c, &quot;PO Required Before&quot;), 
Account.PO_Required_on_Line_Item__c, 
Number_of_Order_Products_without_PO__c = 0 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is PO Provided by Customer (Before)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Line_of_Businesses__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Businesses__c</fullName>
    <label>Line of Businesses</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Number_of_Resources__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Resources__c</fullName>
    <label>Number of Resources</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Override_Account_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Override_Account_Operating_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Account Operating Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Service_Appointment_Scheduled_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Scheduled_Start_Time__c</fullName>
    <label>Service Appointment Scheduled Start Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ServiceTerritory.ParentTerritoryId</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>ServiceTerritory.IsActive</field>
            <operation>notEqual</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSL__VisitingHours__c.field-meta.xml
<CustomField>
    <fullName>FSL__VisitingHours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visiting Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Repair_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Repair_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repair Ticket</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey_Notes__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey_Notes__c</fullName>
    <label>Site Survey Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of Work Order, whether it is a delivery or a work order for a particular line of business</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Work Order</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>NoWork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SpawnPestEmergencyWorkOrders.cls
/**
* Name: SpawnPestEmergencyWorkOrders
* Author: PwC
* Date Created: April 23, 2019
* Purpose: To generate the Pest Emergency Work Order from the Emergency Dispatch Wizard app
*/
public class SpawnPestEmergencyWorkOrders {
    private static Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
    private static Emergency_Dispatch_Wizard_Setttings__c edws = Emergency_Dispatch_Wizard_Setttings__c.getOrgDefaults();
    private static final String DELIMITER = '~';
    
    /**
     * Generates Pest Emergency Service Appointments as specified
     * 
     * @param orderIds  represents all Orders to have Work Orders be generated 
     * @param emergencyTickets  the Emergenct Ticket selected in the Emergency Dispatch Wizard to close
     */
    public static Set<Id> generatePestEmergencyWorkOrders(Set<String> orderIds, List<Case> emergencyTickets, Decimal totalDuration) {
        Map<Id, WorkOrder> workOrdersToGenerate = new Map<Id, WorkOrder>();
        Map<Id, Account> accountMap = new Map<Id, Account>();
        Map<Id, Order> ordersToUpdate = new Map<Id, Order>();
        Set<Id> operatingHoursIds = new Set<Id>();
        Date maxServiceDate = System.today().addDays(Integer.valueOf(edws.Work_Order_Multi_Res_Advance_Days__c));
        
        for (Order o : [SELECT Id, EffectiveDate, AccountId, Site_Survey__c, OpportunityId, Account.OperatingHoursId, Account.Pest_Control_OperatingHoursId__c, Account.Service_Territory__c, Account.PO_Required_for_Orders__c, Number_of_Resources__c, Service_Territory__c, Pricebook2Id, Emergency__c, Site_Survey__r.Notes__c, ShipToContactId, Is_PO_Provided_by_Customer__c, Service_Appointment_Scheduled_Start_Time__c, Override_Account_Operating_Hours__c,
                        (SELECT Id, Status FROM Work_Orders__r ORDER BY CreatedDate DESC LIMIT 1)
                        FROM Order WHERE Id IN :orderIds AND Emergency__c = TRUE AND Line_of_Businesses__c = :dataSets.Pest_LOB__c])
        {
            if (o.EffectiveDate > maxServiceDate || o.EffectiveDate < System.today()) {
                continue;
            }
            
            WorkOrder existingWorkOrder = new WorkOrder();
            
            if (!o.Work_Orders__r.isEmpty()) {
                existingWorkOrder.Id = o.Work_Orders__r[0].Id;
                existingWorkOrder.Status = o.Work_Orders__r[0].Status;
            }
            
            Datetime startDate = Datetime.newInstance(o.EffectiveDate.year(), o.EffectiveDate.month(), o.EffectiveDate.day(), 00, 00, 00),
            		 endDate = Datetime.newInstance(o.EffectiveDate.year(), o.EffectiveDate.month(), o.EffectiveDate.day(), 23, 59, 59);
            
            accountMap.put(o.AccountId, o.Account);
            ordersToUpdate.put(o.Id, o);
            
            Decimal totalDurationForJob;
            
            //ensure the duration on the Work Order always has the minimum value
            if (totalDuration == null || totalDuration == 0) {
            	totalDurationForJob = o.Number_of_Resources__c * edws.Service_Appointment_Minimum_Duration__c;
            } else {
                totalDurationForJob = EDW_UtilityClass.calculateDurationInMinutes(totalDuration);
            }

            workOrdersToGenerate.put(o.Id, new WorkOrder(
                Id = existingWorkOrder.Id,
            	AccountId = o.AccountId,
                Opportunity__c = o.OpportunityId,
                Type__c = dataSets.Label_for_Service_Work_Order_Type__c,
                //Begin:Shashi:9-11-2019:Allows CS to exit without assigning SA
                //Status = String.isBlank(existingWorkOrder.Id) ? dataSets.Work_Order_Scheduled_Status__c : existingWorkOrder.Status,
                Status = String.isBlank(existingWorkOrder.Id) ? dataSets.Work_Order_New_Status__c : existingWorkOrder.Status,
                //End
                Line_of_Business__c = dataSets.Pest_LOB__c,
                Priority = dataSets.Work_Order_Medium_Priority__c,
                FSL__VisitingHours__c = o.Account.OperatingHoursId,
                ServiceTerritoryId = o.Service_Territory__c == null ? o.Account.Service_Territory__c : o.Service_Territory__c,
                Pricebook2Id = o.Pricebook2Id,
                Site_Survey__c = o.Site_Survey__c,
                Order__c = o.Id,
                Emergency__c = o.Emergency__c,
                Site_Survey_Notes__c = o.Site_Survey__r.Notes__c,
                ContactId = o.ShipToContactId,
                StartDate = startDate,
                EndDate = endDate,
                Duration = totalDurationForJob,
                DurationType = dataSets.Duration_Type_Minutes__c
            ));
        }
        
        workOrdersToGenerate.remove(null);
        accountMap.remove(null);
        ordersToUpdate.remove(null);
        
        Map<String, Id> accountLOBOperatingHoursMap = getLOBSpecificOperatingHours(accountMap);
        
        operatingHoursIds.addAll(accountLOBOperatingHoursMap.values());
        
        Map<Id, OperatingHours> workOrderOperatingHours = new Map<Id, OperatingHours>([SELECT Id, Name, TimeZone, 
                                                                                       (SELECT Id, DayOfWeek, StartTime, EndTime FROM TimeSlots ORDER BY DayOfWeek, StartTime, EndTime) 
                                                                                       FROM OperatingHours WHERE Id IN :operatingHoursIds]);
        
        //date manipulation
        for (WorkOrder wo : workOrdersToGenerate.values()) {
            String key = wo.accountId + DELIMITER + wo.Line_of_Business__c;
            OperatingHours oh = workOrderOperatingHours.get(accountLOBOperatingHoursMap.get(key));
            
            Datetime startDate =  Datetime.newInstance(wo.StartDate.year(), wo.StartDate.month(), wo.StartDate.day(), 00, 00, 00);
            Datetime endDate =  Datetime.newInstance(wo.EndDate.year(), wo.EndDate.month(), wo.EndDate.day(), 23, 59, 59);
            
            DatetimeRecord woDates = new DatetimeRecord(startDate, endDate);
            
            if (oh != null) {
                woDates.opHours = oh;
                woDates.emergency = wo.Emergency__c;
                woDates.hasPestControlMonthly = false;
                woDates = DatetimeRecord.getWODates(woDates, System.now());
            }
            
            wo.StartDate = woDates.startDate;
            wo.EndDate = woDates.endDate;
            
            Order orderOnWorkOrder = ordersToUpdate.get(wo.Order__c);
            
            if (orderOnWorkOrder.Override_Account_Operating_Hours__c) {
                String[] timeValues = orderOnWorkOrder.Service_Appointment_Scheduled_Start_Time__c.split('\\:');
                Time overrideTime = Time.newInstance(Integer.valueOf(timeValues[0]), Integer.valueOf(timeValues[1]), 0, 0);
                                
                wo.StartDate = DateTime.newInstance(wo.StartDate.year(), wo.StartDate.month(), wo.StartDate.day(), overrideTime.hour(), overrideTime.minute(), overrideTime.second());
            }
        }
        
        if (workOrdersToGenerate.size() > 0) {
        	upsert workOrdersToGenerate.values();

            closeEmergencyTickets(emergencyTickets);
            
            Set<Id> workOrderIds = new Set<Id>();
            
            for (WorkOrder wo : workOrdersToGenerate.values()) {
                workOrderIds.add(wo.Id);
            }
            
            return workOrderIds;
        }
        
        return null;
    }
    
    /**
     * Retrieves a map of the main Operating Hours on the Account, along with the Pest Control Operating Hours
     * 
     * @param accountMap  all Accounts that require retrieval of their regular Operating Hours and Pest Control Operating Hours
     */
    private static Map<String, Id> getLOBSpecificOperatingHours(Map<Id, Account> accountMap) {
        Map<String, Id> accountLOBOperatingHoursMap = new Map<String, Id>();
        
        if (!accountMap.isEmpty()) {
            for (Account a : accountMap.values()) {
                accountLOBOperatingHoursMap.put(a.Id + DELIMITER + dataSets.Pest_LOB__c, a.Pest_Control_OperatingHoursId__c);
                accountLOBOperatingHoursMap.put(String.valueOf(a.Id), a.OperatingHoursId);
            }
        }
        
        accountLOBOperatingHoursMap.remove(null);
        
        return accountLOBOperatingHoursMap;
    }
    
    /**
     * Closes all specified Emergency Tickets
     * 
     * @param emergencyTickets  the Emergenct Ticket selected in the Emergency Dispatch Wizard to close
     */
    private static void closeEmergencyTickets(List<Case> emergencyTickets) {
        if (emergencyTickets != null && !emergencyTickets.isEmpty()) {
            Map<Id, Case> casesToUpdate = new Map<Id, Case>();
            
            for (Case c : emergencyTickets) {
                if (c == null) { continue; }
                
                c.Pest_Emergency_Order_Draft_Override__c = true;
                c.Status = dataSets.Ticket_Closed_Status__c;
                casesToUpdate.put(c.Id, c);
            }
            
            if (!casesToUpdate.isEmpty()) {
                Database.update(casesToUpdate.values(), false);
            }
        }
    }
}