force-app/main/default/objects/Account/fields/Require_Service_Reports__c.field-meta.xml
<CustomField>
    <fullName>Require_Service_Reports__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Require Service Reports</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/VMI__c.field-meta.xml
<CustomField>
    <fullName>VMI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VMI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Chemical_LOB__c.field-meta.xml
<CustomField>
    <fullName>Chemical_LOB__c</fullName>
    <label>Chemical LOB</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Hygiene_LOB__c.field-meta.xml
<CustomField>
    <fullName>Hygiene_LOB__c</fullName>
    <label>Hygiene LOB</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Life_Safety_LOB__c.field-meta.xml
<CustomField>
    <fullName>Life_Safety_LOB__c</fullName>
    <label>Life Safety LOB</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Pest_LOB__c.field-meta.xml
<CustomField>
    <fullName>Pest_LOB__c</fullName>
    <label>Pest LOB</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Customer_Signature_Captured__c.field-meta.xml
<CustomField>
    <fullName>Customer_Signature_Captured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Signature Captured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Is_Signature_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Signature_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>*******READ THIS******** If the logic that sets this value is changed (currently done via ServiceAppointmentSignatureUtilities) then you must also make the same logic change on the formula field here: WorkOrder.Signature_Required__c</description>
    <label>Signature Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Line_Of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business__c</fullName>
    <label>Line Of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/ServiceReportAlreadySent__c.field-meta.xml
<CustomField>
    <fullName>ServiceReportAlreadySent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ServiceReportAlreadySent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Should_Auto_Generate_Service_Report__c.field-meta.xml
<CustomField>
    <fullName>Should_Auto_Generate_Service_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Should Auto Generate Service Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Should_Auto_Send_Service_Report__c.field-meta.xml
<CustomField>
    <fullName>Should_Auto_Send_Service_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Should Auto Send Service Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Signature_Not_Captured_Reason__c.field-meta.xml
<CustomField>
    <fullName>Signature_Not_Captured_Reason__c</fullName>
    <label>Signature Not Captured Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Service Appointment</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Signature_Required_For__c.field-meta.xml
<CustomField>
    <fullName>Signature_Required_For__c</fullName>
    <inlineHelpText>The system always checks Pest Control SAs for signatures, even if Pest line of business is not selected here.  Additionally, system always checks if signature was captured for: 

-Deliveries

-VMI Account SAs

-SAs with Products Consumed</inlineHelpText>
    <label>Signature Required For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of Work Order, whether it is a delivery or a work order for a particular line of business</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Work Order</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>NoWork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceAppointmentSignatureUtilities.cls
/*
 * Provides utility methods for Service Appointment signature-related
 * logic
 * 
 * @author Ahsan Butt
 */
public class ServiceAppointmentSignatureUtilities {
    private static final String TYPE_DELIVERY = 'Delivery';
    
    // Note: This string should be kept up to date with Service Appointment fields used in the IsSignaturedRequired method,
    // 		 as this method is also being called from a non-trigger context outside this class.  
    // 		 Although not ideal, this provides a modicum of safety against breaking the other calling context, if this logic
    // 		 is modified to require a different field. This was the mechanism settled on between myself and Kevin Hiscock (PwC) 1/18/2019 
    public static final String SA_REQUIRED_FIELDS_FOR_SIGNATURE_CHECK = 'Id, ParentRecordId, AccountId, Line_Of_Business__c, Type__c';
    
    public static Map<Id, Boolean> isSignatureRequired(List<ServiceAppointment> sas) {
        Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
        system.debug('sas ' + sas);
        // Query related objs to determine if a signature was captured and whether one was required
        List<Id> saIds = new List<Id>();
        List<Id> woIds = new List<Id>();
        List<Id> acctIds = new List<Id>();

        for (ServiceAppointment sa : sas) {
            saIds.add(sa.Id);
            woIds.add(sa.ParentRecordId);
            acctIds.add(sa.AccountId);
        }
        
        Map<Id, Account> acctMap = new Map<Id, Account>([
                SELECT Id, Site_Survey__r.Signature_Required_For__c, Require_Service_Reports__c, VMI__c
                FROM Account
                WHERE Id IN :acctIds
        ]);

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>([
                SELECT Id,
                        (SELECT Id FROM ProductsConsumed)
                FROM WorkOrder
                WHERE Id IN :woIds
        ]);
        
        Map<Id, Boolean> isSignatureRequiredMap = new Map<Id, Boolean>();
        
		for (ServiceAppointment sa : sas) {            
            // Check all signature required conditions
            Account relatedAcct = acctMap.get(sa.AccountId);
            WorkOrder relatedWO = woMap.get(sa.ParentRecordId);
            
            // Get line of businesses that require signature (according to account)
            Set<String> lobsRequiringSignature = new Set<String>();

            if (relatedAcct != null
                    && relatedAcct.Site_Survey__c != null
                    && String.isNotBlank(relatedAcct.Site_Survey__r.Signature_Required_For__c) )
            {
                lobsRequiringSignature.addAll(relatedAcct.Site_Survey__r.Signature_Required_For__c.split(';'));
            }            
            
            Boolean isSignatureRequired = false;

            if(sa.Line_Of_Business__c == dataSets.Pest_LOB__c
                    || lobsRequiringSignature.contains(sa.Line_Of_Business__c)
                    || sa.Type__c == TYPE_DELIVERY
                    || (relatedAcct != null
                        && relatedAcct.VMI__c)
                    || (relatedWO.ProductsConsumed != null
                        && relatedWO.ProductsConsumed.size() > 0 ))
            {
                isSignatureRequired = true;
            }
            
            isSignatureRequiredMap.put(sa.Id, isSignatureRequired);
        }
        
        return isSignatureRequiredMap;
    }
    
    /* Does *not* persist changes to SA records */
   /* public static void setSignatureFields(List<ServiceAppointment> completedSAs) {
    	Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
        
        // Query related objs
        List<Id> saIds = new List<Id>();
        List<Id> acctIds = new List<Id>();

        for (ServiceAppointment sa : completedSAs) {
            saIds.add(sa.Id);
            acctIds.add(sa.AccountId);
        }
        
        Map<Id, Account> acctMap = new Map<Id, Account>([
                SELECT Id, Require_Service_Reports__c
                FROM Account
                WHERE Id IN :acctIds
        ]);

        List<ServiceReport> srs = [
                SELECT Id, ParentId
                FROM ServiceReport
                WHERE ParentId IN :saIds AND IsSigned = TRUE
        ];
        
        Set<Id> signedSR = new Set<Id>();
        for (ServiceReport sr : srs) {
            signedSR.add(sr.ParentId);
        }
        
        // Check all signature required conditions
        Map<Id, Boolean> isSignatureRequiredMap = isSignatureRequired(completedSAs);
        
        for (ServiceAppointment sa : completedSAs) {
            
            sa.Customer_Signature_Captured__c = signedSR.contains(sa.Id);
            
            Account relatedAcct = acctMap.get(sa.AccountId);
            
            // Set is signature required field
            sa.Is_Signature_Required__c = isSignatureRequiredMap.get(sa.Id);
            
            // If signature is required, was not captured, and reason not given -- display error
            Boolean validReasonRequiredAndGiven = false;
            if (sa.Is_Signature_Required__c && !sa.Customer_Signature_Captured__c) {
                if (String.isBlank(sa.Signature_Not_Captured_Reason__c)) {
                	sa.Signature_Not_Captured_Reason__c.addError(Label.Signature_Required_And_Reason_Not_Given_Error_Message);    
                } else if (sa.Signature_Not_Captured_Reason__c.length() < 10) {
                    sa.Signature_Not_Captured_Reason__c.addError(Label.Signature_Required_And_Reason_Too_Short_Message); 
                } else {
                    validReasonRequiredAndGiven = true;
                }
            }
            
            // Also set auto-send and auto-gen fields
            sa.Should_Auto_Generate_Service_Report__c = !sa.ServiceReportAlreadySent__c
                                                        && ((sa.Line_Of_Business__c == dataSets.Pest_LOB__c
                                                                || sa.Line_Of_Business__c == dataSets.Hygiene_LOB__c)
                                                            || ((!sa.Is_Signature_Required__c
                                                                    || sa.Customer_Signature_Captured__c
                                                                    || validReasonRequiredAndGiven)
                                                                && (relatedAcct != null
                                                                    && relatedAcct.Require_Service_Reports__c
                                                                    && (sa.Line_Of_Business__c == dataSets.Chemical_LOB__c
                                                                        || sa.Line_Of_Business__c == dataSets.Life_Safety_LOB__c))));
            
			sa.Should_Auto_Send_Service_Report__c = !sa.ServiceReportAlreadySent__c
                                                    && (sa.Line_Of_Business__c == dataSets.Pest_LOB__c
                                                        || ((!sa.Is_Signature_Required__c
                                                                || sa.Customer_Signature_Captured__c
                                                                || validReasonRequiredAndGiven)
                                                            && (relatedAcct != null
                                                                && relatedAcct.Require_Service_Reports__c
                                                                && (sa.Line_Of_Business__c == dataSets.Hygiene_LOB__c
                                                                    || sa.Line_Of_Business__c == dataSets.Chemical_LOB__c
                                                                    || sa.Line_Of_Business__c == dataSets.Life_Safety_LOB__c))));
        }
    }*/
}