force-app/main/default/objects/Account/fields/SalesPricebookId__c.field-meta.xml
<CustomField>
    <fullName>SalesPricebookId__c</fullName>
    <formula>BLANKVALUE( Sales_Pricebook__c,  $Setup.Field_Service_Settings__c.Default_Opportunity_Price_Book_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Pricebook Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Site_Survey__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Related_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>&quot;Related Product : Active = true</errorMessage>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Service_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Service_Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <formula>Opportunity.Site_Survey__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Survey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/Survey_Asset_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Asset Location</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>Survey Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Asset Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Originating_Parent_ID__c.field-meta.xml
<CustomField>
    <fullName>Originating_Parent_ID__c</fullName>
    <externalId>true</externalId>
    <label>Originating Parent ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Related_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Survey Asset Locations (Related Product)</relationshipLabel>
    <relationshipName>Survey_Asset_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Service_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Service_Frequency__c</fullName>
    <label>Service Frequency</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Survey Asset Locations</relationshipLabel>
    <relationshipName>Survey_Asset_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISBLANK(Survey_Location__c ), &quot;Unallocated&quot;, &quot;Allocated&quot;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityValidationWrapper.cls
/**
 * @FileName: OpportunityValidationWrapper
 * @Description: Wrapper class for validating opportunity records and related data
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       3/18/2020         Created
 * Sidhartha		 04/21/2021		   Moved validateAccount() logic to validation rule
 * Darcy             5/5/2021          Bugfix in validateOpportunitiesBeforeUpdate for Existing Service Subcategory record type
 * Darcy             6/21/2021         validation for contact role, inactive products and invalid freq bypassed for System Administrator profile 
 *                                     replaced error message strings with custom labels
 *-----------------------------------------------------------  
 * 
 */
public inherited sharing class OpportunityValidationWrapper {
    // Trigger Data
    private List<Opportunity> opportunityRecords;
    private Map<Id, Opportunity> oldMap;
    private Map<Id, Opportunity> opportunityMap;
    private OpportunityTriggerDataWrapper dataWrapper;

    // Comparison Data
    private Set<Id> siteSurveyErrors;
    private Set<Id> accountIds;

    public OpportunityValidationWrapper(List<Opportunity> opportunityRecords, Map<Id, Opportunity> oldMap, OpportunityTriggerDataWrapper dataWrapper) {
        this(opportunityRecords, oldMap, dataWrapper, null);
    }

    public OpportunityValidationWrapper(List<Opportunity> opportunityRecords, Map<Id, Opportunity> oldMap, OpportunityTriggerDataWrapper dataWrapper, Map<Id,Opportunity> opportunityMap) {
        this.opportunityRecords = opportunityRecords;
        this.oldMap = oldMap;
        this.opportunityMap = opportunityMap;
        this.dataWrapper = dataWrapper;

        this.siteSurveyErrors = new Set<Id>();
        this.accountIds = new Set<Id>();
    }

    // Controller Methods

    public void validateOpportunitiesBeforeInsert() {
        TriggerHelper.checkIfInsert = true;
        for (Opportunity opp : opportunityRecords) {
            if(opp.RecordTypeId != QueryUtils.fieldServiceSettings.Opportunity_RecordType_Frequency_Change__c) {
                if (opp.StageName == QueryUtils.fieldServiceSettings.Opportunity_To_Order_Creation_Stage_Name__c) {
                    validateClosedWonStage(opp);
                    validateSiteSurvey(opp);
                }
            }
            else {
                checkOrderCreationStage(opp);
            }
        }

        for(Opportunity opp : opportunityRecords) {
            Account a = dataWrapper.accountMap.get(opp.AccountId);

            if (a == null) continue;

            //validateAccount(opp, a);
        }
    }
    
    
    List<OpportunityContactRole> lstOcr = new  List<OpportunityContactRole>();
    Boolean checkEmptyRole = false;
    public void validateIfOCRisPresent(List<Opportunity> opportunityRecords, Map<Id, Opportunity> oldMap) {
        if(QueryUtils.fieldServiceSettings.System_Administrator_Profile_Id__c == UserInfo.getProfileId()){
        	return;
        }
        for(OpportunityContactRole ocr: [SELECT Id, Role FROM OpportunityContactRole WHERE OpportunityId IN :opportunityRecords]) {
            lstOcr.add(ocr);
            If(ocr.Role == null) {
                checkEmptyRole = true;
            }
        }
        if(lstOcr.size() == 0 || checkEmptyRole) {
            for (Opportunity opp : opportunityRecords) { 
                //Darcy 2021-05-27 exception for ownership changes
               	Opportunity oldRec = oldMap.get(opp.Id);
            	Boolean ownerChange = opp.OwnerId != oldRec.OwnerId;
                if(!TriggerHelper.checkIfInsert && !ownerChange)
                    opp.addError(Label.OCREmptyCheck);
            }
        }
    }

    public void validateOpportunitiesBeforeUpdate() {
        for (Opportunity opp : opportunityRecords) {
            Opportunity oldRec = oldMap.get(opp.Id);

            Boolean stageChange = opp.StageName != oldRec.StageName;

            if(QueryUtils.fieldServiceSettings.System_Administrator_Profile_Id__c != UserInfo.getProfileId()){
                checkForInactiveLineItems(opp);

                if(stageChange) {
                    checkPrimaryContact(opp);
                    validateLineItemFrequency(opp);
                }
            }

            if (opp.RecordTypeId != QueryUtils.fieldServiceSettings.Opportunity_RecordType_Frequency_Change__c) {
                if(stageChange) {
                    if (opp.StageName == QueryUtils.fieldServiceSettings.Opportunity_To_Order_Creation_Stage_Name__c) {
                        validateClosedWonStage(opp);

                        if(oldRec.StageName != QueryUtils.fieldServiceSettings.Opportunity_Case_Creation_Stage_Name__c) {
                            validateSiteSurveyApproval(opp);
                        }

                        validateSiteSurvey(opp);
                    }
                }
            }
            else if (oldRec.StageName != QueryUtils.fieldServiceSettings.Opportunity_Frequency_Change_Stage_Name__c
                    && oldRec.StageName != QueryUtils.fieldServiceSettings.Opportunity_To_Order_Creation_Stage_Name__c) {
                //Darcy 2021-05-05 previously signed opp will not trigger the checkOrderCreationStage validation for Freq Change Stage name 
                checkOrderCreationStage(opp);
            }
        }

        checkSiteSurveyErrors(siteSurveyErrors);

        for(Opportunity opp : opportunityRecords) {
            Account a = dataWrapper.accountMap.get(opp.AccountId);

            if (a == null) continue;

            Opportunity oldRec = oldMap.get(opp.Id);


            if(opp.Pricebook2Id != oldRec.Pricebook2Id) {
                validatePricebookChange(opp, a);
            }
        }
    }

    // Constructor Helpers

    private void instantiateInsertVariables() {}
    private void instantiateUpdateVariables() {}

    // Helper Methods

    private void checkForInactiveLineItems(Opportunity opp) {
        Opportunity oppComplete = dataWrapper.opportunityMap.get(opp.Id);

        if(oppComplete.OpportunityLineItems.isEmpty()) return;

        if (checkLineItems(oppComplete)) {
            opp.addError(System.Label.Inactive_Products);
        }
    }

    //Deactivated Products Validation Rule - Irfan - 22-Oct-2019
    private Boolean checkLineItems(Opportunity opp) {
        for (OpportunityLineItem oppLineItem : opp.OpportunityLineItems) {
            if (!oppLineItem.Product2.IsActive
                    || (oppLineItem.Related_Product__c != null
                        && !oppLineItem.Related_Product__r.IsActive))
            {
                return true;
            }
        }

        return false;
    }

    private void checkPrimaryContact(Opportunity opp) {
        if (opp.StageName == QueryUtils.fieldServiceSettings.Opportunity_Case_Creation_Stage_Name__c
                || opp.StageName == QueryUtils.fieldServiceSettings.Opportunity_Frequency_Change_Stage_Name__c) {        
            if(dataWrapper.opportunityMap.get(opp.Id).OpportunityContactRoles.isEmpty()) {
                //Please associate at least one contact from this ship-to account to the
                //Contact Roles Related List and mark them as primary,
                //before moving to one of the closed won stages
                String error = System.Label.Contact_Role_Missing;

                opp.addError(error);
            }

            siteSurveyErrors.add(opp.Id);
        }
    }

    private void checkOrderCreationStage(Opportunity opp) {
        system.debug('Opportunity_To_Order_Creation_Stage_Name__c ' + opp.StageName);
        if (opp.StageName != QueryUtils.fieldServiceSettings.Opportunity_To_Order_Creation_Stage_Name__c) return;

        String error = 'Please choose the stage: ' +
                QueryUtils.fieldServiceSettings.Opportunity_Frequency_Change_Stage_Name__c +
                ' to indicate that Opportunity is closed won';

        opp.addError(error);
    }

    private void validateClosedWonStage(Opportunity opp) {
        if (OpportunityConstants.SIGNED_STAGE_ACCESSIBLE.contains(UserInfo.getProfileId())) return;

        String error = 'Please use Closed/Won Stage: ' +
                QueryUtils.fieldServiceSettings.Opportunity_Case_Creation_Stage_Name__c +
                ' to indicate Opportunity is Closed/Won';

        opp.addError(error);
    }

    private void validateSiteSurveyApproval(Opportunity opp) {
        String error = 'You cannot choose ' +
                QueryUtils.fieldServiceSettings.Opportunity_To_Order_Creation_Stage_Name__c +
                ' stage without undergoing Site Survey Approval Process. Choose stage ' +
                QueryUtils.fieldServiceSettings.Opportunity_Case_Creation_Stage_Name__c +
                ' to submit for Site Survey Approval';

        opp.addError(error);
    }


    private void validateSiteSurvey(Opportunity opp) {
        if (opp.StageName != QueryUtils.fieldServiceSettings.Opportunity_Case_Creation_Stage_Name__c
                || opp.Site_Survey__c != null)
        {
        	return;
        }
        String error = System.Label.Site_Survey_Missing;
        opp.addError(error);
    }

    private void checkSiteSurveyErrors(Set<Id> oppIds) {
        List<AggregateResult> results = [
                SELECT COUNT(Id) c, Originating_Parent_ID__c opp
                FROM Survey_Asset_Location__c
                WHERE Originating_Parent_ID__c != NULL
                AND Originating_Parent_ID__c IN :oppIds
                AND Status__c = 'Unallocated'
                GROUP BY Originating_Parent_ID__c
        ];

        for (AggregateResult a : results) {

            String error = String.format(System.Label.Site_Survey_Incomplete, new List<String>{String.valueOf(a.get('c'))});
            /*
            'There are ' +
            String.valueOf(a.get('c')) +
            ' Survey Asset Locations that are unallocated for this Opportunity. ' +
            'Please allocate these items before selecting this Stage.';
            */
            opportunityMap.get(String.valueOf(a.get('opp'))).addError(error);
        }
    }

    private void validateLineItemFrequency(Opportunity opp) {
        Opportunity oppComplete = dataWrapper.opportunityMap.get(opp.Id);

        Integer count = 0;

        for(OpportunityLineItem oli : oppComplete.OpportunityLineItems) {
            if(String.isBlank(oli.Service_Frequency__c)) count++;
        }

        if(count > 0) {
            opp.addError(String.format(System.Label.OLI_Missing_Frequency, new List<String>{String.valueOf(count)}));
                /*'There are ' +
                    count +
                    ' Opportunity Line Items with no Frequency. ' +
                    'Please fill in frequency for all line items before selecting this stage. '
                */
        }
    }

    private void validatePricebookChange(Opportunity opp, Account a) {
        if (opp.Pricebook2Id != null
                && opp.Pricebook2Id != a.SalesPricebookId__c
                && QueryUtils.fieldServiceSettings.System_Administrator_Profile_Id__c != UserInfo.getProfileId()
                && QueryUtils.fieldServiceSettings.Integration_User_Profile__c != UserInfo.getProfileId())
        {
            opp.addError(System.Label.Pricebook_Cannot_Be_Changed);
        }
    }
}