force-app/main/default/objects/Account/fields/Service_Types__c.field-meta.xml
<CustomField>
    <fullName>Service_Types__c</fullName>
    <description>Mapping of associated active Order&apos;s Service Types values retrieved and updated via Apex scheduled jobs.</description>
    <label>Service Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anti Splash</fullName>
            </value>
            <value>
                <fullName>Apron/Bar Rentals</fullName>
            </value>
            <value>
                <fullName>AromaAire</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Bird Work</fullName>
            </value>
            <value>
                <fullName>Chemical Dispenser</fullName>
            </value>
            <value>
                <fullName>Diaper</fullName>
            </value>
            <value>
                <fullName>Disposal Exchange</fullName>
            </value>
            <value>
                <fullName>Disposal Onsite</fullName>
            </value>
            <value>
                <fullName>EcoClean</fullName>
            </value>
            <value>
                <fullName>EcoFresh</fullName>
            </value>
            <value>
                <fullName>First Aid/AED</fullName>
            </value>
            <value>
                <fullName>Fly Light</fullName>
            </value>
            <value>
                <fullName>FreshAire</fullName>
            </value>
            <value>
                <fullName>Kaivac - STI</fullName>
            </value>
            <value>
                <fullName>Mat Rentals</fullName>
            </value>
            <value>
                <fullName>Pest</fullName>
            </value>
            <value>
                <fullName>Pest Special</fullName>
            </value>
            <value>
                <fullName>Rental Mop</fullName>
            </value>
            <value>
                <fullName>SaniClean</fullName>
            </value>
            <value>
                <fullName>Sani - Fixture Cleaning</fullName>
            </value>
            <value>
                <fullName>Sani Restore</fullName>
            </value>
            <value>
                <fullName>Service Charges</fullName>
            </value>
            <value>
                <fullName>Soap</fullName>
            </value>
            <value>
                <fullName>Toilet Seat Sanitizer</fullName>
            </value>
            <value>
                <fullName>Vending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Batch_Job_Results__c/Batch_Job_Results__c.object-meta.xml
<CustomObject>
    <label>Batch Job Results</label>
    <nameField>
        <label>Batch Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Job_Results__c/fields/Total_Errors__c.field-meta.xml
<CustomField>
    <fullName>Total_Errors__c</fullName>
    <label>Total Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Order_Active_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Active_Stage__c</fullName>
    <label>Order Active Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Service_Types__c.field-meta.xml
<CustomField>
    <fullName>Service_Types__c</fullName>
    <description>Mapping of associated Order Product&apos;s Product Code to defined Service Type. Value is to be retrieved and updated to the Order.Service_Type__c field then to Account.Service_Type__c multi-select picklist fields via Apex scheduled jobs.</description>
    <label>Service Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anti Splash</fullName>
            </value>
            <value>
                <fullName>Apron/Bar Rentals</fullName>
            </value>
            <value>
                <fullName>AromaAire</fullName>
            </value>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Bird Work</fullName>
            </value>
            <value>
                <fullName>CannonClean</fullName>
            </value>
            <value>
                <fullName>CannonControl</fullName>
            </value>
            <value>
                <fullName>CannonFresh</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Chemical Dispenser</fullName>
            </value>
            <value>
                <fullName>Diaper</fullName>
            </value>
            <value>
                <fullName>Disposal</fullName>
            </value>
            <value>
                <fullName>Disposal Exchange</fullName>
            </value>
            <value>
                <fullName>Disposal Onsite</fullName>
            </value>
            <value>
                <fullName>EcoClean</fullName>
            </value>
            <value>
                <fullName>EcoFresh</fullName>
            </value>
            <value>
                <fullName>Ecolo</fullName>
            </value>
            <value>
                <fullName>First Aid/AED</fullName>
            </value>
            <value>
                <fullName>Fly Light</fullName>
            </value>
            <value>
                <fullName>FreshAire</fullName>
            </value>
            <value>
                <fullName>Kaivac - STI</fullName>
            </value>
            <value>
                <fullName>Life</fullName>
            </value>
            <value>
                <fullName>Mat Rentals</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pest</fullName>
            </value>
            <value>
                <fullName>Pest Special</fullName>
            </value>
            <value>
                <fullName>Rental Mop</fullName>
            </value>
            <value>
                <fullName>SaniClean</fullName>
            </value>
            <value>
                <fullName>Sani - Fixture Cleaning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Type_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Service_Type_Mapping__c</fullName>
    <description>Mapping of associated Product Code to defined Service Type.  Value is to be retrieved and updated to the Order.Service_Type__c field then to Account.Service_Type__c multi-select picklist fields via Apex scheduled jobs.</description>
    <formula>IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-03&quot;), &quot;Soap&quot;, 
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-04&quot;), &quot;AromaAire&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-05&quot;), &quot;Vending&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-08&quot;), &quot;Automation&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-11-03&quot;), &quot;Sani - Fixture Cleaning&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-11-13&quot;), &quot;Toilet Seat Sanitizer&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-11-14&quot;), &quot;Kaivac - STI&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-11-20&quot;), &quot;Anti Splash&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-14&quot;), &quot;First Aid/AED&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-16&quot;), &quot;Service Charges&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-20-23&quot;), &quot;Diaper&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-20-22&quot;), &quot;Diaper&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-20&quot;), &quot;Disposal Onsite&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-21&quot;), &quot;Disposal Exchange&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-30&quot;), &quot;EcoFresh&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-31&quot;), &quot;EcoClean&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-32&quot;), &quot;FreshAire&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-39&quot;), &quot;EcoClean&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-40&quot;), &quot;Mat Rentals&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-41&quot;), &quot;Apron/Bar Rentals&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-42&quot;), &quot;SaniClean&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-43&quot;), &quot;Rental Mop&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-44&quot;), &quot;Sani Restore&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-50&quot;), &quot;Pest&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-53&quot;), &quot;Fly Light&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-54&quot;), &quot;Bird Work&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-55&quot;), &quot;Pest Special&quot;,
IF(BEGINS (PricebookEntry.Product2.ProductCode, &quot;1-60&quot;), &quot;Chemical Dispenser&quot;,
NULL))))))))))))))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Type Mapping</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderServiceTypeRollupBatchJobImpl.cls
/**
 * Implements Batchable interface. Contains logic specific to Service Type rollup functionality, and includes logic for persisting 
 * Batch Job Results record at the end of the run. Actual rollup logic is delegated to appropriate IRollupBatchExecutor impl.
 * 
 * @author Ahsan Butt
 */
global class OrderServiceTypeRollupBatchJobImpl implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
	global String batchJobName;
    global RollupState state;
    
    global String sourceObject;
    global String sourceField;
    global String mergeField;
    global String targetObject;
    global String targetField;
    global String filter;
    global String function;
    
    global Integer accountRollupBatchSize;
    
    global Integer totalRecords;
    global Integer errors;
    global String notes;
    
    global OrderServiceTypeRollupBatchJobImpl(String jobName, Integer acctRollupBatchSize) {
        Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
        
        batchJobName = jobName;
        state = new RollupState();

        sourceObject = 'OrderItem';
        sourceField = 'Service_Type_Mapping__c';
        mergeField = 'OrderId';
        targetObject = 'Order';
        targetField = 'Service_Types__c';
        filter = 'Order.Status = \'' + dataSets.Order_Active_Stage__c + '\' AND Active__c = true';
        function = 'CONCAT';        
        
        accountRollupBatchSize = acctRollupBatchSize;
        
        totalRecords = 0;
        errors = 0;
        notes = '';
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {        
        // Get last batch job run
    	List<Batch_Job_Results__c> batchJobRuns = [SELECT Id, CreatedDate 
                                                   FROM Batch_Job_Results__c 
                                                   WHERE Name =: batchJobName ORDER BY CreatedDate DESC];
        Batch_Job_Results__c lastRun;
        DateTime lastRunDT;
        
        if (batchJobRuns != null && batchJobRuns.size() > 0) {
            lastRun = batchJobRuns.get(0);
        }
        
        // Add filter condition and newness condition in WHERE clause
        String whereClause = '';
            
        if (lastRun != null) {
        	// Add condition to only retrieve source records created or modified since last batch job run
        	// Note: We do not want to restrict to filter records, since we may need to re-calculate if an order becomes deactivated etc.
            lastRunDT = lastRun.CreatedDate;
            whereClause = 'WHERE LastModifiedDate >= :lastRunDT OR CreatedDate >= :lastRunDT';

        } else {
            // Restrict to active orders
            Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
            whereClause += 'WHERE Order.Status = \'' + dataSets.Order_Active_Stage__c + '\'';
        }
        
        // Format query
        String query = String.format('SELECT Id FROM {0} {1}', new List<String>{targetObject, whereClause});
        System.debug(query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope) {
        // Get executor impl
        IRollupBatchExecutor executor = (IRollupBatchExecutor) RollupBatchExecutorFactory.createInstance(function);
        
        try {
            // Execute
        	state = executor.executeGivenTargetRecords(state, scope, sourceObject, sourceField, mergeField, targetObject, targetField, filter); 
            
            // Record metrics
            totalRecords += executor.getTotalRecords();
            errors += executor.getNumErrors();
            notes += executor.getNotes();
        } catch (Exception e) {
        	notes += e.getMessage();
            errors += scope.size(); 
        }
    }
    
	global void finish(Database.BatchableContext bc) {
        // Insert record for batch job run
        Batch_Job_Results__c batchResults = new Batch_Job_Results__c();
        batchResults.Name = batchJobName;
        batchResults.Total_Records__c = totalRecords;
        batchResults.Total_Errors__c = errors;
        batchResults.Notes__c = notes.length() > 30000 ? notes.substring(0, 30000) : notes;
        
        insert batchResults;

        // Execute Account rollup batch
        AccountServiceTypeRollupBatchJobImpl batch = new AccountServiceTypeRollupBatchJobImpl(batchJobName + ': Account Rollup step', state.processedIds);
        Database.executeBatch(batch, accountRollupBatchSize);
    }
}