force-app/main/default/objects/Account/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ServiceTerritory.ParentTerritoryId</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>ServiceTerritory.IsActive</field>
            <operation>notEqual</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/OperatingHours/fields/Operating_Hours_Type__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type__c</fullName>
    <label>Operating Hours Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Operating Hours</fullName>
            </value>
            <value>
                <fullName>Employee Operating Hours</fullName>
            </value>
            <value>
                <fullName>Territory Operating Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Site_Survey__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Survey_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestUtilsWrapperAccount.cls
/**
 * @FileName: TestUtilsWrapperAccount
 * @Description: Wrapper class for default Account test data
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       11/11/2019         Created
 *-----------------------------------------------------------  
 */
public inherited sharing class TestUtilsWrapperAccount {
    private final List<String> DAYS = new List<String>{
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday'
    };

    public Account account;
    public OperatingHours accountOperatingHours;
    public OperatingHours territoryOperatingHours;
    public List<TimeSlot> timeSlots;
    public List<ServiceTerritory> serviceTerritories;
    public Site_Survey__c survey;
    public Survey_Location__c surveyLocation;

    public TestUtilsWrapperAccount() {
        this(true);
    }

    public TestUtilsWrapperAccount(Boolean doInsert) {
        createTestData(doInsert);
    }

    private void createTestData(Boolean doInsert) {
        accountOperatingHours = (OperatingHours) TestUtils.createSObject(new OperatingHours(Operating_Hours_Type__c = 'Account Operating Hours'));
        territoryOperatingHours = (OperatingHours) TestUtils.createSObject(new OperatingHours(Operating_Hours_Type__c = 'Territory Operating Hours'));

        timeSlots = (List<TimeSlot>)TestUtils.createSObjectList(new TimeSlot(), DAYS.size());

        for (Integer i = 0; i < DAYS.size(); i++) {
            timeSlots[i].DayOfWeek = DAYS[i];
        }

        serviceTerritories = new List<ServiceTerritory>{
                (ServiceTerritory) TestUtils.createSObject(new ServiceTerritory()),
                (ServiceTerritory) TestUtils.createSObject(new ServiceTerritory())
        };

        account = (Account)TestUtils.createSObject(new Account());

        survey = (Site_Survey__c) TestUtils.createSObject(new Site_Survey__c());
        surveyLocation = (Survey_Location__c) TestUtils.createSObject(new Survey_Location__c());

        if (doInsert) doInsert();
    }

    public void doInsert() {
        insert new List<OperatingHours>{accountOperatingHours, territoryOperatingHours};

        for(TimeSlot ts : timeSlots) {
            ts.OperatingHoursId = accountOperatingHours.Id;
        }

        insert timeSlots;

        serviceTerritories[0].OperatingHoursId = territoryOperatingHours.Id;
        insert serviceTerritories[0];

        serviceTerritories[1].OperatingHoursId = territoryOperatingHours.Id;
        serviceTerritories[1].ParentTerritoryId = serviceTerritories[0].Id;
        insert serviceTerritories[1];

        account.OperatingHoursId = accountOperatingHours.Id;
        account.Service_Territory__c = serviceTerritories[1].Id;
        insert account;

        survey.Account__c = account.Id;
        insert survey;

        surveyLocation.Site_Survey__c = survey.Id;
        insert surveyLocation;

        account.Site_Survey__c = survey.Id;
        update account;
    }
}