force-app/main/default/objects/Account/fields/ServicePricebookId__c.field-meta.xml
<CustomField>
    <fullName>ServicePricebookId__c</fullName>
    <formula>BLANKVALUE(  Service_Pricebook__c ,  $Setup.Field_Service_Settings__c.Default_Order_Price_Book_ID__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Pricebook Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Item_Type_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Item_Type_of_Services__c</fullName>
    <label>Item Type of Services</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Non_Recurring_Frequency_Value__c.field-meta.xml
<CustomField>
    <fullName>Non_Recurring_Frequency_Value__c</fullName>
    <label>Non Recurring Frequency Value</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Order_Active_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Active_Stage__c</fullName>
    <label>Order Active Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Shopping_Cart_Order_Draft_Stage__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart_Order_Draft_Stage__c</fullName>
    <label>Shopping Cart Order Draft Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Shopping_Cart_Order_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart_Order_Record_Type_Id__c</fullName>
    <label>Shopping Cart Order Record Type Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/Order/fields/ShoppingCartEID__c.field-meta.xml
<CustomField>
    <fullName>ShoppingCartEID__c</fullName>
    <externalId>true</externalId>
    <label>ShoppingCartEID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <formula>PricebookEntry.Product2.Item_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <inlineHelpText>Indicate if the Customer is charged a Price for the Purchase of this item. Price Entered is per unit. If only Purchase Price is filled in, this would be considered as a One Time Delivery.</inlineHelpText>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Related_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Display_Frequency_In_Portal__c.field-meta.xml
<CustomField>
    <fullName>Display_Frequency_In_Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Frequency In Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MyServices.cls
public class MyServices {
    
    public class PickList {
        @AuraEnabled
        public List<String> caseType { get; set; }
       
        public PickList() {}
        
        public PickList(List<String> caseType) {
            this.caseType = caseType;
        }
    }
    
    public class LineItem {
        @AuraEnabled
        public String ProductName;       
        @AuraEnabled
        public String Quantity; 
        @AuraEnabled
        public String ItemType;
        @AuraEnabled
        public String RelatedProduct;
        @AuraEnabled
        public String RelatedProductId;
        @AuraEnabled
        public String ProductId;
        @AuraEnabled
        public String OrderItemId;
        @AuraEnabled
        public String OrderId;
        @AuraEnabled
        public String OrderNumber;
        @AuraEnabled
        public String Frequency;
        @AuraEnabled
        public String PricebookEntryId;
        @AuraEnabled
        public Boolean displayFreq;
    }
    
    public class ItemMap{
        @AuraEnabled
        public String serviceType;
        @AuraEnabled
        public List<LineItem> itemsMap;
    }
    
    @AuraEnabled
    public static PickList getValues() {
        List<String> t = new List<String>();
        
        for(Schema.PicklistEntry v : Schema.Case.Type.getDescribe().getPicklistValues()){
            t.add(v.getValue());
        } 
        
        PickList values = new PickList(t);        
        return values;
    }
    
    @AuraEnabled 
    public static User getCaseDetails() {
        Id userId = UserInfo.getUserId();
        try{            
           User u = [SELECT ContactId, AccountId, Contact.Name, Account.Name FROM User WHERE Id=:userId];
           return u;  
        }
        catch(Exception e){
            return null;
        }
    }

    
    @AuraEnabled
    public static Map<String,List<LineItem>> getServicesMap(List<String> queryParams, String recordId) {
        System.debug('Entered the init method ' + recordId);
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        Id userId = UserInfo.getUserId();
        List<String> queryParamsServices = queryParams;
        Map<String,List<OrderItem>> mapServices = new Map<String,List<OrderItem>>();
        
        Map<String,List<LineItem>> mapAggregateItems = new Map<String,List<LineItem>>();
        
        

        mapServices.put('Products', new List<OrderItem>());
        mapServices.put('Services', new List<OrderItem>());
        
        try{
            User currentUser = [SELECT Id, AccountId, ContactId, UserType FROM User WHERE Id=:userId];
            Id accountId = currentUser.AccountId;
            Boolean isPortal = accountId!=null ? true: false;
            
            if(isPortal) {
                List<LineItem> lineItems = new List<LineItem>();
                System.debug(accountId);
                Map<String, Order> orderMap = new Map<String, Order>([SELECT Id, OrderNumber, Status, AccountId FROM Order WHERE Status=:fssetting.Order_Active_Stage__c AND AccountId=:accountId]);
                System.debug(orderMap);
                for(AggregateResult ar : [SELECT OrderId orderId, PricebookEntryId pEntry, Product2.Display_Frequency_In_Portal__c displayFreq, Product2.Item_Type__c itemType, Product2.Name name, 
                                          Related_Product__r.Name relatedProd, Frequency__c freq, Active__c active, sum(Quantity) total FROM OrderItem WHERE Order.AccountId=:accountId AND 
                                          Order.Status=:fssetting.Order_Active_Stage__c AND Frequency__c=:fssetting.Non_Recurring_Frequency_Value__c 
                                          AND (Product2.Item_Type__c='Consumables' OR Product2.Item_Type__c=:fssetting.Item_Type_of_Services__c)
                                          GROUP BY OrderId, Product2.Item_Type__c, Product2.Name, PricebookEntryId, Product2.Display_Frequency_In_Portal__c, Related_Product__r.Name, Frequency__c, Active__c
                                          ORDER BY Frequency__c]) 
                {                   
                    String key = String.valueOf(ar.get('itemType'));
                    String key1 = String.valueOf(ar.get('orderId'));
                    LineItem item = createLineItem(key, ar);
                    item.OrderNumber = orderMap.get(key1).OrderNumber;
                    item.displayFreq = Boolean.valueOf(ar.get('displayFreq'));
                    if(mapAggregateItems.containsKey(key)) {
                        mapAggregateItems.get(key).add(item);
                    } else {
                        mapAggregateItems.put(key, new List<LineItem>{item});
                    }
                }
                System.debug(mapAggregateItems);
                
            } else {
                queryParams.add(' Order.AccountId = \'' + recordId + '\'' + ' AND Order.Status = \'Activated\' ' );  
                List<LineItem> lineItems = new List<LineItem>();
                System.debug(recordId);
                Map<String, Order> orderMap = new Map<String, Order>([SELECT Id, OrderNumber, Status, AccountId FROM Order WHERE Status=:fssetting.Order_Active_Stage__c AND AccountId=:recordId]);
                System.debug(orderMap);
                for(AggregateResult ar : [SELECT OrderId orderId, PricebookEntryId pEntry, Product2.Display_Frequency_In_Portal__c displayFreq, Product2.Item_Type__c itemType, Product2.Name name, 
                                          Related_Product__r.Name relatedProd, Frequency__c freq, Active__c active, sum(Quantity) total FROM OrderItem WHERE Order.AccountId=:recordId AND 
                                          Order.Status=:fssetting.Order_Active_Stage__c GROUP BY OrderId, Product2.Item_Type__c, Product2.Name, PricebookEntryId, Product2.Display_Frequency_In_Portal__c, 
                                          Related_Product__r.Name, Frequency__c, Active__c ORDER BY Frequency__c]) 
                {                   
                    String key = String.valueOf(ar.get('itemType'));
                    String key1 = String.valueOf(ar.get('orderId'));
                    LineItem item = createLineItem(key, ar);
                    item.OrderNumber = orderMap.get(key1).OrderNumber;
                    item.displayFreq = true;
                    if(mapAggregateItems.containsKey(key)) {
                        mapAggregateItems.get(key).add(item);
                    } else {
                        mapAggregateItems.put(key, new List<LineItem>{item});
                    }
                }
                System.debug(mapAggregateItems);
            }
         }
     	catch(Exception e){
            System.debug(e.getLineNumber() + ' -- ' + e.getMessage());   
     	}
      return mapAggregateItems;
    }
    
    public static LineItem createLineItem(String itemType, AggregateResult ar) {
        LineItem newItem = new LineItem();
        newItem.ProductName = String.valueOf(ar.get('name'));    
        newItem.Quantity = (ar.get('total')!=null) ? String.valueOf(ar.get('total')).removeEnd('.0') : '0'; 
        newItem.ItemType = (ar.get('itemType')!=null) ? String.valueOf(ar.get('itemType')) : '';   
        newItem.RelatedProduct = (ar.get('relatedProd')!=null) ? String.valueOf(ar.get('relatedProd')) : ''; 
        newItem.PricebookEntryId = (ar.get('pEntry')!=null) ? String.valueOf(ar.get('pEntry')) : ''; 
        newItem.Frequency = (ar.get('freq')!=null) ? String.valueOf(ar.get('freq')) : '';
        return newItem;
    }
    
    @AuraEnabled
    public static String addToCart(String pricebookEntryId) {
        Order o = getOrder();
        try{
            System.debug(o);
            if(o.Id != null) {
                OrderItem newItem = new OrderItem(
                    OrderId = o.Id,
                    ServiceDate = System.today(),
                    Frequency__c='One-Time',
                    PricebookEntryId = pricebookEntryId,
                    Quantity = 1, 
                    UnitPrice = 0.0,
                    Purchase_Price__c = 0.0
                );
                upsert o ShoppingCartEID__c;
                insert newItem;
                System.debug(o);
            }
            return 'Your item has been added to the shopping Cart.';
        } catch(Exception e) {
            System.debug(e);
            return 'There has been an error, Contact Customer Support.';
        }
    }
    
    public static Order getOrder() {
        Id userId = UserInfo.getUserId();
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        User u = [SELECT Id, AccountId, ContactId, Account.Site_Survey__c, Account.ServicePricebookId__c FROM User WHERE Id=:userId];
        
        Order ord;
        try {
            ord = [SELECT Id, ShoppingCartEID__c, OrderNumber FROM Order WHERE ShoppingCartEID__c = :u.ContactId + 'Shopping Cart' LIMIT 1];
        }
        catch (Exception e) {
            ord = new Order(
                BillToContactId = u.ContactId, 
                ShoppingCartEID__c = u.ContactId + 'Shopping Cart', 
                AccountId = u.AccountId, 
                Status = fssetting.Shopping_Cart_Order_Draft_Stage__c, 
                EffectiveDate = Date.today(),  
                PriceBook2Id = (ID)u.Account.ServicePricebookId__c,
                Site_Survey__c = u.Account.Site_Survey__c, 
                RecordTypeId=fssetting.Shopping_Cart_Order_Record_Type_Id__c
            );
        }
        return ord;
    }
}