force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocuSign_Status_Ticket__c/DocuSign_Status_Ticket__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for ticket created on upload of file to Document Status record</description>
    <label>DocuSign Status Ticket Settings</label>
</CustomObject>

force-app/main/default/objects/DocuSign_Status_Ticket__c/fields/Associated_Object__c.field-meta.xml
<CustomField>
    <fullName>Associated_Object__c</fullName>
    <description>Object associated to file</description>
    <label>Associated Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocuSign_Status_Ticket__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>File name to match against uploaded files.</description>
    <inlineHelpText>File name starts with</inlineHelpText>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Default_Opportunity_Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_Opportunity_Price_Book_ID__c</fullName>
    <label>Default Opportunity Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Default_Order_Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_Order_Price_Book_ID__c</fullName>
    <label>Default Order Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/System_Administrator_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Administrator_Profile_Id__c</fullName>
    <label>System Administrator Profile Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <inlineHelpText>What&apos;s the main line of business on this opportunity?</inlineHelpText>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Air Care</fullName>
            </value>
            <value>
                <fullName>Air Treatment</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Consumables and Equipment</fullName>
            </value>
            <value>
                <fullName>Disinfection Service</fullName>
            </value>
            <value>
                <fullName>First Aid</fullName>
            </value>
            <value>
                <fullName>Fixture Cleaning</fullName>
            </value>
            <value>
                <fullName>Hand Sanitizer</fullName>
            </value>
            <value>
                <fullName>Personal Hygiene</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>PPE</fullName>
            </value>
            <value>
                <fullName>Sani-Restore</fullName>
            </value>
            <value>
                <fullName>Sani Guard</fullName>
            </value>
            <value>
                <fullName>Soap</fullName>
            </value>
            <value>
                <fullName>Toilet Seat Cleaner</fullName>
            </value>
            <value>
                <fullName>Urinal &amp; Toilet Hygiene</fullName>
            </value>
            <value>
                <fullName>Urinal Screen &amp; AntiSplash</fullName>
            </value>
            <value>
                <fullName>Vending</fullName>
            </value>
            <value>
                <fullName>Washroom Automation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Service_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Service_Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <formula>Opportunity.Site_Survey__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Survey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SurveyAssetCountChecker__c.field-meta.xml
<CustomField>
    <fullName>SurveyAssetCountChecker__c</fullName>
    <label>SurveyAssetCountChecker</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allowable_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>Allowable_Frequencies__c</fullName>
    <label>Allowable Frequencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_As_Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Available_As_Related_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available As Related Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Service_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Service_Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
                <isActive>false</isActive>
                <label>Fixed Weekly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestContentVersionTrigger.cls
@isTest
public class TestContentVersionTrigger {
    
    @testSetup
    static void setup() {
        List<Product2> products = new List<Product2>();
        List<PricebookEntry> pEntries = new List<PricebookEntry>();
        List<OpportunityLineItem> oppItems = new List<OpportunityLineItem>();
        List<QuoteLineItem> quoteItems = new List<QuoteLineItem>();
        List<String> frequencies = new List<String>{'One-Time','Monthly','Weekly'};
        Id pBook = Test.getStandardPricebookId();
        
        Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Default_Opportunity_Price_Book_ID__c = pBook;
        fssetting.Default_Order_Price_Book_ID__c = pBook;
        fssetting.System_Administrator_Profile_Id__c  = UserInfo.getProfileId();
        insert fssetting;
        
        TestDataFactory.crtAcctContact(1,1);
        
        Test.startTest();
        for(Integer i=0; i<5; i++){
            products.add(
                new Product2(
                    Name='TestProduct'+i,
                    Allowable_Frequencies__c='One-Time;Monthly;Weekly', 
                    IsActive=TRUE, 
                    Available_As_Related_Product__c=TRUE, 
                    Family= (i==1) ? 'Pest Control' : 'Hygiene', 
                    ProductCode='1-6-001'+i
                )       
            );
        }
        
        insert products;
        
        for(Integer i=0; i<5; i++) {
            pEntries.add(
                new PricebookEntry(
                    Pricebook2Id=pBook, 
                    Product2Id=products.get(i).Id, 
                    UnitPrice=1.0, 
                    IsActive=TRUE
                )
            );
        }
        insert pEntries; 
        
        Opportunity op = new Opportunity(
            Name=TestDataFactory.accounts[0].Name+' Opportunity',
            AccountId=TestDataFactory.accounts[0].Id,
            StageName='Presentation', 
            CloseDate=System.today().addDays(30),
            Amount=0.0, 
            Type='Retention', 
            Opportunity_Type__c='Consumables', 
            LeadSource='Call In', 
            Site_Survey__c=TestDataFactory.accounts[0].Site_Survey__c
        ); 
        insert op;
        
        OpportunityContactRole oppRole = new OpportunityContactRole(
            OpportunityId=op.Id,
            ContactId=TestDataFactory.contacts[0].Id, 
            Role='Decision Maker',
            isPrimary=TRUE
        );
        insert oppRole;
        
        for(Integer i=0; i<3; i++) {
            oppItems.add(
                new OpportunityLineItem(
                    Product2Id=pEntries.get(i).Id,  
                    Service_Frequency__c=frequencies.get(i), 
                    UnitPrice=1.0, 
                    Service_Price_Per_Unit__c=1.0, 
                    Quantity=1, 
                    OpportunityId=op.Id, 
                    SurveyAssetCountChecker__c=1
                )
            );
        } 
        insert oppItems;
        
        Contact newContact = new Contact(
            FirstName = 'TestFirstName', 
            LastName = 'TestLastName', 
            Email = 'testUser@UserCommunity.com', 
            AccountId = op.AccountId, 
            Phone = '123456789'            
        );
        insert newContact;
        
        Quote testQuote = new Quote(
            OpportunityId=op.Id, 
            Name=op.Name+'Quote', 
            ContactId=newContact.Id, 
            Pricebook2Id=pBook
        );
        
        insert testQuote;
        
        for(Integer i=0; i<3; i++) {
            quoteItems.add(
                new QuoteLineItem(
                    Product2Id=pEntries.get(i).Id,  
                    Service_Frequency__c=frequencies.get(i), 
                    UnitPrice=1.0, 
                    Service_Price_Per_Unit__c=1.0, 
                    Quantity=1, 
                    QuoteId=testQuote.Id
                )
            );
        } 
        insert quoteItems;
        Test.stopTest();
    }
    
    private static testMethod void testCreate() {
        List<Group> grp = [SELECT Id from group where name like 'Cash%']; 
        System.debug('##GROUP##' + grp.size());
        DocuSign_Status_Ticket__c dst = new DocuSign_Status_Ticket__c();
        dst.Name = 'FILEUPLOAD';
        dst.File_Name__c = 'Invoicing and Payment';
        dst.Associated_Object__c = 'dsfs__DocuSign_Status__c';
        if(grp.size()>0){dst.Ticket_Owner__c = grp[0].Id;}
        dst.Ticket_Record_Type__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Invoice Information').getRecordTypeId();
        dst.Ticket_Status__c = 'New';
        dst.Ticket_Subject__c = 'Payment Options Submitted';
        dst.Ticket_Type__c = 'A/R Inquiry';
        
        insert dst;
        
        Account a = [SELECT Id FROM Account LIMIT 1];
        Contact c = [SELECT Id FROM Contact WHERE AccountId = :a.Id LIMIT 1];
        Quote q = [SELECT Id,OpportunityId FROM Quote Limit 1];
        dsfs__DocuSign_Status__c dstatus = new dsfs__DocuSign_Status__c();
        dstatus.dsfs__Company__c = a.Id;
        dstatus.dsfs__Contact__c = c.Id;
        dstatus.Quote__c = q.Id;
        dstatus.dsfs__Opportunity__c = q.OpportunityId;
        insert dstatus;
        
        ContentVersion contentVersion_1 = new ContentVersion(
            Title = 'English Invoicing and Payment Options',
            PathOnClient = 'English Invoicing and Payment Options.pdf',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion_1;
        
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1];
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = dstatus.id;
        contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
        contentlink.ShareType = 'V';
        insert contentlink; 
        
        System.assertEquals(documents.size(), 1);
        System.assertEquals(documents[0].Id, contentVersion_2.ContentDocumentId);
        System.assertEquals(documents[0].LatestPublishedVersionId, contentVersion_2.Id);
        System.assertEquals(documents[0].Title, contentVersion_2.Title);
    }
}