force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Default_Opportunity_Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_Opportunity_Price_Book_ID__c</fullName>
    <label>Default Opportunity Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Default_Order_Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_Order_Price_Book_ID__c</fullName>
    <label>Default Order Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/System_Administrator_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Administrator_Profile_Id__c</fullName>
    <label>System Administrator Profile Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <formula>Opportunity.Site_Survey__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Survey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Location</label>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Survey_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Date__c</fullName>
    <label>Survey Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/Survey_Asset_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Asset Location</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>Survey Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Asset Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Survey Asset Locations</relationshipLabel>
    <relationshipName>Survey_Asset_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISBLANK(Survey_Location__c ), &quot;Unallocated&quot;, &quot;Allocated&quot;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Survey_Location__c.Site_Survey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site_Survey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipLabel>Survey Asset Locations</relationshipLabel>
    <relationshipName>Survey_Assets_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Site_Survey__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <inlineHelpText>Floor/Level (Name or #)</inlineHelpText>
    <label>Floor/Level</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Location_SubType__c.field-meta.xml
<CustomField>
    <fullName>Location_SubType__c</fullName>
    <description>If a new value is added or existing values are changed, please update Location SubType field on both Work Order Location object and Work Order Object. Also please execute SLPickListValue.getDependantValues() to update the Configuration__c object</description>
    <label>Location SubType</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Location_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unisex</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Accessible</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Visitor</fullName>
            </value>
            <value>
                <fullName>Co-Ed</fullName>
            </value>
            <value>
                <fullName>Family Room</fullName>
            </value>
            <value>
                <fullName>Staff - Female</fullName>
            </value>
            <value>
                <fullName>Staff - Male</fullName>
            </value>
            <value>
                <fullName>Staff - Unisex</fullName>
            </value>
            <value>
                <fullName>Employee - Female</fullName>
            </value>
            <value>
                <fullName>Employee - Male</fullName>
            </value>
            <value>
                <fullName>Employee - Unisex</fullName>
            </value>
            <value>
                <fullName>Visitor - Female</fullName>
            </value>
            <value>
                <fullName>Visitor - Male</fullName>
            </value>
            <value>
                <fullName>Visitor - Unisex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>If a new value is added or existing values are changed, please update Location Type field on both Work Order Location object and Work Order Object. Also please execute SLPickListValue.getDependantValues() to update the Configuration__c object</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auditorium/Theatre</fullName>
            </value>
            <value>
                <fullName>Bar</fullName>
            </value>
            <value>
                <fullName>Basement</fullName>
            </value>
            <value>
                <fullName>Base of building</fullName>
            </value>
            <value>
                <fullName>Cafeteria/Lunch Room</fullName>
            </value>
            <value>
                <fullName>Compactor Room</fullName>
            </value>
            <value>
                <fullName>Day Care</fullName>
            </value>
            <value>
                <fullName>Dining area</fullName>
            </value>
            <value>
                <fullName>Finish Product Warehouse</fullName>
            </value>
            <value>
                <fullName>First Aid Room</fullName>
            </value>
            <value>
                <fullName>Floor</fullName>
            </value>
            <value>
                <fullName>Food Court</fullName>
            </value>
            <value>
                <fullName>Gym/Fitness Centre</fullName>
            </value>
            <value>
                <fullName>Hallway</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Kitchenette</fullName>
            </value>
            <value>
                <fullName>Level</fullName>
            </value>
            <value>
                <fullName>Loading dock</fullName>
            </value>
            <value>
                <fullName>Lobby</fullName>
            </value>
            <value>
                <fullName>Locker Room/Change Room</fullName>
            </value>
            <value>
                <fullName>Main Office</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Patio</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Raw Product Storage</fullName>
            </value>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Shipping &amp; receiving</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Washroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Survey_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestQuoteObjectTriggers.cls
@isTest
public class TestQuoteObjectTriggers {
    
    @TestSetup static void setup() {
        List<OrderItem> orderItems = new List<OrderItem>();
        List<Product2> products = new List<Product2>();
        List<PricebookEntry> pEntries = new List<PricebookEntry>();
        List<Survey_Asset_Location__c> surveyAssetLocations = new List<Survey_Asset_Location__c>();
        List<OpportunityLineItem> oppItems = new List<OpportunityLineItem>();
        List<String> frequencies = new List<String>{'One-Time','Monthly','Weekly'};
        Id pBook = Test.getStandardPricebookId();
        
        Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Default_Opportunity_Price_Book_ID__c = pBook;
        fssetting.Default_Order_Price_Book_ID__c = pBook;
        fssetting.System_Administrator_Profile_Id__c  = UserInfo.getProfileId();
        insert fssetting;
        
        TestDataFactory.crtAcctContact(1, 1);
        Account a = TestDataFactory.accounts.get(0); 
        a.Name = 'TestAccount'; 
        update a;
        Contact c = TestDataFactory.contacts.get(0);
        
        Site_Survey__c ss = new Site_Survey__c(
            Account__c=a.Id, 
            Survey_Date__c = System.today(),
            Status__c = 'Approved'
        );
        insert ss;
        
        Survey_Location__c location = new Survey_Location__c(
            Site_Survey__c=ss.Id, 
            Building__c = 'Building',
            Floor__c = 'Floor', 
            Location_Type__c='Washroom', 
            Location_SubType__c='Unisex',
            Name='Location'
        );
        insert location;
        
        a.Site_Survey__c = ss.Id;
        update a;
        
        for(Integer i=0; i<5; i++){
            products.add(
                new Product2(
                    Name='TestProduct'+i,
                    Allowable_Frequencies__c='One-Time;Monthly;Weekly', 
                    IsActive=TRUE, 
                    Available_As_Related_Product__c=TRUE, 
                    Family= (i==1) ? 'Pest Control' : 'Hygiene', 
                    ProductCode='1-6-001'+i
                )       
            );
        }
        
        insert products;
        
        for(Integer i=0; i<5; i++) {
            pEntries.add(
                new PricebookEntry(
                    Pricebook2Id=pBook, 
                    Product2Id=products.get(i).Id, 
                    UnitPrice=1.0, 
                    IsActive=TRUE
                )
            );
        }
        insert pEntries; 
        
        Opportunity op = new Opportunity(
            Name=a.Name+' Opportunity',
            AccountId=a.Id,
            StageName='Presentation', 
            CloseDate=System.today().addDays(30),
            Amount=0.0, 
            Type='Retention', 
            Opportunity_Type__c='Consumables', 
            LeadSource='Call In', 
            Site_Survey__c=a.Site_Survey__c
        ); 
        insert op;
        
        OpportunityContactRole oppRole = new OpportunityContactRole(
            OpportunityId=op.Id,
            ContactId=c.Id, 
            Role='Decision Maker',
            isPrimary=TRUE
        );
        insert oppRole;
        
        for(Integer i=0; i<3; i++) {
            oppItems.add(
                new OpportunityLineItem(
                    Product2Id=pEntries.get(i).Id,  
                    Service_Frequency__c=frequencies.get(i), 
                    UnitPrice=1.0, 
                    Service_Price_Per_Unit__c=1.0, 
                    Quantity=1, 
                    OpportunityId=op.Id, 
                    SurveyAssetCountChecker__c=1
                )
            );
        } 
        insert oppItems;
        
        for(Integer i=0; i<3; i++) {
            //oppItems.get(i).SurveyAssetCountChecker__c=oppItems.get(i).Quantity;
            surveyAssetLocations.add(
                new Survey_Asset_Location__c(
                    Originating_Parent_ID__c=op.Id,  
                    Originating_Record_ID__c=oppItems.get(i).Id, 
                    Product__c=products.get(i).Id, 
                    Quantity__c=1, 
                    Site_Survey__c=op.Site_Survey__c, 
                    Service_Frequency__c=oppItems.get(i).Service_Frequency__c, 
                    Survey_Location__c=location.Id
                )
            );
        }
        insert surveyAssetLocations;
        
        /*Quote testQuote = new Quote(
            OpportunityId=op.Id, 
            Name=op.Name+'Quote', 
            Pricebook2Id=pBook
        );
        
        insert testQuote;
        
        op.SyncedQuoteId = testQuote.Id;
        update op;*/
    }
    
    static testMethod void testInsertQuote() {
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        
        Opportunity op = [SELECT Id, Name, AccountId FROM Opportunity WHERE Name='TestAccount Opportunity'];
        Id pBook = Test.getStandardPricebookId();
        List<QuoteLineItem> quoteItems = new List<QuoteLineItem>();
        List<String> frequencies = new List<String>{'One-Time','Monthly','Weekly'};
        List<PricebookEntry> pEntries = [SELECT Id, Pricebook2Id FROM PricebookEntry WHERE Pricebook2Id=:pBook];
        
        Contact newContact = new Contact(
            FirstName = 'TestFirstName', 
            LastName = 'TestLastName', 
            Email = 'testUser@UserCommunity.com', 
            AccountId = op.AccountId, 
            Phone = '123456789'            
        );
        insert newContact;
        
        Quote testQuote = new Quote(
            OpportunityId=op.Id, 
            Name=op.Name+'Quote', 
            ContactId=newContact.Id, 
            Pricebook2Id=pBook
        );
        
        insert testQuote;
        
        for(Integer i=0; i<3; i++) {
            quoteItems.add(
                new QuoteLineItem(
                    Product2Id=pEntries.get(i).Id,  
                    Service_Frequency__c=frequencies.get(i), 
                    UnitPrice=1.0, 
                    Service_Price_Per_Unit__c=1.0, 
                    Quantity=1, 
                    QuoteId=testQuote.Id
                )
            );
        } 
        insert quoteItems;
    }
    
    static testMethod void testInsertQuoteSync() {
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        
        Opportunity op = [SELECT Id, Name, AccountId FROM Opportunity WHERE Name='TestAccount Opportunity'];
        
        Quote testQuote = new Quote(
            OpportunityId=op.Id, 
            Name=op.Name+'Quote', 
            Pricebook2Id=fssetting.Default_Opportunity_Price_Book_ID__c
        );
        
        insert testQuote;
        
        op.SyncedQuoteId = testQuote.Id;
        update op;
    }

}