force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Emergency_Dispatch_Wizard_Setttings__c/Emergency_Dispatch_Wizard_Setttings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Emergency Dispatch Wizard Setttings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/Province_Time_Zones_Operating_Hours__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A table to map each province to appropriate time zones, for Citron users to only associate Accounts to appropriate time zones.</description>
    <label>Province Time Zones - Operating Hours</label>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder/fields/Create_Quality_Assurance__c.field-meta.xml
<CustomField>
    <fullName>Create_Quality_Assurance__c</fullName>
    <label>Create Quality Assurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>QA Work Order</fullName>
            </value>
            <value>
                <fullName>QA Work Order and Service Appointment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/FSL__VisitingHours__c.field-meta.xml
<CustomField>
    <fullName>FSL__VisitingHours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visiting Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DatetimeRecordTest.cls
/**
 * @FileName: DatetimeRecordTest
 * @Description: Test methods for DatetimeRecord class
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       1/27/2020       Created
 *                                   Moved logic from TestDatetimeRecord
 *                                   Updated setup method
 *-----------------------------------------------------------  
 */
@IsTest
private class DatetimeRecordTest {

    @TestSetup
    static void setupTest() {
        setupHelper();
    }

    @IsTest
    static void workOrderRegular() {
        Datetime todaysDate = Datetime.now();

        Account a = [SELECT Id, Site_Survey__c, Name FROM Account LIMIT 1];

        WorkOrder wo = [
                SELECT Id, Create_Quality_Assurance__c, Status, AccountId, StartDate, FSL__VisitingHours__c
                FROM WorkOrder
                WHERE AccountId = :a.Id
                LIMIT 1
        ];

        OperatingHours oh = [
                SELECT Id, Name, TimeZone, (
                        SELECT Id, DayOfWeek, StartTime, EndTime
                        FROM TimeSlots
                        ORDER BY DayOfWeek, StartTime, EndTime
                )
                FROM OperatingHours
                WHERE Id = :wo.FSL__VisitingHours__c
        ];

        Test.startTest();
        DatetimeRecord param = new DatetimeRecord(
                todaysDate.addDays(3),
                todaysDate.addDays(3),
                false,
                false,
                oh
        );
        DatetimeRecord values = DatetimeRecord.getWODates(param, todaysDate);
        Test.stopTest();
    }

    @IsTest
    static void workOrderEmergencyFuture1() {
        Datetime todaysDate = Datetime.now();

        Account a = [SELECT Id, Site_Survey__c, Name FROM Account LIMIT 1];

        WorkOrder wo = [
                SELECT Id, Create_Quality_Assurance__c, Status, AccountId, StartDate, FSL__VisitingHours__c
                FROM WorkOrder
                WHERE AccountId = :a.Id
                LIMIT 1
        ];

        OperatingHours oh = [
                SELECT Id, Name, TimeZone, (
                        SELECT Id, DayOfWeek, StartTime, EndTime
                        FROM TimeSlots
                        ORDER BY DayOfWeek, StartTime, EndTime
                )
                FROM OperatingHours
                WHERE Id = :wo.FSL__VisitingHours__c
        ];

        Test.startTest();
        DatetimeRecord param = new DatetimeRecord(
                todaysDate.addDays(3),
                todaysDate.addDays(3),
                false,
                true,
                oh
        );

        DatetimeRecord values = DatetimeRecord.getWODates(param, todaysDate);
        Test.stopTest();
    }

    @IsTest
    static void workOrderEmergencyFuture2() {
        Datetime todaysDate = Datetime.now();

        Account a = [SELECT Id, Site_Survey__c, Name FROM Account LIMIT 1];

        WorkOrder wo = [
                SELECT Id, Create_Quality_Assurance__c, Status, AccountId, StartDate, FSL__VisitingHours__c
                FROM WorkOrder
                WHERE AccountId = :a.Id
                LIMIT 1
        ];

        OperatingHours oh = [
                SELECT Id, Name, TimeZone, (
                        SELECT Id, DayOfWeek, StartTime, EndTime
                        FROM TimeSlots
                        ORDER BY DayOfWeek, StartTime, EndTime
                )
                FROM OperatingHours
                WHERE Id = :wo.FSL__VisitingHours__c
        ];

        Test.startTest();
        DatetimeRecord param = new DatetimeRecord(
                todaysDate.addDays(3),
                todaysDate.addDays(3),
                true,
                false,
                oh);

        DatetimeRecord values = DatetimeRecord.getWODates(param, todaysDate);
        Test.stopTest();
    }

    @IsTest
    static void workOrderEmergencyPast() {
        Datetime todaysDate = Datetime.now();

        Account a = [SELECT Id, Site_Survey__c, Name FROM Account LIMIT 1];

        WorkOrder wo = [
                SELECT Id, Create_Quality_Assurance__c, Status, AccountId, StartDate, FSL__VisitingHours__c
                FROM WorkOrder
                WHERE AccountId = :a.Id
                LIMIT 1
        ];

        OperatingHours oh = [
                SELECT Id, Name, TimeZone, (
                        SELECT Id, DayOfWeek, StartTime, EndTime
                        FROM TimeSlots
                        ORDER BY DayOfWeek, StartTime, EndTime
                )
                FROM OperatingHours
                WHERE Id = :wo.FSL__VisitingHours__c
        ];

        Test.startTest();
        DatetimeRecord param = new DatetimeRecord(
                todaysDate.addDays(3),
                todaysDate.addDays(3),
                true,
                true,
                oh
        );

        DatetimeRecord values = DatetimeRecord.getWODates(param, todaysDate);
        Test.stopTest();
    }

    // HELPER METHODS
    static void setupHelper() {
        TestUtils.createSObject(new Field_Service_Settings__c(), true);
        TestUtils.createSObject(new Emergency_Dispatch_Wizard_Setttings__c(), true);
        TestUtils.createSObject(new Province_Time_Zones_Operating_Hours__c(), true);

        TestUtilsWrapperPricebook pricebookWrapper = new TestUtilsWrapperPricebook(20);
        TestUtilsWrapperAccount accountWrapper = new TestUtilsWrapperAccount();
        TestUtilsWrapperOrder orderWrapper = new TestUtilsWrapperOrder(accountWrapper, pricebookWrapper);
        new TestUtilsWrapperWorkOrder(accountWrapper, orderWrapper);
    }
}