force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Default_Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Default_Skill_Level__c</fullName>
    <label>Default Skill Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <inlineHelpText>What&apos;s the main line of business on this opportunity?</inlineHelpText>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Air Care</fullName>
            </value>
            <value>
                <fullName>Air Treatment</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Consumables and Equipment</fullName>
            </value>
            <value>
                <fullName>Disinfection Service</fullName>
            </value>
            <value>
                <fullName>First Aid</fullName>
            </value>
            <value>
                <fullName>Fixture Cleaning</fullName>
            </value>
            <value>
                <fullName>Hand Sanitizer</fullName>
            </value>
            <value>
                <fullName>Personal Hygiene</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>PPE</fullName>
            </value>
            <value>
                <fullName>Sani-Restore</fullName>
            </value>
            <value>
                <fullName>Sani Guard</fullName>
            </value>
            <value>
                <fullName>Soap</fullName>
            </value>
            <value>
                <fullName>Toilet Seat Cleaner</fullName>
            </value>
            <value>
                <fullName>Urinal &amp; Toilet Hygiene</fullName>
            </value>
            <value>
                <fullName>Urinal Screen &amp; AntiSplash</fullName>
            </value>
            <value>
                <fullName>Vending</fullName>
            </value>
            <value>
                <fullName>Washroom Automation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Survey__c/fields/Survey_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Date__c</fullName>
    <label>Survey Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SiteSurvey_RequiredSkills__c/SiteSurvey_RequiredSkills__c.object-meta.xml
<CustomObject>
    <label>SiteSurvey RequiredSkills</label>
    <nameField>
        <label>RequiredSkills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteSurvey RequiredSkills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteSurvey_RequiredSkills__c/fields/EID__c.field-meta.xml
<CustomField>
    <fullName>EID__c</fullName>
    <externalId>true</externalId>
    <label>EID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SiteSurvey_RequiredSkills__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteSurvey_RequiredSkills__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>RequiredSkills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SiteSurvey_RequiredSkills__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <label>Skill Level</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SiteSurvey_RequiredSkills__c/fields/Skill_Name__c.field-meta.xml
<CustomField>
    <fullName>Skill_Name__c</fullName>
    <label>Skill Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SiteSurvey_RequiredSkills__c/fields/Skill_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Skill_Record_Id__c</fullName>
    <label>Skill Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestSiteSurveySettingsController.cls
@IsTest
public class TestSiteSurveySettingsController {

    @TestSetup static void setup() {
        Field_Service_Settings__c dataSets =  new Field_Service_Settings__c(Default_Skill_Level__c=1.0/*, Site_Survey_Skill_Requirement_Tab_Access__c=UserInfo.getProfileId()*/);
        Date todaysDate = System.today();
        List<Account> accounts = new List<Account>();
        List<Site_Survey__c> siteSurveys = new List<Site_Survey__c>();
        
        TestDataFactory.crtBillToAcctContact(3, 1);
        
        integer n = 1; 
        For(Account acct: TestDataFactory.accounts){
            acct.name = 'TestAccount'+n;
            n++; 
            accounts.add(acct);
        }
        update accounts; 
        
        System.debug(accounts);
        for(Integer i=1; i<3; i++) {
            siteSurveys.add(
                new Site_Survey__c(
                    Account__c=accounts.get(i).Id, 
                    Survey_Date__c = System.today(),
                    Status__c = 'Draft'
                )
            );
        }
        insert siteSurveys;
        
        Account a1 = accounts.get(1);
        Account a2 = accounts.get(2);
		a1.Site_Survey__c = siteSurveys.get(0).Id;
        a2.Site_Survey__c = siteSurveys.get(1).Id;
        update new List<Account>{a1, a2};
        
        Opportunity op = new Opportunity(
        	Name=accounts.get(0).Name+' Opportunity',
            AccountId=accounts.get(0).Id,
            StageName='Presentation', 
            CloseDate=System.today().addDays(30),
            Amount=0.0, 
            Type='Retention', 
            Opportunity_Type__c='Consumables', 
            LeadSource='Call In'
        ); 
        insert op;

        OpportunityContactRole oppRole = new OpportunityContactRole(
            OpportunityId=op.Id,
            ContactId=TestDataFactory.contacts[0].Id, 
            Role='Decision Maker',
            isPrimary=TRUE
        );
        insert oppRole;
        
        Order o = new Order(
        	AccountId=accounts.get(0).Id, 
            Status='Draft', 
            EffectiveDate=System.today()
        ); 
        insert o;
        
        List<SiteSurvey_RequiredSkills__c> skillRecords = new List<SiteSurvey_RequiredSkills__c>();
        for(Integer i=0; i<3; i++) {
            skillRecords.add(
                new SiteSurvey_RequiredSkills__c(
                    Site_Survey__c = a2.Site_Survey__c,  
                    Skill_Level__c = 1.0,
                    Skill_Name__c = 'TestSkill'+i,
                    Name = 'TestSkill'+i,
                    Skill_Record_Id__c = 'TestSkillId'+i,
                    EID__c = a2.Site_Survey__c +'.' + 'TestSkillId'+i, 
                    Line_of_Business__c = i==0 ? 'Chemical' : ''
                )
            );
        }
        insert skillRecords; 
    }
    
    static testMethod void testGetSiteSurveyIdOpportunityWithoutSSPart1() {
        List<String> queryParams = new List<String>{'Id, AccountId, Site_Survey__c, Account.Site_Survey__c'};
        Opportunity op = [SELECT Id, Name, AccountId, Site_Survey__c FROM Opportunity WHERE Name='TestAccount1 Opportunity'];
        Account acc = [SELECT Id, Site_Survey__c FROM Account WHERE Id =: op.AccountId];
        Account acc2 = [SELECT Id, Site_Survey__c FROM Account WHERE Name='TestAccount2'];
        acc.Site_Survey__c = null;
        update acc;
        SiteSurveySettingsController.getSiteSurveyId(op.Id, queryParams);
        acc.Site_Survey__c = acc2.Site_Survey__c;
        update acc;
        SiteSurveySettingsController.getSiteSurveyId(op.Id, queryParams);
    }
    
    static testMethod void testGetSiteSurveyIdOpportunityWithoutSSPart2() {
        List<String> queryParams = new List<String>{'Id, AccountId, Site_Survey__c, Account.Site_Survey__c'};
        Opportunity op = [SELECT Id, Name, AccountId FROM Opportunity WHERE Name='TestAccount1 Opportunity'];
        List<Site_Survey__c> siteSurveys = new List<Site_Survey__c>();
        for(Integer i=0; i<2; i++) {
            siteSurveys.add(
                new Site_Survey__c(
                    Account__c=op.AccountId, 
                    Survey_Date__c = System.today(),
                    Status__c = 'Draft'
                )
            );
        }
        insert siteSurveys;
        SiteSurveySettingsController.getSiteSurveyId(op.Id, queryParams);
    }
    
    static testMethod void testGetSiteSurveyIdOrderWithoutSSPart1() {
        List<String> queryParams = new List<String>{'Id, AccountId, Site_Survey__c, Account.Site_Survey__c'};
        Order o = [SELECT Id, Account.Name, AccountId FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        List<Site_Survey__c> siteSurveys = new List<Site_Survey__c>();
        for(Integer i=0; i<2; i++) {
            siteSurveys.add(
                new Site_Survey__c(
                    Account__c=o.AccountId, 
                    Survey_Date__c = System.today(),
                    Status__c = 'Draft'
                )
            );
        }
        insert siteSurveys;
        SiteSurveySettingsController.getSiteSurveyId(o.Id, queryParams);
    }
    
    static testMethod void testGetSiteSurveyIdOrderWithoutSSPart2() {
        List<String> queryParams = new List<String>{'Id, AccountId, Site_Survey__c, Account.Site_Survey__c'};
        Order o = [SELECT Id, Account.Name, Site_Survey__c, AccountId FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        SiteSurveySettingsController.getSiteSurveyId(o.Id, queryParams);
        Account acc = [SELECT Id, Site_Survey__c FROM Account WHERE Id =: o.AccountId];
        Account acc2 = [SELECT Id, Site_Survey__c FROM Account WHERE Name='TestAccount2'];
        acc.Site_Survey__c = null;
        update acc;
        SiteSurveySettingsController.getSiteSurveyId(o.Id, queryParams);
        acc.Site_Survey__c = acc2.Site_Survey__c;
        update acc;
        SiteSurveySettingsController.getSiteSurveyId(o.Id, queryParams);
    }
    
    static testMethod void testGetSiteSurveyIdOpportunityWithSS() {
        List<String> queryParams = new List<String>{'Id, AccountId, Site_Survey__c, Account.Site_Survey__c'};
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount2'];
        Opportunity op = [SELECT Id, Name, AccountId FROM Opportunity WHERE Name='TestAccount1 Opportunity'];
        op.AccountId=a.Id;
        update op;
        SiteSurveySettingsController.getSiteSurveyId(op.Id, queryParams);
    }
    
    static testMethod void testGetSiteSurveyIdOrderWithSS() {
        List<String> queryParams = new List<String>{'Id, AccountId, Site_Survey__c, Account.Site_Survey__c'};
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount2'];
        Order o = [SELECT Id, Account.Name, AccountId FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        o.AccountId=a.Id;
        update o;
        SiteSurveySettingsController.getSiteSurveyId(o.Id, queryParams);
    }
    
    static testMethod void testGetSiteSurveyIdOpportunityWithDifferentSS() {
        List<String> queryParams = new List<String>{'Id, AccountId, Site_Survey__c, Account.Site_Survey__c'};
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount2'];
        Opportunity op = [SELECT Id, Name, AccountId FROM Opportunity WHERE Name='TestAccount1 Opportunity'];
        Site_Survey__c ss = [SELECT Id, Account__c, Account__r.Name FROM Site_Survey__c WHERE Account__r.Name='TestAccount3' LIMIT 1].get(0);
        op.AccountId=a.Id;
        op.Site_Survey__c=ss.Id;
        update op;
        SiteSurveySettingsController.getSiteSurveyId(op.Id, queryParams);
    }
    
    static testMethod void testGetSiteSurveyIdOrderWithDifferentSS() {
        List<String> queryParams = new List<String>{'Id, AccountId, Site_Survey__c, Account.Site_Survey__c'};
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount2'];
        Order o = [SELECT Id, Account.Name, AccountId FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        Site_Survey__c ss = [SELECT Id, Account__c, Account__r.Name FROM Site_Survey__c WHERE Account__r.Name='TestAccount3' LIMIT 1].get(0);
        o.AccountId=a.Id;
        o.Site_Survey__c=ss.Id;
        update o;
        SiteSurveySettingsController.getSiteSurveyId(o.Id, queryParams);
    }
    
    static testMethod void testSaveSiteSurvey(){
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount1'];
        
        Site_Survey__c ss = new Site_Survey__c(
            Account__c=a.Id, 
            Survey_Date__c = System.today(),
            Status__c = 'Draft'
        );
        insert ss; 
        SiteSurveySettingsController.saveSiteSurvey(ss);
        SiteSurveySettingsController.getlob();
    }
    
    static testMethod void testInitSkills() {
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        
        Site_Survey__c ss = [SELECT Id, Account__c, Account__r.Name FROM Site_Survey__c WHERE Account__r.Name='TestAccount3' LIMIT 1].get(0);
        SiteSurveySettingsController.initSkills(ss.Id);
    }
    
    static testMethod void testUpdateSkills() {
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        
        Site_Survey__c ss = [SELECT Id, Account__c, Account__r.Name FROM Site_Survey__c WHERE Account__r.Name='TestAccount3' LIMIT 1].get(0);
        List<SiteSurvey_RequiredSkills__c> skillRecords = [SELECT Id, Name, Site_Survey__c, Skill_Level__c, Skill_Record_Id__c, Skill_Name__c, Line_of_Business__c 
                                                                   FROM SiteSurvey_RequiredSkills__c WHERE Site_Survey__c =:ss.Id];
       
        
        SiteSurvey_RequiredSkills__c record = skillRecords.get(0);
        record.Skill_Level__c=20.0;  
        SiteSurveySettingsController.SkillRecord newRecord = new SiteSurveySettingsController.SkillRecord(record.Name, record.Skill_Name__c, record.Skill_Level__c, record.Skill_Record_Id__c, record.Id);
        SiteSurveySettingsController.Picklist newLob = new SiteSurveySettingsController.Picklist('Hygiene', true);
        newRecord.lineOfBusinesses = new Set<SiteSurveySettingsController.Picklist>{newLob};
        
        String skillString = JSON.serialize(newRecord);
        SiteSurveySettingsController.upsertSkill(skillString, ss.Id);
    }
    
    static testMethod void testSaveSkills() {
        Site_Survey__c ss = [SELECT Id, Account__c, Account__r.Name FROM Site_Survey__c WHERE Account__r.Name='TestAccount3' LIMIT 1].get(0);
        
        SiteSurveySettingsController.SkillRecord newRecord = new SiteSurveySettingsController.SkillRecord('TestSkillABC', 'TestSkillABC', true);
        newRecord.skillId = 'TestSkillRecordId';
        SiteSurveySettingsController.Picklist newLob = new SiteSurveySettingsController.Picklist('Chemical', true);
        newRecord.lineOfBusinesses = new Set<SiteSurveySettingsController.Picklist>{newLob};
        
        String skillString = JSON.serialize(newRecord);
        SiteSurveySettingsController.upsertSkill(skillString, ss.Id);
    }
    
    static testMethod void testDeleteSkills() {
        Site_Survey__c ss = [SELECT Id, Account__c, Account__r.Name FROM Site_Survey__c WHERE Account__r.Name='TestAccount3' LIMIT 1].get(0);
        List<SiteSurvey_RequiredSkills__c> skillRecords = [SELECT Id, Name, Site_Survey__c, Skill_Level__c, Skill_Record_Id__c, Skill_Name__c, Line_of_Business__c 
                                                                   FROM SiteSurvey_RequiredSkills__c WHERE Site_Survey__c =:ss.Id];
        SiteSurvey_RequiredSkills__c record = skillRecords.get(0);
        
        SiteSurveySettingsController.deleteSkill(record.Id, record.Site_Survey__c);
        
    }
    
    static testMethod void testGetColumns() {
        List<String> columnAPINames = new List<String>{'SiteSurvey_RequiredSkills__c.Name','SiteSurvey_RequiredSkills__c.Skill_Level__c','SiteSurvey_RequiredSkills__c.Line_of_Business__c'};
        SiteSurveySettingsController.getColumns(columnAPINames);
    }
    
    static testMethod void testExceptionsPart1() {
        List<String> queryParams = new List<String>{'Id, AccountId, Site_Survey__c, Account.Site_Survey__c, StageName, Status'};
        Order o = [SELECT Id, Account.Name FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        Opportunity op = [SELECT Id, Name, AccountId FROM Opportunity WHERE Name='TestAccount1 Opportunity'];
        SiteSurveySettingsController.getSiteSurveyId(o.Id, queryParams);
        SiteSurveySettingsController.getSiteSurveyId(op.Id, queryParams);
    }
     
    static testMethod void testExceptionsPart3() {
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount2'];
        Site_Survey__c ss = new Site_Survey__c(
            Account__c=a.Id, 
            Survey_Date__c = System.today(),
            Status__c = 'Draft'
        );
        try {
        	SiteSurveySettingsController.saveSiteSurvey(ss);
        } catch (Exception e) {
            //just for testing purposes, don't care here
        }
    }
    
    static testMethod void testExceptionsPart4() {
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount2'];
        Opportunity op = new Opportunity(
        	Name=a.Name+' Opportunity',
            AccountId=a.Id,
            StageName='Presentation', 
            CloseDate=System.today().addDays(30),
            Amount=0.0, 
            Type='Retention', 
            Opportunity_Type__c='Consumables', 
            LeadSource='Call In'
        ); 
        SiteSurveySettingsController.createSiteSurvey(a.Id, op, null);
    }
    
    static testMethod void testExceptionsPart5() {
        SiteSurveySettingsController.upsertSkill('', '');
    }
}