force-app/main/default/objects/Account/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Site_Survey__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Accounts_Receivable_Queue__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Receivable_Queue__c</fullName>
    <label>Accounts Receivable Queue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/App_Support_Team_Queue__c.field-meta.xml
<CustomField>
    <fullName>App_Support_Team_Queue__c</fullName>
    <label>App Support Team Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Billing_Queue__c.field-meta.xml
<CustomField>
    <fullName>Billing_Queue__c</fullName>
    <label>Billing Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Billing_Team__c.field-meta.xml
<CustomField>
    <fullName>Billing_Team__c</fullName>
    <label>Billing Team</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/CS_Chemical_Queue__c.field-meta.xml
<CustomField>
    <fullName>CS_Chemical_Queue__c</fullName>
    <label>CS Chemical Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/CS_Data_Cleanup__c.field-meta.xml
<CustomField>
    <fullName>CS_Data_Cleanup__c</fullName>
    <label>CS Data Cleanup</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/CS_Hygiene_Queue__c.field-meta.xml
<CustomField>
    <fullName>CS_Hygiene_Queue__c</fullName>
    <label>CS Hygiene Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/CS_Orders__c.field-meta.xml
<CustomField>
    <fullName>CS_Orders__c</fullName>
    <label>CS Orders</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/CS_Pest_Queue__c.field-meta.xml
<CustomField>
    <fullName>CS_Pest_Queue__c</fullName>
    <label>CS Pest Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Customer_Success_Queue__c.field-meta.xml
<CustomField>
    <fullName>Customer_Success_Queue__c</fullName>
    <label>Customer Success Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Default_Opportunity_Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_Opportunity_Price_Book_ID__c</fullName>
    <label>Default Opportunity Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Default_Order_Price_Book_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_Order_Price_Book_ID__c</fullName>
    <label>Default Order Price Book ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Finance_Master_Data_Queue__c.field-meta.xml
<CustomField>
    <fullName>Finance_Master_Data_Queue__c</fullName>
    <label>Finance Master Data Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Inside_Sales_Queue__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Queue__c</fullName>
    <label>Inside Sales Queue</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Inside_Sales_Team__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Team__c</fullName>
    <label>Inside Sales Team</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Invoice_Information_Case_RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Information_Case_RecordTypeId__c</fullName>
    <label>Invoice Information Case RecordTypeId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Operating_Hours_Type_Account__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Type_Account__c</fullName>
    <label>Operating Hours Type - Account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Order_Active_Stage__c.field-meta.xml
<CustomField>
    <fullName>Order_Active_Stage__c</fullName>
    <label>Order Active Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Regular_Order_Draft_Stage__c.field-meta.xml
<CustomField>
    <fullName>Regular_Order_Draft_Stage__c</fullName>
    <label>Regular Order Draft Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Regular_Order_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Regular_Order_Record_Type_Id__c</fullName>
    <label>Regular Order Record Type Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Shopping_Cart_Order_Draft_Stage__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart_Order_Draft_Stage__c</fullName>
    <label>Shopping Cart Order Draft Stage</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Status_Value_for_Install_of_a_Product__c.field-meta.xml
<CustomField>
    <fullName>Status_Value_for_Install_of_a_Product__c</fullName>
    <label>Status Value for Install of a Product</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/System_Administrator_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Administrator_Profile_Id__c</fullName>
    <label>System Administrator Profile Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Ticket_Type_for_New_Lead__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type_for_New_Lead__c</fullName>
    <label>Ticket Type for New Lead</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Ticket_Type_for_Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type_for_Site_Survey__c</fullName>
    <label>Ticket Type for Site Survey</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item_Location__c/Order_Item_Location__c.object-meta.xml
<CustomObject>
    <label>Order Item Location</label>
    <nameField>
        <displayFormat>OIL-{000000}</displayFormat>
        <label>Order Item Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Item Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item_Location__c/fields/Survey_Asset_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Asset_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Asset Location</label>
    <referenceTo>Survey_Asset_Location__c</referenceTo>
    <relationshipLabel>Order Item Locations</relationshipLabel>
    <relationshipName>Order_Item_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/Province_Time_Zones_Operating_Hours__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A table to map each province to appropriate time zones, for Citron users to only associate Accounts to appropriate time zones.</description>
    <label>Province Time Zones - Operating Hours</label>
</CustomObject>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/fields/Province_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_Territory_Code__c</fullName>
    <label>Province/Territory Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Province_Time_Zones_Operating_Hours__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Surveys</relationshipLabel>
    <relationshipName>Site_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/Survey_Asset_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Asset Location</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>Survey Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Asset Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Survey_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Asset_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Survey Asset Locations</relationshipLabel>
    <relationshipName>Survey_Asset_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Site_Survey__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipName>Survey_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestOrderObjectTriggers.cls
@isTest
public class TestOrderObjectTriggers {
    
    @TestSetup static void setup() {
        List<Account> accounts = new List<Account>();
        List<OrderItem> orderItems = new List<OrderItem>();
        List<Product2> products = new List<Product2>();
        List<PricebookEntry> pEntries = new List<PricebookEntry>();
        List<Survey_Asset_Location__c> surveyAssetLocations = new List<Survey_Asset_Location__c>();
        List<Order_Item_Location__c> orderItemLocations = new List<Order_Item_Location__c>();
        List<String> frequencies = new List<String>{'One-Time','Monthly','Weekly'};
        Id pBook = Test.getStandardPricebookId();
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Invoice Information').getRecordTypeId();
        Id regularOrderRecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Regular Order').getRecordTypeId();
        
        Group testGroup = new Group(Name='TestGroup', Type='Queue');
        insert testGroup;
        
        Province_Time_Zones_Operating_Hours__c setting = new Province_Time_Zones_Operating_Hours__c();
        setting.Name = 'ON';
        setting.Province_Territory_Code__c = 'ON';
        setting.TimeZone__c = 'America/New_York';
        insert setting;
        
        Field_Service_Settings__c fssetting = new Field_Service_Settings__c();
        fssetting.Order_Active_Stage__c = 'Activated';
        fssetting.Regular_Order_Draft_Stage__c = 'Draft';
        fssetting.Shopping_Cart_Order_Draft_Stage__c = 'Shopping Cart';
        fssetting.Regular_Order_Record_Type_Id__c = regularOrderRecordTypeId;
        fssetting.Status_Value_for_Install_of_a_Product__c = 'Install';
        fssetting.System_Administrator_Profile_Id__c = UserInfo.getProfileId();
        fssetting.Accounts_Receivable_Queue__c = testGroup.Id;
        fssetting.Billing_Team__c = testGroup.Id;
        fssetting.Invoice_Information_Case_RecordTypeId__c = devRecordTypeId;
        fssetting.Operating_Hours_Type_Account__c = 'Account Operating Hours';
        fssetting.Default_Opportunity_Price_Book_ID__c = pBook;
        fssetting.Default_Order_Price_Book_ID__c = pBook;
        
        fssetting.Inside_Sales_Team__c = testGroup.Id;
        fssetting.Billing_Team__c = testGroup.Id;
        fssetting.Ticket_Type_for_New_Lead__c = 'New Lead';
        fssetting.Ticket_Type_for_Site_Survey__c = 'Site Survey';
        fssetting.CS_Pest_Queue__c = testGroup.Id;
        fssetting.CS_Chemical_Queue__c = testGroup.Id;
        fssetting.CS_Hygiene_Queue__c = testGroup.Id;
        fssetting.Inside_Sales_Queue__c = testGroup.Id;
        fssetting.Customer_Success_Queue__c = testGroup.Id;
        fssetting.Billing_Queue__c = testGroup.Id;
        fssetting.CS_Orders__c = testGroup.Id;
        fssetting.CS_Data_Cleanup__c = testGroup.Id;
        fssetting.App_Support_Team_Queue__c = testGroup.Id;
        fssetting.Finance_Master_Data_Queue__c = testGroup.Id;
        
        insert fssetting;
        
        Frequency__c setting1 =  new Frequency__c(Name=frequencies.get(0));
        setting1.Hygiene_Minus_Days__c = 5;
        setting1.Hygiene_Plus_Days__c = 5;
        setting1.Occurrences_In_Year__c = 1;
        setting1.Discount_Percent__c = 0.0;
        setting1.Pest_Minus_Days__c = 1;
        setting1.Pest_Plus_Days__c = 1;
        insert setting1;
        
        Frequency__c setting2 =  new Frequency__c(Name=frequencies.get(1));
        setting2.Hygiene_Minus_Days__c = 5;
        setting2.Hygiene_Plus_Days__c = 5;
        setting2.Occurrences_In_Year__c = 12;
        setting2.Discount_Percent__c = 0.0;
        setting2.Pest_Minus_Days__c = 1;
        setting2.Pest_Plus_Days__c = 1;
        insert setting2;
        
        Frequency__c setting3 =  new Frequency__c(Name=frequencies.get(2));
        setting3.Hygiene_Minus_Days__c = 5;
        setting3.Hygiene_Plus_Days__c = 5;
        setting3.Occurrences_In_Year__c = 54;
        setting3.Discount_Percent__c = 0.0;
        setting3.Pest_Minus_Days__c = 1;
        setting3.Pest_Plus_Days__c = 1;
        insert setting3;
        TestDataFactory.crtCPQSettings();
        TestDataFactory.crtAcctContact(2, 0); 
        accounts = TestDataFactory.accounts; 
		ID rTBillTo = [select id from recordType where name = 'Customer Bill To'].id; 
        Id rTShipTo = [select id from recordType where name = 'Customer Ship To'].id; 
        
        Account a0 = accounts.get(0);
        a0.OperatingHoursId = TestDataFactory.opthours[1].Id;
        a0.Service_Territory__c = TestDataFactory.srvTers[1].Id;
        a0.AccPac_Account__c='1234567-0'; 
        a0.RecordTypeId = rTBillTo;
        update a0;
        Account a = accounts.get(1);
        a.OperatingHoursId = TestDataFactory.opthours[1].Id;
        a.Service_Territory__c = TestDataFactory.srvTers[1].Id;
        a.AccPac_Account__c='1234567-1'; 
        a.ParentId = a0.Id;
        a.RecordTypeId = rTShipTo;
        update a;
        
        Site_Survey__c ss = new Site_Survey__c(
            Account__c=a.Id, 
            Survey_Date__c = System.today(),
            Status__c = 'Draft'
        );
        insert ss;
        
        Survey_Location__c location = new Survey_Location__c(
            Site_Survey__c=ss.Id, 
            Building__c = 'Building',
            Floor__c = 'Floor', 
            Location_Type__c='Washroom', 
            Location_SubType__c='Unisex',
            Name='Location'
        );
        insert location;
        
        a.Site_Survey__c = ss.Id;
        update a;
        
        Order o = new Order(
            AccountId=a.Id, 
            Status='Draft', 
            EffectiveDate=System.today(), 
            Pricebook2Id=pBook,
            Site_Survey__c=a.Site_Survey__c
        ); 
        insert o;
        
        for(Integer i=0; i<5; i++){
            products.add(
                new Product2(
                    Name='TestProduct'+i,
                    Allowable_Frequencies__c='One-Time;Monthly;Weekly', 
                    IsActive=TRUE, 
                    Available_As_Related_Product__c=TRUE,
                    ExternalId__c = '3-55-7-02-1' + i
                )       
            );
        }
        
        insert products;
        
        for(Integer i=0; i<5; i++) {
            pEntries.add(
                new PricebookEntry(
                    Pricebook2Id=pBook, 
                    Product2Id=products.get(i).Id, 
                    UnitPrice=1.0, 
                    IsActive=TRUE
                )
            );
        }
        insert pEntries; 
        
        for(Integer i=0; i<3; i++) {
            orderItems.add(
                new OrderItem(
                    Product2Id=pEntries.get(i).Id,  
                    Frequency__c=frequencies.get(1), 
                    UnitPrice=1.0, 
                    Service_Price_Per_Unit__c=1.0, 
                    Quantity=1, 
                    OrderId=o.Id, 
                    HasSurveyAssets__c=TRUE
                )
            );
        } 
        
        orderItems.add(
            new OrderItem(
                Product2Id=pEntries.get(2).Id,  
                Frequency__c=frequencies.get(0), 
                UnitPrice=1.0, 
                Purchase_Price__c=1.0, 
                Quantity=1, 
                OrderId=o.Id
            )
        );
        
        insert orderItems;
        
        for(Integer i=0; i<3; i++) {
            surveyAssetLocations.add(
                new Survey_Asset_Location__c(
                    Originating_Parent_ID__c=o.Id,  
                    Originating_Record_ID__c=orderItems.get(i).Id, 
                    Product__c=products.get(i).Id, 
                    Quantity__c=1, 
                    Site_Survey__c=o.Site_Survey__c, 
                    Service_Frequency__c=orderItems.get(i).Frequency__c, 
                    Survey_Location__c = location.Id
                )
            );
        } 
        insert surveyAssetLocations;
        
        for(Integer i=0; i<3; i++) {
            orderItems.get(i).HasSurveyAssets__c=true;
            orderItemLocations.add(
                new Order_Item_Location__c(
                    Order__c=o.Id,  
                    Order_Product__c=orderItems.get(i).Id, 
                    Survey_Asset_Location__c=surveyAssetLocations.get(i).Id
                )
            );
        }
        
        insert orderItemLocations;
        
        User newCommUser = new User(
            Alias = 'testA', 
            Email = 'testUser@UserCommunity.com', 
            EmailEncodingKey = 'ISO-8859-1', 
            FirstName = 'TestFirstName',
            LastName = 'TestLastName', 
            LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_CA', 
            ProfileId = UserInfo.getProfileId(),
            TimeZoneSidKey = 'America/New_York', 
            UserName = 'testUser@UserCommunity.com', 
            Employee_Number__c = 'ABCD123TEST'
        );
        insert newCommUser;
        
        QueuesObject testQueue = new QueueSObject(QueueID = testGroup.id, SobjectType = 'Case');
        
        System.runAs(newCommUser) {
            insert testQueue;
        }
    }
    
    static testMethod void insertOrder() {
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount1'];
        
        Id pBook = Test.getStandardPricebookId();
        
        Order o = new Order(
          AccountId=a.Id, 
            Status='Draft', 
            EffectiveDate=System.today(), 
            Pricebook2Id=pBook,
            Site_Survey__c=a.Site_Survey__c
        ); 
        
        Test.startTest();
        
        insert o;
        
        Test.stopTest();
    }
    
    static testMethod void insertOrderNoSiteSurveyAndPBook() {
        Account a = [SELECT Id, Site_Survey__c, Name, BillingStreet, ShippingCity, ParentId FROM Account WHERE Name='TestAccount1'];
        a.Site_Survey__c=null;
       
        Order o = new Order(
        	AccountId=a.Id, 
            Status='Draft', 
            EffectiveDate=System.today()
        ); 
        
        Test.startTest();
        
        update a;
        insert o;
        
        Test.stopTest();
    }
    
    static testMethod void insertOrderWithTicket() { 
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount1'];
        system.debug('++++' + a);
        Id pBook = Test.getStandardPricebookId();
        
        Case testCase = new Case(
          AccountId=a.Id, 
            Type='Other', 
            Status='New', 
            Priority='Low'
        );
        
        Test.startTest();
        
        insert testCase;
        
        Order o = new Order(
            AccountId = a.Id,
        	Ticket__c=testCase.Id,
            Status='Draft', 
            EffectiveDate=System.today(), 
            Pricebook2Id=pBook,
            PoNumber='111111',
            Site_Survey__c=a.Site_Survey__c
        ); 
        
        insert o;
        
        o.PoNumber = '112222';
        update o;
        Test.stopTest();
    }
    
    static testMethod void updateOrder() {
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount1'];
        Id pBook = Test.getStandardPricebookId();
   
        Order o = new Order(
          AccountId=a.Id, 
            Status='Draft', 
            EffectiveDate=System.today(), 
            Pricebook2Id=pBook
        ); 
        
        Test.startTest();
        
        insert o;
        
        o.Site_Survey__c=a.Site_Survey__c;
        o.Pricebook2Id=null;
        
        update o;
        
        Test.stopTest();
    }
    
    static testMethod void updateOrderRevenueChange() {
        Account a = [SELECT Id, Site_Survey__c, Name FROM Account WHERE Name='TestAccount1'];
        Order o = [SELECT Id, Account.Name, AccountId, RecordTypeId FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        Group testGroup = [SELECT Id FROM Group WHERE Name='TestGroup' LIMIT 1].get(0);
        OrderItem oi = [SELECT Id, OrderId, PricebookEntryId, Frequency__c, Quantity, UnitPrice, Service_Price_Per_Unit__c, Purchase_Price__c, Order.Status, Installation_Price__c, Installation_Status__c,
                        HasSurveyAssets__c, SurveyAssetCountChecker__c FROM OrderItem WHERE OrderId=:o.Id LIMIT 1].get(0);
        OrderItem newItem = oi.clone(false, true, false, false);
        newItem.Service_Price_Per_Unit__c=null;
        newItem.Purchase_Price__c=111.111;
        newItem.Installation_Price__c=null;
        newItem.Installation_Status__c=null;
        newItem.HasSurveyAssets__c=FALSE;
        newItem.SurveyAssetCountChecker__c=0;
        
        Field_Service_Settings__c fssetting = Field_Service_Settings__c.getOrgDefaults();
        
        List<String> frequencies = new List<String>{'One-Time','Monthly','Weekly'};
            
        Test.startTest();
        
        o.Status='Activated';
        update o;
        
        o.Status='Draft';
        update o;
        
        oi.Frequency__c = 'Weekly';
        oi.Service_Price_Per_Unit__c = 112.0;
        oi.Purchase_Price__c = 221.0;
        oi.Installation_Price__c = 231.0;
        oi.Installation_Status__c = fssetting.Status_Value_for_Install_of_a_Product__c;
        upsert new List<OrderItem> {oi, newItem};
        
        o.Status='Activated';
        update o;
        
        Test.stopTest();
    }
    
    static testMethod void updateOrderError1() {
        List<Survey_Asset_Location__c> surveyAssets = new List<Survey_Asset_Location__c>();
        Order o = [SELECT Id, Account.Name, AccountId FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        
        for(Survey_Asset_Location__c sa : [SELECT Id, Survey_Location__c, Originating_Parent_ID__c FROM Survey_Asset_Location__c WHERE Originating_Parent_ID__c=:o.Id]) {
            sa.Survey_Location__c=null;
            surveyAssets.add(sa);
        }
        
        Test.startTest();
        
        update surveyAssets;
        
        o.Status='Activated';
        
        try {
            update o;
        } catch (Exception e) {
            String message = e.getMessage();
          System.assert(e.getMessage().contains('There are Survey Asset Locations'), 'message=' + e.getMessage());
        }
        
        Test.stopTest();
    }
    
    static testMethod void updateOrderError2() {
        Account a0 = [SELECT Id, Site_Survey__c, Name, BillingStreet, ShippingCity, BillingCity FROM Account WHERE Name='TestAccount0'];
        Account a = [SELECT Id, Site_Survey__c, Name, BillingStreet, ShippingCity FROM Account WHERE Name='TestAccount1'];
        
        Order o = [SELECT Id, Account.Name, AccountId, BillingStreet, ShippingCity FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        
        o.ShippingCity=null;
        o.BillingStreet=null;
        o.Status='Activated';
        
        a0.BillingStreet=null;
        a0.BillingCity=null;
        
        Test.startTest();
        
        try {
            update a0;
          update o;
        } catch (Exception e) {
          System.assert(e.getMessage().contains('Please ensure'), 'message=' + e.getMessage());
        }
        
        Test.stopTest();
    }
    
    static testMethod void updateOrderError3() {
        Account a = [SELECT Id, Site_Survey__c, Name, BillingStreet, ShippingCity, ParentId FROM Account WHERE Name='TestAccount1'];
        a.BillingStreet=null;
        a.BillingCity=null;
        //a.ParentId=null;
        update a;
        
        Order o = [SELECT Id, Account.Name, AccountId, BillingStreet, ShippingCity FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        o.Status='Activated';
        
        Test.startTest();
        
        try {
            update o;
        } catch (Exception e) {
          System.assert(e.getMessage().contains('Please ensure'), 'message=' + e.getMessage());
        }
        
        Test.stopTest();
    }
    
    static testMethod void updateOrderError4() {
        Account a = [SELECT Id, Site_Survey__c, Name, BillingStreet, ShippingCity, ParentId, Service_Territory__c, OperatingHoursId FROM Account WHERE Name='TestAccount1'];
        a.Service_Territory__c=null;
        a.OperatingHoursId=null;
        update a;
        
        Order o = [SELECT Id, Account.Name, AccountId, BillingStreet, ShippingCity, Service_Territory__c FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        o.Service_Territory__c=null;
        o.Status='Activated';
        
        Test.startTest();
        
        try {
            update o;
        } catch (Exception e) {
          System.assert(e.getMessage().contains('Please fill in the'), 'message=' + e.getMessage());
        }
        
        Test.stopTest();
    }
    
    static testMethod void deleteOrder() {
        Order o = [SELECT Id, Account.Name, AccountId FROM Order WHERE Account.Name='TestAccount1' LIMIT 1].get(0);
        
        Test.startTest();

        delete o;
        
        Test.stopTest();
    }
}