force-app/main/default/objects/FSA_Service_Territory_Mapping__c/FSA_Service_Territory_Mapping__c.object-meta.xml
<CustomObject>
    <label>FSA &amp; Service Territory Mapping</label>
    <nameField>
        <label>FSA Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FSA &amp; Service Territory Mappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FSA_Service_Territory_Mapping__c/fields/FSA__c.field-meta.xml
<CustomField>
    <fullName>FSA__c</fullName>
    <externalId>true</externalId>
    <label>FSA</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FSA_Service_Territory_Mapping__c/fields/Sales_Territory__c.field-meta.xml
<CustomField>
    <fullName>Sales_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Territory</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected sales territory is inactive</errorMessage>
        <filterItems>
            <field>Sales_Territory__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Territory__c</referenceTo>
    <relationshipLabel>FSA &amp; Service Territory Mappings</relationshipLabel>
    <relationshipName>FSA_Service_Territory_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FSA_Lead_Assignment__c.field-meta.xml
<CustomField>
    <fullName>FSA_Lead_Assignment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to trigger the postal code lead assignment to a sales person</description>
    <inlineHelpText>Used to trigger the postal code lead assignment to a sales person</inlineHelpText>
    <label>FSA Lead Assignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Setting__mdt/Sales_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Sales Setting</label>
    <pluralLabel>Sales Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sales_Setting__mdt/fields/Lead_Assignment_Queue_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_Assignment_Queue_ID__c</fullName>
    <label>Lead Assignment Queue ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Territory__c/Sales_Territory__c.object-meta.xml
<CustomObject>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Territory__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked when sales territory is active</description>
    <inlineHelpText>Checked when sales territory is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Territory__c/fields/Assigned_Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Sales_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assigned Sales Rep</description>
    <inlineHelpText>User assigned to this sales territory</inlineHelpText>
    <label>Assigned Sales Representative</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assigned user is inactive</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
/**
 * @FileName: LeadTriggerHandler
 * @Description: Consolidated Trigger Handler Class 
 * @Author: Irfan Tarique
 * @ModificationLog:
 *-------------------------------------------------------------------------------------------------------------------------
 * Author            	Date            Modification 			Description
 *-------------------------------------------------------------------------------------------------------------------------
 *Irfan Tarique 		May 14th,2020	assignWebLeadOwner  	Assign lead owners based on matching FSA - Sales Territory
 *-------------------------------------------------------------------------------------------------------------------------
 **/

public class LeadTriggerHandler extends TriggerHandler {
    
    /** TRIGGER EVENTS **/
    protected override void beforeInsert(){
        assignWebLeadOwner();
    }
    protected override void beforeUpdate(){
        assignWebLeadOwner();
    }
    protected override void afterInsert(){}
    protected override void afterUpdate(){}
    protected override void beforeDelete(){}   
    
    
	/**Variables**/
    Private List<Lead> listNew;
    Private List<Lead> listOld;

    Private Map<Id, Lead> mapNew;
    Private Map<Id, Lead> mapOld;
    
    Sales_Setting__mdt[] salesSettings; 
    
    public leadTriggerHandler(){
        listNew = Trigger.new;
        listOld = Trigger.old;
        mapNew = (map<Id, Lead>)Trigger.newMap;
        mapOld = (map<Id, Lead>)Trigger.oldMap;
       	salesSettings = [SELECT id, label, Lead_Assignment_Queue_ID__c FROM Sales_Setting__mdt];
    }
    
    private void assignWebLeadOwner(){
       List<Lead> leadFSA = new List<lead>();
    
       for(Lead newLead: listNew){
            if(newLead.FSA_Lead_Assignment__c){ 
            	leadFSA.add(newLead);
            }
        }
        
        if(!leadFSA.isEmpty()){
            List<FSA_Service_Territory_Mapping__c> FSA = New List<FSA_Service_Territory_Mapping__c>
                ([SELECT id, name, FSA__c, Sales_Territory__c, Sales_Territory__r.Assigned_Sales_Representative__c 
                  FROM FSA_Service_Territory_Mapping__c 
                  WHERE Sales_Territory__r.Assigned_Sales_Representative__r.IsActive = TRUE AND Sales_Territory__r.Active__c = TRUE]);
            
            Map<String, Id> salesTerritoryRepFSA = New Map<String, Id>();   
                
            For(FSA_Service_Territory_Mapping__c pCode : FSA){  
            	salesTerritoryRepFSA.put(pCode.FSA__c, pCode.Sales_Territory__r.Assigned_Sales_Representative__c);
            }

            for(Lead l : leadFSA){ 
                String postalCode = Null;
                
                if(l.PostalCode != Null){postalCode = l.PostalCode.substring(0,3).toUppercase();}
  				l.FSA_Lead_Assignment__c = false;
                
                if(salesTerritoryRepFSA.containskey(postalCode)){
                    //Assign to Sales Territory Rep
                    l.OwnerId = salesTerritoryRepFSA.get(postalCode);
                }
                else{
                    //Assign to a queue
                    l.OwnerId = salesSettings[0].Lead_Assignment_Queue_ID__c;
                }
            }
        }
    }
}