force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Standing_Order_Custom_Permission_Id__c.field-meta.xml
<CustomField>
    <fullName>Standing_Order_Custom_Permission_Id__c</fullName>
    <label>Standing Order Custom Permission Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Standing_Order_Override_Permission_Id__c.field-meta.xml
<CustomField>
    <fullName>Standing_Order_Override_Permission_Id__c</fullName>
    <label>Standing Order Override Permission Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StandingOrderUtilityClass.cls
public class StandingOrderUtilityClass {
    static final String CUSTOM_PERMISSION = 'CustomPermission';
    static Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
    
    public static Boolean isPriceOverrideAllowed() {
        Boolean isPermitted = [SELECT count() FROM PermissionSetAssignment WHERE PermissionSetId = :dataSets.Standing_Order_Override_Permission_Id__c AND AssigneeId = :UserInfo.getUserId()] > 0;
        
        if (isPermitted) {
        	return [SELECT count() FROM SetupEntityAccess WHERE SetupEntityType = :CUSTOM_PERMISSION AND ParentId =:dataSets.Standing_Order_Override_Permission_Id__c AND SetupEntityId = :dataSets.Standing_Order_Custom_Permission_Id__c] > 0;
        }
        System.debug('is permitted >>> ' + isPermitted);
        return false;
    }
}