force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Label_for_Service_Work_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Label_for_Service_Work_Order_Type__c</fullName>
    <label>Label for Service Work Order Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Pest_LOB__c.field-meta.xml
<CustomField>
    <fullName>Pest_LOB__c</fullName>
    <label>Pest LOB</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Settings__c/fields/Work_Order_New_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_New_Status__c</fullName>
    <label>Work Order New Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>PricebookEntry.IsActive  &amp;&amp;  PricebookEntry.Product2.IsActive &amp;&amp;  Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Family)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line of Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Order Item cannot have the custom Order field set as it&apos;s Inactive.</errorMessage>
        <filterItems>
            <field>$Source.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Active Order Products without PO Number</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Work_Type__c</fullName>
    <formula>PricebookEntry.Product2.Service_Work_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Work Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Survey_Location__c.field-meta.xml
<CustomField>
    <fullName>Survey_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Location</label>
    <referenceTo>Survey_Location__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Service_Notes__c.field-meta.xml
<CustomField>
    <fullName>Service_Notes__c</fullName>
    <label>Service Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Life Safety</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Product_Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Service_Price_Per_Unit__c</fullName>
    <label>Product Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Service_Notes__c.field-meta.xml
<CustomField>
    <fullName>Service_Notes__c</fullName>
    <label>Service Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Type_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Service__c</fullName>
    <label>Type of Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SpawnPestEmergencyWorkOrderLineItems.cls
/**
* Name: SpawnPestEmergencyWorkOrders
* Author: PwC
* Date Created: April 23, 2019
* Purpose: To generate the Pest Emergency Work Order Line Items from the Emergency Dispatch Wizard app
*/
global class SpawnPestEmergencyWorkOrderLineItems implements Database.Batchable<SObject> {
    private Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
    private Set<Id> workOrderIds;
    
    global SpawnPestEmergencyWorkOrderLineItems(Set<Id> workOrderIds) {
        this.workOrderIds = workOrderIds;
    }
    
	global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id FROM WorkOrder WHERE Id IN :workOrderIds]);
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> batch) {
        Set<Id> workOrderIds = new Set<Id>();
        
        for (WorkOrder wo : (List<WorkOrder>)batch) {
            workOrderIds.add(wo.Id);
        }
        
        processWorkOrderLineItems(workOrderIds);
    }
    
    global void finish(Database.BatchableContext bc) {
        Database.executeBatch(new SpawnWorkOrderRooms(workOrderIds, true), 50);
    }
    
    /**
     * Generates and sanitizes all Pest Emergency Work Order Line Items as specified
     * 
     * @param workOrderIds  the Ids representing the Work Orders to have their Line Items generated and sanitized
     */
    global void processWorkOrderLineItems(Set<Id> workOrderIds) {
        workOrderIds.remove(null);
        
        if (workOrderIds.isEmpty()) {
            System.debug('empty request');
            return;
        }
        
        Map<Id, WorkOrder> orderToWorkOrderMap = new Map<Id, WorkOrder>();
        Map<Id, List<WorkOrderLineItem>> workOrderLineItemsMap = new Map<Id, List<WorkOrderLineItem>>();
        List<WorkOrderLineItem> workOrderLineItemsToInsert = new List<WorkOrderLineItem>();
        Map<Id, WorkOrderLineItem> existingLineItems = new Map<Id, WorkOrderLineItem>();
        Map<Id, WorkOrderLineItem> existingLineItemsToDelete = new Map<Id, WorkOrderLineItem>();
        
        if (!workOrderIds.isEmpty()) {
            for (WorkOrder wo : [SELECT Id, Order__c, StartDate, EndDate, (SELECT Id, Order_Product__c, Order_Product__r.IsActive__c FROM WorkOrderLineItems) FROM WorkOrder WHERE Id IN :workOrderIds AND Emergency__c = TRUE AND Line_of_Business__c = :dataSets.Pest_LOB__c]) {
                orderToWorkOrderMap.put(wo.Order__c, wo);
                workOrderLineItemsMap.put(wo.Order__c, new List<WorkOrderLineItem>());
                
                if (!wo.WorkOrderLineItems.isEmpty()) {
                    for (WorkOrderLineItem woli : wo.WorkOrderLineItems) {
                        if (String.isBlank(woli.Order_Product__c) || !woli.Order_Product__r.IsActive__c) {
                            existingLineItemsToDelete.put(woli.Id, woli);
                        } else {
                            existingLineItems.put(woli.Order_Product__c, woli);
                        }
                    }
                }
            }
        }
        
        existingLineItemsToDelete.remove(null);
        existingLineItems.remove(null);
        
        if (!workOrderLineItemsMap.isEmpty()) {
            for (OrderItem oi : [SELECT Id, OrderId, Survey_Location__c, Product2Id, PricebookEntryId, Service_Work_Type__c, Service_Notes__c, Service_Price_Per_Unit__c FROM OrderItem WHERE OrderId IN :workOrderLineItemsMap.keySet()]) {
                WorkOrder wo = orderToWorkOrderMap.get(oi.OrderId);
                
                WorkOrderLineItem existingWOLI = existingLineItems.get(oi.Id);
                
                WorkOrderLineItem woli = new WorkOrderLineItem(
                    WorkOrderId = wo.Id,
                    OrderId = oi.OrderId,
                    Order_Product__c = oi.Id,
                    Product__c = oi.Product2Id,
                    Quantity = 1,
                    PricebookEntryId = oi.PricebookEntryId,
                    StartDate = wo.StartDate,
                    EndDate = wo.EndDate,
                    Type_of_Service__c = dataSets.Label_for_Service_Work_Order_Type__c,
                    Status = dataSets.Work_Order_New_Status__c,
                    WorkTypeId = oi.Service_Work_Type__c,
                    Service_Notes__c = oi.Service_Notes__c,
                    Product_Service_Price_Per_Unit__c = oi.Service_Price_Per_Unit__c//7.3 change request
                );
                
                if (existingWOLI != null) {
                    woli.Id = existingWOLI.Id;
                }
                
                workOrderLineItemsMap.get(oi.OrderId).add(woli);
            }
        }
        
        workOrderLineItemsMap.remove(null);
        
        for (Id orderId : workOrderLineItemsMap.keySet()) {
            workOrderLineItemsToInsert.addAll(workOrderLineItemsMap.get(orderId));
        }
        
        if (!workOrderLineItemsToInsert.isEmpty()) {
            upsert workOrderLineItemsToInsert;
        }
        
        if (!existingLineItemsToDelete.isEmpty()) {
            delete existingLineItemsToDelete.values();
        }
    }
}