force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Work_Order_Chatter_File_Extensions__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Chatter_File_Extensions__c</fullName>
    <inlineHelpText>Comma separated list of file extensions that will be included in the Work Order File Automation process.
Leave blank or set to &quot;All&quot; to include all file types</inlineHelpText>
    <label>Work Order Chatter File Extensions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>(EffectiveDate &lt;= (Today() +  $Setup.Field_Service_Settings__c.Work_Orders_In_Advance__c )) &amp;&amp; ISPICKVAL(Status, &quot;Activated&quot;) &amp;&amp;  (EndDate &gt; Today() || ISBLANK(EndDate))</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Survey__c/Site_Survey__c.object-meta.xml
<CustomObject>
    <label>Site Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Site Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <formula>(Last_Batch_Updated_Date__c = TODAY() || Last_Batch_Updated_Date__c = TODAY() + (-1)) &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Completed&apos; &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Cannot Complete&apos; &amp;&amp; TEXT(StatusCategory) &lt;&gt; &apos;Dispatched&apos;</formula>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Survey__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Survey</label>
    <referenceTo>Site_Survey__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of Work Order, whether it is a delivery or a work order for a particular line of business</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>QA Work Order</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>DeInstall</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>NoWork</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SpawnWorkOrderFiles.cls
global class SpawnWorkOrderFiles implements Database.Batchable<SObject>, Schedulable {
    
    public String queryString { get; set; }
    public Field_Service_Settings__c custSetting;
    public Boolean isOrderId { get; set; }
    
    global SpawnWorkOrderFiles() {
        isOrderId = false;
        custSetting = Field_Service_Settings__c.getOrgDefaults();
    }
    
    global SpawnWorkOrderFiles(String s) {
        isOrderId = false;
        queryString = 'SELECT Id FROM WorkOrder WHERE Id=\'' + s + '\'';
        custSetting = Field_Service_Settings__c.getOrgDefaults();
    }
    
    global SpawnWorkOrderFiles(String s, Boolean isOrderId) {
        this.isOrderId = isOrderId;
        custSetting = Field_Service_Settings__c.getOrgDefaults();
        if(isOrderId) {
            queryString = 'SELECT Id, Order__c FROM WorkOrder WHERE Order__c=\'' + s + '\' AND isValid__c=TRUE';
        } else {
            queryString = 'SELECT Id FROM WorkOrder WHERE Id=\'' + s + '\'';
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        if (queryString == null) {
            return Database.getQueryLocator([SELECT Id FROM WorkOrder where (StatusCategory='New' OR StatusCategory='In Progress' OR StatusCategory='Dispatched')]);
        } else {
            System.debug('executing custom query: ' + queryString);
            return Database.getQueryLocator(queryString);
        }
    }

    global void execute(Database.BatchableContext bc, List<SObject> batch) {
        Set<Id> workOrderIds = new Set<Id>();
        for(WorkOrder o : (List<WorkOrder>) batch){
            workOrderIds.add(o.Id);
        }
        processWorkOrderFiles(workOrderIds);
    }
    
    global void processWorkOrderFiles(Set<Id> ids) {
        
        System.debug('SpawnWorkOrderFiles.processWorkOrderFiles(): ' + ids);
        
        Set<Id> workOrderIds = new Set<Id>();
        
        System.debug(' isOrder ' + isOrderId);
        if(isOrderId) {
            for(WorkOrder wo : [SELECT Id, Order__c , CreatedDate FROM WorkOrder WHERE Order__c IN:ids AND isValid__c=TRUE]) {
                workOrderIds.add(wo.Id);
            }
        } else {
            workOrderIds.addAll(ids);
        }
        
        Map<String, FeedItem> feedMap = new Map<String, FeedItem>();
        Map<Id, WorkOrder> workOrderMap = new Map<Id, WorkOrder>([Select Id, CreatedDate, Type__c, Site_Survey__c, Order__r.OpportunityId, (Select ContentDocumentId from ContentDocumentLinks) from WorkOrder where Id in: workOrderIds]);
        
        Map<Id, List<ContentDocumentLink>> contentLinkMap = new Map<Id, List<ContentDocumentLink>>();
        
        List<FeedItem> newContentLinksToAdd = new List<FeedItem>();
        
        Set<Id> oppIds = new Set<Id>();
        Set<Id> surveyIds = new Set<Id>();
        Set<String> existingWorkOrderFiles = new Set<String>();
        
        String oppPrefix = Opportunity.sobjecttype.getDescribe().getKeyPrefix();
        String siteSurveyPrefix = Site_Survey__c.sobjecttype.getDescribe().getKeyPrefix();
        
        System.debug('workOrderMap: ' + workOrderMap);
        
        for(WorkOrder w : workOrderMap.values()) {
            if(w.Type__c=='Installation') {
                oppIds.add(w.Order__r.OpportunityId);
            }
            surveyIds.add(w.Site_Survey__c);
            
            for(ContentDocumentLink c : w.ContentDocumentLinks) {
                existingWorkOrderFiles.add(w.Id+'-'+c.ContentDocumentId);
            }
        }
        oppIds.remove(null);
        surveyIds.remove(null);
        
        System.debug('Opp IDs: ' + oppIds);
        System.debug('Survey IDs: ' + surveyIds);
        System.debug('existingWorkOrderFiles: ' + existingWorkOrderFiles);
        
        if(!oppIds.isEmpty() || !surveyIds.isEmpty()) {
            
            Boolean includeAllFileTypes = custSetting==null||custSetting.Work_Order_Chatter_File_Extensions__c==null||custSetting.Work_Order_Chatter_File_Extensions__c==''||custSetting.Work_Order_Chatter_File_Extensions__c.contains('All');
            
            Set<String> fileExtensionsToInclude = new Set<String>();
            if(!includeAllFileTypes && custSetting.Work_Order_Chatter_File_Extensions__c!=null) {
                fileExtensionsToInclude.addAll(custSetting.Work_Order_Chatter_File_Extensions__c.split(',')); 
            }
            
            for(ContentDocumentLink c : Database.query('SELECT SystemModStamp, LinkedEntityId, ContentDocumentId, ContentDocument.LatestPublishedVersionId FROM ContentDocumentLink WHERE (LinkedEntityId in: oppIds OR LinkedEntityId in: surveyIds) '+(includeAllFileTypes?'':' AND ContentDocument.FileExtension in: fileExtensionsToInclude ')+' ORDER BY SystemModStamp ASC')) {
                
                if(contentLinkMap.containsKey(c.LinkedEntityId)) {
                    contentLinkMap.get(c.LinkedEntityId).add(c);
                } else {
                    contentLinkMap.put(c.LinkedEntityId, new List<ContentDocumentLink>{c});
                }
            }
            
            System.debug('contentLinkMap: ' + contentLinkMap);
            
            for(WorkOrder w : workOrderMap.values()) {
                List<ContentDocumentLink> temp = new List<ContentDocumentLink>();
                
                if(w.Type__c=='Installation' && w.Order__r.OpportunityId!=null && contentLinkMap.containsKey(w.Order__r.OpportunityId)) {
                    temp.addAll(contentLinkMap.get(w.Order__r.OpportunityId));
                }
                if(w.Site_Survey__c!=null && contentLinkMap.containsKey(w.Site_Survey__c)) {
                    temp.addAll(contentLinkMap.get(w.Site_Survey__c));
                }
                if(!temp.isEmpty()) {
                    for(ContentDocumentLink c : temp) {
                        
                        String key = w.Id+'-'+c.ContentDocumentId;
                        System.debug('ContentDocumentLink ('+key+'): ' + c);

                        if(
                            existingWorkOrderFiles.contains(key) || //If file already added to Work Order, then skip
                            c.SystemModStamp>w.CreatedDate //If file was created after work order, then skip
                        ) { 
                            continue; 
                        }
                        Boolean isOppFile = String.valueOf(c.LinkedEntityId).startsWithIgnoreCase(oppPrefix);
                        
                        newContentLinksToAdd.add(new FeedItem(
                            Body = ('File posted on related '+(isOppFile?'Opportunity':'Survey')), 
                            ParentId = w.Id, 
                            RelatedRecordId = c.ContentDocument.LatestPublishedVersionId, 
                            Type = 'ContentPost'
                        ));
                    }
                }
            }
            
            System.debug('newContentLinksToAdd: ' + newContentLinksToAdd);
            
            if(!newContentLinksToAdd.isEmpty()) {
                Database.insert(newContentLinksToAdd);
            }
        }
    }

    global void finish(Database.BatchableContext bc){
        if(!Test.isRunningTest()){
        	Database.executeBatch(new ClearBatchErrors());
        }
    }

    global void execute(SchedulableContext ctx) {
        Database.executeBatch(new SpawnWorkOrderFiles());
    }
}