force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Standing_Order__c/Standing_Order__c.object-meta.xml
<CustomObject>
    <label>Standing Order</label>
    <nameField>
        <label>Standing Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standing Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Standing_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Standing Orders</relationshipLabel>
    <relationshipName>Standing_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Standing_Order__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If the record is in Accpac, it is considered Active.</description>
    <inlineHelpText>If the record is in Accpac, it is considered Active.</inlineHelpText>
    <label>SO Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Standing_Order_Line_Item__c/Standing_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Standing Order Line Item</label>
    <nameField>
        <label>Standing Order Line Item No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standing Order Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Standing_Order_Line_Item__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If the record is in Accpac, it is considered Active.</description>
    <inlineHelpText>If the record is in Accpac, it is considered Active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Standing_Order_Line_Item__c/fields/Frequency_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Picklist__c</fullName>
    <label>Frequency Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Fixed Weekly</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Standing_Order_Line_Item__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <label>Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Standing_Order_Line_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Standing_Order_Line_Item__c/fields/Service_Price_Per_Visit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Visit__c</fullName>
    <description>This value is used in Darci&apos;s integration. It represents the customer&apos;s price everytime we service this product. The formula populating this field is the customer&apos;standing order price multiplied by their billing frequency divided by the number of services in a year.</description>
    <label>Service Price Per Visit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Standing_Order_Line_Item__c/fields/Standing_Order__c.field-meta.xml
<CustomField>
    <fullName>Standing_Order__c</fullName>
    <label>Standing Order</label>
    <referenceTo>Standing_Order__c</referenceTo>
    <relationshipLabel>Standing Order Line Item</relationshipLabel>
    <relationshipName>Standing_Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PriceCalculationUtility.cls
public class PriceCalculationUtility {
    static Field_Service_Settings__c dataSets = Field_Service_Settings__c.getOrgDefaults();
    static final String KEY_DELIMITER = '.';
    static final String ITEM_NUMBER_DELIMITER = '-';
    static final Integer EXPECTED_NUMBER_OF_DELIMITED_VALUES = 3;
    static final String PEST_SPECIAL = 'PEST_SPECIAL';
    static final String PEST_SPECIAL_CODE = '1-55';//put in code, not in a custom setting because this value should not change - please don't change this value
    
    public static Map<String, Decimal> buildStandingOrderPriceMap(Set<Id> accountIds) {
        if (accountIds.isEmpty()) {
			System.debug('accountsIds is empty');
            return null;
        }
        
        Map<String, Decimal> standingOrderLinePriceItemMapWithFrequency = new Map<String, Decimal>();
        
        for (Standing_Order_Line_Item__c item : [SELECT Price__c, Item_Number__c, Standing_Order__r.Account__c, Frequency_Picklist__c, Service_Price_Per_Visit__c FROM Standing_Order_Line_Item__c 
                                                 WHERE Standing_Order__r.Account__c IN:accountIds AND Standing_Order__r.Active__c=TRUE AND Active__c=TRUE
                                                 AND Price__c!= NULL ORDER BY Price__c ASC])
        {
            
            String[] delimitedValues = item.Item_Number__c.split(ITEM_NUMBER_DELIMITER);
            String allOtherKey = item.Item_Number__c + KEY_DELIMITER + item.Standing_Order__r.Account__c;
            
            if (delimitedValues.size() >= EXPECTED_NUMBER_OF_DELIMITED_VALUES) {
                String serviceKey;
                
                if (item.Item_Number__c.startsWith(PEST_SPECIAL_CODE)) {
                    System.debug(item.Item_Number__c);
                    serviceKey = item.Item_Number__c + KEY_DELIMITER + item.Standing_Order__r.Account__c + KEY_DELIMITER + PEST_SPECIAL;
                } else {
                    serviceKey = delimitedValues[0] + ITEM_NUMBER_DELIMITER + delimitedValues[1] + ITEM_NUMBER_DELIMITER + delimitedValues[2] + KEY_DELIMITER + item.Standing_Order__r.Account__c + KEY_DELIMITER + item.Frequency_Picklist__c;
                }
                
                System.debug('~~ServiceKey:' + serviceKey);
                
                //price ordered by descending so the first one is the one we want (highest)
                if (!standingOrderLinePriceItemMapWithFrequency.containsKey(serviceKey)) {
                    standingOrderLinePriceItemMapWithFrequency.put(serviceKey, item.Service_Price_Per_Visit__c);
                } else {
                    Decimal currentPrice = standingOrderLinePriceItemMapWithFrequency.get(serviceKey);
                    if (currentPrice > item.Service_Price_Per_Visit__c) {
                        standingOrderLinePriceItemMapWithFrequency.put(serviceKey, item.Service_Price_Per_Visit__c);
                    }
                }
            } else {
                System.debug('bad data >>> ' + delimitedValues);
            }
            
            if (!standingOrderLinePriceItemMapWithFrequency.containsKey(allOtherKey)) {
                standingOrderLinePriceItemMapWithFrequency.put(allOtherKey, item.Price__c);
            } else {
                Decimal currentPrice = standingOrderLinePriceItemMapWithFrequency.get(allOtherKey);
                
                if (currentPrice > item.Service_Price_Per_Visit__c) {
                    standingOrderLinePriceItemMapWithFrequency.put(allOtherKey, item.Service_Price_Per_Visit__c);
                }
            }
        }
        return standingOrderLinePriceItemMapWithFrequency;
    }
}