force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/Order/fields/Order_Merge_Job_Message__c.field-meta.xml
<CustomField>
    <fullName>Order_Merge_Job_Message__c</fullName>
    <description>Used by the Order Merge batch job.</description>
    <inlineHelpText>Used by the Order Merge batch job.</inlineHelpText>
    <label>Order Merge Job Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Merge_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Merge_Job_Status__c</fullName>
    <description>Used by the Order Merge batch job. Set the value to ‘To be Processed’ to have the batch job pick this record up.</description>
    <inlineHelpText>Used by the Order Merge batch job. Set the value to ‘To be Processed’ to have the batch job pick this record up.</inlineHelpText>
    <label>Order Merge Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ready for Work Order Reparenting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prevent_Invoice_Change_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Invoice_Change_Ticket__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to prevent the Invoice Change Ticket from being created</description>
    <inlineHelpText>Used to prevent the Invoice Change Ticket from being created</inlineHelpText>
    <label>Prevent Invoice Change Ticket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Surviving_Order__c.field-meta.xml
<CustomField>
    <fullName>Surviving_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surviving Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Surviving Order must have same account</errorMessage>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (Surviving Order)</relationshipLabel>
    <relationshipName>SurvivingOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Cloned_From_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Order Line was created via the Order Merge batch</description>
    <inlineHelpText>This Order Line was created via the Order Merge batch</inlineHelpText>
    <label>Cloned From Order Line</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products (Cloned From Order Line)</relationshipLabel>
    <relationshipName>Cloned_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Order Item cannot have the custom Order field set as it&apos;s Inactive.</errorMessage>
        <filterItems>
            <field>$Source.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Active Order Products without PO Number</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WorkOrderMergerTest.cls
/**
 * @FileName: WorkOrderMergerTest
 * @Description: Test class for WorkOrderMerger class
 * @Author: Ahsan Butt
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Ahsan Butt        N/A             Created
 * Graeme Ward       02/10/2020      Fixed test method, updated to new test framework
 *-----------------------------------------------------------
 */
@IsTest
public class WorkOrderMergerTest {

    @TestSetup
    static void setupTest() {
        setupHelper();
    }

    @IsTest
    static void doMerges() {
        Order o = [
                SELECT Id, AccountId, Status, EffectiveDate, Pricebook2Id,
                        (SELECT Id, Description, Product2Id, Frequency__c, UnitPrice, Service_Price_Per_Unit__c,
                                Quantity, OrderId, PricebookEntryId
                        FROM OrderItems)
                FROM Order LIMIT 1
        ];

        Order survivingOrder = o.clone(false, true);
        insert survivingOrder;

        List<OrderItem> survivingItems = new List<OrderItem>();

        for(OrderItem item : o.OrderItems) {
            OrderItem itemClone = item.clone(false, true);
            itemClone.OrderId = survivingOrder.Id;
            itemClone.Cloned_From_Order_Line__c = item.Id;
            survivingItems.add(itemClone);
        }

        o.Surviving_Order__c = survivingOrder.Id;
        update o;

        List<Order> srcOrders = [
                SELECT Id, Surviving_Order__c, Status, Prevent_Invoice_Change_Ticket__c, Order_Merge_Job_Status__c,
                        Order_Merge_Job_Message__c
                FROM Order
                WHERE Id = :o.Id
        ];

        WorkOrder wo = [
                SELECT Id, Order__c, Order__r.Surviving_Order__c,
                        (SELECT Id, Order_Product__c, OrderId FROM WorkOrderLineItems)
                FROM WorkOrder
                LIMIT 1
        ];

        Test.startTest();
        // inside start test due to SOQL governor limits
        insert survivingItems;

        OrderMerger.doMerges(
                srcOrders,
                'Clone_Fields',
                new List<String>{'FrequencyOrderItemFilter'},
                new List<String>()
        );

        WorkOrderMerger.doMerges(new List<WorkOrder>{wo});
        Test.stopTest();

        List<WorkOrder> wosAfter = [SELECT Id FROM WorkOrder WHERE Id = :wo.Id AND Order__c = :survivingOrder.Id];

        System.assertEquals(1, wosAfter.size(), 'Work Order should be reparented');
    }

    // HELPER METHODS
    static void setupHelper() {
        TestUtils.createSObject(new Field_Service_Settings__c(), true);

        TestUtilsWrapperPricebook pricebookWrapper = new TestUtilsWrapperPricebook(1);
        TestUtilsWrapperAccount accountWrapper = new TestUtilsWrapperAccount();
        TestUtilsWrapperOrder orderWrapper = new TestUtilsWrapperOrder(accountWrapper, pricebookWrapper);
        new TestUtilsWrapperWorkOrder(accountWrapper, orderWrapper);
    }
}