force-app/main/default/objects/Field_Service_Settings__c/Field_Service_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Field Service Settings</label>
</CustomObject>

force-app/main/default/objects/Field_Service_Settings__c/fields/Fixed_Weekly_Service_Frequency_Value__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Weekly_Service_Frequency_Value__c</fullName>
    <label>Fixed Weekly Service Frequency Value</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Frequency__c/Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Frequency</label>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Service Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
                <default>true</default>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>28 Days</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>42 Days</fullName>
            </value>
            <value>
                <fullName>56 Days</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>84 Days</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>112 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>168 Days</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>182 Days</fullName>
            </value>
            <value>
                <fullName>2X Per Year</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2X Per Week</fullName>
            </value>
            <value>
                <fullName>3X Per Week</fullName>
            </value>
            <value>
                <fullName>5X Per Week</fullName>
            </value>
            <value>
                <fullName>6X Per Week</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_Automation_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Automation_Created_Date__c</fullName>
    <description>This field is System Generated during the nightly Work Order Generation batch job. Changing this would have implications on Work Order Generation Logic</description>
    <label>Last Automation Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Last_InFlight_WO_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_InFlight_WO_Date__c</fullName>
    <label>Last InFlight WO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Service_Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Service_Price_Per_Unit__c</fullName>
    <inlineHelpText>Indicate a recurring Service. Price is entered for per visit for per unit of this item. This should be filled in to indicate a recurring Service.</inlineHelpText>
    <label>Service Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>One-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderItemFilterTest.cls
/**
 * Unit tests for all impls of IOrderItemFilter.
 * 
 * @author: Ahsan Butt
 */
@isTest
private class OrderItemFilterTest {
     static testmethod void testActiveFilter() {
    	ActiveOrderItemFilter f = new ActiveOrderItemFilter();
        f.getFields();
        
        OrderItem oi = new OrderItem();
        
        Boolean actual = f.filter(oi);
        System.assertEquals(false, actual, 'Active Filter should have failed');
    }
    
    static testmethod void testFrequencyFilter() {
    	Field_Service_Settings__c fss = new Field_Service_Settings__c();
        fss.Fixed_Weekly_Service_Frequency_Value__c = 'Fixed Weekly';
        insert fss;
        
        FrequencyOrderItemFilter f = new FrequencyOrderItemFilter();
        f.getFields();
        
        OrderItem oi = new OrderItem();
        oi.Frequency__c = fss.Fixed_Weekly_Service_Frequency_Value__c;
        
        Boolean actual = f.filter(oi);
        System.assertEquals(false, actual, 'Frequency Filter should have failed (frequency is non-recurring)');
        
        oi.Frequency__c = 'Weekly';
        actual = f.filter(oi);
        System.assertEquals(true, actual, 'Frequency Filter should have passed');
    }
    
    static testmethod void testProductCodesOrderItemFilter() {
        OrderMerger.ORDER_ITEM_FILTER_PRODUCT_CODES = new List<String>{'123-12-123'};
    
        // Create underlying product and order
        Id pBook = Test.getStandardPricebookId();
        Product2 product = new Product2(
            Name = 'TEST',
            ExternalID__c = OrderMerger.ORDER_ITEM_FILTER_PRODUCT_CODES.get(0)
        );
        insert product;
      	
       	PricebookEntry pEntry =  new PricebookEntry(
                    Pricebook2Id = pBook, 
                    Product2Id = product.Id, 
                    UnitPrice = 1.0, 
                    IsActive = true
        ); 
        insert pEntry; 
        
        TestDataFactory.crtBillToAcctContact(1, 1);
                
        Order o = new Order(
        	AccountId = TestDataFactory.accounts[0].Id, 
            Status = 'Draft', 
            EffectiveDate = System.today(), 
            Pricebook2Id = pbook
        ); 
        insert o;
        
        // Create Order Item
        OrderItem oi = new OrderItem(
            Description='',
            Product2Id=pEntry.Id,  
            UnitPrice=1.0, 
            Service_Price_Per_Unit__c=1.0, 
            Quantity=1, 
            OrderId=o.Id,
            Last_Automation_Created_Date__c = Date.today()
        );
        
        insert oi;
        
        // Refresh from DB, such that Product's External Id is retrieved
        oi = [SELECT Id, Product2.ExternalID__c FROM OrderItem WHERE Id = :oi.Id LIMIT 1];
        
        ProductCodesOrderItemFilter f = new ProductCodesOrderItemFilter();
        f.getFields();
        
        
        Boolean actual = f.filter(oi);
        System.assertEquals(false, actual, 'Product code should be filtered out');
        
        // alter product code list
        OrderMerger.ORDER_ITEM_FILTER_PRODUCT_CODES = new List<String>{'FOO_BAR'};
        actual = f.filter(oi);
        System.assertEquals(true, actual, 'Product code filter should have passed');
    }
    
	static testmethod void testLACDFilter() {
    	LastAutomationCreatedDateOrderItemFilter f = new LastAutomationCreatedDateOrderItemFilter();
        f.getFields();
        
        OrderItem oi = new OrderItem();
        
        Boolean actual = f.filter(oi);
        System.assertEquals(false, actual, 'LACD Filter should have failed');
        
        oi.Last_Automation_Created_Date__c = Date.today();
        
        actual = f.filter(oi);
        System.assertEquals(true, actual, 'LACD Filter should have passed');
    }
    
    static testmethod void testLIFDFilter() {
    	LastInflightWODateOrderItemFilter f = new LastInflightWODateOrderItemFilter();
        f.getFields();
        
        OrderItem oi = new OrderItem();
        
        Boolean actual = f.filter(oi);
        System.assertEquals(false, actual, 'LIFD Filter should have failed');
        
        oi.Last_InFlight_WO_Date__c = Date.today();
        
        actual = f.filter(oi);
        System.assertEquals(true, actual, 'LIFD Filter should have passed');
    }
}