force-app/main/default/objects/SentimentBatchSettings__c/SentimentBatchSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Sentiment Batch Settings</label>
</CustomObject>

force-app/main/default/objects/SentimentBatchSettings__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <label>Query</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SentimentBatchSettings__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SentimentBatchSettings__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <label>Target Field</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SentimentSchedulableImplTest.cls
/**
 * Unit test for SentimentSchedulableImpl.
 * 
 * @author: Ahsan Butt
 */
@isTest
private class SentimentSchedulableImplTest {
    
    static testmethod void testExecute() {
        // Create custom settings
        SentimentBatchSettings__c sentimentSettings = new SentimentBatchSettings__c();
        sentimentSettings.Name = 'Lead Event Sentiment';
        sentimentSettings.Query__c = 'SELECT Id, Name FROM LEAD';
        sentimentSettings.Source_Field__c = 'Name';
        sentimentSettings.Target_Field__c = 'N/A';
        
        insert sentimentSettings;
        
        // Invoke schedulable
        SentimentSchedulableImpl sched = new SentimentSchedulableImpl('Test', 'Lead Event Sentiment');
        sched.execute(null);
    }
}