force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Service_Order__c</fullName>
    <label>Service Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WorkOrderLocationFutureCalls.cls
public class WorkOrderLocationFutureCalls {
	@future
    public static void updateServiceOrder(Map<Id, Decimal> serviceOrders) {
        if (!serviceOrders.isEmpty()) {
            List<Survey_Location__c> locsToUpdate = new List<Survey_Location__c>();
            for (Id loc : serviceOrders.keySet()) {
                locsToUpdate.add(new Survey_Location__c(Id=loc, Service_Order__c=serviceOrders.get(loc)));
            }
            
            if (!locsToUpdate.isEmpty()) {
            	update locsToUpdate;
            }
        }
    }
}