force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <label>Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/ControllingFieldName__c.field-meta.xml
<CustomField>
    <fullName>ControllingFieldName__c</fullName>
    <label>ControllingFieldName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/DependantFieldName__c.field-meta.xml
<CustomField>
    <fullName>DependantFieldName__c</fullName>
    <label>DependantFieldName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>ObjectName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Location__c/Survey_Location__c.object-meta.xml
<CustomObject>
    <label>Survey Location</label>
    <nameField>
        <label>Survey Location Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Location__c/fields/Location_SubType__c.field-meta.xml
<CustomField>
    <fullName>Location_SubType__c</fullName>
    <description>If a new value is added or existing values are changed, please update Location SubType field on both Work Order Location object and Work Order Object. Also please execute SLPickListValue.getDependantValues() to update the Configuration__c object</description>
    <label>Location SubType</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Location_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unisex</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Accessible</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Visitor</fullName>
            </value>
            <value>
                <fullName>Co-Ed</fullName>
            </value>
            <value>
                <fullName>Family Room</fullName>
            </value>
            <value>
                <fullName>Staff - Female</fullName>
            </value>
            <value>
                <fullName>Staff - Male</fullName>
            </value>
            <value>
                <fullName>Staff - Unisex</fullName>
            </value>
            <value>
                <fullName>Employee - Female</fullName>
            </value>
            <value>
                <fullName>Employee - Male</fullName>
            </value>
            <value>
                <fullName>Employee - Unisex</fullName>
            </value>
            <value>
                <fullName>Visitor - Female</fullName>
            </value>
            <value>
                <fullName>Visitor - Male</fullName>
            </value>
            <value>
                <fullName>Visitor - Unisex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Location__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>If a new value is added or existing values are changed, please update Location Type field on both Work Order Location object and Work Order Object. Also please execute SLPickListValue.getDependantValues() to update the Configuration__c object</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auditorium/Theatre</fullName>
            </value>
            <value>
                <fullName>Bar</fullName>
            </value>
            <value>
                <fullName>Basement</fullName>
            </value>
            <value>
                <fullName>Base of building</fullName>
            </value>
            <value>
                <fullName>Cafeteria/Lunch Room</fullName>
            </value>
            <value>
                <fullName>Compactor Room</fullName>
            </value>
            <value>
                <fullName>Day Care</fullName>
            </value>
            <value>
                <fullName>Dining area</fullName>
            </value>
            <value>
                <fullName>Finish Product Warehouse</fullName>
            </value>
            <value>
                <fullName>First Aid Room</fullName>
            </value>
            <value>
                <fullName>Floor</fullName>
            </value>
            <value>
                <fullName>Food Court</fullName>
            </value>
            <value>
                <fullName>Gym/Fitness Centre</fullName>
            </value>
            <value>
                <fullName>Hallway</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Kitchenette</fullName>
            </value>
            <value>
                <fullName>Level</fullName>
            </value>
            <value>
                <fullName>Loading dock</fullName>
            </value>
            <value>
                <fullName>Lobby</fullName>
            </value>
            <value>
                <fullName>Locker Room/Change Room</fullName>
            </value>
            <value>
                <fullName>Main Office</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Patio</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Raw Product Storage</fullName>
            </value>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Shipping &amp; receiving</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Washroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SLPicklistValue.cls
global class SLPicklistValue implements Database.AllowsCallouts {
    
    public static void getDependantValues() {
        
        Map<String, List<String>> mapDependency = new Map<String,List<String>>();
        
        //build map of controlling and dependant field values
        Schema.DescribeFieldResult fieldResult = Survey_Location__c.Location_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry s:ple) {
            mapDependency.put( s.getLabel(), new List<String>() );            
        } 
        
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        
        // Read Custom Field (dependent picklist)
        MetadataService.CustomField customField = (MetadataService.CustomField) service.readMetadata('CustomField', new String[] { 'Survey_Location__c.Location_SubType__c' },'').getRecords()[0];
        
        List<MetadataService.PicklistValue> filteredDependentValues = new List<MetadataService.PicklistValue>();
        
        for(String controllingFieldValue : mapDependency.keySet()) {
            System.debug(' Controlling ' + controllingFieldValue);
            //System.debug(' Dependants ' + customField.picklist.picklistValues);
            for (MetadataService.PicklistValue picklistValue : customField.picklist.picklistValues) {
                System.debug('Depended Types Controlling field  ' + picklistValue.controllingFieldValues + ' The dependent field ' + picklistValue.fullName);
                if (( picklistValue.controllingFieldValues != null ) &&  new Set<String>(picklistValue.controllingFieldValues).contains( controllingFieldValue)) {
                    List<String> currValues = mapDependency.get(controllingFieldValue);
                    System.debug(currValues);
                    currValues.add(picklistValue.fullName);
                    //System.debug(' Dependent ' + picklistValue.fullName);
                    mapDependency.put(controllingFieldValue, currValues);
                }
            }
            System.debug(mapDependency);
        }
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        for(String controllingField : mapDependency.keySet() ){
            gen.writeFieldName(EncodingUtil.urlDecode(controllingField,'UTF-8'));        
            gen.writeStartArray();
            for(String dependantVal : mapDependency.get(controllingField) ){
                gen.writeString(dependantVal);    
            }
            gen.writeEndArray();                
        }
        gen.writeEndObject();
        String s = gen.getAsString().replace('\n','');
        System.debug(s);
        
        insert new Configuration__c(
            Name=String.valueOf(DateTime.now()),
            Content__c = gen.getAsString().replace('\n','') ,
            ControllingFieldName__c = 'Location_Type__c',
            DependantFieldName__c = 'Location_SubType__c',
            ObjectName__c = 'Survey_Location__c'
        );
    }
}